// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/FlxG.h>
#include <flixel/FlxObject.h>
extern hl_type t$flixel_FlxObject;
extern hl_type t$_dyn;
extern flixel__$FlxG g$_flixel_FlxG;
void flixel_system_scaleModes_BaseScaleMode_onMeasure(flixel__system__scaleModes__BaseScaleMode,int,int);
#include <lime/ui/Window.h>
#include <openfl/display/Application.h>
openfl__display__Application openfl_Lib_get_application(void);
void lime_ui_Window_resize(lime__ui__Window,int,int);
#include <hl/ctx/1aa73.h>
extern String s$switchTo;
vdynamic* Reflect_field(vdynamic*,String);
extern hl_type t$_bool;
extern hl_type t$ctx_0d1aa73;
extern hl_type t$fun_cb7fdbf;
void flixel_FlxState_startOutro(flixel__FlxState,vclosure*);
#include <hl/types/ArrayDyn.h>
hl__Class Type_getClass(vdynamic*);
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
#include <hl/types/ArrayBase.h>
hl__types__ArrayDyn hl_types_ArrayDyn_alloc(hl__types__ArrayBase,bool*);
vdynamic* Type_createInstance(hl__Class,hl__types__ArrayDyn);
extern hl_type t$flixel_FlxState;
#include <flixel/system/FlxQuadTree.h>
extern flixel__system__$FlxQuadTree g$_flixel_system_FlxQuadTree;
flixel__system__FlxQuadTree flixel_system_FlxQuadTree_recycle(double,double,double,double,flixel__system__FlxQuadTree);
void flixel_system_FlxQuadTree_load(flixel__system__FlxQuadTree,flixel__FlxBasic,flixel__FlxBasic,vclosure*,vclosure*);
bool flixel_system_FlxQuadTree_execute(flixel__system__FlxQuadTree);
void flixel_system_FlxQuadTree_destroy(flixel__system__FlxQuadTree);
bool flixel_util_FlxCollision_pixelPerfectCheck(flixel__FlxSprite,flixel__FlxSprite,int*,flixel__FlxCamera);
bool flixel_FlxObject_separate(flixel__FlxObject,flixel__FlxObject);
extern hl_type t$fun_fce8c20;
extern hl_type t$fun_a7c8055;
#include <openfl/display/Sprite.h>
#include <openfl/display/DisplayObjectContainer.h>
int openfl_display_DisplayObjectContainer_getChildIndex(openfl__display__DisplayObjectContainer,openfl__display__DisplayObject);
int openfl_display_DisplayObjectContainer_get_numChildren(openfl__display__DisplayObjectContainer);
int flixel_math_FlxMath_maxAdd(int,int,int,int*);
openfl__display__DisplayObject openfl_display_DisplayObjectContainer_addChildAt(openfl__display__DisplayObjectContainer,openfl__display__DisplayObject,int);
bool openfl_display_DisplayObjectContainer_contains(openfl__display__DisplayObjectContainer,openfl__display__DisplayObject);
openfl__display__DisplayObject openfl_display_DisplayObjectContainer_removeChild(openfl__display__DisplayObjectContainer,openfl__display__DisplayObject);
#include <_std/EReg.h>
#include <openfl/net/URLRequest.h>
extern String s$_blank;
extern String s$;
extern hl_type t$EReg;
extern String s$_https_;
void EReg_new(EReg,String,String);
bool EReg_match(EReg,String);
extern String s$http_;
extern hl_type t$openfl_net_URLRequest;
String String___add__(String,String);
void openfl_net_URLRequest_new(openfl__net__URLRequest,String);
void openfl_Lib_getURL(openfl__net__URLRequest,String);
#include <openfl/display/MovieClip.h>
void flixel_FlxG_initRenderMethod(void);
openfl__display__MovieClip openfl_Lib_get_current(void);
extern hl_type t$flixel_input_keyboard_FlxKeyboard;
void flixel_input_keyboard_FlxKeyboard_new(flixel__input__keyboard__FlxKeyboard);
flixel__input__keyboard__FlxKeyboard flixel_system_frontEnds_InputFrontEnd_add_flixel_input_keyboard_FlxKeyboard(flixel__system__frontEnds__InputFrontEnd,flixel__input__keyboard__FlxKeyboard);
extern hl_type t$flixel_input_mouse_FlxMouse;
void flixel_input_mouse_FlxMouse_new(flixel__input__mouse__FlxMouse,openfl__display__Sprite);
flixel__input__mouse__FlxMouse flixel_system_frontEnds_InputFrontEnd_add_flixel_input_mouse_FlxMouse(flixel__system__frontEnds__InputFrontEnd,flixel__input__mouse__FlxMouse);
flixel__input__mouse__FlxMouse flixel_FlxG_set_mouse(flixel__input__mouse__FlxMouse);
extern hl_type t$flixel_input_gamepad_FlxGamepadManager;
void flixel_input_gamepad_FlxGamepadManager_new(flixel__input__gamepad__FlxGamepadManager);
flixel__input__gamepad__FlxGamepadManager flixel_system_frontEnds_InputFrontEnd_add_flixel_input_gamepad_FlxGamepadManager(flixel__system__frontEnds__InputFrontEnd,flixel__input__gamepad__FlxGamepadManager);
void flixel_FlxG_initSave(void);
extern hl_type t$flixel_system_frontEnds_PluginFrontEnd;
void flixel_system_frontEnds_PluginFrontEnd_new(flixel__system__frontEnds__PluginFrontEnd);
extern hl_type t$flixel_system_frontEnds_VCRFrontEnd;
void flixel_system_frontEnds_VCRFrontEnd_new(flixel__system__frontEnds__VCRFrontEnd);
extern hl_type t$flixel_system_frontEnds_SoundFrontEnd;
void flixel_system_frontEnds_SoundFrontEnd_new(flixel__system__frontEnds__SoundFrontEnd);
#include <lime/graphics/RenderContext.h>
extern venum* g$flixel_FlxRenderMethod_BLITTING;
extern venum* g$b4117e8;
extern flixel__$FlxObject g$_flixel_FlxObject;
#include <flixel/util/FlxSaveStatus.h>
#include <haxe/ds/StringMap.h>
#include <lime/app/Application.h>
extern String s$file;
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
String flixel_util_FlxSave_validate(String);
bool flixel_util_FlxSave_bind(flixel__util__FlxSave,String,String);
bool flixel_util_FlxSave_isEmpty(flixel__util__FlxSave);
extern String s$flixel;
bool flixel_util_FlxSave_mergeDataFrom(flixel__util__FlxSave,String,String,bool*,bool*,int*);
double Math_random(void);
void flixel_system_frontEnds_BitmapFrontEnd_reset(flixel__system__frontEnds__BitmapFrontEnd);
void flixel_system_frontEnds_InputFrontEnd_reset(flixel__system__frontEnds__InputFrontEnd);
void flixel_system_frontEnds_SoundFrontEnd_destroy(flixel__system__frontEnds__SoundFrontEnd,bool*);
#include <openfl/events/Event.h>
void flixel_FlxGame_onResize(flixel__FlxGame,openfl__events__Event);
flixel__input__mouse__FlxMouse flixel_system_frontEnds_InputFrontEnd_replace_flixel_input_mouse_FlxMouse(flixel__system__frontEnds__InputFrontEnd,flixel__input__mouse__FlxMouse,flixel__input__mouse__FlxMouse);
void flixel_input_mouse_FlxMouse_destroy(flixel__input__mouse__FlxMouse);
double openfl_display_Stage_set_frameRate(openfl__display__Stage,double);
vdynamic* openfl_display_Stage_get_displayState(openfl__display__Stage);
extern hl_type t$_i32;
vdynamic* openfl_display_Stage_set_displayState(openfl__display__Stage,vdynamic*);

bool flixel_FlxG_collide__$1(vclosure* r0,vdynamic* r1,vdynamic* r2) {
	bool r5;
	flixel__FlxObject r3, r4;
	r3 = (flixel__FlxObject)hl_dyn_castp(&r1,&t$_dyn,&t$flixel_FlxObject);
	r4 = (flixel__FlxObject)hl_dyn_castp(&r2,&t$_dyn,&t$flixel_FlxObject);
	r5 = r0->hasValue ? ((bool (*)(vdynamic*,flixel__FlxObject,flixel__FlxObject))r0->fun)((vdynamic*)r0->value,r3,r4) : ((bool (*)(flixel__FlxObject,flixel__FlxObject))r0->fun)(r3,r4);
	return r5;
}

void flixel_FlxG_resizeGame(int r0,int r1) {
	flixel__system__scaleModes__BaseScaleMode r3;
	flixel__$FlxG r4;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r4->scaleMode;
	if( r3 == NULL ) hl_null_access();
	flixel_system_scaleModes_BaseScaleMode_onMeasure(r3,r0,r1);
	return;
}

void flixel_FlxG_resizeWindow(int r0,int r1) {
	openfl__display__Application r4;
	lime__ui__Window r3;
	r4 = openfl_Lib_get_application();
	if( r4 == NULL ) hl_null_access();
	r3 = r4->__window;
	if( r3 == NULL ) hl_null_access();
	lime_ui_Window_resize(r3,r0,r1);
	return;
}

void flixel_FlxG_resetGame() {
	bool r2;
	flixel__$FlxG r1;
	flixel__FlxGame r0;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r0 = r1->game;
	if( r0 == NULL ) hl_null_access();
	r2 = true;
	r0->_resetGame = r2;
	return;
}

void flixel_FlxG_switchState__$1(venum* r0) {
	flixel__FlxState r2, r5;
	flixel__$FlxG r4;
	flixel__FlxGame r3;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r4->game;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->_state;
	r5 = ((Enumt$ctx_0d1aa73*)r0)->p1;
	if( r2 != r5 ) goto label$7b92ddc_5_11;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r4->game;
	if( r3 == NULL ) hl_null_access();
	r2 = ((Enumt$ctx_0d1aa73*)r0)->p0;
	r3->_requestedState = r2;
	label$7b92ddc_5_11:
	return;
}

void flixel_FlxG_switchState(flixel__FlxState r0) {
	String r7;
	flixel__FlxState r1, r6;
	venum *r10;
	bool r8;
	flixel__$FlxG r3;
	vclosure *r9;
	vdynamic *r5;
	flixel__FlxGame r2;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r2 = r3->game;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->_state;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r2 = r3->game;
	if( r2 == NULL ) hl_null_access();
	r6 = r2->_state;
	r7 = (String)s$switchTo;
	r5 = Reflect_field(((vdynamic*)r6),r7);
	if( r5 == NULL ) hl_null_access();
	{
		vdynamic *args[] = {(vdynamic*)r0};
		r5 = (vdynamic*)hl_dyn_call((vclosure*)r5,args,1);
	}
	r8 = (bool)hl_dyn_casti(&r5,&t$_dyn,&t$_bool);
	if( !r8 ) goto label$7b92ddc_6_24;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r2 = r3->game;
	if( r2 == NULL ) hl_null_access();
	r6 = r2->_state;
	if( r6 == NULL ) hl_null_access();
	r10 = hl_alloc_enum(&t$ctx_0d1aa73,0);
	((Enumt$ctx_0d1aa73*)r10)->p0 = (flixel__FlxState)r0;
	((Enumt$ctx_0d1aa73*)r10)->p1 = (flixel__FlxState)r1;
	r9 = hl_alloc_closure_ptr(&t$fun_cb7fdbf,flixel_FlxG_switchState__$1,r10);
	flixel_FlxState_startOutro(r6,r9);
	label$7b92ddc_6_24:
	return;
}

void flixel_FlxG_resetState__$1(venum* r0) {
	flixel__FlxState r2, r5;
	flixel__$FlxG r4;
	flixel__FlxGame r3;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r4->game;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->_state;
	r5 = ((Enumt$ctx_0d1aa73*)r0)->p1;
	if( r2 != r5 ) goto label$7b92ddc_7_11;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r4->game;
	if( r3 == NULL ) hl_null_access();
	r2 = ((Enumt$ctx_0d1aa73*)r0)->p0;
	r3->_requestedState = r2;
	label$7b92ddc_7_11:
	return;
}

void flixel_FlxG_resetState() {
	String r15;
	bool *r11;
	flixel__FlxState r2, r13, r14;
	hl__Class r1;
	hl__types__ArrayObj r9;
	venum *r17;
	hl_type *r7;
	bool r10;
	flixel__$FlxG r4;
	vclosure *r16;
	hl__types__ArrayDyn r5;
	flixel__FlxGame r3;
	vdynamic *r0;
	int r8;
	varray *r6;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r4->game;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->_state;
	r1 = Type_getClass(((vdynamic*)r2));
	r7 = &t$_dyn;
	r8 = 0;
	r6 = hl_alloc_array(r7,r8);
	r9 = hl_types_ArrayObj_alloc(r6);
	r10 = true;
	r11 = &r10;
	r5 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r9),r11);
	r0 = Type_createInstance(r1,r5);
	r2 = (flixel__FlxState)hl_dyn_castp(&r0,&t$_dyn,&t$flixel_FlxState);
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r4->game;
	if( r3 == NULL ) hl_null_access();
	r13 = r3->_state;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r4->game;
	if( r3 == NULL ) hl_null_access();
	r14 = r3->_state;
	r15 = (String)s$switchTo;
	r0 = Reflect_field(((vdynamic*)r14),r15);
	if( r0 == NULL ) hl_null_access();
	{
		vdynamic *args[] = {(vdynamic*)r2};
		r0 = (vdynamic*)hl_dyn_call((vclosure*)r0,args,1);
	}
	r10 = (bool)hl_dyn_casti(&r0,&t$_dyn,&t$_bool);
	if( !r10 ) goto label$7b92ddc_8_38;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r4->game;
	if( r3 == NULL ) hl_null_access();
	r14 = r3->_state;
	if( r14 == NULL ) hl_null_access();
	r17 = hl_alloc_enum(&t$ctx_0d1aa73,0);
	((Enumt$ctx_0d1aa73*)r17)->p0 = (flixel__FlxState)r2;
	((Enumt$ctx_0d1aa73*)r17)->p1 = (flixel__FlxState)r13;
	r16 = hl_alloc_closure_ptr(&t$fun_cb7fdbf,flixel_FlxG_resetState__$1,r17);
	flixel_FlxState_startOutro(r14,r16);
	label$7b92ddc_8_38:
	return;
}

bool flixel_FlxG_overlap(flixel__FlxBasic r0,flixel__FlxBasic r1,vclosure* r2,vclosure* r3) {
	flixel__FlxState r6;
	bool r17;
	flixel__$FlxG r8;
	flixel__math__FlxRect r13;
	flixel__system__FlxQuadTree r11;
	double r12, r14, r15, r16;
	flixel__system__$FlxQuadTree r10;
	flixel__FlxGame r7;
	flixel__FlxBasic r5;
	int r9;
	if( r0 ) goto label$7b92ddc_9_6;
	r8 = (flixel__$FlxG)g$_flixel_FlxG;
	r7 = r8->game;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->_state;
	r0 = ((flixel__FlxBasic)r6);
	label$7b92ddc_9_6:
	if( r1 != r0 ) goto label$7b92ddc_9_9;
	r5 = NULL;
	r1 = r5;
	label$7b92ddc_9_9:
	r8 = (flixel__$FlxG)g$_flixel_FlxG;
	r9 = r8->worldDivisions;
	r10 = (flixel__system__$FlxQuadTree)g$_flixel_system_FlxQuadTree;
	r10->divisions = r9;
	r8 = (flixel__$FlxG)g$_flixel_FlxG;
	r13 = r8->worldBounds;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->x;
	r8 = (flixel__$FlxG)g$_flixel_FlxG;
	r13 = r8->worldBounds;
	if( r13 == NULL ) hl_null_access();
	r14 = r13->y;
	r8 = (flixel__$FlxG)g$_flixel_FlxG;
	r13 = r8->worldBounds;
	if( r13 == NULL ) hl_null_access();
	r15 = r13->width;
	r8 = (flixel__$FlxG)g$_flixel_FlxG;
	r13 = r8->worldBounds;
	if( r13 == NULL ) hl_null_access();
	r16 = r13->height;
	r11 = NULL;
	r11 = flixel_system_FlxQuadTree_recycle(r12,r14,r15,r16,r11);
	if( r11 == NULL ) hl_null_access();
	flixel_system_FlxQuadTree_load(r11,r0,r1,((vclosure*)r2),((vclosure*)r3));
	r17 = flixel_system_FlxQuadTree_execute(r11);
	flixel_system_FlxQuadTree_destroy(r11);
	return r17;
}

bool flixel_FlxG_pixelPerfectOverlap(flixel__FlxSprite r0,flixel__FlxSprite r1,int* r2,flixel__FlxCamera r3) {
	bool r5;
	int r4, r6;
	if( r2 ) goto label$7b92ddc_10_3;
	r4 = 255;
	goto label$7b92ddc_10_4;
	label$7b92ddc_10_3:
	r4 = *r2;
	label$7b92ddc_10_4:
	r6 = r4;
	r2 = &r6;
	r5 = flixel_util_FlxCollision_pixelPerfectCheck(r0,r1,r2,r3);
	return r5;
}

bool flixel_FlxG_collide(flixel__FlxBasic r0,flixel__FlxBasic r1,vclosure* r2) {
	bool r3;
	vclosure *r4, *r5;
	static vclosure cl$0 = { &t$fun_fce8c20, flixel_FlxObject_separate, 0 };
	r4 = &cl$0;
	if( r4 ) goto label$7b92ddc_11_4;
	r5 = NULL;
	goto label$7b92ddc_11_5;
	label$7b92ddc_11_4:
	r5 = hl_alloc_closure_ptr(&t$fun_a7c8055,flixel_FlxG_collide__$1,r4);
	label$7b92ddc_11_5:
	r3 = flixel_FlxG_overlap(r0,r1,r2,r5);
	return r3;
}

openfl__display__DisplayObject flixel_FlxG_addChildBelowMouse(openfl__display__DisplayObject r0,int* r1) {
	openfl__display__DisplayObject r10;
	flixel__$FlxG r5;
	flixel__FlxGame r4, r7;
	openfl__display__Sprite r6;
	int r2, r3, r8, r9;
	if( r1 ) goto label$7b92ddc_12_3;
	r2 = 0;
	goto label$7b92ddc_12_4;
	label$7b92ddc_12_3:
	r2 = *r1;
	label$7b92ddc_12_4:
	r5 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r5->game;
	if( r4 == NULL ) hl_null_access();
	r5 = (flixel__$FlxG)g$_flixel_FlxG;
	r7 = r5->game;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->_inputContainer;
	r3 = openfl_display_DisplayObjectContainer_getChildIndex(((openfl__display__DisplayObjectContainer)r4),((openfl__display__DisplayObject)r6));
	r5 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r5->game;
	if( r4 == NULL ) hl_null_access();
	r8 = openfl_display_DisplayObjectContainer_get_numChildren(((openfl__display__DisplayObjectContainer)r4));
	r1 = NULL;
	r9 = flixel_math_FlxMath_maxAdd(r3,r2,r8,r1);
	r5 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r5->game;
	if( r4 == NULL ) hl_null_access();
	r10 = openfl_display_DisplayObjectContainer_addChildAt(((openfl__display__DisplayObjectContainer)r4),r0,r9);
	return r0;
}

openfl__display__DisplayObject flixel_FlxG_removeChild(openfl__display__DisplayObject r0) {
	openfl__display__DisplayObject r4;
	bool r1;
	flixel__$FlxG r3;
	flixel__FlxGame r2;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r2 = r3->game;
	if( r2 == NULL ) hl_null_access();
	r1 = openfl_display_DisplayObjectContainer_contains(((openfl__display__DisplayObjectContainer)r2),r0);
	if( !r1 ) goto label$7b92ddc_13_9;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r2 = r3->game;
	if( r2 == NULL ) hl_null_access();
	r4 = openfl_display_DisplayObjectContainer_removeChild(((openfl__display__DisplayObjectContainer)r2),r0);
	label$7b92ddc_13_9:
	return r0;
}

flixel__effects__postprocess__PostProcess flixel_FlxG_addPostProcess(flixel__effects__postprocess__PostProcess r0) {
	return r0;
}

void flixel_FlxG_removePostProcess(flixel__effects__postprocess__PostProcess r0) {
	return;
}

void flixel_FlxG_openURL(String r0,String r1) {
	String r2, r6, r7;
	bool r4;
	EReg r5;
	openfl__net__URLRequest r8;
	if( r1 ) goto label$7b92ddc_16_3;
	r2 = (String)s$_blank;
	r1 = r2;
	label$7b92ddc_16_3:
	r2 = (String)s$;
	r5 = (EReg)hl_alloc_obj(&t$EReg);
	r6 = (String)s$_https_;
	r7 = (String)s$;
	EReg_new(r5,r6,r7);
	r4 = EReg_match(r5,r0);
	if( r4 ) goto label$7b92ddc_16_12;
	r6 = (String)s$http_;
	r2 = r6;
	label$7b92ddc_16_12:
	r8 = (openfl__net__URLRequest)hl_alloc_obj(&t$openfl_net_URLRequest);
	r6 = String___add__(r2,r0);
	openfl_net_URLRequest_new(r8,r6);
	openfl_Lib_getURL(r8,r1);
	return;
}

void flixel_FlxG_init(flixel__FlxGame r0,int r1,int r2) {
	flixel__input__mouse__FlxMouse r15;
	flixel__input__keyboard__FlxKeyboard r13;
	flixel__system__frontEnds__VCRFrontEnd r19;
	flixel__input__gamepad__FlxGamepadManager r17;
	flixel__system__scaleModes__BaseScaleMode r12;
	flixel__system__frontEnds__PluginFrontEnd r18;
	flixel__$FlxG r4;
	flixel__system__frontEnds__SoundFrontEnd r20;
	flixel__system__frontEnds__InputFrontEnd r14;
	openfl__display__MovieClip r10;
	openfl__display__Stage r9;
	double r5, r8;
	flixel__FlxGame r3;
	openfl__display__Sprite r16;
	int r6, r11;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r4->game = r0;
	r5 = (double)r1;
	r5 = hl_math_abs(r5);
	r6 = (int)r5;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r4->width = r6;
	r8 = (double)r2;
	r8 = hl_math_abs(r8);
	r6 = (int)r8;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r4->height = r6;
	flixel_FlxG_initRenderMethod();
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r6 = r4->width;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r4->initialWidth = r6;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r6 = r4->height;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r4->initialHeight = r6;
	r10 = openfl_Lib_get_current();
	if( r10 == NULL ) hl_null_access();
	r9 = r10->stage;
	if( r9 == NULL ) hl_null_access();
	r6 = r9->stageWidth;
	r10 = openfl_Lib_get_current();
	if( r10 == NULL ) hl_null_access();
	r9 = r10->stage;
	if( r9 == NULL ) hl_null_access();
	r11 = r9->stageHeight;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r12 = r4->scaleMode;
	if( r12 == NULL ) hl_null_access();
	flixel_system_scaleModes_BaseScaleMode_onMeasure(r12,r6,r11);
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r14 = r4->inputs;
	if( r14 == NULL ) hl_null_access();
	r13 = (flixel__input__keyboard__FlxKeyboard)hl_alloc_obj(&t$flixel_input_keyboard_FlxKeyboard);
	flixel_input_keyboard_FlxKeyboard_new(r13);
	r13 = flixel_system_frontEnds_InputFrontEnd_add_flixel_input_keyboard_FlxKeyboard(r14,r13);
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r4->keys = r13;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r14 = r4->inputs;
	if( r14 == NULL ) hl_null_access();
	r15 = (flixel__input__mouse__FlxMouse)hl_alloc_obj(&t$flixel_input_mouse_FlxMouse);
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r4->game;
	if( r3 == NULL ) hl_null_access();
	r16 = r3->_inputContainer;
	flixel_input_mouse_FlxMouse_new(r15,r16);
	r15 = flixel_system_frontEnds_InputFrontEnd_add_flixel_input_mouse_FlxMouse(r14,r15);
	r15 = flixel_FlxG_set_mouse(r15);
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r14 = r4->inputs;
	if( r14 == NULL ) hl_null_access();
	r17 = (flixel__input__gamepad__FlxGamepadManager)hl_alloc_obj(&t$flixel_input_gamepad_FlxGamepadManager);
	flixel_input_gamepad_FlxGamepadManager_new(r17);
	r17 = flixel_system_frontEnds_InputFrontEnd_add_flixel_input_gamepad_FlxGamepadManager(r14,r17);
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r4->gamepads = r17;
	flixel_FlxG_initSave();
	r18 = (flixel__system__frontEnds__PluginFrontEnd)hl_alloc_obj(&t$flixel_system_frontEnds_PluginFrontEnd);
	flixel_system_frontEnds_PluginFrontEnd_new(r18);
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r4->plugins = r18;
	r19 = (flixel__system__frontEnds__VCRFrontEnd)hl_alloc_obj(&t$flixel_system_frontEnds_VCRFrontEnd);
	flixel_system_frontEnds_VCRFrontEnd_new(r19);
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r4->vcr = r19;
	r20 = (flixel__system__frontEnds__SoundFrontEnd)hl_alloc_obj(&t$flixel_system_frontEnds_SoundFrontEnd);
	flixel_system_frontEnds_SoundFrontEnd_new(r20);
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r4->sound = r20;
	return;
}

void flixel_FlxG_initRenderMethod() {
	String r3;
	venum *r0, *r12, *r14;
	bool r13;
	lime__ui__Window r5;
	flixel__$FlxG r1;
	openfl__display__MovieClip r7;
	openfl__display__Stage r6;
	lime__graphics__RenderContext r4;
	flixel__$FlxObject r15;
	vbyte *r10, *r11;
	int r8, r9;
	r0 = (venum*)g$flixel_FlxRenderMethod_BLITTING;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r1->renderMethod = r0;
	r7 = openfl_Lib_get_current();
	if( r7 == NULL ) hl_null_access();
	r6 = r7->stage;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->window;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->context;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->type;
	if( !r3 ) goto label$7b92ddc_18_21;
	r8 = r3->length;
	r9 = 6;
	if( r8 != r9 ) goto label$7b92ddc_18_21;
	r10 = r3->bytes;
	r11 = (vbyte*)USTR("opengl");
	r8 = hl_string_compare(r10,r11,r8);
	r9 = 0;
	if( r8 == r9 ) goto label$7b92ddc_18_41;
	label$7b92ddc_18_21:
	if( !r3 ) goto label$7b92ddc_18_30;
	r8 = r3->length;
	r9 = 8;
	if( r8 != r9 ) goto label$7b92ddc_18_30;
	r10 = r3->bytes;
	r11 = (vbyte*)USTR("opengles");
	r8 = hl_string_compare(r10,r11,r8);
	r9 = 0;
	if( r8 == r9 ) goto label$7b92ddc_18_41;
	label$7b92ddc_18_30:
	if( !r3 ) goto label$7b92ddc_18_39;
	r8 = r3->length;
	r9 = 5;
	if( r8 != r9 ) goto label$7b92ddc_18_39;
	r10 = r3->bytes;
	r11 = (vbyte*)USTR("webgl");
	r8 = hl_string_compare(r10,r11,r8);
	r9 = 0;
	if( r8 == r9 ) goto label$7b92ddc_18_41;
	label$7b92ddc_18_39:
	r12 = (venum*)g$flixel_FlxRenderMethod_BLITTING;
	goto label$7b92ddc_18_42;
	label$7b92ddc_18_41:
	r12 = (venum*)g$b4117e8;
	label$7b92ddc_18_42:
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r1->renderMethod = r12;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r12 = r1->renderMethod;
	r14 = (venum*)g$flixel_FlxRenderMethod_BLITTING;
	if( r12 == r14 ) goto label$7b92ddc_18_50;
	r13 = false;
	goto label$7b92ddc_18_51;
	label$7b92ddc_18_50:
	r13 = true;
	label$7b92ddc_18_51:
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r1->renderBlit = r13;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r12 = r1->renderMethod;
	r14 = (venum*)g$b4117e8;
	if( r12 == r14 ) goto label$7b92ddc_18_59;
	r13 = false;
	goto label$7b92ddc_18_60;
	label$7b92ddc_18_59:
	r13 = true;
	label$7b92ddc_18_60:
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r1->renderTile = r13;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r13 = r1->renderBlit;
	r15 = (flixel__$FlxObject)g$_flixel_FlxObject;
	r15->defaultPixelPerfectPosition = r13;
	return;
}

void flixel_FlxG_initSave() {
	bool *r15, *r17;
	String r6, r7, r14;
	haxe__ds__StringMap r10;
	venum *r0;
	bool r8, r16;
	flixel__$FlxG r2;
	openfl__display__MovieClip r13;
	openfl__display__Stage r12;
	lime__app__Application r11;
	flixel__util__FlxSave r1;
	int *r18;
	vdynamic *r9;
	int r4, r5;
	r2 = (flixel__$FlxG)g$_flixel_FlxG;
	r1 = r2->save;
	if( r1 == NULL ) hl_null_access();
	r0 = r1->status;
	if( r0 == NULL ) hl_null_access();
	r4 = HL__ENUM_INDEX__(r0);
	r5 = 1;
	if( r4 != r5 ) goto label$7b92ddc_19_12;
	r6 = ((flixel_util_FlxSaveStatus_BOUND*)r0)->p0;
	r7 = ((flixel_util_FlxSaveStatus_BOUND*)r0)->p1;
	r8 = true;
	goto label$7b92ddc_19_13;
	label$7b92ddc_19_12:
	r8 = false;
	label$7b92ddc_19_13:
	if( !r8 ) goto label$7b92ddc_19_15;
	return;
	label$7b92ddc_19_15:
	r13 = openfl_Lib_get_current();
	if( r13 == NULL ) hl_null_access();
	r12 = r13->stage;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->application;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->meta;
	if( r10 == NULL ) hl_null_access();
	r6 = (String)s$file;
	r9 = haxe_ds_StringMap_get(r10,r6);
	r6 = (String)r9;
	r2 = (flixel__$FlxG)g$_flixel_FlxG;
	r1 = r2->save;
	if( r1 == NULL ) hl_null_access();
	r7 = flixel_util_FlxSave_validate(r6);
	r14 = NULL;
	r8 = flixel_util_FlxSave_bind(r1,r7,r14);
	r2 = (flixel__$FlxG)g$_flixel_FlxG;
	r1 = r2->save;
	if( r1 == NULL ) hl_null_access();
	r8 = flixel_util_FlxSave_isEmpty(r1);
	if( !r8 ) goto label$7b92ddc_19_48;
	r2 = (flixel__$FlxG)g$_flixel_FlxG;
	r1 = r2->save;
	if( r1 == NULL ) hl_null_access();
	r7 = (String)s$flixel;
	r14 = NULL;
	r8 = false;
	r15 = &r8;
	r16 = false;
	r17 = &r16;
	r18 = NULL;
	r8 = flixel_util_FlxSave_mergeDataFrom(r1,r7,r14,r15,r17,r18);
	label$7b92ddc_19_48:
	return;
}

void flixel_FlxG_reset() {
	bool *r16;
	bool r15, r17;
	flixel__system__frontEnds__BitmapFrontEnd r12;
	flixel__$FlxG r1;
	flixel__system__frontEnds__SoundFrontEnd r14;
	flixel__system__frontEnds__InputFrontEnd r13;
	flixel__math__FlxRandom r0;
	flixel__math__FlxRect r18;
	double r3, r4, r8, r9;
	int r5, r6, r7, r10, r11;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r0 = r1->random;
	r3 = Math_random();
	r4 = 2147483647.;
	r3 = r3 * r4;
	r5 = (int)r3;
	r7 = 1;
	if( r5 >= r7 ) goto label$7b92ddc_20_10;
	r4 = 1.;
	goto label$7b92ddc_20_11;
	label$7b92ddc_20_10:
	r4 = (double)r5;
	label$7b92ddc_20_11:
	r9 = 2147483646.;
	if( !(r9 < r4) ) goto label$7b92ddc_20_15;
	r8 = 2147483646.;
	goto label$7b92ddc_20_16;
	label$7b92ddc_20_15:
	r8 = r4;
	label$7b92ddc_20_16:
	r6 = (int)r8;
	r10 = 1;
	if( r6 >= r10 ) goto label$7b92ddc_20_21;
	r4 = 1.;
	goto label$7b92ddc_20_22;
	label$7b92ddc_20_21:
	r4 = (double)r6;
	label$7b92ddc_20_22:
	r9 = 2147483646.;
	if( !(r9 < r4) ) goto label$7b92ddc_20_26;
	r8 = 2147483646.;
	goto label$7b92ddc_20_27;
	label$7b92ddc_20_26:
	r8 = r4;
	label$7b92ddc_20_27:
	r7 = (int)r8;
	if( r0 == NULL ) hl_null_access();
	r11 = 1;
	if( r7 >= r11 ) goto label$7b92ddc_20_33;
	r4 = 1.;
	goto label$7b92ddc_20_34;
	label$7b92ddc_20_33:
	r4 = (double)r7;
	label$7b92ddc_20_34:
	r9 = 2147483646.;
	if( !(r9 < r4) ) goto label$7b92ddc_20_38;
	r8 = 2147483646.;
	goto label$7b92ddc_20_39;
	label$7b92ddc_20_38:
	r8 = r4;
	label$7b92ddc_20_39:
	r10 = (int)r8;
	r4 = (double)r10;
	r0->internalSeed = r4;
	r10 = (int)r4;
	r0->initialSeed = r10;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r12 = r1->bitmap;
	if( r12 == NULL ) hl_null_access();
	flixel_system_frontEnds_BitmapFrontEnd_reset(r12);
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r13 = r1->inputs;
	if( r13 == NULL ) hl_null_access();
	flixel_system_frontEnds_InputFrontEnd_reset(r13);
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r14 = r1->sound;
	if( r14 == NULL ) hl_null_access();
	r15 = true;
	r16 = &r15;
	flixel_system_frontEnds_SoundFrontEnd_destroy(r14,r16);
	r17 = true;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r1->autoPause = r17;
	r17 = true;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r1->fixedTimestep = r17;
	r3 = 1.;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r1->timeScale = r3;
	r3 = 0.;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r1->elapsed = r3;
	r3 = 0.10000000000000001;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r1->maxElapsed = r3;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r18 = r1->worldBounds;
	if( r18 == NULL ) hl_null_access();
	r3 = -10.;
	r18->x = r3;
	r3 = -10.;
	r18->y = r3;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r5 = r1->width;
	r6 = 20;
	r5 = r5 + r6;
	r3 = (double)r5;
	r18->width = r3;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r5 = r1->height;
	r6 = 20;
	r5 = r5 + r6;
	r3 = (double)r5;
	r18->height = r3;
	r5 = 6;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r1->worldDivisions = r5;
	return;
}

flixel__system__scaleModes__BaseScaleMode flixel_FlxG_set_scaleMode(flixel__system__scaleModes__BaseScaleMode r0) {
	openfl__events__Event r4;
	flixel__$FlxG r1;
	flixel__FlxGame r3;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r1->scaleMode = r0;
	r1 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r1->game;
	if( r3 == NULL ) hl_null_access();
	r4 = NULL;
	flixel_FlxGame_onResize(r3,r4);
	return r0;
}

flixel__input__mouse__FlxMouse flixel_FlxG_set_mouse(flixel__input__mouse__FlxMouse r0) {
	flixel__input__mouse__FlxMouse r2, r5;
	flixel__$FlxG r3;
	flixel__system__frontEnds__InputFrontEnd r4;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r2 = r3->mouse;
	if( r2 ) goto label$7b92ddc_22_12;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r3->inputs;
	if( r4 == NULL ) hl_null_access();
	r2 = flixel_system_frontEnds_InputFrontEnd_add_flixel_input_mouse_FlxMouse(r4,r0);
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r3->mouse = r2;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r2 = r3->mouse;
	return r2;
	label$7b92ddc_22_12:
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r2 = r3->mouse;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r3->inputs;
	if( r4 == NULL ) hl_null_access();
	r5 = flixel_system_frontEnds_InputFrontEnd_replace_flixel_input_mouse_FlxMouse(r4,r2,r0);
	if( !r5 ) goto label$7b92ddc_22_24;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r3->mouse = r5;
	if( r2 == NULL ) hl_null_access();
	flixel_input_mouse_FlxMouse_destroy(r2);
	return r0;
	label$7b92ddc_22_24:
	return r2;
}

int flixel_FlxG_set_updateFramerate(int r0) {
	bool r1;
	flixel__$FlxG r3;
	double r5, r6;
	flixel__FlxGame r4, r7;
	int r2;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r2 = r3->drawFramerate;
	if( r0 < r2 ) goto label$7b92ddc_23_5;
	r1 = false;
	goto label$7b92ddc_23_6;
	label$7b92ddc_23_5:
	r1 = true;
	label$7b92ddc_23_6:
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r3->updateFramerate = r0;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r3->game;
	if( r4 == NULL ) hl_null_access();
	r5 = 1000.;
	r6 = (double)r0;
	r5 = r5 / r6;
	r5 = hl_math_abs(r5);
	r4->_stepMS = r5;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r3->game;
	if( r4 == NULL ) hl_null_access();
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r7 = r3->game;
	if( r7 == NULL ) hl_null_access();
	r5 = r7->_stepMS;
	r6 = 1000.;
	r5 = r5 / r6;
	r4->_stepSeconds = r5;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r3->game;
	if( r4 == NULL ) hl_null_access();
	r5 = r4->_maxAccumulation;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r3->game;
	if( r4 == NULL ) hl_null_access();
	r6 = r4->_stepMS;
	if( !(r5 < r6) ) goto label$7b92ddc_23_43;
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r3->game;
	if( r4 == NULL ) hl_null_access();
	r3 = (flixel__$FlxG)g$_flixel_FlxG;
	r7 = r3->game;
	if( r7 == NULL ) hl_null_access();
	r5 = r7->_stepMS;
	r4->_maxAccumulation = r5;
	label$7b92ddc_23_43:
	return r0;
}

int flixel_FlxG_set_drawFramerate(int r0) {
	bool r1;
	flixel__$FlxG r4;
	openfl__display__Stage r7;
	double r5, r6, r9;
	flixel__FlxGame r8, r10;
	int r2, r3;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r3 = r4->updateFramerate;
	if( r0 > r3 ) goto label$7b92ddc_24_5;
	r1 = false;
	goto label$7b92ddc_24_6;
	label$7b92ddc_24_5:
	r1 = true;
	label$7b92ddc_24_6:
	r5 = (double)r0;
	r5 = hl_math_abs(r5);
	r2 = (int)r5;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r4->drawFramerate = r2;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r8 = r4->game;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->stage;
	if( !r7 ) goto label$7b92ddc_24_25;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r8 = r4->game;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->stage;
	if( r7 == NULL ) hl_null_access();
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r2 = r4->drawFramerate;
	r6 = (double)r2;
	r6 = openfl_display_Stage_set_frameRate(r7,r6);
	label$7b92ddc_24_25:
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r8 = r4->game;
	if( r8 == NULL ) hl_null_access();
	r6 = 2000.;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r2 = r4->drawFramerate;
	r9 = (double)r2;
	r6 = r6 / r9;
	r9 = 1.;
	r6 = r6 - r9;
	r8->_maxAccumulation = r6;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r8 = r4->game;
	if( r8 == NULL ) hl_null_access();
	r6 = r8->_maxAccumulation;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r8 = r4->game;
	if( r8 == NULL ) hl_null_access();
	r9 = r8->_stepMS;
	if( !(r6 < r9) ) goto label$7b92ddc_24_53;
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r8 = r4->game;
	if( r8 == NULL ) hl_null_access();
	r4 = (flixel__$FlxG)g$_flixel_FlxG;
	r10 = r4->game;
	if( r10 == NULL ) hl_null_access();
	r6 = r10->_stepMS;
	r8->_maxAccumulation = r6;
	label$7b92ddc_24_53:
	return r0;
}

bool flixel_FlxG_get_fullscreen() {
	bool r5;
	openfl__display__MovieClip r2;
	openfl__display__Stage r1;
	vdynamic *r0, *r4;
	int r3;
	r2 = openfl_Lib_get_current();
	if( r2 == NULL ) hl_null_access();
	r1 = r2->stage;
	if( r1 == NULL ) hl_null_access();
	r0 = openfl_display_Stage_get_displayState(r1);
	r3 = 0;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r3;
	if( r0 == r4 || (r0 && r4 && (r0->v.i == r4->v.i)) ) goto label$7b92ddc_25_20;
	r2 = openfl_Lib_get_current();
	if( r2 == NULL ) hl_null_access();
	r1 = r2->stage;
	if( r1 == NULL ) hl_null_access();
	r0 = openfl_display_Stage_get_displayState(r1);
	r3 = 1;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r3;
	if( r0 == r4 || (r0 && r4 && (r0->v.i == r4->v.i)) ) goto label$7b92ddc_25_18;
	r5 = false;
	goto label$7b92ddc_25_19;
	label$7b92ddc_25_18:
	r5 = true;
	label$7b92ddc_25_19:
	return r5;
	label$7b92ddc_25_20:
	r5 = true;
	return r5;
}

bool flixel_FlxG_set_fullscreen(bool r0) {
	openfl__display__MovieClip r3;
	openfl__display__Stage r2;
	vdynamic *r1;
	int r4;
	r3 = openfl_Lib_get_current();
	if( r3 == NULL ) hl_null_access();
	r2 = r3->stage;
	if( r2 == NULL ) hl_null_access();
	if( !r0 ) goto label$7b92ddc_26_8;
	r4 = 0;
	r1 = hl_alloc_dynamic(&t$_i32);
	r1->v.i = r4;
	goto label$7b92ddc_26_10;
	label$7b92ddc_26_8:
	r4 = 2;
	r1 = hl_alloc_dynamic(&t$_i32);
	r1->v.i = r4;
	label$7b92ddc_26_10:
	r1 = openfl_display_Stage_set_displayState(r2,r1);
	return r0;
}

openfl__display__Stage flixel_FlxG_get_stage() {
	openfl__display__MovieClip r1;
	openfl__display__Stage r0;
	r1 = openfl_Lib_get_current();
	if( r1 == NULL ) hl_null_access();
	r0 = r1->stage;
	return r0;
}

flixel__FlxState flixel_FlxG_get_state() {
	flixel__FlxState r0;
	flixel__$FlxG r2;
	flixel__FlxGame r1;
	r2 = (flixel__$FlxG)g$_flixel_FlxG;
	r1 = r2->game;
	if( r1 == NULL ) hl_null_access();
	r0 = r1->_state;
	return r0;
}

bool flixel_FlxG_get_onMobile() {
	bool r0;
	r0 = false;
	return r0;
}

