// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__display3D___internal__Context3DState
#define INC_openfl__display3D___internal__Context3DState
typedef struct _openfl__display3D___internal__$Context3DState *openfl__display3D___internal__$Context3DState;
typedef struct _openfl__display3D___internal__Context3DState *openfl__display3D___internal__Context3DState;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <openfl/display3D/Program3D.h>
#include <openfl/display3D/textures/TextureBase.h>
#include <hl/types/ArrayObj.h>
#include <openfl/geom/Rectangle.h>
#include <openfl/display/Shader.h>
#include <lime/graphics/opengl/GLObject.h>


struct _openfl__display3D___internal__$Context3DState {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _openfl__display3D___internal__Context3DState {
	hl_type *$type;
	bool backBufferEnableDepthAndStencil;
	vdynamic* blendDestinationAlphaFactor;
	vdynamic* blendSourceAlphaFactor;
	vdynamic* blendDestinationRGBFactor;
	vdynamic* blendSourceRGBFactor;
	bool colorMaskRed;
	bool colorMaskGreen;
	bool colorMaskBlue;
	bool colorMaskAlpha;
	vdynamic* culling;
	vdynamic* depthCompareMode;
	bool depthMask;
	openfl__display3D__Program3D program;
	openfl__display3D__textures__TextureBase renderToTexture;
	int renderToTextureAntiAlias;
	bool renderToTextureDepthStencil;
	int renderToTextureSurfaceSelector;
	hl__types__ArrayObj samplerStates;
	bool scissorEnabled;
	openfl__geom__Rectangle scissorRectangle;
	vdynamic* stencilCompareMode;
	vdynamic* stencilDepthFail;
	vdynamic* stencilFail;
	vdynamic* stencilPass;
	int stencilReadMask;
	int stencilReferenceValue;
	vdynamic* stencilTriangleFace;
	int stencilWriteMask;
	hl__types__ArrayObj textures;
	openfl__display__Shader shader;
	lime__graphics__opengl__GLObject __currentGLArrayBuffer;
	lime__graphics__opengl__GLObject __currentGLElementArrayBuffer;
	lime__graphics__opengl__GLObject __currentGLFramebuffer;
	lime__graphics__opengl__GLObject __currentGLTexture2D;
	lime__graphics__opengl__GLObject __currentGLTextureCubeMap;
	bool __enableGLBlend;
	bool __enableGLCullFace;
	bool __enableGLDepthTest;
	bool __enableGLScissorTest;
	bool __enableGLStencilTest;
	bool __frontFaceGLCCW;
	int __glBlendEquation;
	lime__graphics__opengl__GLObject __primaryGLFramebuffer;
	lime__graphics__opengl__GLObject __rttDepthGLRenderbuffer;
	lime__graphics__opengl__GLObject __rttGLFramebuffer;
	lime__graphics__opengl__GLObject __rttGLRenderbuffer;
	lime__graphics__opengl__GLObject __rttStencilGLRenderbuffer;
};
#endif

