// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/Exception.h>
varray* haxe_NativeStackTrace_exceptionStack(void);
#include <hl/natives.h>
extern hl_type t$hl_symbol;
String haxe_Exception_get_message(haxe__Exception);

void haxe_Exception_new(haxe__Exception r0,String r1,haxe__Exception r2,vdynamic* r3) {
	hl_type *r8;
	int r6, r7;
	varray *r5;
	r0->__exceptionMessage = r1;
	r0->__previousException = r2;
	if( !r3 ) goto label$2937a61_1_7;
	r5 = haxe_NativeStackTrace_exceptionStack();
	r0->__nativeStack = r5;
	r0->__nativeException = r3;
	goto label$2937a61_1_14;
	label$2937a61_1_7:
	r5 = NULL;
	r6 = hl_call_stack_raw(r5);
	r8 = &t$hl_symbol;
	r5 = hl_alloc_array(r8,r6);
	r7 = hl_call_stack_raw(r5);
	r0->__nativeStack = r5;
	r0->__nativeException = ((vdynamic*)r0);
	label$2937a61_1_14:
	return;
}

vbyte* haxe_Exception___string(haxe__Exception r0) {
	String r2;
	vbyte *r1;
	r2 = ((String (*)(haxe__Exception))r0->$type->vobj_proto[0])(r0);
	if( r2 == NULL ) hl_null_access();
	r1 = r2->bytes;
	return r1;
}

String haxe_Exception_toString(haxe__Exception r0) {
	String r1;
	r1 = haxe_Exception_get_message(r0);
	return r1;
}

String haxe_Exception_get_message(haxe__Exception r0) {
	String r1;
	r1 = r0->__exceptionMessage;
	return r1;
}

