// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/utils/_DataPointer/DataPointer_Impl_.h>
#include <hl/natives.h>
double lime_utils__DataPointer_DataPointer_Impl__fromBytes(haxe__io__Bytes);
haxe__io__Bytes haxe_io_Bytes_ofData(haxe__io__BytesDataImpl);
double lime_system__CFFIPointer_CFFIPointer_Impl__get(vdynamic*);
haxe__io__Bytes lime_utils__Bytes_Bytes_Impl__fromFile(String);
extern hl_type t$_f64;

double lime_utils__DataPointer_DataPointer_Impl___new(double r0) {
	return r0;
}

double lime_utils__DataPointer_DataPointer_Impl__fromInt(int r0) {
	double r1, r2;
	r1 = (double)r0;
	r2 = lime_utils__DataPointer_DataPointer_Impl___new(r1);
	return r2;
}

double lime_utils__DataPointer_DataPointer_Impl__fromBytesPointer(lime__utils__BytePointerData r0) {
	haxe__io__Bytes r1;
	double r3, r4;
	int r2;
	if( !r0 ) goto label$95d0d19_3_4;
	if( r0 == NULL ) hl_null_access();
	r1 = r0->bytes;
	if( r1 ) goto label$95d0d19_3_7;
	label$95d0d19_3_4:
	r2 = 0;
	r3 = (double)r2;
	return r3;
	label$95d0d19_3_7:
	r1 = r0->bytes;
	r2 = r0->offset;
	r3 = lime_hl_bytes_get_data_pointer_offset(r1,r2);
	r4 = lime_utils__DataPointer_DataPointer_Impl___new(r3);
	return r4;
}

double lime_utils__DataPointer_DataPointer_Impl__fromArrayBufferView(lime__utils__ArrayBufferView r0) {
	haxe__io__Bytes r3;
	double r2, r4;
	int r1;
	if( r0 ) goto label$95d0d19_4_4;
	r1 = 0;
	r2 = (double)r1;
	return r2;
	label$95d0d19_4_4:
	if( r0 == NULL ) hl_null_access();
	r3 = r0->buffer;
	r1 = r0->byteOffset;
	r2 = lime_hl_bytes_get_data_pointer_offset(r3,r1);
	r4 = lime_utils__DataPointer_DataPointer_Impl___new(r2);
	return r4;
}

double lime_utils__DataPointer_DataPointer_Impl__fromArrayBuffer(haxe__io__Bytes r0) {
	double r2;
	int r1;
	if( r0 ) goto label$95d0d19_5_4;
	r1 = 0;
	r2 = (double)r1;
	return r2;
	label$95d0d19_5_4:
	r2 = lime_utils__DataPointer_DataPointer_Impl__fromBytes(r0);
	return r2;
}

double lime_utils__DataPointer_DataPointer_Impl__fromBytes(haxe__io__Bytes r0) {
	double r2, r3;
	int r1;
	if( r0 ) goto label$95d0d19_6_4;
	r1 = 0;
	r2 = (double)r1;
	return r2;
	label$95d0d19_6_4:
	r2 = lime_hl_bytes_get_data_pointer(r0);
	r3 = lime_utils__DataPointer_DataPointer_Impl___new(r2);
	return r3;
}

double lime_utils__DataPointer_DataPointer_Impl__fromBytesData(haxe__io__BytesDataImpl r0) {
	haxe__io__Bytes r3;
	double r2;
	int r1;
	if( r0 ) goto label$95d0d19_7_4;
	r1 = 0;
	r2 = (double)r1;
	return r2;
	label$95d0d19_7_4:
	r3 = haxe_io_Bytes_ofData(r0);
	r2 = lime_utils__DataPointer_DataPointer_Impl__fromBytes(r3);
	return r2;
}

double lime_utils__DataPointer_DataPointer_Impl__fromLimeBytes(haxe__io__Bytes r0) {
	double r1;
	r1 = lime_utils__DataPointer_DataPointer_Impl__fromBytes(r0);
	return r1;
}

double lime_utils__DataPointer_DataPointer_Impl__fromCFFIPointer(vdynamic* r0) {
	double r2;
	int r1;
	if( r0 ) goto label$95d0d19_9_4;
	r1 = 0;
	r2 = (double)r1;
	return r2;
	label$95d0d19_9_4:
	r2 = lime_system__CFFIPointer_CFFIPointer_Impl__get(r0);
	r2 = lime_utils__DataPointer_DataPointer_Impl___new(r2);
	return r2;
}

double lime_utils__DataPointer_DataPointer_Impl__fromFile(String r0) {
	haxe__io__Bytes r2;
	double r1;
	r2 = lime_utils__Bytes_Bytes_Impl__fromFile(r0);
	r1 = lime_utils__DataPointer_DataPointer_Impl__fromBytes(r2);
	return r1;
}

double lime_utils__DataPointer_DataPointer_Impl____withOffset(double r0,int r1) {
	double r2, r3;
	int r4;
	r3 = 0.;
	if( r0 != r3 ) goto label$95d0d19_11_5;
	r4 = 0;
	r2 = (double)r4;
	return r2;
	label$95d0d19_11_5:
	r2 = lime_hl_data_pointer_offset(r0,r1);
	r3 = lime_utils__DataPointer_DataPointer_Impl___new(r2);
	return r3;
}

bool lime_utils__DataPointer_DataPointer_Impl__equals(double r0,int r1) {
	bool r2;
	double r3;
	r3 = (double)r1;
	if( r0 == r3 ) goto label$95d0d19_12_4;
	r2 = false;
	goto label$95d0d19_12_5;
	label$95d0d19_12_4:
	r2 = true;
	label$95d0d19_12_5:
	return r2;
}

bool lime_utils__DataPointer_DataPointer_Impl__equalsPointer(double r0,double r1) {
	bool r2;
	if( r0 == r1 ) goto label$95d0d19_13_3;
	r2 = false;
	goto label$95d0d19_13_4;
	label$95d0d19_13_3:
	r2 = true;
	label$95d0d19_13_4:
	return r2;
}

bool lime_utils__DataPointer_DataPointer_Impl__greaterThan(double r0,int r1) {
	bool r2;
	double r3;
	r3 = (double)r1;
	if( r0 > r3 ) goto label$95d0d19_14_4;
	r2 = false;
	goto label$95d0d19_14_5;
	label$95d0d19_14_4:
	r2 = true;
	label$95d0d19_14_5:
	return r2;
}

bool lime_utils__DataPointer_DataPointer_Impl__greaterThanPointer(double r0,vdynamic* r1) {
	bool r2;
	double r3, r5;
	vdynamic *r4;
	r4 = hl_alloc_dynamic(&t$_f64);
	r4->v.d = r0;
	r3 = lime_system__CFFIPointer_CFFIPointer_Impl__get(r4);
	r5 = lime_system__CFFIPointer_CFFIPointer_Impl__get(r1);
	if( r3 > r5 ) goto label$95d0d19_15_6;
	r2 = false;
	goto label$95d0d19_15_7;
	label$95d0d19_15_6:
	r2 = true;
	label$95d0d19_15_7:
	return r2;
}

bool lime_utils__DataPointer_DataPointer_Impl__greaterThanOrEqual(double r0,int r1) {
	bool r2;
	double r3;
	r3 = (double)r1;
	if( r0 >= r3 ) goto label$95d0d19_16_4;
	r2 = false;
	goto label$95d0d19_16_5;
	label$95d0d19_16_4:
	r2 = true;
	label$95d0d19_16_5:
	return r2;
}

bool lime_utils__DataPointer_DataPointer_Impl__greaterThanOrEqualPointer(double r0,vdynamic* r1) {
	bool r2;
	double r3, r5;
	vdynamic *r4;
	r4 = hl_alloc_dynamic(&t$_f64);
	r4->v.d = r0;
	r3 = lime_system__CFFIPointer_CFFIPointer_Impl__get(r4);
	r5 = lime_system__CFFIPointer_CFFIPointer_Impl__get(r1);
	if( r3 >= r5 ) goto label$95d0d19_17_6;
	r2 = false;
	goto label$95d0d19_17_7;
	label$95d0d19_17_6:
	r2 = true;
	label$95d0d19_17_7:
	return r2;
}

bool lime_utils__DataPointer_DataPointer_Impl__lessThan(double r0,int r1) {
	bool r2;
	double r3;
	r3 = (double)r1;
	if( r0 < r3 ) goto label$95d0d19_18_4;
	r2 = false;
	goto label$95d0d19_18_5;
	label$95d0d19_18_4:
	r2 = true;
	label$95d0d19_18_5:
	return r2;
}

bool lime_utils__DataPointer_DataPointer_Impl__lessThanPointer(double r0,vdynamic* r1) {
	bool r2;
	double r3, r5;
	vdynamic *r4;
	r4 = hl_alloc_dynamic(&t$_f64);
	r4->v.d = r0;
	r3 = lime_system__CFFIPointer_CFFIPointer_Impl__get(r4);
	r5 = lime_system__CFFIPointer_CFFIPointer_Impl__get(r1);
	if( r3 < r5 ) goto label$95d0d19_19_6;
	r2 = false;
	goto label$95d0d19_19_7;
	label$95d0d19_19_6:
	r2 = true;
	label$95d0d19_19_7:
	return r2;
}

bool lime_utils__DataPointer_DataPointer_Impl__lessThanOrEqual(double r0,int r1) {
	bool r2;
	double r3;
	r3 = (double)r1;
	if( r0 <= r3 ) goto label$95d0d19_20_4;
	r2 = false;
	goto label$95d0d19_20_5;
	label$95d0d19_20_4:
	r2 = true;
	label$95d0d19_20_5:
	return r2;
}

bool lime_utils__DataPointer_DataPointer_Impl__lessThanOrEqualPointer(double r0,vdynamic* r1) {
	bool r2;
	double r3, r5;
	vdynamic *r4;
	r4 = hl_alloc_dynamic(&t$_f64);
	r4->v.d = r0;
	r3 = lime_system__CFFIPointer_CFFIPointer_Impl__get(r4);
	r5 = lime_system__CFFIPointer_CFFIPointer_Impl__get(r1);
	if( r3 <= r5 ) goto label$95d0d19_21_6;
	r2 = false;
	goto label$95d0d19_21_7;
	label$95d0d19_21_6:
	r2 = true;
	label$95d0d19_21_7:
	return r2;
}

bool lime_utils__DataPointer_DataPointer_Impl__notEquals(double r0,int r1) {
	bool r2;
	double r3;
	r3 = (double)r1;
	if( r0 != r3 ) goto label$95d0d19_22_4;
	r2 = false;
	goto label$95d0d19_22_5;
	label$95d0d19_22_4:
	r2 = true;
	label$95d0d19_22_5:
	return r2;
}

bool lime_utils__DataPointer_DataPointer_Impl__notEqualsPointer(double r0,double r1) {
	bool r2;
	if( r0 != r1 ) goto label$95d0d19_23_3;
	r2 = false;
	goto label$95d0d19_23_4;
	label$95d0d19_23_3:
	r2 = true;
	label$95d0d19_23_4:
	return r2;
}

double lime_utils__DataPointer_DataPointer_Impl__plus(double r0,int r1) {
	double r2;
	r2 = lime_utils__DataPointer_DataPointer_Impl____withOffset(r0,r1);
	return r2;
}

double lime_utils__DataPointer_DataPointer_Impl__plusPointer(double r0,double r1) {
	double r2;
	int r3;
	r3 = (int)r1;
	r2 = lime_utils__DataPointer_DataPointer_Impl____withOffset(r0,r3);
	return r2;
}

double lime_utils__DataPointer_DataPointer_Impl__minus(double r0,int r1) {
	double r2;
	int r3;
	r3 = -r1;
	r2 = lime_utils__DataPointer_DataPointer_Impl____withOffset(r0,r3);
	return r2;
}

double lime_utils__DataPointer_DataPointer_Impl__minusPointer(double r0,double r1) {
	double r2;
	int r3;
	r3 = (int)r1;
	r3 = -r3;
	r2 = lime_utils__DataPointer_DataPointer_Impl____withOffset(r0,r3);
	return r2;
}

