// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__system__debug__Tooltip
#define INC_flixel__system__debug__Tooltip
typedef struct _flixel__system__debug__$Tooltip *flixel__system__debug__$Tooltip;
typedef struct _flixel__system__debug__Tooltip *flixel__system__debug__Tooltip;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>
#include <openfl/display/Sprite.h>
#include <flixel/system/debug/TooltipOverlay.h>


struct _flixel__system__debug__$Tooltip {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	hl__types__ArrayObj _tooltips;
	openfl__display__Sprite _container;
	vclosure* init;
	vclosure* add;
	vclosure* remove;
};
struct _flixel__system__debug__Tooltip {
	hl_type *$type;
};
#endif

