// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime___internal__backend__native__KeyEventInfo
#define INC_lime___internal__backend__native__KeyEventInfo
typedef struct _lime___internal__backend__native__$KeyEventInfo *lime___internal__backend__native__$KeyEventInfo;
typedef struct _lime___internal__backend__native__KeyEventInfo *lime___internal__backend__native__KeyEventInfo;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime___internal__backend__native__$KeyEventInfo {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime___internal__backend__native__KeyEventInfo {
	hl_type *$type;
	double keyCode;
	int modifier;
	int type;
	int windowID;
};
#endif

