// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/net/_HTTPRequest/AbstractHTTPRequest.h>
extern String s$c71c861;
extern hl_type t$haxe_ds_StringMap;
void haxe_ds_StringMap_new(haxe__ds__StringMap);
extern hl_type t$lime_net_HTTPRequestHeader;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern String s$GET;
extern hl_type t$lime__internal_backend_native_NativeHTTPRequest;
void lime__internal_backend_native_NativeHTTPRequest_new(lime___internal__backend__native__NativeHTTPRequest);
extern hl_type t$vrt_ccc308a;
void lime__internal_backend_native_NativeHTTPRequest_init(lime___internal__backend__native__NativeHTTPRequest,vvirtual*);
void lime__internal_backend_native_NativeHTTPRequest_cancel(lime___internal__backend__native__NativeHTTPRequest);
#include <lime/app/Future.h>

void lime_net__HTTPRequest_AbstractHTTPRequest_new(lime__net___HTTPRequest__AbstractHTTPRequest r0,String r1) {
	String r2;
	vvirtual *r11;
	hl__types__ArrayObj r6;
	haxe__ds__StringMap r4;
	hl_type *r8;
	bool r3;
	lime___internal__backend__native__NativeHTTPRequest r10;
	int r9;
	varray *r7;
	r0->uri = r1;
	r2 = (String)s$c71c861;
	r0->contentType = r2;
	r3 = true;
	r0->followRedirects = r3;
	r3 = false;
	r0->enableResponseHeaders = r3;
	r4 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r4);
	r0->formData = r4;
	r8 = &t$lime_net_HTTPRequestHeader;
	r9 = 0;
	r7 = hl_alloc_array(r8,r9);
	r6 = hl_types_ArrayObj_alloc(r7);
	r0->headers = r6;
	r2 = (String)s$GET;
	r0->method = r2;
	r9 = 30000;
	r0->timeout = r9;
	r3 = false;
	r0->withCredentials = r3;
	r3 = true;
	r0->manageCookies = r3;
	r10 = (lime___internal__backend__native__NativeHTTPRequest)hl_alloc_obj(&t$lime__internal_backend_native_NativeHTTPRequest);
	lime__internal_backend_native_NativeHTTPRequest_new(r10);
	r0->__backend = r10;
	r10 = r0->__backend;
	if( r10 == NULL ) hl_null_access();
	r11 = r0->f$16;
	if( r11 ) goto label$f81c787_1_32;
	r11 = hl_to_virtual(&t$vrt_ccc308a,(vdynamic*)r0);
	r0->f$16 = r11;
	label$f81c787_1_32:
	lime__internal_backend_native_NativeHTTPRequest_init(r10,r11);
	return;
}

void lime_net__HTTPRequest_AbstractHTTPRequest_cancel(lime__net___HTTPRequest__AbstractHTTPRequest r0) {
	lime___internal__backend__native__NativeHTTPRequest r2;
	r2 = r0->__backend;
	if( r2 == NULL ) hl_null_access();
	lime__internal_backend_native_NativeHTTPRequest_cancel(r2);
	return;
}

lime__app__Future lime_net__HTTPRequest_AbstractHTTPRequest_load(lime__net___HTTPRequest__AbstractHTTPRequest r0,String r1) {
	lime__app__Future r2;
	r2 = NULL;
	return r2;
}

