// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__input__FlxPointer
#define INC_flixel__input__FlxPointer
typedef struct _flixel__input__$FlxPointer *flixel__input__$FlxPointer;
typedef struct _flixel__input__FlxPointer *flixel__input__FlxPointer;
#include <flixel/FlxCamera.h>
#include <hl/types/ArrayObj.h>
#include <flixel/input/FlxPointer.h>
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <flixel/math/FlxBasePoint.h>


typedef struct {
	HL__ENUM_CONSTRUCT__
	flixel__FlxCamera p0;
	hl__types__ArrayObj p1;
	flixel__input__FlxPointer p2;
} Enumt$ctx_25edb5a;
struct _flixel__input__$FlxPointer {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	flixel__math__FlxBasePoint _cachedPoint;
};
struct _flixel__input__FlxPointer {
	hl_type *$type;
	int x;
	int y;
	int screenX;
	int screenY;
	int _globalScreenX;
	int _globalScreenY;
};
#endif

