// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__utils___AGALMiniAssembler__OpCode
#define INC_openfl__utils___AGALMiniAssembler__OpCode
typedef struct _openfl__utils___AGALMiniAssembler__$OpCode *openfl__utils___AGALMiniAssembler__$OpCode;
typedef struct _openfl__utils___AGALMiniAssembler__OpCode *openfl__utils___AGALMiniAssembler__OpCode;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _openfl__utils___AGALMiniAssembler__$OpCode {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _openfl__utils___AGALMiniAssembler__OpCode {
	hl_type *$type;
	int emitCode;
	int flags;
	String name;
	int numRegister;
};
#endif

