// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__utils___AGALMiniAssembler__Sampler
#define INC_openfl__utils___AGALMiniAssembler__Sampler
typedef struct _openfl__utils___AGALMiniAssembler__$Sampler *openfl__utils___AGALMiniAssembler__$Sampler;
typedef struct _openfl__utils___AGALMiniAssembler__Sampler *openfl__utils___AGALMiniAssembler__Sampler;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _openfl__utils___AGALMiniAssembler__$Sampler {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _openfl__utils___AGALMiniAssembler__Sampler {
	hl_type *$type;
	int flag;
	int mask;
	String name;
};
#endif

