// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__display___internal__Context3DElementType
#define INC_openfl__display___internal__Context3DElementType
typedef struct _openfl__display___internal__$Context3DElementType *openfl__display___internal__$Context3DElementType;
#include <hl/Enum.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>


struct _openfl__display___internal__$Context3DElementType {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __ename__;
	hl_bytes_map* __emap__;
	hl__types__ArrayObj __constructs__;
	varray* __evalues__;
};
#endif

