// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/display/_internal/Context3DBitmapData.h>
#include <openfl/display3D/Context3D.h>
#include <lime/_internal/backend/native/NativeOpenGLRenderContext.h>
#include <openfl/display/DisplayObjectShader.h>
#include <hl/types/ArrayBytes_Float.h>
#include <openfl/geom/Matrix.h>
#include <openfl/geom/ColorTransform.h>
#include <openfl/display3D/VertexBuffer3D.h>
#include <openfl/geom/Rectangle.h>
#include <openfl/display/DisplayObject.h>
#include <openfl/display/ShaderParameter_Float.h>
#include <openfl/display3D/IndexBuffer3D.h>
extern hl_type t$_i32;
void openfl_display_OpenGLRenderer___setBlendMode(openfl__display__OpenGLRenderer,vdynamic*);
#include <openfl/display/Shader.h>
void openfl_display_OpenGLRenderer_setShader(openfl__display__OpenGLRenderer,openfl__display__Shader);
void openfl_display_OpenGLRenderer_applyBitmapData(openfl__display__OpenGLRenderer,openfl__display__BitmapData,bool,bool*);
hl__types__ArrayBytes_Float openfl_display_OpenGLRenderer___getMatrix(openfl__display__OpenGLRenderer,openfl__geom__Matrix,vdynamic*);
void openfl_display_OpenGLRenderer_applyMatrix(openfl__display__OpenGLRenderer,hl__types__ArrayBytes_Float);
void openfl_display_OpenGLRenderer_applyAlpha(openfl__display__OpenGLRenderer,double);
void openfl_display_OpenGLRenderer_applyColorTransform(openfl__display__OpenGLRenderer,openfl__geom__ColorTransform);
void openfl_display_OpenGLRenderer_updateShader(openfl__display__OpenGLRenderer);
openfl__display3D__VertexBuffer3D openfl_display_BitmapData_getVertexBuffer(openfl__display__BitmapData,openfl__display3D__Context3D,openfl__geom__Rectangle,openfl__display__DisplayObject);
extern hl_type t$_dyn;
void openfl_display3D_Context3D_setVertexBufferAt(openfl__display3D__Context3D,int,openfl__display3D__VertexBuffer3D,int*,vdynamic*);
openfl__display3D__IndexBuffer3D openfl_display_BitmapData_getIndexBuffer(openfl__display__BitmapData,openfl__display3D__Context3D,openfl__geom__Rectangle);
void openfl_display3D_Context3D_drawTriangles(openfl__display3D__Context3D,openfl__display3D__IndexBuffer3D,int*,int*);
void openfl_display_OpenGLRenderer___clearShader(openfl__display__OpenGLRenderer);
#include <openfl/display/_internal/Context3DMaskShader.h>

void openfl_display__internal_Context3DBitmapData_renderDrawable(openfl__display__BitmapData r0,openfl__display__OpenGLRenderer r1) {
	bool *r9;
	openfl__display3D__Context3D r2;
	openfl__geom__Rectangle r15;
	openfl__display__DisplayObject r16;
	bool r8;
	openfl__display3D__VertexBuffer3D r14;
	lime___internal__backend__native__NativeOpenGLRenderContext r4;
	openfl__display__ShaderParameter_Float r17;
	openfl__geom__ColorTransform r13;
	openfl__geom__Matrix r11;
	hl__types__ArrayBytes_Float r10;
	openfl__display3D__IndexBuffer3D r23;
	double r12;
	int *r20, *r24;
	openfl__display__DisplayObjectShader r7;
	vdynamic *r6, *r18;
	int r5, r19, r21, r22;
	if( r1 == NULL ) hl_null_access();
	r2 = r1->__context3D;
	if( r2 == NULL ) hl_null_access();
	r4 = r2->gl;
	r5 = 10;
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r5;
	openfl_display_OpenGLRenderer___setBlendMode(r1,r6);
	r7 = r1->__defaultDisplayShader;
	openfl_display_OpenGLRenderer_setShader(r1,((openfl__display__Shader)r7));
	r8 = r1->__upscaled;
	r9 = NULL;
	openfl_display_OpenGLRenderer_applyBitmapData(r1,r0,r8,r9);
	if( r0 == NULL ) hl_null_access();
	r11 = r0->__worldTransform;
	r5 = 1;
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r5;
	r10 = openfl_display_OpenGLRenderer___getMatrix(r1,r11,r6);
	openfl_display_OpenGLRenderer_applyMatrix(r1,r10);
	r12 = r0->__worldAlpha;
	openfl_display_OpenGLRenderer_applyAlpha(r1,r12);
	r13 = r0->__worldColorTransform;
	openfl_display_OpenGLRenderer_applyColorTransform(r1,r13);
	openfl_display_OpenGLRenderer_updateShader(r1);
	r15 = NULL;
	r16 = NULL;
	r14 = openfl_display_BitmapData_getVertexBuffer(r0,r2,r15,r16);
	if( r7 == NULL ) hl_null_access();
	r17 = r7->__position;
	if( !r17 ) goto label$5899eaa_1_38;
	r17 = r7->__position;
	if( r17 == NULL ) hl_null_access();
	r18 = r17->index;
	r5 = (int)hl_dyn_casti(&r18,&t$_dyn,&t$_i32);
	r19 = 0;
	r20 = &r19;
	r21 = 3;
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r21;
	openfl_display3D_Context3D_setVertexBufferAt(r2,r5,r14,r20,r6);
	label$5899eaa_1_38:
	r17 = r7->__textureCoord;
	if( !r17 ) goto label$5899eaa_1_49;
	r17 = r7->__textureCoord;
	if( r17 == NULL ) hl_null_access();
	r18 = r17->index;
	r5 = (int)hl_dyn_casti(&r18,&t$_dyn,&t$_i32);
	r21 = 3;
	r20 = &r21;
	r22 = 2;
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r22;
	openfl_display3D_Context3D_setVertexBufferAt(r2,r5,r14,r20,r6);
	label$5899eaa_1_49:
	r15 = NULL;
	r23 = openfl_display_BitmapData_getIndexBuffer(r0,r2,r15);
	r20 = NULL;
	r24 = NULL;
	openfl_display3D_Context3D_drawTriangles(r2,r23,r20,r24);
	openfl_display_OpenGLRenderer___clearShader(r1);
	return;
}

void openfl_display__internal_Context3DBitmapData_renderDrawableMask(openfl__display__BitmapData r0,openfl__display__OpenGLRenderer r1) {
	bool *r7;
	openfl__display3D__Context3D r2;
	openfl__geom__Rectangle r13;
	openfl__display__DisplayObject r14;
	bool r6;
	openfl__display3D__VertexBuffer3D r12;
	lime___internal__backend__native__NativeOpenGLRenderContext r4;
	openfl__display__ShaderParameter_Float r15;
	openfl__geom__Matrix r9;
	openfl__display___internal__Context3DMaskShader r5;
	hl__types__ArrayBytes_Float r8;
	openfl__display3D__IndexBuffer3D r21;
	int *r18, *r22;
	vdynamic *r11, *r16;
	int r10, r17, r19, r20;
	if( r1 == NULL ) hl_null_access();
	r2 = r1->__context3D;
	if( r2 == NULL ) hl_null_access();
	r4 = r2->gl;
	r5 = r1->__maskShader;
	openfl_display_OpenGLRenderer_setShader(r1,((openfl__display__Shader)r5));
	r6 = r1->__upscaled;
	r7 = NULL;
	openfl_display_OpenGLRenderer_applyBitmapData(r1,r0,r6,r7);
	if( r0 == NULL ) hl_null_access();
	r9 = r0->__worldTransform;
	r10 = 1;
	r11 = hl_alloc_dynamic(&t$_i32);
	r11->v.i = r10;
	r8 = openfl_display_OpenGLRenderer___getMatrix(r1,r9,r11);
	openfl_display_OpenGLRenderer_applyMatrix(r1,r8);
	openfl_display_OpenGLRenderer_updateShader(r1);
	r13 = NULL;
	r14 = NULL;
	r12 = openfl_display_BitmapData_getVertexBuffer(r0,r2,r13,r14);
	if( r5 == NULL ) hl_null_access();
	r15 = r5->__position;
	if( !r15 ) goto label$5899eaa_2_31;
	r15 = r5->__position;
	if( r15 == NULL ) hl_null_access();
	r16 = r15->index;
	r10 = (int)hl_dyn_casti(&r16,&t$_dyn,&t$_i32);
	r17 = 0;
	r18 = &r17;
	r19 = 3;
	r11 = hl_alloc_dynamic(&t$_i32);
	r11->v.i = r19;
	openfl_display3D_Context3D_setVertexBufferAt(r2,r10,r12,r18,r11);
	label$5899eaa_2_31:
	r15 = r5->__textureCoord;
	if( !r15 ) goto label$5899eaa_2_42;
	r15 = r5->__textureCoord;
	if( r15 == NULL ) hl_null_access();
	r16 = r15->index;
	r10 = (int)hl_dyn_casti(&r16,&t$_dyn,&t$_i32);
	r19 = 3;
	r18 = &r19;
	r20 = 2;
	r11 = hl_alloc_dynamic(&t$_i32);
	r11->v.i = r20;
	openfl_display3D_Context3D_setVertexBufferAt(r2,r10,r12,r18,r11);
	label$5899eaa_2_42:
	r13 = NULL;
	r21 = openfl_display_BitmapData_getIndexBuffer(r0,r2,r13);
	r18 = NULL;
	r22 = NULL;
	openfl_display3D_Context3D_drawTriangles(r2,r21,r18,r22);
	openfl_display_OpenGLRenderer___clearShader(r1);
	return;
}

