// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/display/_internal/Context3DBuffer.h>
void openfl_display__internal_Context3DBuffer_resize(openfl__display___internal__Context3DBuffer,int,int*);
#include <openfl/display3D/IndexBuffer3D.h>
void openfl_display3D_Context3D_drawTriangles(openfl__display3D__Context3D,openfl__display3D__IndexBuffer3D,int*,int*);
#include <hl/natives.h>
double Math_min(double,double);
extern hl_type t$_i32;
openfl__display3D__VertexBuffer3D openfl_display3D_Context3D_createVertexBuffer(openfl__display3D__Context3D,int,int,vdynamic*);
void openfl_display3D_VertexBuffer3D_uploadFromTypedArray(openfl__display3D__VertexBuffer3D,lime__utils__ArrayBufferView,int*);
#include <haxe/io/Bytes.h>
#include <hl/types/ArrayDyn.h>
#include <openfl/_Vector/FloatVector.h>
extern hl_type t$lime_utils_ArrayBufferView;
void lime_utils_ArrayBufferView_new(lime__utils__ArrayBufferView,vdynamic*,int);
void haxe_io_Bytes_blit(haxe__io__Bytes,int,haxe__io__Bytes,int,int);
void lime_utils_ArrayBufferView_copyFromArray(lime__utils__ArrayBufferView,hl__types__ArrayDyn,int*);
extern String s$53c6d62;

void openfl_display__internal_Context3DBuffer_new(openfl__display___internal__Context3DBuffer r0,openfl__display3D__Context3D r1,venum* r2,int r3,int r4) {
	int *r7;
	int r5;
	r0->context3D = r1;
	r0->elementType = r2;
	r0->dataPerVertex = r4;
	r5 = 0;
	r0->indexCount = r5;
	r5 = 0;
	r0->vertexCount = r5;
	r7 = NULL;
	openfl_display__internal_Context3DBuffer_resize(r0,r3,r7);
	return;
}

void openfl_display__internal_Context3DBuffer_drawElements(openfl__display___internal__Context3DBuffer r0,int r1,int* r2) {
	hl__types__ArrayObj r10;
	openfl__display3D__Context3D r9;
	venum *r8;
	double r17, r18;
	openfl__display3D__IndexBuffer3D r11;
	int *r14;
	vdynamic *r7;
	varray *r12;
	int r3, r5, r6, r13, r15, r16, r19, r20;
	if( r2 ) goto label$e24854b_2_3;
	r3 = -1;
	goto label$e24854b_2_4;
	label$e24854b_2_3:
	r3 = *r2;
	label$e24854b_2_4:
	r5 = r0->indexCount;
	r6 = 0;
	if( r5 == r6 ) goto label$e24854b_2_10;
	r5 = r0->vertexCount;
	r6 = 0;
	if( r5 != r6 ) goto label$e24854b_2_11;
	label$e24854b_2_10:
	return;
	label$e24854b_2_11:
	r8 = r0->elementType;
	if( r8 == NULL ) hl_null_access();
	r5 = HL__ENUM_INDEX__(r8);
	r6 = 0;
	if( r5 != r6 ) goto label$e24854b_2_86;
	r6 = -1;
	if( r3 != r6 ) goto label$e24854b_2_22;
	r5 = r0->elementCount;
	r6 = 2;
	r5 = r5 * r6;
	r3 = r5;
	label$e24854b_2_22:
	r6 = 10922;
	if( r1 >= r6 ) goto label$e24854b_2_46;
	r5 = r3 - r1;
	r6 = 10922;
	if( r5 >= r6 ) goto label$e24854b_2_46;
	r9 = r0->context3D;
	if( r9 == NULL ) hl_null_access();
	r10 = r0->indexBuffers;
	if( r10 == NULL ) hl_null_access();
	r5 = 0;
	r6 = r10->length;
	if( ((unsigned)r5) < ((unsigned)r6) ) goto label$e24854b_2_36;
	r11 = NULL;
	goto label$e24854b_2_39;
	label$e24854b_2_36:
	r12 = r10->array;
	r7 = ((vdynamic**)(r12 + 1))[r5];
	r11 = (openfl__display3D__IndexBuffer3D)r7;
	label$e24854b_2_39:
	r5 = r1;
	r2 = &r5;
	r13 = 2;
	r6 = r3 * r13;
	r14 = &r6;
	openfl_display3D_Context3D_drawTriangles(r9,r11,r2,r14);
	goto label$e24854b_2_86;
	label$e24854b_2_46:
	r13 = r1 + r3;
	label$e24854b_2_47:
	if( r1 >= r13 ) goto label$e24854b_2_86;
	r17 = (double)r1;
	r18 = 10922.;
	r17 = r17 / r18;
	r15 = hl_math_floor(r17);
	r16 = r13 - r1;
	r17 = (double)r16;
	r18 = 10922.;
	r17 = Math_min(r17,r18);
	r16 = (int)r17;
	r3 = r16;
	r19 = 0;
	if( r19 < r16 ) goto label$e24854b_2_62;
	goto label$e24854b_2_86;
	label$e24854b_2_62:
	r9 = r0->context3D;
	if( r9 == NULL ) hl_null_access();
	r10 = r0->indexBuffers;
	if( r10 == NULL ) hl_null_access();
	r19 = r10->length;
	if( ((unsigned)r15) < ((unsigned)r19) ) goto label$e24854b_2_70;
	r11 = NULL;
	goto label$e24854b_2_73;
	label$e24854b_2_70:
	r12 = r10->array;
	r7 = ((vdynamic**)(r12 + 1))[r15];
	r11 = (openfl__display3D__IndexBuffer3D)r7;
	label$e24854b_2_73:
	r20 = 10922;
	r19 = r15 * r20;
	r16 = r1 - r19;
	r19 = 3;
	r16 = r16 * r19;
	r2 = &r16;
	r20 = 2;
	r19 = r3 * r20;
	r14 = &r19;
	openfl_display3D_Context3D_drawTriangles(r9,r11,r2,r14);
	r20 = r1 + r3;
	r1 = r20;
	goto label$e24854b_2_47;
	label$e24854b_2_86:
	return;
}

void openfl_display__internal_Context3DBuffer_flushVertexBufferData(openfl__display___internal__Context3DBuffer r0) {
	openfl__display3D__Context3D r6;
	openfl__display3D__VertexBuffer3D r5;
	lime__utils__ArrayBufferView r3;
	int *r9;
	vdynamic *r8;
	int r2, r4, r7;
	r3 = r0->vertexBufferData;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	r4 = r0->vertexCount;
	if( r4 >= r2 ) goto label$e24854b_3_17;
	r3 = r0->vertexBufferData;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	r0->vertexCount = r2;
	r6 = r0->context3D;
	if( r6 == NULL ) hl_null_access();
	r2 = r0->vertexCount;
	r4 = r0->dataPerVertex;
	r7 = 0;
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r7;
	r5 = openfl_display3D_Context3D_createVertexBuffer(r6,r2,r4,r8);
	r0->vertexBuffer = r5;
	label$e24854b_3_17:
	r5 = r0->vertexBuffer;
	if( r5 == NULL ) hl_null_access();
	r3 = r0->vertexBufferData;
	r9 = NULL;
	openfl_display3D_VertexBuffer3D_uploadFromTypedArray(r5,r3,r9);
	return;
}

void openfl_display__internal_Context3DBuffer_resize(openfl__display___internal__Context3DBuffer r0,int r1,int* r2) {
	String r25;
	venum *r8;
	haxe__io__Bytes r11, r21, r24;
	openfl__display3D__VertexBuffer3D r7;
	openfl___Vector__FloatVector r13;
	hl__types__ArrayDyn r12, r18;
	lime__utils__ArrayBufferView r10, r15, r16, r19;
	vdynamic *r14, *r17;
	int r3, r4, r6, r9, r20, r22, r23;
	if( r2 ) goto label$e24854b_4_3;
	r3 = -1;
	goto label$e24854b_4_4;
	label$e24854b_4_3:
	r3 = *r2;
	label$e24854b_4_4:
	r0->elementCount = r1;
	r6 = -1;
	if( r3 != r6 ) goto label$e24854b_4_9;
	r4 = r0->dataPerVertex;
	r3 = r4;
	label$e24854b_4_9:
	r6 = r0->dataPerVertex;
	if( r3 == r6 ) goto label$e24854b_4_16;
	r7 = NULL;
	r0->vertexBuffer = r7;
	r4 = 0;
	r0->vertexCount = r4;
	r0->dataPerVertex = r3;
	label$e24854b_4_16:
	r4 = 0;
	r8 = r0->elementType;
	if( r8 == NULL ) hl_null_access();
	r6 = HL__ENUM_INDEX__(r8);
	switch(r6) {
		default:
			goto label$e24854b_4_33;
		case 0:
			r9 = 4;
			r6 = r1 * r9;
			r4 = r6;
			goto label$e24854b_4_33;
		case 1:
			r9 = 3;
			r6 = r1 * r9;
			r4 = r6;
			goto label$e24854b_4_33;
		case 2:
			r9 = 3;
			r6 = r1 * r9;
			r4 = r6;
	}
	label$e24854b_4_33:
	r6 = r4 * r3;
	r10 = r0->vertexBufferData;
	if( r10 ) goto label$e24854b_4_47;
	r11 = NULL;
	r12 = NULL;
	r13 = NULL;
	r10 = NULL;
	r14 = NULL;
	r16 = (lime__utils__ArrayBufferView)hl_alloc_obj(&t$lime_utils_ArrayBufferView);
	r17 = hl_alloc_dynamic(&t$_i32);
	r17->v.i = r6;
	r9 = 8;
	lime_utils_ArrayBufferView_new(r16,r17,r9);
	r0->vertexBufferData = r16;
	goto label$e24854b_4_87;
	label$e24854b_4_47:
	r10 = r0->vertexBufferData;
	if( r10 == NULL ) hl_null_access();
	r20 = r10->length;
	if( r20 >= r6 ) goto label$e24854b_4_87;
	r10 = r0->vertexBufferData;
	r11 = NULL;
	r12 = NULL;
	r13 = NULL;
	r15 = NULL;
	r14 = NULL;
	r19 = (lime__utils__ArrayBufferView)hl_alloc_obj(&t$lime_utils_ArrayBufferView);
	r17 = hl_alloc_dynamic(&t$_i32);
	r17->v.i = r6;
	r9 = 8;
	lime_utils_ArrayBufferView_new(r19,r17,r9);
	r0->vertexBufferData = r19;
	r19 = r0->vertexBufferData;
	r18 = NULL;
	r9 = 0;
	if( !r10 ) goto label$e24854b_4_78;
	if( r18 ) goto label$e24854b_4_78;
	if( r19 == NULL ) hl_null_access();
	r21 = r19->buffer;
	if( r21 == NULL ) hl_null_access();
	r22 = r19->bytesPerElement;
	r20 = r9 * r22;
	if( r10 == NULL ) hl_null_access();
	r24 = r10->buffer;
	r22 = r10->byteOffset;
	r23 = r10->byteLength;
	haxe_io_Bytes_blit(r21,r20,r24,r22,r23);
	goto label$e24854b_4_87;
	label$e24854b_4_78:
	if( !r18 ) goto label$e24854b_4_85;
	if( r10 ) goto label$e24854b_4_85;
	if( r19 == NULL ) hl_null_access();
	r20 = r9;
	r2 = &r20;
	lime_utils_ArrayBufferView_copyFromArray(r19,r18,r2);
	goto label$e24854b_4_87;
	label$e24854b_4_85:
	r25 = (String)s$53c6d62;
	hl_throw((vdynamic*)r25);
	label$e24854b_4_87:
	return;
}

