// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__display___internal__Context3DGraphics
#define INC_openfl__display___internal__Context3DGraphics
typedef struct _openfl__display___internal__$Context3DGraphics *openfl__display___internal__$Context3DGraphics;
typedef struct _openfl__display___internal__Context3DGraphics *openfl__display___internal__Context3DGraphics;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <openfl/display/BitmapData.h>
#include <openfl/geom/ColorTransform.h>
#include <openfl/display/Graphics.h>
#include <openfl/display/OpenGLRenderer.h>


struct _openfl__display___internal__$Context3DGraphics {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	openfl__display__BitmapData blankBitmapData;
	bool maskRender;
	openfl__geom__ColorTransform tempColorTransform;
	vclosure* buildBuffer;
	vclosure* isCompatible;
	vclosure* render;
	vclosure* renderMask;
	vclosure* resizeIndexBuffer;
	vclosure* resizeVertexBuffer;
};
struct _openfl__display___internal__Context3DGraphics {
	hl_type *$type;
};
#endif

