// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/display/_internal/DOMShape.h>

void openfl_display__internal_DOMShape_clear(openfl__display__DisplayObject r0,openfl__display__DOMRenderer r1) {
	return;
}

void openfl_display__internal_DOMShape_render(openfl__display__DisplayObject r0,openfl__display__DOMRenderer r1) {
	return;
}

