// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__display___internal__DOMTextField
#define INC_openfl__display___internal__DOMTextField
typedef struct _openfl__display___internal__$DOMTextField *openfl__display___internal__$DOMTextField;
typedef struct _openfl__display___internal__DOMTextField *openfl__display___internal__DOMTextField;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <_std/EReg.h>
#include <openfl/text/TextField.h>
#include <openfl/display/DOMRenderer.h>


struct _openfl__display___internal__$DOMTextField {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	EReg __regexColor;
	EReg __regexFace;
	EReg __regexFont;
	EReg __regexCloseFont;
	EReg __regexSize;
	vclosure* clear;
	vclosure* measureText;
	vclosure* render;
	vclosure* renderDrawable;
	vclosure* renderDrawableClear;
	vclosure* __getAttributeMatch;
};
struct _openfl__display___internal__DOMTextField {
	hl_type *$type;
};
#endif

