// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/display/_internal/DOMTextField.h>
String EReg_matched(EReg,int);

void openfl_display__internal_DOMTextField_clear(openfl__text__TextField r0,openfl__display__DOMRenderer r1) {
	return;
}

void openfl_display__internal_DOMTextField_measureText(openfl__text__TextField r0) {
	return;
}

void openfl_display__internal_DOMTextField_render(openfl__text__TextField r0,openfl__display__DOMRenderer r1) {
	return;
}

void openfl_display__internal_DOMTextField_renderDrawable(openfl__text__TextField r0,openfl__display__DOMRenderer r1) {
	return;
}

void openfl_display__internal_DOMTextField_renderDrawableClear(openfl__text__TextField r0,openfl__display__DOMRenderer r1) {
	openfl_display__internal_DOMTextField_clear(r0,r1);
	return;
}

String openfl_display__internal_DOMTextField___getAttributeMatch(EReg r0) {
	String r1;
	int r2;
	if( r0 == NULL ) hl_null_access();
	r2 = 2;
	r1 = EReg_matched(r0,r2);
	if( !r1 ) goto label$574f4be_6_7;
	r2 = 2;
	r1 = EReg_matched(r0,r2);
	return r1;
	label$574f4be_6_7:
	r2 = 3;
	r1 = EReg_matched(r0,r2);
	return r1;
}

