// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/tweens/motion/LinearMotion.h>
double flixel_tweens_motion_LinearMotion_get_distance(flixel__tweens__motion__LinearMotion);
flixel__tweens__FlxTween flixel_tweens_FlxTween_start(flixel__tweens__FlxTween);
void flixel_tweens_motion_Motion_update(flixel__tweens__motion__Motion,double);
void flixel_tweens_motion_Motion_postUpdate(flixel__tweens__motion__Motion);
#include <hl/natives.h>
void flixel_tweens_motion_Motion_new(flixel__tweens__motion__Motion,vvirtual*,flixel__tweens__FlxTweenManager);

flixel__tweens__motion__LinearMotion flixel_tweens_motion_LinearMotion_setMotion(flixel__tweens__motion__LinearMotion r0,double r1,double r2,double r3,double r4,double r5,bool* r6) {
	flixel__tweens__FlxTween r9;
	bool r7;
	double r8;
	if( r6 ) goto label$c03fb0b_1_3;
	r7 = true;
	goto label$c03fb0b_1_4;
	label$c03fb0b_1_3:
	r7 = *r6;
	label$c03fb0b_1_4:
	r8 = -1.;
	r0->_distance = r8;
	r0->_fromX = r1;
	r0->x = r1;
	r0->_fromY = r2;
	r0->y = r2;
	r8 = r3 - r1;
	r0->_moveX = r8;
	r8 = r4 - r2;
	r0->_moveY = r8;
	if( !r7 ) goto label$c03fb0b_1_17;
	r0->duration = r5;
	goto label$c03fb0b_1_20;
	label$c03fb0b_1_17:
	r8 = flixel_tweens_motion_LinearMotion_get_distance(r0);
	r8 = r8 / r5;
	r0->duration = r8;
	label$c03fb0b_1_20:
	r9 = flixel_tweens_FlxTween_start(((flixel__tweens__FlxTween)r0));
	return r0;
}

void flixel_tweens_motion_LinearMotion_update(flixel__tweens__motion__LinearMotion r0,double r1) {
	bool r6;
	double r3, r4, r5;
	flixel_tweens_motion_Motion_update(((flixel__tweens__motion__Motion)r0),r1);
	r3 = r0->_fromX;
	r4 = r0->_moveX;
	r5 = r0->scale;
	r4 = r4 * r5;
	r3 = r3 + r4;
	r0->x = r3;
	r3 = r0->_fromY;
	r4 = r0->_moveY;
	r5 = r0->scale;
	r4 = r4 * r5;
	r3 = r3 + r4;
	r0->y = r3;
	r3 = r0->x;
	r4 = r0->_fromX;
	r5 = r0->_moveX;
	r4 = r4 + r5;
	if( r3 != r4 ) goto label$c03fb0b_2_30;
	r3 = r0->y;
	r4 = r0->_fromY;
	r5 = r0->_moveY;
	r4 = r4 + r5;
	if( r3 != r4 ) goto label$c03fb0b_2_30;
	r6 = r0->active;
	if( !r6 ) goto label$c03fb0b_2_30;
	r3 = r0->_secondsSinceStart;
	r4 = r0->duration;
	if( !(r3 >= r4) ) goto label$c03fb0b_2_30;
	r6 = true;
	r0->finished = r6;
	label$c03fb0b_2_30:
	r6 = r0->finished;
	if( !r6 ) goto label$c03fb0b_2_33;
	flixel_tweens_motion_Motion_postUpdate(((flixel__tweens__motion__Motion)r0));
	label$c03fb0b_2_33:
	return;
}

double flixel_tweens_motion_LinearMotion_get_distance(flixel__tweens__motion__LinearMotion r0) {
	double r1, r2, r3;
	r1 = r0->_distance;
	r2 = 0.;
	if( !(r1 >= r2) ) goto label$c03fb0b_3_5;
	r1 = r0->_distance;
	return r1;
	label$c03fb0b_3_5:
	r1 = r0->_moveX;
	r2 = r0->_moveX;
	r1 = r1 * r2;
	r2 = r0->_moveY;
	r3 = r0->_moveY;
	r2 = r2 * r3;
	r1 = r1 + r2;
	r1 = hl_math_sqrt(r1);
	r0->_distance = r1;
	return r1;
}

void flixel_tweens_motion_LinearMotion_new(flixel__tweens__motion__LinearMotion r0,vvirtual* r1,flixel__tweens__FlxTweenManager r2) {
	double r3;
	r3 = -1.;
	r0->_distance = r3;
	r3 = 0.;
	r0->_moveY = r3;
	r3 = 0.;
	r0->_moveX = r3;
	r3 = 0.;
	r0->_fromY = r3;
	r3 = 0.;
	r0->_fromX = r3;
	flixel_tweens_motion_Motion_new(((flixel__tweens__motion__Motion)r0),r1,r2);
	return;
}

