// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__input__gamepad__mappings__PSVitaMapping
#define INC_flixel__input__gamepad__mappings__PSVitaMapping
typedef struct _flixel__input__gamepad__mappings__$PSVitaMapping *flixel__input__gamepad__mappings__$PSVitaMapping;
typedef struct _flixel__input__gamepad__mappings__PSVitaMapping *flixel__input__gamepad__mappings__PSVitaMapping;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <flixel/input/gamepad/mappings/FlxGamepadMapping.h>
#include <flixel/input/gamepad/FlxGamepadAnalogStick.h>
#include <flixel/input/gamepad/FlxGamepadAttachment.h>
#include <flixel/input/gamepad/mappings/Manufacturer.h>


struct _flixel__input__gamepad__mappings__$PSVitaMapping {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _flixel__input__gamepad__mappings__PSVitaMapping {
	hl_type *$type;
	bool supportsMotion;
	bool supportsPointer;
	flixel__input__gamepad__FlxGamepadAnalogStick leftStick;
	flixel__input__gamepad__FlxGamepadAnalogStick rightStick;
	venum* attachment;
	venum* manufacturer;
};
#endif

