// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/tile/FlxTileblock.h>
extern hl_type t$_f64;
void flixel_FlxSprite_new(flixel__FlxSprite,vdynamic*,vdynamic*,vdynamic*);
flixel__FlxSprite flixel_FlxSprite_makeGraphic(flixel__FlxSprite,int,int,int*,bool*,String);
bool flixel_FlxBasic_set_active(flixel__FlxBasic,bool);
bool flixel_FlxObject_set_immovable(flixel__FlxObject,bool);
bool flixel_FlxObject_set_moves(flixel__FlxObject,bool);
extern hl_type t$vrt_39c5c14;
vdynamic* flixel_util_FlxDestroyUtil_destroy(vvirtual*);
extern hl_type t$flixel_FlxSprite;
extern hl_type t$_dyn;
void flixel_FlxSprite_destroy(flixel__FlxSprite);
#include <flixel/graphics/frames/FlxTileFrames.h>
#include <flixel/math/FlxRandom.h>
#include <flixel/FlxG.h>
#include <hl/types/ArrayBytes_Float.h>
double flixel_FlxObject_get_width(flixel__FlxObject);
double flixel_FlxObject_set_width(flixel__FlxObject,double);
double flixel_FlxObject_get_height(flixel__FlxObject);
double flixel_FlxObject_set_height(flixel__FlxObject,double);
flixel__FlxSprite flixel_util_FlxSpriteUtil_fill(flixel__FlxSprite,int);
extern flixel__$FlxG g$_flixel_FlxG;
double flixel_math_FlxRandom_float(flixel__math__FlxRandom,double*,double*,hl__types__ArrayBytes_Float);
void flixel_animation_FlxAnimationController_randomFrame(flixel__animation__FlxAnimationController);
void flixel_FlxSprite_stamp(flixel__FlxSprite,flixel__FlxSprite,int*,int*);
#include <flixel/system/frontEnds/BitmapFrontEnd.h>
#include <flixel/util/FlxPool_flixel_math_FlxBasePoint.h>
#include <flixel/math/FlxBasePoint.h>
flixel__graphics__FlxGraphic flixel_system_frontEnds_BitmapFrontEnd_add(flixel__system__frontEnds__BitmapFrontEnd,vdynamic*,bool*,String);
extern flixel__math__$FlxBasePoint g$_flixel_math_FlxBasePoint;
flixel__math__FlxBasePoint flixel_util_FlxPool_flixel_math_FlxBasePoint_get(flixel__util__FlxPool_flixel_math_FlxBasePoint);
flixel__graphics__frames__FlxTileFrames flixel_graphics_frames_FlxTileFrames_fromGraphic(flixel__graphics__FlxGraphic,flixel__math__FlxBasePoint,flixel__math__FlxRect,flixel__math__FlxBasePoint);
int flixel_animation_FlxAnimationController_set_frameIndex(flixel__animation__FlxAnimationController,int);

void flixel_tile_FlxTileblock_new(flixel__tile__FlxTileblock r0,int r1,int r2,int r3,int r4) {
	String r15;
	bool *r14;
	bool r13, r16;
	double r6;
	int *r12;
	vdynamic *r7, *r8, *r9;
	int r11;
	flixel__FlxSprite r10;
	r6 = (double)r1;
	r7 = hl_alloc_dynamic(&t$_f64);
	r7->v.d = r6;
	r6 = (double)r2;
	r8 = hl_alloc_dynamic(&t$_f64);
	r8->v.d = r6;
	r9 = NULL;
	flixel_FlxSprite_new(((flixel__FlxSprite)r0),r7,r8,r9);
	r11 = 0;
	r12 = &r11;
	r13 = true;
	r14 = &r13;
	r15 = NULL;
	r10 = flixel_FlxSprite_makeGraphic(((flixel__FlxSprite)r0),r3,r4,r12,r14,r15);
	r16 = false;
	r16 = flixel_FlxBasic_set_active(((flixel__FlxBasic)r0),r16);
	r16 = true;
	r16 = flixel_FlxObject_set_immovable(((flixel__FlxObject)r0),r16);
	r16 = false;
	r16 = flixel_FlxObject_set_moves(((flixel__FlxObject)r0),r16);
	return;
}

void flixel_tile_FlxTileblock_destroy(flixel__tile__FlxTileblock r0) {
	vvirtual *r3;
	vdynamic *r1;
	flixel__FlxSprite r2;
	r2 = r0->tileSprite;
	if( r2 ) goto label$83be7ae_2_4;
	r3 = NULL;
	goto label$83be7ae_2_8;
	label$83be7ae_2_4:
	r3 = r2->f$7;
	if( r3 ) goto label$83be7ae_2_8;
	r3 = hl_to_virtual(&t$vrt_39c5c14,(vdynamic*)r2);
	r2->f$7 = r3;
	label$83be7ae_2_8:
	r1 = flixel_util_FlxDestroyUtil_destroy(r3);
	r2 = (flixel__FlxSprite)hl_dyn_castp(&r1,&t$_dyn,&t$flixel_FlxSprite);
	r0->tileSprite = r2;
	flixel_FlxSprite_destroy(((flixel__FlxSprite)r0));
	return;
}

flixel__tile__FlxTileblock flixel_tile_FlxTileblock_loadFrames(flixel__tile__FlxTileblock r0,flixel__graphics__frames__FlxTileFrames r1,int* r2) {
	String r25;
	bool *r24;
	bool r17, r20, r40;
	flixel__$FlxG r32;
	flixel__math__FlxRandom r31;
	hl__types__ArrayBytes_Float r35;
	double r10, r12, r14, r18, r22, r36;
	int *r38;
	double *r33, *r34;
	vdynamic *r5, *r7, *r8;
	flixel__animation__FlxAnimationController r37;
	flixel__graphics__frames__FlxFramesCollection r9;
	flixel__FlxSprite r6;
	int r3, r11, r13, r15, r16, r19, r21, r23, r26, r27, r28, r29, r30, r39;
	if( r2 ) goto label$83be7ae_3_3;
	r3 = 0;
	goto label$83be7ae_3_4;
	label$83be7ae_3_3:
	r3 = *r2;
	label$83be7ae_3_4:
	if( r1 ) goto label$83be7ae_3_6;
	return r0;
	label$83be7ae_3_6:
	r6 = r0->tileSprite;
	if( r6 ) goto label$83be7ae_3_14;
	r6 = (flixel__FlxSprite)hl_alloc_obj(&t$flixel_FlxSprite);
	r7 = NULL;
	r8 = NULL;
	r5 = NULL;
	flixel_FlxSprite_new(r6,r7,r8,r5);
	goto label$83be7ae_3_15;
	label$83be7ae_3_14:
	r6 = r0->tileSprite;
	label$83be7ae_3_15:
	r0->tileSprite = r6;
	r6 = r0->tileSprite;
	if( r6 == NULL ) hl_null_access();
	r9 = ((flixel__graphics__frames__FlxFramesCollection (*)(flixel__FlxSprite,flixel__graphics__frames__FlxTileFrames))r6->$type->vobj_proto[55])(r6,r1);
	r6 = r0->tileSprite;
	if( r6 == NULL ) hl_null_access();
	r10 = ((double (*)(flixel__FlxSprite))r6->$type->vobj_proto[26])(r6);
	r11 = (int)r10;
	r6 = r0->tileSprite;
	if( r6 == NULL ) hl_null_access();
	r12 = ((double (*)(flixel__FlxSprite))r6->$type->vobj_proto[27])(r6);
	r13 = (int)r12;
	r6 = r0->tileSprite;
	if( r6 == NULL ) hl_null_access();
	r15 = r6->numFrames;
	r15 = r15 + r3;
	r17 = false;
	r14 = flixel_FlxObject_get_width(((flixel__FlxObject)r0));
	r6 = r0->tileSprite;
	if( r6 == NULL ) hl_null_access();
	r18 = ((double (*)(flixel__FlxSprite))r6->$type->vobj_proto[26])(r6);
	r14 = fmod(r14,r18);
	r18 = 0.;
	if( r14 == r18 ) goto label$83be7ae_3_50;
	r14 = flixel_FlxObject_get_width(((flixel__FlxObject)r0));
	r18 = (double)r11;
	r14 = r14 / r18;
	r18 = 1.;
	r14 = r14 + r18;
	r16 = (int)r14;
	r16 = r16 * r11;
	r18 = (double)r16;
	r18 = flixel_FlxObject_set_width(((flixel__FlxObject)r0),r18);
	r20 = true;
	r17 = r20;
	label$83be7ae_3_50:
	r14 = flixel_FlxObject_get_height(((flixel__FlxObject)r0));
	r6 = r0->tileSprite;
	if( r6 == NULL ) hl_null_access();
	r18 = ((double (*)(flixel__FlxSprite))r6->$type->vobj_proto[27])(r6);
	r14 = fmod(r14,r18);
	r18 = 0.;
	if( r14 == r18 ) goto label$83be7ae_3_68;
	r14 = flixel_FlxObject_get_height(((flixel__FlxObject)r0));
	r18 = (double)r13;
	r14 = r14 / r18;
	r18 = 1.;
	r14 = r14 + r18;
	r16 = (int)r14;
	r16 = r16 * r13;
	r18 = (double)r16;
	r18 = flixel_FlxObject_set_height(((flixel__FlxObject)r0),r18);
	r20 = true;
	r17 = r20;
	label$83be7ae_3_68:
	if( !r17 ) goto label$83be7ae_3_80;
	r14 = flixel_FlxObject_get_width(((flixel__FlxObject)r0));
	r16 = (int)r14;
	r18 = flixel_FlxObject_get_height(((flixel__FlxObject)r0));
	r21 = (int)r18;
	r23 = 0;
	r2 = &r23;
	r20 = true;
	r24 = &r20;
	r25 = NULL;
	r6 = flixel_FlxSprite_makeGraphic(((flixel__FlxSprite)r0),r16,r21,r2,r24,r25);
	goto label$83be7ae_3_82;
	label$83be7ae_3_80:
	r16 = 0;
	r6 = flixel_util_FlxSpriteUtil_fill(((flixel__FlxSprite)r0),r16);
	label$83be7ae_3_82:
	r16 = 0;
	r19 = 0;
	r14 = flixel_FlxObject_get_width(((flixel__FlxObject)r0));
	r18 = (double)r11;
	r14 = r14 / r18;
	r21 = (int)r14;
	r18 = flixel_FlxObject_get_height(((flixel__FlxObject)r0));
	r22 = (double)r13;
	r18 = r18 / r22;
	r26 = (int)r18;
	label$83be7ae_3_92:
	if( r16 >= r26 ) goto label$83be7ae_3_134;
	r28 = 0;
	r27 = r28;
	r29 = 0;
	r28 = r29;
	label$83be7ae_3_98:
	if( r28 >= r21 ) goto label$83be7ae_3_130;
	r32 = (flixel__$FlxG)g$_flixel_FlxG;
	r31 = r32->random;
	if( r31 == NULL ) hl_null_access();
	r33 = NULL;
	r34 = NULL;
	r35 = NULL;
	r22 = flixel_math_FlxRandom_float(r31,r33,r34,r35);
	r36 = (double)r15;
	r22 = r22 * r36;
	r36 = (double)r3;
	if( !(r36 < r22) ) goto label$83be7ae_3_126;
	r6 = r0->tileSprite;
	if( r6 == NULL ) hl_null_access();
	r37 = r6->animation;
	if( r37 == NULL ) hl_null_access();
	flixel_animation_FlxAnimationController_randomFrame(r37);
	r6 = r0->tileSprite;
	if( r6 == NULL ) hl_null_access();
	r24 = NULL;
	((void (*)(flixel__FlxSprite,bool*))r6->$type->vobj_proto[41])(r6,r24);
	r6 = r0->tileSprite;
	r29 = r27;
	r2 = &r29;
	r30 = r19;
	r38 = &r30;
	flixel_FlxSprite_stamp(((flixel__FlxSprite)r0),r6,r2,r38);
	label$83be7ae_3_126:
	r39 = r27 + r11;
	r27 = r39;
	++r28;
	goto label$83be7ae_3_98;
	label$83be7ae_3_130:
	r39 = r19 + r13;
	r19 = r39;
	++r16;
	goto label$83be7ae_3_92;
	label$83be7ae_3_134:
	r40 = true;
	r0->dirty = r40;
	return r0;
}

flixel__tile__FlxTileblock flixel_tile_FlxTileblock_loadTiles(flixel__tile__FlxTileblock r0,vdynamic* r1,int* r2,int* r3,int* r4) {
	String r12;
	bool *r11;
	flixel__graphics__frames__FlxTileFrames r23;
	flixel__math__FlxBasePoint r15, r25;
	bool r22;
	flixel__$FlxG r10;
	flixel__system__frontEnds__BitmapFrontEnd r9;
	flixel__util__FlxPool_flixel_math_FlxBasePoint r16;
	flixel__math__FlxRect r24;
	flixel__tile__FlxTileblock r26;
	flixel__graphics__FlxGraphic r8;
	double r18, r20;
	double *r19, *r21;
	flixel__math__$FlxBasePoint r17;
	int r5, r6, r7, r13, r14;
	if( r2 ) goto label$83be7ae_4_3;
	r5 = 0;
	goto label$83be7ae_4_4;
	label$83be7ae_4_3:
	r5 = *r2;
	label$83be7ae_4_4:
	if( r3 ) goto label$83be7ae_4_7;
	r6 = 0;
	goto label$83be7ae_4_8;
	label$83be7ae_4_7:
	r6 = *r3;
	label$83be7ae_4_8:
	if( r4 ) goto label$83be7ae_4_11;
	r7 = 0;
	goto label$83be7ae_4_12;
	label$83be7ae_4_11:
	r7 = *r4;
	label$83be7ae_4_12:
	if( r1 ) goto label$83be7ae_4_14;
	return r0;
	label$83be7ae_4_14:
	r10 = (flixel__$FlxG)g$_flixel_FlxG;
	r9 = r10->bitmap;
	if( r9 == NULL ) hl_null_access();
	r11 = NULL;
	r12 = NULL;
	r8 = flixel_system_frontEnds_BitmapFrontEnd_add(r9,r1,r11,r12);
	if( r8 ) goto label$83be7ae_4_22;
	return r0;
	label$83be7ae_4_22:
	r14 = 0;
	if( r5 != r14 ) goto label$83be7ae_4_31;
	if( r8 == NULL ) hl_null_access();
	r13 = r8->height;
	r5 = r13;
	r14 = r8->width;
	if( r14 >= r13 ) goto label$83be7ae_4_31;
	r13 = r8->width;
	r5 = r13;
	label$83be7ae_4_31:
	r14 = 0;
	if( r6 != r14 ) goto label$83be7ae_4_39;
	r6 = r5;
	if( r8 == NULL ) hl_null_access();
	r14 = r8->height;
	if( r14 >= r5 ) goto label$83be7ae_4_39;
	r13 = r8->height;
	r6 = r13;
	label$83be7ae_4_39:
	r17 = (flixel__math__$FlxBasePoint)g$_flixel_math_FlxBasePoint;
	r16 = r17->pool;
	if( r16 == NULL ) hl_null_access();
	r15 = flixel_util_FlxPool_flixel_math_FlxBasePoint_get(r16);
	if( r15 == NULL ) hl_null_access();
	r18 = (double)r5;
	r19 = &r18;
	r20 = (double)r6;
	r21 = &r20;
	r15 = ((flixel__math__FlxBasePoint (*)(flixel__math__FlxBasePoint,double*,double*))r15->$type->vobj_proto[0])(r15,r19,r21);
	if( r15 == NULL ) hl_null_access();
	r22 = false;
	r15->_inPool = r22;
	r24 = NULL;
	r25 = NULL;
	r23 = flixel_graphics_frames_FlxTileFrames_fromGraphic(r8,r15,r24,r25);
	r13 = r7;
	r2 = &r13;
	r26 = flixel_tile_FlxTileblock_loadFrames(r0,r23,r2);
	return r26;
}

void flixel_tile_FlxTileblock_setTile(flixel__tile__FlxTileblock r0,int r1,int r2,int r3) {
	bool r16;
	double r8, r11;
	int *r12, *r15;
	flixel__FlxSprite r6, r9;
	flixel__animation__FlxAnimationController r5;
	int r4, r10, r13, r14;
	r6 = r0->tileSprite;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->animation;
	if( r5 == NULL ) hl_null_access();
	r4 = flixel_animation_FlxAnimationController_set_frameIndex(r5,r3);
	r6 = r0->tileSprite;
	r9 = r0->tileSprite;
	if( r9 == NULL ) hl_null_access();
	r8 = ((double (*)(flixel__FlxSprite))r9->$type->vobj_proto[26])(r9);
	r10 = (int)r8;
	r4 = r1 * r10;
	r9 = r0->tileSprite;
	if( r9 == NULL ) hl_null_access();
	r11 = ((double (*)(flixel__FlxSprite))r9->$type->vobj_proto[27])(r9);
	r10 = r4;
	r12 = &r10;
	r14 = (int)r11;
	r13 = r2 * r14;
	r15 = &r13;
	flixel_FlxSprite_stamp(((flixel__FlxSprite)r0),r6,r12,r15);
	r16 = true;
	r0->dirty = r16;
	return;
}

