// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__input__gamepad__id__SwitchProID
#define INC_flixel__input__gamepad__id__SwitchProID
typedef struct _flixel__input__gamepad__id__$SwitchProID *flixel__input__gamepad__id__$SwitchProID;
typedef struct _flixel__input__gamepad__id__SwitchProID *flixel__input__gamepad__id__SwitchProID;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <flixel/input/gamepad/FlxGamepadAnalogStick.h>


struct _flixel__input__gamepad__id__$SwitchProID {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	int ZL;
	int ZR;
	int B;
	int A;
	int Y;
	int X;
	int MINUS;
	int HOME;
	int PLUS;
	int LEFT_STICK_CLICK;
	int RIGHT_STICK_CLICK;
	int L;
	int R;
	int DPAD_UP;
	int DPAD_DOWN;
	int DPAD_LEFT;
	int DPAD_RIGHT;
	int CAPTURE;
	flixel__input__gamepad__FlxGamepadAnalogStick LEFT_ANALOG_STICK;
	flixel__input__gamepad__FlxGamepadAnalogStick RIGHT_ANALOG_STICK;
};
struct _flixel__input__gamepad__id__SwitchProID {
	hl_type *$type;
};
#endif

