// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/graphics/opengl/ext/AMD_program_binary_Z400.h>

void lime_graphics_opengl_ext_AMD_program_binary_Z400_new(lime__graphics__opengl__ext__AMD_program_binary_Z400 r0) {
	int r1;
	r1 = 34624;
	r0->Z400_BINARY_AMD = r1;
	return;
}

