// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__graphics__opengl__ext__AMD_performance_monitor
#define INC_lime__graphics__opengl__ext__AMD_performance_monitor
typedef struct _lime__graphics__opengl__ext__$AMD_performance_monitor *lime__graphics__opengl__ext__$AMD_performance_monitor;
typedef struct _lime__graphics__opengl__ext__AMD_performance_monitor *lime__graphics__opengl__ext__AMD_performance_monitor;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__graphics__opengl__ext__$AMD_performance_monitor {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__graphics__opengl__ext__AMD_performance_monitor {
	hl_type *$type;
	int COUNTER_TYPE_AMD;
	int COUNTER_RANGE_AMD;
	int UNSIGNED_INT64_AMD;
	int PERCENTAGE_AMD;
	int PERFMON_RESULT_AVAILABLE_AMD;
	int PERFMON_RESULT_SIZE_AMD;
	int PERFMON_RESULT_AMD;
};
#endif

