// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__graphics__opengl__ext__APPLE_rgb_422
#define INC_lime__graphics__opengl__ext__APPLE_rgb_422
typedef struct _lime__graphics__opengl__ext__$APPLE_rgb_422 *lime__graphics__opengl__ext__$APPLE_rgb_422;
typedef struct _lime__graphics__opengl__ext__APPLE_rgb_422 *lime__graphics__opengl__ext__APPLE_rgb_422;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__graphics__opengl__ext__$APPLE_rgb_422 {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__graphics__opengl__ext__APPLE_rgb_422 {
	hl_type *$type;
	int RGB_422_APPLE;
	int UNSIGNED_SHORT_8_8_APPLE;
	int UNSIGNED_SHORT_8_8_REV_APPLE;
};
#endif

