// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/graphics/opengl/ext/APPLE_framebuffer_multisample.h>

void lime_graphics_opengl_ext_APPLE_framebuffer_multisample_new(lime__graphics__opengl__ext__APPLE_framebuffer_multisample r0) {
	int r1;
	r1 = 36010;
	r0->READ_FRAMEBUFFER_BINDING_APPLE = r1;
	r1 = 36006;
	r0->DRAW_FRAMEBUFFER_BINDING_APPLE = r1;
	r1 = 36009;
	r0->DRAW_FRAMEBUFFER_APPLE = r1;
	r1 = 36008;
	r0->READ_FRAMEBUFFER_APPLE = r1;
	r1 = 36183;
	r0->MAX_SAMPLES_APPLE = r1;
	r1 = 36182;
	r0->FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE = r1;
	r1 = 36011;
	r0->RENDERBUFFER_SAMPLES_APPLE = r1;
	return;
}

