// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/graphics/opengl/ext/DMP_shader_binary.h>

void lime_graphics_opengl_ext_DMP_shader_binary_new(lime__graphics__opengl__ext__DMP_shader_binary r0) {
	int r1;
	r1 = 37456;
	r0->SHADER_BINARY_DMP = r1;
	return;
}

