// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/graphics/opengl/ext/EXT_shader_framebuffer_fetch.h>

void lime_graphics_opengl_ext_EXT_shader_framebuffer_fetch_new(lime__graphics__opengl__ext__EXT_shader_framebuffer_fetch r0) {
	int r1;
	r1 = 35410;
	r0->FRAGMENT_SHADER_DISCARDS_SAMPLES_EXT = r1;
	return;
}

