// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__graphics__opengl__ext__EXT_bgra
#define INC_lime__graphics__opengl__ext__EXT_bgra
typedef struct _lime__graphics__opengl__ext__$EXT_bgra *lime__graphics__opengl__ext__$EXT_bgra;
typedef struct _lime__graphics__opengl__ext__EXT_bgra *lime__graphics__opengl__ext__EXT_bgra;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__graphics__opengl__ext__$EXT_bgra {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__graphics__opengl__ext__EXT_bgra {
	hl_type *$type;
	int BGR_EXT;
	int BGRA_EXT;
};
#endif

