// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__graphics__opengl__ext__FJ_shader_binary_GCCSO
#define INC_lime__graphics__opengl__ext__FJ_shader_binary_GCCSO
typedef struct _lime__graphics__opengl__ext__$FJ_shader_binary_GCCSO *lime__graphics__opengl__ext__$FJ_shader_binary_GCCSO;
typedef struct _lime__graphics__opengl__ext__FJ_shader_binary_GCCSO *lime__graphics__opengl__ext__FJ_shader_binary_GCCSO;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__graphics__opengl__ext__$FJ_shader_binary_GCCSO {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__graphics__opengl__ext__FJ_shader_binary_GCCSO {
	hl_type *$type;
	int GCCSO_SHADER_BINARY_FJ;
};
#endif

