// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__graphics__opengl__ext__OES_vertex_half_float
#define INC_lime__graphics__opengl__ext__OES_vertex_half_float
typedef struct _lime__graphics__opengl__ext__$OES_vertex_half_float *lime__graphics__opengl__ext__$OES_vertex_half_float;
typedef struct _lime__graphics__opengl__ext__OES_vertex_half_float *lime__graphics__opengl__ext__OES_vertex_half_float;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__graphics__opengl__ext__$OES_vertex_half_float {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__graphics__opengl__ext__OES_vertex_half_float {
	hl_type *$type;
	int HALF_FLOAT_OES;
};
#endif

