// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/graphics/opengl/ext/OES_depth24.h>

void lime_graphics_opengl_ext_OES_depth24_new(lime__graphics__opengl__ext__OES_depth24 r0) {
	int r1;
	r1 = 33190;
	r0->DEPTH_COMPONENT24_OES = r1;
	return;
}

