// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/graphics/opengl/ext/OES_mapbuffer.h>

void lime_graphics_opengl_ext_OES_mapbuffer_new(lime__graphics__opengl__ext__OES_mapbuffer r0) {
	int r1;
	r1 = 35005;
	r0->BUFFER_MAP_POINTER_OES = r1;
	r1 = 35004;
	r0->BUFFER_MAPPED_OES = r1;
	r1 = 35003;
	r0->BUFFER_ACCESS_OES = r1;
	r1 = 35001;
	r0->WRITE_ONLY_OES = r1;
	return;
}

