// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/graphics/opengl/ext/QCOM_driver_control.h>

void lime_graphics_opengl_ext_QCOM_driver_control_new(lime__graphics__opengl__ext__QCOM_driver_control r0) {
	return;
}

