// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__graphics__opengl__ext__QCOM_alpha_test
#define INC_lime__graphics__opengl__ext__QCOM_alpha_test
typedef struct _lime__graphics__opengl__ext__$QCOM_alpha_test *lime__graphics__opengl__ext__$QCOM_alpha_test;
typedef struct _lime__graphics__opengl__ext__QCOM_alpha_test *lime__graphics__opengl__ext__QCOM_alpha_test;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__graphics__opengl__ext__$QCOM_alpha_test {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__graphics__opengl__ext__QCOM_alpha_test {
	hl_type *$type;
	int ALPHA_TEST_QCOM;
	int ALPHA_TEST_FUNC_QCOM;
	int ALPHA_TEST_REF_QCOM;
};
#endif

