// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__graphics__opengl__ext__QCOM_binning_control
#define INC_lime__graphics__opengl__ext__QCOM_binning_control
typedef struct _lime__graphics__opengl__ext__$QCOM_binning_control *lime__graphics__opengl__ext__$QCOM_binning_control;
typedef struct _lime__graphics__opengl__ext__QCOM_binning_control *lime__graphics__opengl__ext__QCOM_binning_control;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__graphics__opengl__ext__$QCOM_binning_control {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__graphics__opengl__ext__QCOM_binning_control {
	hl_type *$type;
	int BINNING_CONTROL_HINT_QCOM;
	int CPU_OPTIMIZED_QCOM;
	int GPU_OPTIMIZED_QCOM;
	int RENDER_DIRECT_TO_FRAMEBUFFER_QCOM;
};
#endif

