// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/graphics/opengl/ext/QCOM_writeonly_rendering.h>

void lime_graphics_opengl_ext_QCOM_writeonly_rendering_new(lime__graphics__opengl__ext__QCOM_writeonly_rendering r0) {
	int r1;
	r1 = 34851;
	r0->WRITEONLY_RENDERING_QCOM = r1;
	return;
}

