// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__text__TextLineMetrics
#define INC_openfl__text__TextLineMetrics
typedef struct _openfl__text__$TextLineMetrics *openfl__text__$TextLineMetrics;
typedef struct _openfl__text__TextLineMetrics *openfl__text__TextLineMetrics;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _openfl__text__$TextLineMetrics {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _openfl__text__TextLineMetrics {
	hl_type *$type;
	double ascent;
	double descent;
	double height;
	double leading;
	double width;
	double x;
};
#endif

