// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl___Vector__FunctionVector
#define INC_openfl___Vector__FunctionVector
typedef struct _openfl___Vector__$FunctionVector *openfl___Vector__$FunctionVector;
typedef struct _openfl___Vector__FunctionVector *openfl___Vector__FunctionVector;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayDyn.h>


struct _openfl___Vector__$FunctionVector {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _openfl___Vector__FunctionVector {
	hl_type *$type;
	bool fixed;
	hl__types__ArrayDyn __array;
	int __tempIndex;
	vvirtual* f$3;
};
#endif

