// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/media/openal/_ALBuffer/ALBuffer_Impl_.h>

vdynamic* lime_media_openal__ALBuffer_ALBuffer_Impl___new(vdynamic* r0) {
	return r0;
}

