// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/system/frontEnds/BitmapFrontEnd.h>
#include <flixel/graphics/FlxGraphic.h>
vvirtual* haxe_ds_StringMap_keys(haxe__ds__StringMap);
extern hl_type t$fun_bf7849e;
extern hl_type t$fun_820f49a;
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
void flixel_graphics_FlxGraphic_onAssetsReload(flixel__graphics__FlxGraphic);
void flixel_graphics_FlxGraphic_onContext(flixel__graphics__FlxGraphic);
void flixel_graphics_FlxGraphic_dump(flixel__graphics__FlxGraphic);
void flixel_graphics_FlxGraphic_undump(flixel__graphics__FlxGraphic);
flixel__graphics__FlxGraphic flixel_graphics_FlxGraphic_fromRectangle(int,int,int,bool*,String);
#include <openfl/display/BitmapData.h>
extern flixel__graphics__$FlxGraphic g$_flixel_graphics_FlxGraphic;
bool Std_isOfType(vdynamic*,vdynamic*);
extern hl_type t$flixel_graphics_FlxGraphic;
extern hl_type t$_dyn;
flixel__graphics__FlxGraphic flixel_graphics_FlxGraphic_fromGraphic(flixel__graphics__FlxGraphic,bool*,String);
extern openfl__display__$BitmapData g$_openfl_display_BitmapData;
extern hl_type t$openfl_display_BitmapData;
flixel__graphics__FlxGraphic flixel_graphics_FlxGraphic_fromBitmapData(openfl__display__BitmapData,bool*,String,bool*);
String Std_string(vdynamic*);
flixel__graphics__FlxGraphic flixel_graphics_FlxGraphic_fromAssetKey(String,bool*,String,bool*);
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);
String Type_getClassName(hl__Class);
String flixel_system_frontEnds_BitmapFrontEnd_getUniqueKey(flixel__system__frontEnds__BitmapFrontEnd,String);
extern String s$pixels;
#include <hl/natives.h>
String String___alloc__(vbyte*,int);
String String___add__(String,String);
#include <flixel/math/FlxBasePoint.h>
#include <flixel/math/FlxRect.h>
extern String s$_Region_;
extern String s$b14a7b8;
extern String s$_FrameSize_;
extern String s$_Spaces_;
extern String s$_Border_;
#include <openfl/media/Sound.h>
#include <openfl/text/Font.h>
#include <openfl/utils/Assets.h>
extern openfl__utils__$Assets g$_openfl_utils_Assets;
extern hl_type t$fun_a1d0651;
bool haxe_ds_StringMap_remove(haxe__ds__StringMap,String);
void flixel_graphics_FlxGraphic_destroy(flixel__graphics__FlxGraphic);
int flixel_graphics_FlxGraphic_get_useCount(flixel__graphics__FlxGraphic);
extern hl_type t$haxe_ds_StringMap;
void haxe_ds_StringMap_new(haxe__ds__StringMap);
bool flixel_graphics_FlxGraphic_get_destroyOnNoUse(flixel__graphics__FlxGraphic);
#include <lime/_internal/backend/native/NativeOpenGLRenderContext.h>
#include <lime/graphics/opengl/GL.h>
extern lime__graphics__opengl__$GL g$_lime_graphics_opengl_GL;
vdynamic* lime__internal_backend_native_NativeOpenGLRenderContext_getParameter(lime___internal__backend__native__NativeOpenGLRenderContext,int);
extern hl_type t$_i32;
#include <flixel/FlxG.h>
#include <flixel/graphics/frames/FlxImageFrame.h>
void openfl_display_BitmapData_new(openfl__display__BitmapData,int,int,bool*,int*);
extern flixel__$FlxG g$_flixel_FlxG;
extern String s$whitePixels;
flixel__graphics__frames__FlxImageFrame flixel_graphics_FlxGraphic_get_imageFrame(flixel__graphics__FlxGraphic);
flixel__graphics__frames__FlxFrame flixel_graphics_frames_FlxImageFrame_get_frame(flixel__graphics__frames__FlxImageFrame);

void flixel_system_frontEnds_BitmapFrontEnd_onAssetsReload(flixel__system__frontEnds__BitmapFrontEnd r0,vdynamic* r1) {
	String r6, r8;
	hl__Class r10;
	haxe__ds__StringMap r3;
	vvirtual *r2;
	bool r5;
	flixel__graphics__FlxGraphic r9;
	vdynamic *r7;
	r3 = r0->_cache;
	if( r3 == NULL ) hl_null_access();
	r2 = haxe_ds_StringMap_keys(r3);
	label$87ef034_1_3:
	if( r2 == NULL ) hl_null_access();
	if( hl_vfields(r2)[0] ) r5 = ((bool (*)(vdynamic*))hl_vfields(r2)[0])(r2->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r2->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r5 = (bool)ret.v.i;
	}
	if( !r5 ) goto label$87ef034_1_20;
	if( hl_vfields(r2)[1] ) r6 = ((String (*)(vdynamic*))hl_vfields(r2)[1])(r2->value); else {
		r6 = (String)hl_dyn_call_obj(r2->value,&t$fun_820f49a,151160317/*next*/,NULL,NULL);
	}
	r3 = r0->_cache;
	if( r3 == NULL ) hl_null_access();
	r7 = haxe_ds_StringMap_get(r3,r6);
	r9 = (flixel__graphics__FlxGraphic)r7;
	if( !r9 ) goto label$87ef034_1_19;
	if( r9 == NULL ) hl_null_access();
	r10 = r9->assetsClass;
	if( r10 ) goto label$87ef034_1_18;
	r8 = r9->assetsKey;
	if( !r8 ) goto label$87ef034_1_19;
	label$87ef034_1_18:
	flixel_graphics_FlxGraphic_onAssetsReload(r9);
	label$87ef034_1_19:
	goto label$87ef034_1_3;
	label$87ef034_1_20:
	return;
}

void flixel_system_frontEnds_BitmapFrontEnd_onContext(flixel__system__frontEnds__BitmapFrontEnd r0) {
	String r5;
	haxe__ds__StringMap r2;
	vvirtual *r1;
	bool r4;
	flixel__graphics__FlxGraphic r7;
	vdynamic *r6;
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r1 = haxe_ds_StringMap_keys(r2);
	label$87ef034_2_3:
	if( r1 == NULL ) hl_null_access();
	if( hl_vfields(r1)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r1)[0])(r1->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r1->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$87ef034_2_18;
	if( hl_vfields(r1)[1] ) r5 = ((String (*)(vdynamic*))hl_vfields(r1)[1])(r1->value); else {
		r5 = (String)hl_dyn_call_obj(r1->value,&t$fun_820f49a,151160317/*next*/,NULL,NULL);
	}
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r6 = haxe_ds_StringMap_get(r2,r5);
	r7 = (flixel__graphics__FlxGraphic)r6;
	if( !r7 ) goto label$87ef034_2_17;
	if( r7 == NULL ) hl_null_access();
	r4 = r7->isDumped;
	if( !r4 ) goto label$87ef034_2_17;
	flixel_graphics_FlxGraphic_onContext(r7);
	label$87ef034_2_17:
	goto label$87ef034_2_3;
	label$87ef034_2_18:
	return;
}

void flixel_system_frontEnds_BitmapFrontEnd_dumpCache(flixel__system__frontEnds__BitmapFrontEnd r0) {
	String r5, r7;
	hl__Class r9;
	haxe__ds__StringMap r2;
	vvirtual *r1;
	bool r4;
	flixel__graphics__FlxGraphic r8;
	vdynamic *r6;
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r1 = haxe_ds_StringMap_keys(r2);
	label$87ef034_3_3:
	if( r1 == NULL ) hl_null_access();
	if( hl_vfields(r1)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r1)[0])(r1->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r1->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$87ef034_3_20;
	if( hl_vfields(r1)[1] ) r5 = ((String (*)(vdynamic*))hl_vfields(r1)[1])(r1->value); else {
		r5 = (String)hl_dyn_call_obj(r1->value,&t$fun_820f49a,151160317/*next*/,NULL,NULL);
	}
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r6 = haxe_ds_StringMap_get(r2,r5);
	r8 = (flixel__graphics__FlxGraphic)r6;
	if( !r8 ) goto label$87ef034_3_19;
	if( r8 == NULL ) hl_null_access();
	r9 = r8->assetsClass;
	if( r9 ) goto label$87ef034_3_18;
	r7 = r8->assetsKey;
	if( !r7 ) goto label$87ef034_3_19;
	label$87ef034_3_18:
	flixel_graphics_FlxGraphic_dump(r8);
	label$87ef034_3_19:
	goto label$87ef034_3_3;
	label$87ef034_3_20:
	return;
}

void flixel_system_frontEnds_BitmapFrontEnd_undumpCache(flixel__system__frontEnds__BitmapFrontEnd r0) {
	String r5;
	haxe__ds__StringMap r2;
	vvirtual *r1;
	bool r4;
	flixel__graphics__FlxGraphic r7;
	vdynamic *r6;
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r1 = haxe_ds_StringMap_keys(r2);
	label$87ef034_4_3:
	if( r1 == NULL ) hl_null_access();
	if( hl_vfields(r1)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r1)[0])(r1->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r1->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$87ef034_4_18;
	if( hl_vfields(r1)[1] ) r5 = ((String (*)(vdynamic*))hl_vfields(r1)[1])(r1->value); else {
		r5 = (String)hl_dyn_call_obj(r1->value,&t$fun_820f49a,151160317/*next*/,NULL,NULL);
	}
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r6 = haxe_ds_StringMap_get(r2,r5);
	r7 = (flixel__graphics__FlxGraphic)r6;
	if( !r7 ) goto label$87ef034_4_17;
	if( r7 == NULL ) hl_null_access();
	r4 = r7->isDumped;
	if( !r4 ) goto label$87ef034_4_17;
	flixel_graphics_FlxGraphic_undump(r7);
	label$87ef034_4_17:
	goto label$87ef034_4_3;
	label$87ef034_4_18:
	return;
}

bool flixel_system_frontEnds_BitmapFrontEnd_checkCache(flixel__system__frontEnds__BitmapFrontEnd r0,String r1) {
	haxe__ds__StringMap r4;
	bool r2;
	flixel__graphics__FlxGraphic r5, r6;
	vdynamic *r3;
	r4 = r0->_cache;
	if( r4 == NULL ) hl_null_access();
	r3 = haxe_ds_StringMap_get(r4,r1);
	r5 = (flixel__graphics__FlxGraphic)r3;
	r6 = NULL;
	if( r5 != r6 ) goto label$87ef034_5_8;
	r2 = false;
	goto label$87ef034_5_9;
	label$87ef034_5_8:
	r2 = true;
	label$87ef034_5_9:
	return r2;
}

flixel__graphics__FlxGraphic flixel_system_frontEnds_BitmapFrontEnd_create(flixel__system__frontEnds__BitmapFrontEnd r0,int r1,int r2,int r3,bool* r4,String r5) {
	bool r6, r8;
	flixel__graphics__FlxGraphic r7;
	if( r4 ) goto label$87ef034_6_3;
	r6 = false;
	goto label$87ef034_6_4;
	label$87ef034_6_3:
	r6 = *r4;
	label$87ef034_6_4:
	r8 = r6;
	r4 = &r8;
	r7 = flixel_graphics_FlxGraphic_fromRectangle(r1,r2,r3,r4,r5);
	return r7;
}

flixel__graphics__FlxGraphic flixel_system_frontEnds_BitmapFrontEnd_add(flixel__system__frontEnds__BitmapFrontEnd r0,vdynamic* r1,bool* r2,String r3) {
	bool *r12;
	String r8;
	bool r4, r5, r9, r13;
	openfl__display__$BitmapData r10;
	flixel__graphics__FlxGraphic r7;
	flixel__graphics__$FlxGraphic r6;
	openfl__display__BitmapData r11;
	if( r2 ) goto label$87ef034_7_3;
	r4 = false;
	goto label$87ef034_7_4;
	label$87ef034_7_3:
	r4 = *r2;
	label$87ef034_7_4:
	r6 = (flixel__graphics__$FlxGraphic)g$_flixel_graphics_FlxGraphic;
	r5 = Std_isOfType(r1,((vdynamic*)r6));
	if( !r5 ) goto label$87ef034_7_12;
	r7 = (flixel__graphics__FlxGraphic)hl_dyn_castp(&r1,&t$_dyn,&t$flixel_graphics_FlxGraphic);
	r5 = r4;
	r2 = &r5;
	r7 = flixel_graphics_FlxGraphic_fromGraphic(r7,r2,r3);
	return r7;
	label$87ef034_7_12:
	r10 = (openfl__display__$BitmapData)g$_openfl_display_BitmapData;
	r9 = Std_isOfType(r1,((vdynamic*)r10));
	if( !r9 ) goto label$87ef034_7_21;
	r11 = (openfl__display__BitmapData)hl_dyn_castp(&r1,&t$_dyn,&t$openfl_display_BitmapData);
	r9 = r4;
	r2 = &r9;
	r12 = NULL;
	r7 = flixel_graphics_FlxGraphic_fromBitmapData(r11,r2,r3,r12);
	return r7;
	label$87ef034_7_21:
	r8 = Std_string(r1);
	r13 = r4;
	r2 = &r13;
	r12 = NULL;
	r7 = flixel_graphics_FlxGraphic_fromAssetKey(r8,r2,r3,r12);
	return r7;
}

flixel__graphics__FlxGraphic flixel_system_frontEnds_BitmapFrontEnd_addGraphic(flixel__system__frontEnds__BitmapFrontEnd r0,flixel__graphics__FlxGraphic r1) {
	String r4;
	haxe__ds__StringMap r3;
	r3 = r0->_cache;
	if( r3 == NULL ) hl_null_access();
	if( r1 == NULL ) hl_null_access();
	r4 = r1->key;
	haxe_ds_StringMap_set(r3,r4,((vdynamic*)r1));
	return r1;
}

flixel__graphics__FlxGraphic flixel_system_frontEnds_BitmapFrontEnd_get(flixel__system__frontEnds__BitmapFrontEnd r0,String r1) {
	haxe__ds__StringMap r3;
	flixel__graphics__FlxGraphic r4;
	vdynamic *r2;
	r3 = r0->_cache;
	if( r3 == NULL ) hl_null_access();
	r2 = haxe_ds_StringMap_get(r3,r1);
	r4 = (flixel__graphics__FlxGraphic)r2;
	return r4;
}

String flixel_system_frontEnds_BitmapFrontEnd_findKeyForBitmap(flixel__system__frontEnds__BitmapFrontEnd r0,openfl__display__BitmapData r1) {
	String r5;
	haxe__ds__StringMap r3;
	vvirtual *r2;
	bool r4;
	flixel__graphics__FlxGraphic r7;
	vdynamic *r6;
	openfl__display__BitmapData r8;
	r3 = r0->_cache;
	if( r3 == NULL ) hl_null_access();
	r2 = haxe_ds_StringMap_keys(r3);
	label$87ef034_10_3:
	if( r2 == NULL ) hl_null_access();
	if( hl_vfields(r2)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r2)[0])(r2->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r2->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$87ef034_10_18;
	if( hl_vfields(r2)[1] ) r5 = ((String (*)(vdynamic*))hl_vfields(r2)[1])(r2->value); else {
		r5 = (String)hl_dyn_call_obj(r2->value,&t$fun_820f49a,151160317/*next*/,NULL,NULL);
	}
	r3 = r0->_cache;
	if( r3 == NULL ) hl_null_access();
	r6 = haxe_ds_StringMap_get(r3,r5);
	r7 = (flixel__graphics__FlxGraphic)r6;
	if( !r7 ) goto label$87ef034_10_17;
	if( r7 == NULL ) hl_null_access();
	r8 = r7->bitmap;
	if( r8 != r1 ) goto label$87ef034_10_17;
	return r5;
	label$87ef034_10_17:
	goto label$87ef034_10_3;
	label$87ef034_10_18:
	r5 = NULL;
	return r5;
}

String flixel_system_frontEnds_BitmapFrontEnd_getKeyForClass(flixel__system__frontEnds__BitmapFrontEnd r0,hl__Class r1) {
	String r2;
	r2 = Type_getClassName(r1);
	return r2;
}

String flixel_system_frontEnds_BitmapFrontEnd_generateKey(flixel__system__frontEnds__BitmapFrontEnd r0,String r1,String r2,bool* r3) {
	String r5, r6;
	bool r4;
	if( r3 ) goto label$87ef034_12_3;
	r4 = false;
	goto label$87ef034_12_4;
	label$87ef034_12_3:
	r4 = *r3;
	label$87ef034_12_4:
	r5 = r2;
	if( r2 ) goto label$87ef034_12_7;
	r5 = r1;
	label$87ef034_12_7:
	if( r4 ) goto label$87ef034_12_9;
	if( r5 ) goto label$87ef034_12_11;
	label$87ef034_12_9:
	r6 = flixel_system_frontEnds_BitmapFrontEnd_getUniqueKey(r0,r5);
	r5 = r6;
	label$87ef034_12_11:
	return r5;
}

String flixel_system_frontEnds_BitmapFrontEnd_getUniqueKey(flixel__system__frontEnds__BitmapFrontEnd r0,String r1) {
	String r2, r8, r12;
	haxe__ds__StringMap r4;
	bool r7;
	flixel__graphics__FlxGraphic r5;
	int *r10;
	vdynamic *r3;
	vbyte *r11;
	int r6, r9;
	if( r1 ) goto label$87ef034_13_3;
	r2 = (String)s$pixels;
	r1 = r2;
	label$87ef034_13_3:
	r4 = r0->_cache;
	if( r4 == NULL ) hl_null_access();
	r2 = r1;
	r3 = haxe_ds_StringMap_get(r4,r1);
	r5 = (flixel__graphics__FlxGraphic)r3;
	if( r5 ) goto label$87ef034_13_10;
	return r1;
	label$87ef034_13_10:
	r6 = r0->_lastUniqueKeyIndex;
	label$87ef034_13_11:
	r7 = true;
	if( !r7 ) goto label$87ef034_13_28;
	++r6;
	r9 = r6;
	r10 = &r9;
	r11 = hl_itos(r9,r10);
	r12 = String___alloc__(r11,r9);
	r8 = String___add__(r1,r12);
	r2 = r8;
	r4 = r0->_cache;
	if( r4 == NULL ) hl_null_access();
	r3 = haxe_ds_StringMap_get(r4,r8);
	r5 = (flixel__graphics__FlxGraphic)r3;
	if( r5 ) goto label$87ef034_13_27;
	goto label$87ef034_13_28;
	label$87ef034_13_27:
	goto label$87ef034_13_11;
	label$87ef034_13_28:
	r0->_lastUniqueKeyIndex = r6;
	return r2;
}

String flixel_system_frontEnds_BitmapFrontEnd_getKeyWithSpacesAndBorders(flixel__system__frontEnds__BitmapFrontEnd r0,String r1,flixel__math__FlxBasePoint r2,flixel__math__FlxBasePoint r3,flixel__math__FlxBasePoint r4,flixel__math__FlxRect r5) {
	String r6, r7, r8, r13;
	double r9;
	int *r11;
	vbyte *r12;
	int r10;
	r6 = r1;
	if( !r5 ) goto label$87ef034_14_32;
	r8 = (String)s$_Region_;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->x;
	r11 = &r10;
	r12 = hl_ftos(r9,r11);
	r13 = String___alloc__(r12,r10);
	r8 = String___add__(r8,r13);
	r13 = (String)s$b14a7b8;
	r8 = String___add__(r8,r13);
	r9 = r5->y;
	r11 = &r10;
	r12 = hl_ftos(r9,r11);
	r13 = String___alloc__(r12,r10);
	r8 = String___add__(r8,r13);
	r13 = (String)s$b14a7b8;
	r8 = String___add__(r8,r13);
	r9 = r5->width;
	r11 = &r10;
	r12 = hl_ftos(r9,r11);
	r13 = String___alloc__(r12,r10);
	r8 = String___add__(r8,r13);
	r13 = (String)s$b14a7b8;
	r8 = String___add__(r8,r13);
	r9 = r5->height;
	r11 = &r10;
	r12 = hl_ftos(r9,r11);
	r13 = String___alloc__(r12,r10);
	r8 = String___add__(r8,r13);
	r7 = String___add__(r1,r8);
	r6 = r7;
	label$87ef034_14_32:
	if( !r2 ) goto label$87ef034_14_49;
	r8 = (String)s$_FrameSize_;
	if( r2 == NULL ) hl_null_access();
	r9 = r2->x;
	r11 = &r10;
	r12 = hl_ftos(r9,r11);
	r13 = String___alloc__(r12,r10);
	r8 = String___add__(r8,r13);
	r13 = (String)s$b14a7b8;
	r8 = String___add__(r8,r13);
	r9 = r2->y;
	r11 = &r10;
	r12 = hl_ftos(r9,r11);
	r13 = String___alloc__(r12,r10);
	r8 = String___add__(r8,r13);
	r7 = String___add__(r6,r8);
	r6 = r7;
	label$87ef034_14_49:
	if( !r3 ) goto label$87ef034_14_66;
	r8 = (String)s$_Spaces_;
	if( r3 == NULL ) hl_null_access();
	r9 = r3->x;
	r11 = &r10;
	r12 = hl_ftos(r9,r11);
	r13 = String___alloc__(r12,r10);
	r8 = String___add__(r8,r13);
	r13 = (String)s$b14a7b8;
	r8 = String___add__(r8,r13);
	r9 = r3->y;
	r11 = &r10;
	r12 = hl_ftos(r9,r11);
	r13 = String___alloc__(r12,r10);
	r8 = String___add__(r8,r13);
	r7 = String___add__(r6,r8);
	r6 = r7;
	label$87ef034_14_66:
	if( !r4 ) goto label$87ef034_14_83;
	r8 = (String)s$_Border_;
	if( r4 == NULL ) hl_null_access();
	r9 = r4->x;
	r11 = &r10;
	r12 = hl_ftos(r9,r11);
	r13 = String___alloc__(r12,r10);
	r8 = String___add__(r8,r13);
	r13 = (String)s$b14a7b8;
	r8 = String___add__(r8,r13);
	r9 = r4->y;
	r11 = &r10;
	r12 = hl_ftos(r9,r11);
	r13 = String___alloc__(r12,r10);
	r8 = String___add__(r8,r13);
	r7 = String___add__(r6,r8);
	r6 = r7;
	label$87ef034_14_83:
	return r6;
}

void flixel_system_frontEnds_BitmapFrontEnd_remove(flixel__system__frontEnds__BitmapFrontEnd r0,flixel__graphics__FlxGraphic r1) {
	openfl__utils__$Assets r6;
	String r3;
	haxe__ds__StringMap r7;
	vvirtual *r5;
	bool r4;
	if( !r1 ) goto label$87ef034_15_12;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->key;
	if( !r3 ) goto label$87ef034_15_11;
	r6 = (openfl__utils__$Assets)g$_openfl_utils_Assets;
	r5 = r6->cache;
	if( r5 == NULL ) hl_null_access();
	if( hl_vfields(r5)[6] ) r4 = ((bool (*)(vdynamic*,String))hl_vfields(r5)[6])(r5->value,r3); else {
		void *args[] = {r3};
		vdynamic ret;
		hl_dyn_call_obj(r5->value,&t$fun_a1d0651,-311831779/*removeBitmapData*/,args,&ret);
		r4 = (bool)ret.v.i;
	}
	r7 = r0->_cache;
	if( r7 == NULL ) hl_null_access();
	r4 = haxe_ds_StringMap_remove(r7,r3);
	label$87ef034_15_11:
	flixel_graphics_FlxGraphic_destroy(r1);
	label$87ef034_15_12:
	return;
}

void flixel_system_frontEnds_BitmapFrontEnd_removeByKey(flixel__system__frontEnds__BitmapFrontEnd r0,String r1) {
	openfl__utils__$Assets r8;
	vvirtual *r7;
	haxe__ds__StringMap r4;
	bool r6;
	flixel__graphics__FlxGraphic r5;
	vdynamic *r3;
	if( !r1 ) goto label$87ef034_16_16;
	r4 = r0->_cache;
	if( r4 == NULL ) hl_null_access();
	r3 = haxe_ds_StringMap_get(r4,r1);
	r5 = (flixel__graphics__FlxGraphic)r3;
	if( !r1 ) goto label$87ef034_16_13;
	r8 = (openfl__utils__$Assets)g$_openfl_utils_Assets;
	r7 = r8->cache;
	if( r7 == NULL ) hl_null_access();
	if( hl_vfields(r7)[6] ) r6 = ((bool (*)(vdynamic*,String))hl_vfields(r7)[6])(r7->value,r1); else {
		void *args[] = {r1};
		vdynamic ret;
		hl_dyn_call_obj(r7->value,&t$fun_a1d0651,-311831779/*removeBitmapData*/,args,&ret);
		r6 = (bool)ret.v.i;
	}
	r4 = r0->_cache;
	if( r4 == NULL ) hl_null_access();
	r6 = haxe_ds_StringMap_remove(r4,r1);
	label$87ef034_16_13:
	if( !r5 ) goto label$87ef034_16_16;
	if( r5 == NULL ) hl_null_access();
	flixel_graphics_FlxGraphic_destroy(r5);
	label$87ef034_16_16:
	return;
}

void flixel_system_frontEnds_BitmapFrontEnd_removeIfNoUse(flixel__system__frontEnds__BitmapFrontEnd r0,flixel__graphics__FlxGraphic r1) {
	bool r5;
	int r3, r4;
	if( !r1 ) goto label$87ef034_17_8;
	if( r1 == NULL ) hl_null_access();
	r3 = flixel_graphics_FlxGraphic_get_useCount(r1);
	r4 = 0;
	if( r3 != r4 ) goto label$87ef034_17_8;
	r5 = r1->persist;
	if( r5 ) goto label$87ef034_17_8;
	flixel_system_frontEnds_BitmapFrontEnd_remove(r0,r1);
	label$87ef034_17_8:
	return;
}

void flixel_system_frontEnds_BitmapFrontEnd_clearCache(flixel__system__frontEnds__BitmapFrontEnd r0) {
	openfl__utils__$Assets r11;
	String r6;
	vvirtual *r4, *r10;
	haxe__ds__StringMap r2;
	bool r5;
	flixel__graphics__FlxGraphic r7;
	vdynamic *r3;
	int r8, r9;
	r2 = r0->_cache;
	if( r2 ) goto label$87ef034_18_6;
	r2 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r2);
	r0->_cache = r2;
	return;
	label$87ef034_18_6:
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r4 = haxe_ds_StringMap_keys(r2);
	label$87ef034_18_9:
	if( r4 == NULL ) hl_null_access();
	if( hl_vfields(r4)[0] ) r5 = ((bool (*)(vdynamic*))hl_vfields(r4)[0])(r4->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r4->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r5 = (bool)ret.v.i;
	}
	if( !r5 ) goto label$87ef034_18_35;
	if( hl_vfields(r4)[1] ) r6 = ((String (*)(vdynamic*))hl_vfields(r4)[1])(r4->value); else {
		r6 = (String)hl_dyn_call_obj(r4->value,&t$fun_820f49a,151160317/*next*/,NULL,NULL);
	}
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r3 = haxe_ds_StringMap_get(r2,r6);
	r7 = (flixel__graphics__FlxGraphic)r3;
	if( !r7 ) goto label$87ef034_18_34;
	if( r7 == NULL ) hl_null_access();
	r5 = r7->persist;
	if( r5 ) goto label$87ef034_18_34;
	r8 = flixel_graphics_FlxGraphic_get_useCount(r7);
	r9 = 0;
	if( r9 < r8 ) goto label$87ef034_18_34;
	if( !r6 ) goto label$87ef034_18_33;
	r11 = (openfl__utils__$Assets)g$_openfl_utils_Assets;
	r10 = r11->cache;
	if( r10 == NULL ) hl_null_access();
	if( hl_vfields(r10)[6] ) r5 = ((bool (*)(vdynamic*,String))hl_vfields(r10)[6])(r10->value,r6); else {
		void *args[] = {r6};
		vdynamic ret;
		hl_dyn_call_obj(r10->value,&t$fun_a1d0651,-311831779/*removeBitmapData*/,args,&ret);
		r5 = (bool)ret.v.i;
	}
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r5 = haxe_ds_StringMap_remove(r2,r6);
	label$87ef034_18_33:
	flixel_graphics_FlxGraphic_destroy(r7);
	label$87ef034_18_34:
	goto label$87ef034_18_9;
	label$87ef034_18_35:
	return;
}

void flixel_system_frontEnds_BitmapFrontEnd_removeKey(flixel__system__frontEnds__BitmapFrontEnd r0,String r1) {
	openfl__utils__$Assets r5;
	haxe__ds__StringMap r6;
	vvirtual *r4;
	bool r3;
	if( !r1 ) goto label$87ef034_19_8;
	r5 = (openfl__utils__$Assets)g$_openfl_utils_Assets;
	r4 = r5->cache;
	if( r4 == NULL ) hl_null_access();
	if( hl_vfields(r4)[6] ) r3 = ((bool (*)(vdynamic*,String))hl_vfields(r4)[6])(r4->value,r1); else {
		void *args[] = {r1};
		vdynamic ret;
		hl_dyn_call_obj(r4->value,&t$fun_a1d0651,-311831779/*removeBitmapData*/,args,&ret);
		r3 = (bool)ret.v.i;
	}
	r6 = r0->_cache;
	if( r6 == NULL ) hl_null_access();
	r3 = haxe_ds_StringMap_remove(r6,r1);
	label$87ef034_19_8:
	return;
}

void flixel_system_frontEnds_BitmapFrontEnd_reset(flixel__system__frontEnds__BitmapFrontEnd r0) {
	openfl__utils__$Assets r9;
	String r6;
	vvirtual *r4, *r8;
	haxe__ds__StringMap r2;
	bool r5;
	flixel__graphics__FlxGraphic r7;
	vdynamic *r3;
	r2 = r0->_cache;
	if( r2 ) goto label$87ef034_20_6;
	r2 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r2);
	r0->_cache = r2;
	return;
	label$87ef034_20_6:
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r4 = haxe_ds_StringMap_keys(r2);
	label$87ef034_20_9:
	if( r4 == NULL ) hl_null_access();
	if( hl_vfields(r4)[0] ) r5 = ((bool (*)(vdynamic*))hl_vfields(r4)[0])(r4->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r4->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r5 = (bool)ret.v.i;
	}
	if( !r5 ) goto label$87ef034_20_30;
	if( hl_vfields(r4)[1] ) r6 = ((String (*)(vdynamic*))hl_vfields(r4)[1])(r4->value); else {
		r6 = (String)hl_dyn_call_obj(r4->value,&t$fun_820f49a,151160317/*next*/,NULL,NULL);
	}
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r3 = haxe_ds_StringMap_get(r2,r6);
	r7 = (flixel__graphics__FlxGraphic)r3;
	if( !r6 ) goto label$87ef034_20_26;
	r9 = (openfl__utils__$Assets)g$_openfl_utils_Assets;
	r8 = r9->cache;
	if( r8 == NULL ) hl_null_access();
	if( hl_vfields(r8)[6] ) r5 = ((bool (*)(vdynamic*,String))hl_vfields(r8)[6])(r8->value,r6); else {
		void *args[] = {r6};
		vdynamic ret;
		hl_dyn_call_obj(r8->value,&t$fun_a1d0651,-311831779/*removeBitmapData*/,args,&ret);
		r5 = (bool)ret.v.i;
	}
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r5 = haxe_ds_StringMap_remove(r2,r6);
	label$87ef034_20_26:
	if( !r7 ) goto label$87ef034_20_29;
	if( r7 == NULL ) hl_null_access();
	flixel_graphics_FlxGraphic_destroy(r7);
	label$87ef034_20_29:
	goto label$87ef034_20_9;
	label$87ef034_20_30:
	return;
}

void flixel_system_frontEnds_BitmapFrontEnd_clearUnused(flixel__system__frontEnds__BitmapFrontEnd r0) {
	String r5;
	haxe__ds__StringMap r2;
	vvirtual *r1;
	bool r4;
	flixel__graphics__FlxGraphic r7;
	vdynamic *r6;
	int r8, r9;
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r1 = haxe_ds_StringMap_keys(r2);
	label$87ef034_21_3:
	if( r1 == NULL ) hl_null_access();
	if( hl_vfields(r1)[0] ) r4 = ((bool (*)(vdynamic*))hl_vfields(r1)[0])(r1->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r1->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r4 = (bool)ret.v.i;
	}
	if( !r4 ) goto label$87ef034_21_23;
	if( hl_vfields(r1)[1] ) r5 = ((String (*)(vdynamic*))hl_vfields(r1)[1])(r1->value); else {
		r5 = (String)hl_dyn_call_obj(r1->value,&t$fun_820f49a,151160317/*next*/,NULL,NULL);
	}
	r2 = r0->_cache;
	if( r2 == NULL ) hl_null_access();
	r6 = haxe_ds_StringMap_get(r2,r5);
	r7 = (flixel__graphics__FlxGraphic)r6;
	if( !r7 ) goto label$87ef034_21_22;
	if( r7 == NULL ) hl_null_access();
	r8 = flixel_graphics_FlxGraphic_get_useCount(r7);
	r9 = 0;
	if( r9 < r8 ) goto label$87ef034_21_22;
	r4 = r7->persist;
	if( r4 ) goto label$87ef034_21_22;
	r4 = flixel_graphics_FlxGraphic_get_destroyOnNoUse(r7);
	if( !r4 ) goto label$87ef034_21_22;
	flixel_system_frontEnds_BitmapFrontEnd_removeByKey(r0,r5);
	label$87ef034_21_22:
	goto label$87ef034_21_3;
	label$87ef034_21_23:
	return;
}

int flixel_system_frontEnds_BitmapFrontEnd_get_maxTextureSize(flixel__system__frontEnds__BitmapFrontEnd r0) {
	lime__graphics__opengl__$GL r3;
	lime___internal__backend__native__NativeOpenGLRenderContext r2;
	vdynamic *r1;
	int r4;
	r3 = (lime__graphics__opengl__$GL)g$_lime_graphics_opengl_GL;
	r2 = r3->context;
	if( r2 == NULL ) hl_null_access();
	r4 = 3379;
	r1 = lime__internal_backend_native_NativeOpenGLRenderContext_getParameter(r2,r4);
	r4 = (int)hl_dyn_casti(&r1,&t$_dyn,&t$_i32);
	return r4;
}

flixel__graphics__frames__FlxFrame flixel_system_frontEnds_BitmapFrontEnd_get_whitePixel(flixel__system__frontEnds__BitmapFrontEnd r0) {
	String r14;
	bool *r7;
	flixel__graphics__frames__FlxImageFrame r16;
	bool r6, r13, r15;
	flixel__$FlxG r12;
	flixel__system__frontEnds__BitmapFrontEnd r11;
	flixel__graphics__FlxGraphic r10;
	flixel__graphics__frames__FlxFrame r2;
	int *r9;
	int r4, r5, r8;
	openfl__display__BitmapData r3;
	r2 = r0->_whitePixel;
	if( r2 ) goto label$87ef034_23_24;
	r3 = (openfl__display__BitmapData)hl_alloc_obj(&t$openfl_display_BitmapData);
	r4 = 10;
	r5 = 10;
	r6 = true;
	r7 = &r6;
	r8 = -1;
	r9 = &r8;
	openfl_display_BitmapData_new(r3,r4,r5,r7,r9);
	r12 = (flixel__$FlxG)g$_flixel_FlxG;
	r11 = r12->bitmap;
	if( r11 == NULL ) hl_null_access();
	r13 = true;
	r7 = &r13;
	r14 = (String)s$whitePixels;
	r10 = flixel_system_frontEnds_BitmapFrontEnd_add(r11,((vdynamic*)r3),r7,r14);
	if( r10 == NULL ) hl_null_access();
	r15 = true;
	r10->persist = r15;
	r16 = flixel_graphics_FlxGraphic_get_imageFrame(r10);
	if( r16 == NULL ) hl_null_access();
	r2 = flixel_graphics_frames_FlxImageFrame_get_frame(r16);
	r0->_whitePixel = r2;
	label$87ef034_23_24:
	r2 = r0->_whitePixel;
	return r2;
}

void flixel_system_frontEnds_BitmapFrontEnd_new(flixel__system__frontEnds__BitmapFrontEnd r0) {
	int r1;
	r1 = 0;
	r0->_lastUniqueKeyIndex = r1;
	flixel_system_frontEnds_BitmapFrontEnd_reset(r0);
	return;
}

