// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/ui/Gamepad.h>
extern hl_type t$String;
#include <hl/natives.h>
extern lime__ui__$Gamepad g$_lime_ui_Gamepad;
bool haxe_ds_IntMap_exists(haxe__ds__IntMap,int);
extern hl_type t$lime_ui_Gamepad;
void lime_ui_Gamepad_new(lime__ui__Gamepad,int);
void haxe_ds_IntMap_set(haxe__ds__IntMap,int,vdynamic*);
void lime_app__Event_lime_ui_Gamepad_Void_dispatch(lime__app___Event_lime_ui_Gamepad_Void,lime__ui__Gamepad);
vdynamic* haxe_ds_IntMap_get(haxe__ds__IntMap,int);
bool haxe_ds_IntMap_remove(haxe__ds__IntMap,int);
void lime_app__Event_Void_Void_dispatch(lime__app___Event_Void_Void);
String String_fromUTF8(vbyte*);
extern hl_type t$lime_app__Event_Void_Void;
void lime_app__Event_Void_Void_new(lime__app___Event_Void_Void);
extern hl_type t$lime_app__Event_lime_ui_GamepadButton_Void;
void lime_app__Event_lime_ui_GamepadButton_Void_new(lime__app___Event_lime_ui_GamepadButton_Void);
extern hl_type t$lime_app__Event_lime_ui_GamepadAxis_Float_Void;
void lime_app__Event_lime_ui_GamepadAxis_Float_Void_new(lime__app___Event_lime_ui_GamepadAxis_Float_Void);

void lime_ui_Gamepad_addMappings(hl__types__ArrayObj r0) {
	String r9;
	hl_type *r5;
	vdynamic *r10;
	varray *r4, *r11;
	int r1, r3, r6, r7, r8;
	if( r0 == NULL ) hl_null_access();
	r1 = r0->length;
	r5 = &t$String;
	r4 = hl_alloc_array(r5,r1);
	r3 = 0;
	r6 = r0->length;
	label$91f1127_1_6:
	if( r3 >= r6 ) goto label$91f1127_1_20;
	r7 = r3;
	++r3;
	if( r0 == NULL ) hl_null_access();
	r8 = r0->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$91f1127_1_15;
	r9 = NULL;
	goto label$91f1127_1_18;
	label$91f1127_1_15:
	r11 = r0->array;
	r10 = ((vdynamic**)(r11 + 1))[r7];
	r9 = (String)r10;
	label$91f1127_1_18:
	((String*)(r4 + 1))[r7] = r9;
	goto label$91f1127_1_6;
	label$91f1127_1_20:
	lime_hl_gamepad_add_mappings(r4);
	return;
}

void lime_ui_Gamepad___connect(int r0) {
	bool r2;
	lime__ui__Gamepad r5;
	haxe__ds__IntMap r3;
	lime__ui__$Gamepad r4;
	lime__app___Event_lime_ui_Gamepad_Void r6;
	r4 = (lime__ui__$Gamepad)g$_lime_ui_Gamepad;
	r3 = r4->devices;
	if( r3 == NULL ) hl_null_access();
	r2 = haxe_ds_IntMap_exists(r3,r0);
	if( r2 ) goto label$91f1127_2_15;
	r5 = (lime__ui__Gamepad)hl_alloc_obj(&t$lime_ui_Gamepad);
	lime_ui_Gamepad_new(r5,r0);
	r4 = (lime__ui__$Gamepad)g$_lime_ui_Gamepad;
	r3 = r4->devices;
	if( r3 == NULL ) hl_null_access();
	haxe_ds_IntMap_set(r3,r0,((vdynamic*)r5));
	r4 = (lime__ui__$Gamepad)g$_lime_ui_Gamepad;
	r6 = r4->onConnect;
	if( r6 == NULL ) hl_null_access();
	lime_app__Event_lime_ui_Gamepad_Void_dispatch(r6,r5);
	label$91f1127_2_15:
	return;
}

void lime_ui_Gamepad___disconnect(int r0) {
	lime__app___Event_Void_Void r7;
	bool r6;
	lime__ui__Gamepad r4;
	haxe__ds__IntMap r2;
	lime__ui__$Gamepad r3;
	vdynamic *r1;
	r3 = (lime__ui__$Gamepad)g$_lime_ui_Gamepad;
	r2 = r3->devices;
	if( r2 == NULL ) hl_null_access();
	r1 = haxe_ds_IntMap_get(r2,r0);
	r4 = (lime__ui__Gamepad)r1;
	if( !r4 ) goto label$91f1127_3_9;
	if( r4 == NULL ) hl_null_access();
	r6 = false;
	r4->connected = r6;
	label$91f1127_3_9:
	r3 = (lime__ui__$Gamepad)g$_lime_ui_Gamepad;
	r2 = r3->devices;
	if( r2 == NULL ) hl_null_access();
	r6 = haxe_ds_IntMap_remove(r2,r0);
	if( !r4 ) goto label$91f1127_3_18;
	if( r4 == NULL ) hl_null_access();
	r7 = r4->onDisconnect;
	if( r7 == NULL ) hl_null_access();
	lime_app__Event_Void_Void_dispatch(r7);
	label$91f1127_3_18:
	return;
}

String lime_ui_Gamepad_get_guid(lime__ui__Gamepad r0) {
	String r1;
	int r3;
	vbyte *r2;
	r3 = r0->id;
	r2 = lime_hl_gamepad_get_device_guid(r3);
	r1 = String_fromUTF8(r2);
	return r1;
}

String lime_ui_Gamepad_get_name(lime__ui__Gamepad r0) {
	String r1;
	int r3;
	vbyte *r2;
	r3 = r0->id;
	r2 = lime_hl_gamepad_get_device_name(r3);
	r1 = String_fromUTF8(r2);
	return r1;
}

void lime_ui_Gamepad_new(lime__ui__Gamepad r0,int r1) {
	bool r6;
	lime__app___Event_Void_Void r2;
	lime__app___Event_lime_ui_GamepadButton_Void r4;
	lime__app___Event_lime_ui_GamepadAxis_Float_Void r5;
	r2 = (lime__app___Event_Void_Void)hl_alloc_obj(&t$lime_app__Event_Void_Void);
	lime_app__Event_Void_Void_new(r2);
	r0->onDisconnect = r2;
	r4 = (lime__app___Event_lime_ui_GamepadButton_Void)hl_alloc_obj(&t$lime_app__Event_lime_ui_GamepadButton_Void);
	lime_app__Event_lime_ui_GamepadButton_Void_new(r4);
	r0->onButtonUp = r4;
	r4 = (lime__app___Event_lime_ui_GamepadButton_Void)hl_alloc_obj(&t$lime_app__Event_lime_ui_GamepadButton_Void);
	lime_app__Event_lime_ui_GamepadButton_Void_new(r4);
	r0->onButtonDown = r4;
	r5 = (lime__app___Event_lime_ui_GamepadAxis_Float_Void)hl_alloc_obj(&t$lime_app__Event_lime_ui_GamepadAxis_Float_Void);
	lime_app__Event_lime_ui_GamepadAxis_Float_Void_new(r5);
	r0->onAxisMove = r5;
	r0->id = r1;
	r6 = true;
	r0->connected = r6;
	return;
}

