// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/ui/Joystick.h>
extern lime__ui__$Joystick g$_lime_ui_Joystick;
bool haxe_ds_IntMap_exists(haxe__ds__IntMap,int);
extern hl_type t$lime_ui_Joystick;
void lime_ui_Joystick_new(lime__ui__Joystick,int);
void haxe_ds_IntMap_set(haxe__ds__IntMap,int,vdynamic*);
void lime_app__Event_lime_ui_Joystick_Void_dispatch(lime__app___Event_lime_ui_Joystick_Void,lime__ui__Joystick);
vdynamic* haxe_ds_IntMap_get(haxe__ds__IntMap,int);
bool haxe_ds_IntMap_remove(haxe__ds__IntMap,int);
void lime_app__Event_Void_Void_dispatch(lime__app___Event_Void_Void);
#include <hl/natives.h>
String String_fromUTF8(vbyte*);
extern hl_type t$lime_app__Event_Int_Float_Float_Void;
void lime_app__Event_Int_Float_Float_Void_new(lime__app___Event_Int_Float_Float_Void);
extern hl_type t$lime_app__Event_Int_lime_ui_JoystickHatPosition_Void;
void lime_app__Event_Int_lime_ui_JoystickHatPosition_Void_new(lime__app___Event_Int_lime_ui_JoystickHatPosition_Void);
extern hl_type t$lime_app__Event_Void_Void;
void lime_app__Event_Void_Void_new(lime__app___Event_Void_Void);
extern hl_type t$lime_app__Event_Int_Void;
void lime_app__Event_Int_Void_new(lime__app___Event_Int_Void);
extern hl_type t$lime_app__Event_Int_Float_Void;
void lime_app__Event_Int_Float_Void_new(lime__app___Event_Int_Float_Void);

void lime_ui_Joystick___connect(int r0) {
	bool r2;
	lime__ui__Joystick r5;
	haxe__ds__IntMap r3;
	lime__ui__$Joystick r4;
	lime__app___Event_lime_ui_Joystick_Void r6;
	r4 = (lime__ui__$Joystick)g$_lime_ui_Joystick;
	r3 = r4->devices;
	if( r3 == NULL ) hl_null_access();
	r2 = haxe_ds_IntMap_exists(r3,r0);
	if( r2 ) goto label$e7ac539_1_15;
	r5 = (lime__ui__Joystick)hl_alloc_obj(&t$lime_ui_Joystick);
	lime_ui_Joystick_new(r5,r0);
	r4 = (lime__ui__$Joystick)g$_lime_ui_Joystick;
	r3 = r4->devices;
	if( r3 == NULL ) hl_null_access();
	haxe_ds_IntMap_set(r3,r0,((vdynamic*)r5));
	r4 = (lime__ui__$Joystick)g$_lime_ui_Joystick;
	r6 = r4->onConnect;
	if( r6 == NULL ) hl_null_access();
	lime_app__Event_lime_ui_Joystick_Void_dispatch(r6,r5);
	label$e7ac539_1_15:
	return;
}

void lime_ui_Joystick___disconnect(int r0) {
	lime__app___Event_Void_Void r7;
	bool r6;
	lime__ui__Joystick r4;
	haxe__ds__IntMap r2;
	lime__ui__$Joystick r3;
	vdynamic *r1;
	r3 = (lime__ui__$Joystick)g$_lime_ui_Joystick;
	r2 = r3->devices;
	if( r2 == NULL ) hl_null_access();
	r1 = haxe_ds_IntMap_get(r2,r0);
	r4 = (lime__ui__Joystick)r1;
	if( !r4 ) goto label$e7ac539_2_9;
	if( r4 == NULL ) hl_null_access();
	r6 = false;
	r4->connected = r6;
	label$e7ac539_2_9:
	r3 = (lime__ui__$Joystick)g$_lime_ui_Joystick;
	r2 = r3->devices;
	if( r2 == NULL ) hl_null_access();
	r6 = haxe_ds_IntMap_remove(r2,r0);
	if( !r4 ) goto label$e7ac539_2_18;
	if( r4 == NULL ) hl_null_access();
	r7 = r4->onDisconnect;
	if( r7 == NULL ) hl_null_access();
	lime_app__Event_Void_Void_dispatch(r7);
	label$e7ac539_2_18:
	return;
}

String lime_ui_Joystick_get_guid(lime__ui__Joystick r0) {
	String r1;
	int r3;
	vbyte *r2;
	r3 = r0->id;
	r2 = lime_hl_joystick_get_device_guid(r3);
	r1 = String_fromUTF8(r2);
	return r1;
}

String lime_ui_Joystick_get_name(lime__ui__Joystick r0) {
	String r1;
	int r3;
	vbyte *r2;
	r3 = r0->id;
	r2 = lime_hl_joystick_get_device_name(r3);
	r1 = String_fromUTF8(r2);
	return r1;
}

int lime_ui_Joystick_get_numAxes(lime__ui__Joystick r0) {
	int r1;
	r1 = r0->id;
	r1 = lime_hl_joystick_get_num_axes(r1);
	return r1;
}

int lime_ui_Joystick_get_numButtons(lime__ui__Joystick r0) {
	int r1;
	r1 = r0->id;
	r1 = lime_hl_joystick_get_num_buttons(r1);
	return r1;
}

int lime_ui_Joystick_get_numHats(lime__ui__Joystick r0) {
	int r1;
	r1 = r0->id;
	r1 = lime_hl_joystick_get_num_hats(r1);
	return r1;
}

int lime_ui_Joystick_get_numTrackballs(lime__ui__Joystick r0) {
	int r1;
	r1 = r0->id;
	r1 = lime_hl_joystick_get_num_trackballs(r1);
	return r1;
}

void lime_ui_Joystick_new(lime__ui__Joystick r0,int r1) {
	bool r8;
	lime__app___Event_Void_Void r5;
	lime__app___Event_Int_Float_Float_Void r2;
	lime__app___Event_Int_Void r6;
	lime__app___Event_Int_Float_Void r7;
	lime__app___Event_Int_lime_ui_JoystickHatPosition_Void r4;
	r2 = (lime__app___Event_Int_Float_Float_Void)hl_alloc_obj(&t$lime_app__Event_Int_Float_Float_Void);
	lime_app__Event_Int_Float_Float_Void_new(r2);
	r0->onTrackballMove = r2;
	r4 = (lime__app___Event_Int_lime_ui_JoystickHatPosition_Void)hl_alloc_obj(&t$lime_app__Event_Int_lime_ui_JoystickHatPosition_Void);
	lime_app__Event_Int_lime_ui_JoystickHatPosition_Void_new(r4);
	r0->onHatMove = r4;
	r5 = (lime__app___Event_Void_Void)hl_alloc_obj(&t$lime_app__Event_Void_Void);
	lime_app__Event_Void_Void_new(r5);
	r0->onDisconnect = r5;
	r6 = (lime__app___Event_Int_Void)hl_alloc_obj(&t$lime_app__Event_Int_Void);
	lime_app__Event_Int_Void_new(r6);
	r0->onButtonUp = r6;
	r6 = (lime__app___Event_Int_Void)hl_alloc_obj(&t$lime_app__Event_Int_Void);
	lime_app__Event_Int_Void_new(r6);
	r0->onButtonDown = r6;
	r7 = (lime__app___Event_Int_Float_Void)hl_alloc_obj(&t$lime_app__Event_Int_Float_Void);
	lime_app__Event_Int_Float_Void_new(r7);
	r0->onAxisMove = r7;
	r0->id = r1;
	r8 = true;
	r0->connected = r8;
	return;
}

