// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__graphics__opengl___GLVertexArrayObject__GLVertexArrayObject_Impl_
#define INC_lime__graphics__opengl___GLVertexArrayObject__GLVertexArrayObject_Impl_
typedef struct _lime__graphics__opengl___GLVertexArrayObject__$GLVertexArrayObject_Impl_ *lime__graphics__opengl___GLVertexArrayObject__$GLVertexArrayObject_Impl_;
typedef struct _lime__graphics__opengl___GLVertexArrayObject__GLVertexArrayObject_Impl_ *lime__graphics__opengl___GLVertexArrayObject__GLVertexArrayObject_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <lime/graphics/opengl/GLObject.h>


struct _lime__graphics__opengl___GLVertexArrayObject__$GLVertexArrayObject_Impl_ {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* fromInt;
};
struct _lime__graphics__opengl___GLVertexArrayObject__GLVertexArrayObject_Impl_ {
	hl_type *$type;
};
#endif

