// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/ui/GameInputDevice.h>
#include <openfl/utils/ByteArrayData.h>
#include <openfl/ui/GameInputControl.h>
#include <openfl/_Vector/ObjectVector.h>
extern hl_type t$hl_types_ArrayObj;
void hl_types_ArrayObj_new(hl__types__ArrayObj);
extern hl_type t$haxe_ds_IntMap;
void haxe_ds_IntMap_new(haxe__ds__IntMap);
extern hl_type t$openfl_ui_GameInputControl;
extern String s$AXIS_;
#include <hl/natives.h>
String String___alloc__(vbyte*,int);
String String___add__(String,String);
void openfl_ui_GameInputControl_new(openfl__ui__GameInputControl,openfl__ui__GameInputDevice,String,double,double,double*);
void haxe_ds_IntMap_set(haxe__ds__IntMap,int,vdynamic*);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
extern String s$BUTTON_;

int openfl_ui_GameInputDevice_getCachedSamples(openfl__ui__GameInputDevice r0,openfl__utils__ByteArrayData r1,bool* r2) {
	bool r3;
	int r4;
	if( r2 ) goto label$fba6457_1_3;
	r3 = false;
	goto label$fba6457_1_4;
	label$fba6457_1_3:
	r3 = *r2;
	label$fba6457_1_4:
	r4 = 0;
	return r4;
}

openfl__ui__GameInputControl openfl_ui_GameInputDevice_getControlAt(openfl__ui__GameInputDevice r0,int r1) {
	hl__types__ArrayObj r3;
	openfl__ui__GameInputControl r4;
	vdynamic *r5;
	varray *r6;
	int r2;
	r2 = 0;
	if( r1 < r2 ) goto label$fba6457_2_16;
	r3 = r0->__controls;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	if( r1 >= r2 ) goto label$fba6457_2_16;
	r3 = r0->__controls;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	if( ((unsigned)r1) < ((unsigned)r2) ) goto label$fba6457_2_12;
	r4 = NULL;
	goto label$fba6457_2_15;
	label$fba6457_2_12:
	r6 = r3->array;
	r5 = ((vdynamic**)(r6 + 1))[r1];
	r4 = (openfl__ui__GameInputControl)r5;
	label$fba6457_2_15:
	return r4;
	label$fba6457_2_16:
	r4 = NULL;
	return r4;
}

void openfl_ui_GameInputDevice_startCachingSamples(openfl__ui__GameInputDevice r0,int r1,openfl___Vector__ObjectVector r2) {
	return;
}

void openfl_ui_GameInputDevice_stopCachingSamples(openfl__ui__GameInputDevice r0) {
	return;
}

int openfl_ui_GameInputDevice_get_numControls(openfl__ui__GameInputDevice r0) {
	hl__types__ArrayObj r2;
	int r1;
	r2 = r0->__controls;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->length;
	return r1;
}

void openfl_ui_GameInputDevice_new(openfl__ui__GameInputDevice r0,String r1,String r2) {
	String r6, r11;
	hl__types__ArrayObj r3;
	haxe__ds__IntMap r5;
	openfl__ui__GameInputControl r7;
	double r12, r13;
	double *r14;
	int *r9;
	vbyte *r10;
	int r8, r15, r16;
	r3 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r3);
	r0->__controls = r3;
	r5 = (haxe__ds__IntMap)hl_alloc_obj(&t$haxe_ds_IntMap);
	haxe_ds_IntMap_new(r5);
	r0->__button = r5;
	r5 = (haxe__ds__IntMap)hl_alloc_obj(&t$haxe_ds_IntMap);
	haxe_ds_IntMap_new(r5);
	r0->__axis = r5;
	r0->id = r1;
	r0->name = r2;
	r7 = (openfl__ui__GameInputControl)hl_alloc_obj(&t$openfl_ui_GameInputControl);
	r6 = (String)s$AXIS_;
	r8 = 0;
	r9 = &r8;
	r10 = hl_itos(r8,r9);
	r11 = String___alloc__(r10,r8);
	r6 = String___add__(r6,r11);
	r12 = -1.;
	r13 = 1.;
	r14 = NULL;
	openfl_ui_GameInputControl_new(r7,r0,r6,r12,r13,r14);
	r5 = r0->__axis;
	if( r5 == NULL ) hl_null_access();
	r8 = 0;
	haxe_ds_IntMap_set(r5,r8,((vdynamic*)r7));
	r3 = r0->__controls;
	if( r3 == NULL ) hl_null_access();
	r8 = hl_types_ArrayObj_push(r3,((vdynamic*)r7));
	r7 = (openfl__ui__GameInputControl)hl_alloc_obj(&t$openfl_ui_GameInputControl);
	r6 = (String)s$AXIS_;
	r8 = 1;
	r9 = &r8;
	r10 = hl_itos(r8,r9);
	r11 = String___alloc__(r10,r8);
	r6 = String___add__(r6,r11);
	r12 = -1.;
	r13 = 1.;
	r14 = NULL;
	openfl_ui_GameInputControl_new(r7,r0,r6,r12,r13,r14);
	r5 = r0->__axis;
	if( r5 == NULL ) hl_null_access();
	r8 = 1;
	haxe_ds_IntMap_set(r5,r8,((vdynamic*)r7));
	r3 = r0->__controls;
	if( r3 == NULL ) hl_null_access();
	r8 = hl_types_ArrayObj_push(r3,((vdynamic*)r7));
	r7 = (openfl__ui__GameInputControl)hl_alloc_obj(&t$openfl_ui_GameInputControl);
	r6 = (String)s$AXIS_;
	r8 = 2;
	r9 = &r8;
	r10 = hl_itos(r8,r9);
	r11 = String___alloc__(r10,r8);
	r6 = String___add__(r6,r11);
	r12 = -1.;
	r13 = 1.;
	r14 = NULL;
	openfl_ui_GameInputControl_new(r7,r0,r6,r12,r13,r14);
	r5 = r0->__axis;
	if( r5 == NULL ) hl_null_access();
	r8 = 2;
	haxe_ds_IntMap_set(r5,r8,((vdynamic*)r7));
	r3 = r0->__controls;
	if( r3 == NULL ) hl_null_access();
	r8 = hl_types_ArrayObj_push(r3,((vdynamic*)r7));
	r7 = (openfl__ui__GameInputControl)hl_alloc_obj(&t$openfl_ui_GameInputControl);
	r6 = (String)s$AXIS_;
	r8 = 3;
	r9 = &r8;
	r10 = hl_itos(r8,r9);
	r11 = String___alloc__(r10,r8);
	r6 = String___add__(r6,r11);
	r12 = -1.;
	r13 = 1.;
	r14 = NULL;
	openfl_ui_GameInputControl_new(r7,r0,r6,r12,r13,r14);
	r5 = r0->__axis;
	if( r5 == NULL ) hl_null_access();
	r8 = 3;
	haxe_ds_IntMap_set(r5,r8,((vdynamic*)r7));
	r3 = r0->__controls;
	if( r3 == NULL ) hl_null_access();
	r8 = hl_types_ArrayObj_push(r3,((vdynamic*)r7));
	r7 = (openfl__ui__GameInputControl)hl_alloc_obj(&t$openfl_ui_GameInputControl);
	r6 = (String)s$AXIS_;
	r8 = 4;
	r9 = &r8;
	r10 = hl_itos(r8,r9);
	r11 = String___alloc__(r10,r8);
	r6 = String___add__(r6,r11);
	r12 = -1.;
	r13 = 1.;
	r14 = NULL;
	openfl_ui_GameInputControl_new(r7,r0,r6,r12,r13,r14);
	r5 = r0->__axis;
	if( r5 == NULL ) hl_null_access();
	r8 = 4;
	haxe_ds_IntMap_set(r5,r8,((vdynamic*)r7));
	r3 = r0->__controls;
	if( r3 == NULL ) hl_null_access();
	r8 = hl_types_ArrayObj_push(r3,((vdynamic*)r7));
	r7 = (openfl__ui__GameInputControl)hl_alloc_obj(&t$openfl_ui_GameInputControl);
	r6 = (String)s$AXIS_;
	r8 = 5;
	r9 = &r8;
	r10 = hl_itos(r8,r9);
	r11 = String___alloc__(r10,r8);
	r6 = String___add__(r6,r11);
	r12 = -1.;
	r13 = 1.;
	r14 = NULL;
	openfl_ui_GameInputControl_new(r7,r0,r6,r12,r13,r14);
	r5 = r0->__axis;
	if( r5 == NULL ) hl_null_access();
	r8 = 5;
	haxe_ds_IntMap_set(r5,r8,((vdynamic*)r7));
	r3 = r0->__controls;
	if( r3 == NULL ) hl_null_access();
	r8 = hl_types_ArrayObj_push(r3,((vdynamic*)r7));
	r8 = 0;
	label$fba6457_6_120:
	r16 = 15;
	if( r8 >= r16 ) goto label$fba6457_6_143;
	r15 = r8;
	++r8;
	r7 = (openfl__ui__GameInputControl)hl_alloc_obj(&t$openfl_ui_GameInputControl);
	r6 = (String)s$BUTTON_;
	r16 = r15;
	r9 = &r16;
	r10 = hl_itos(r16,r9);
	r11 = String___alloc__(r10,r16);
	r6 = String___add__(r6,r11);
	r12 = 0.;
	r13 = 1.;
	r14 = NULL;
	openfl_ui_GameInputControl_new(r7,r0,r6,r12,r13,r14);
	r5 = r0->__button;
	if( r5 == NULL ) hl_null_access();
	haxe_ds_IntMap_set(r5,r15,((vdynamic*)r7));
	r3 = r0->__controls;
	if( r3 == NULL ) hl_null_access();
	r16 = hl_types_ArrayObj_push(r3,((vdynamic*)r7));
	goto label$fba6457_6_120;
	label$fba6457_6_143:
	return;
}

