// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/display3D/_Context3DStencilAction/Context3DStencilAction_Impl_.h>
#include <hl/natives.h>
extern hl_type t$_i32;
extern String s$decrementSaturate;
extern String s$decrementWrap;
extern String s$incrementSaturate;
extern String s$incrementWrap;
extern String s$invert;
extern String s$keep;
extern String s$set;
extern String s$zero;

vdynamic* openfl_display3D__Context3DStencilAction_Context3DStencilAction_Impl__fromString(String r0) {
	vdynamic *r5;
	vbyte *r3, *r4;
	int r1, r2;
	if( !r0 ) goto label$97aa805_1_9;
	r1 = r0->length;
	r2 = 17;
	if( r1 != r2 ) goto label$97aa805_1_9;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("decrementSaturate");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$97aa805_1_74;
	label$97aa805_1_9:
	if( !r0 ) goto label$97aa805_1_18;
	r1 = r0->length;
	r2 = 13;
	if( r1 != r2 ) goto label$97aa805_1_18;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("decrementWrap");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$97aa805_1_77;
	label$97aa805_1_18:
	if( !r0 ) goto label$97aa805_1_27;
	r1 = r0->length;
	r2 = 17;
	if( r1 != r2 ) goto label$97aa805_1_27;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("incrementSaturate");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$97aa805_1_80;
	label$97aa805_1_27:
	if( !r0 ) goto label$97aa805_1_36;
	r1 = r0->length;
	r2 = 13;
	if( r1 != r2 ) goto label$97aa805_1_36;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("incrementWrap");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$97aa805_1_83;
	label$97aa805_1_36:
	if( !r0 ) goto label$97aa805_1_45;
	r1 = r0->length;
	r2 = 6;
	if( r1 != r2 ) goto label$97aa805_1_45;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("invert");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$97aa805_1_86;
	label$97aa805_1_45:
	if( !r0 ) goto label$97aa805_1_54;
	r1 = r0->length;
	r2 = 4;
	if( r1 != r2 ) goto label$97aa805_1_54;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("keep");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$97aa805_1_89;
	label$97aa805_1_54:
	if( !r0 ) goto label$97aa805_1_63;
	r1 = r0->length;
	r2 = 3;
	if( r1 != r2 ) goto label$97aa805_1_63;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("set");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$97aa805_1_92;
	label$97aa805_1_63:
	if( !r0 ) goto label$97aa805_1_72;
	r1 = r0->length;
	r2 = 4;
	if( r1 != r2 ) goto label$97aa805_1_72;
	r3 = r0->bytes;
	r4 = (vbyte*)USTR("zero");
	r1 = hl_string_compare(r3,r4,r1);
	r2 = 0;
	if( r1 == r2 ) goto label$97aa805_1_95;
	label$97aa805_1_72:
	r5 = NULL;
	return r5;
	label$97aa805_1_74:
	r1 = 0;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r1;
	return r5;
	label$97aa805_1_77:
	r1 = 1;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r1;
	return r5;
	label$97aa805_1_80:
	r1 = 2;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r1;
	return r5;
	label$97aa805_1_83:
	r1 = 3;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r1;
	return r5;
	label$97aa805_1_86:
	r1 = 4;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r1;
	return r5;
	label$97aa805_1_89:
	r1 = 5;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r1;
	return r5;
	label$97aa805_1_92:
	r1 = 6;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r1;
	return r5;
	label$97aa805_1_95:
	r1 = 7;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r1;
	return r5;
}

String openfl_display3D__Context3DStencilAction_Context3DStencilAction_Impl__toString(vdynamic* r0) {
	String r2;
	int r1;
	r1 = r0 ? r0->v.i : 0;
	switch(r1) {
		default:
			r2 = NULL;
			return r2;
		case 0:
			r2 = (String)s$decrementSaturate;
			return r2;
		case 1:
			r2 = (String)s$decrementWrap;
			return r2;
		case 2:
			r2 = (String)s$incrementSaturate;
			return r2;
		case 3:
			r2 = (String)s$incrementWrap;
			return r2;
		case 4:
			r2 = (String)s$invert;
			return r2;
		case 5:
			r2 = (String)s$keep;
			return r2;
		case 6:
			r2 = (String)s$set;
			return r2;
		case 7:
			r2 = (String)s$zero;
			return r2;
	}
}

