// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__app___Event_Int_Int_Void
#define INC_lime__app___Event_Int_Int_Void
typedef struct _lime__app__$_Event_Int_Int_Void *lime__app__$_Event_Int_Int_Void;
typedef struct _lime__app___Event_Int_Int_Void *lime__app___Event_Int_Int_Void;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>
#include <hl/types/ArrayBytes_Int.h>


struct _lime__app__$_Event_Int_Int_Void {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__app___Event_Int_Int_Void {
	hl_type *$type;
	bool canceled;
	hl__types__ArrayObj __repeat;
	hl__types__ArrayBytes_Int __priorities;
	hl__types__ArrayObj __listeners;
};
#endif

