// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/graphics/cairo/Cairo.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>
#include <lime/graphics/cairo/CairoGlyph.h>
extern hl_type t$lime_graphics_cairo_CairoGlyph;
#include <lime/math/Matrix3.h>
#include <lime/math/Vector2.h>
extern hl_type t$lime_math_Vector2;
void lime_math_Vector2_new(lime__math__Vector2,double*,double*);
#include <hl/types/ArrayBytes_Float.h>
hl__types__ArrayBytes_Float hl_types_ArrayBase_allocF64(vbyte*,int);
void hl_types_ArrayBytes_Float___expand(hl__types__ArrayBytes_Float,int);
extern hl_type t$_f64;
extern hl_type t$lime_math_Matrix3;
void lime_math_Matrix3_new(lime__math__Matrix3,double*,double*,double*,double*,double*,double*);
String String_fromUTF8(vbyte*);

void lime_graphics_cairo_Cairo_new(lime__graphics__cairo__Cairo r0,vdynamic* r1) {
	vdynamic *r3;
	if( !r1 ) goto label$d92d261_1_3;
	r3 = lime_hl_cairo_create(r1);
	r0->handle = r3;
	label$d92d261_1_3:
	return;
}

void lime_graphics_cairo_Cairo_arc(lime__graphics__cairo__Cairo r0,double r1,double r2,double r3,double r4,double r5) {
	vdynamic *r7;
	r7 = r0->handle;
	lime_hl_cairo_arc(r7,r1,r2,r3,r4,r5);
	return;
}

void lime_graphics_cairo_Cairo_arcNegative(lime__graphics__cairo__Cairo r0,double r1,double r2,double r3,double r4,double r5) {
	vdynamic *r7;
	r7 = r0->handle;
	lime_hl_cairo_arc_negative(r7,r1,r2,r3,r4,r5);
	return;
}

void lime_graphics_cairo_Cairo_clip(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_clip(r2);
	return;
}

void lime_graphics_cairo_Cairo_clipExtents(lime__graphics__cairo__Cairo r0,double r1,double r2,double r3,double r4) {
	vdynamic *r6;
	r6 = r0->handle;
	lime_hl_cairo_clip_extents(r6,r1,r2,r3,r4);
	return;
}

void lime_graphics_cairo_Cairo_clipPreserve(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_clip_preserve(r2);
	return;
}

void lime_graphics_cairo_Cairo_closePath(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_close_path(r2);
	return;
}

void lime_graphics_cairo_Cairo_copyPage(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_copy_page(r2);
	return;
}

void lime_graphics_cairo_Cairo_curveTo(lime__graphics__cairo__Cairo r0,double r1,double r2,double r3,double r4,double r5,double r6) {
	vdynamic *r8;
	r8 = r0->handle;
	lime_hl_cairo_curve_to(r8,r1,r2,r3,r4,r5,r6);
	return;
}

void lime_graphics_cairo_Cairo_fill(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_fill(r2);
	return;
}

void lime_graphics_cairo_Cairo_fillExtents(lime__graphics__cairo__Cairo r0,double r1,double r2,double r3,double r4) {
	vdynamic *r6;
	r6 = r0->handle;
	lime_hl_cairo_fill_extents(r6,r1,r2,r3,r4);
	return;
}

void lime_graphics_cairo_Cairo_fillPreserve(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_fill_preserve(r2);
	return;
}

int lime_graphics_cairo_Cairo_getOperator(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	int r1;
	r2 = r0->handle;
	r1 = lime_hl_cairo_get_operator(r2);
	return r1;
}

void lime_graphics_cairo_Cairo_identityMatrix(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_identity_matrix(r2);
	return;
}

bool lime_graphics_cairo_Cairo_inClip(lime__graphics__cairo__Cairo r0,double r1,double r2) {
	bool r3;
	vdynamic *r4;
	r4 = r0->handle;
	r3 = lime_hl_cairo_in_clip(r4,r1,r2);
	return r3;
}

bool lime_graphics_cairo_Cairo_inFill(lime__graphics__cairo__Cairo r0,double r1,double r2) {
	bool r3;
	vdynamic *r4;
	r4 = r0->handle;
	r3 = lime_hl_cairo_in_fill(r4,r1,r2);
	return r3;
}

bool lime_graphics_cairo_Cairo_inStroke(lime__graphics__cairo__Cairo r0,double r1,double r2) {
	bool r3;
	vdynamic *r4;
	r4 = r0->handle;
	r3 = lime_hl_cairo_in_stroke(r4,r1,r2);
	return r3;
}

void lime_graphics_cairo_Cairo_lineTo(lime__graphics__cairo__Cairo r0,double r1,double r2) {
	vdynamic *r4;
	r4 = r0->handle;
	lime_hl_cairo_line_to(r4,r1,r2);
	return;
}

void lime_graphics_cairo_Cairo_mask(lime__graphics__cairo__Cairo r0,vdynamic* r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_mask(r3,r1);
	return;
}

void lime_graphics_cairo_Cairo_maskSurface(lime__graphics__cairo__Cairo r0,vdynamic* r1,double r2,double r3) {
	vdynamic *r5;
	r5 = r0->handle;
	lime_hl_cairo_mask_surface(r5,r1,r2,r3);
	return;
}

void lime_graphics_cairo_Cairo_moveTo(lime__graphics__cairo__Cairo r0,double r1,double r2) {
	vdynamic *r4;
	r4 = r0->handle;
	lime_hl_cairo_move_to(r4,r1,r2);
	return;
}

void lime_graphics_cairo_Cairo_newPath(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_new_path(r2);
	return;
}

void lime_graphics_cairo_Cairo_paint(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_paint(r2);
	return;
}

void lime_graphics_cairo_Cairo_paintWithAlpha(lime__graphics__cairo__Cairo r0,double r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_paint_with_alpha(r3,r1);
	return;
}

vdynamic* lime_graphics_cairo_Cairo_popGroup(lime__graphics__cairo__Cairo r0) {
	vdynamic *r1;
	r1 = r0->handle;
	r1 = lime_hl_cairo_pop_group(r1);
	return r1;
}

void lime_graphics_cairo_Cairo_popGroupToSource(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_pop_group_to_source(r2);
	return;
}

void lime_graphics_cairo_Cairo_pushGroup(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_push_group(r2);
	return;
}

void lime_graphics_cairo_Cairo_pushGroupWithContent(lime__graphics__cairo__Cairo r0,int r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_push_group_with_content(r3,r1);
	return;
}

void lime_graphics_cairo_Cairo_recreate(lime__graphics__cairo__Cairo r0,vdynamic* r1) {
	vdynamic *r2;
	r2 = lime_hl_cairo_create(r1);
	r0->handle = r2;
	return;
}

void lime_graphics_cairo_Cairo_rectangle(lime__graphics__cairo__Cairo r0,double r1,double r2,double r3,double r4) {
	vdynamic *r6;
	r6 = r0->handle;
	lime_hl_cairo_rectangle(r6,r1,r2,r3,r4);
	return;
}

void lime_graphics_cairo_Cairo_relCurveTo(lime__graphics__cairo__Cairo r0,double r1,double r2,double r3,double r4,double r5,double r6) {
	vdynamic *r8;
	r8 = r0->handle;
	lime_hl_cairo_rel_curve_to(r8,r1,r2,r3,r4,r5,r6);
	return;
}

void lime_graphics_cairo_Cairo_relLineTo(lime__graphics__cairo__Cairo r0,double r1,double r2) {
	vdynamic *r4;
	r4 = r0->handle;
	lime_hl_cairo_rel_line_to(r4,r1,r2);
	return;
}

void lime_graphics_cairo_Cairo_relMoveTo(lime__graphics__cairo__Cairo r0,double r1,double r2) {
	vdynamic *r4;
	r4 = r0->handle;
	lime_hl_cairo_rel_move_to(r4,r1,r2);
	return;
}

void lime_graphics_cairo_Cairo_resetClip(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_reset_clip(r2);
	return;
}

void lime_graphics_cairo_Cairo_restore(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_restore(r2);
	return;
}

void lime_graphics_cairo_Cairo_rotate(lime__graphics__cairo__Cairo r0,double r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_rotate(r3,r1);
	return;
}

void lime_graphics_cairo_Cairo_save(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_save(r2);
	return;
}

void lime_graphics_cairo_Cairo_scale(lime__graphics__cairo__Cairo r0,double r1,double r2) {
	vdynamic *r4;
	r4 = r0->handle;
	lime_hl_cairo_scale(r4,r1,r2);
	return;
}

void lime_graphics_cairo_Cairo_setFontSize(lime__graphics__cairo__Cairo r0,double r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_font_size(r3,r1);
	return;
}

int lime_graphics_cairo_Cairo_setOperator(lime__graphics__cairo__Cairo r0,int r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_operator(r3,r1);
	return r1;
}

void lime_graphics_cairo_Cairo_setSourceRGB(lime__graphics__cairo__Cairo r0,double r1,double r2,double r3) {
	vdynamic *r5;
	r5 = r0->handle;
	lime_hl_cairo_set_source_rgb(r5,r1,r2,r3);
	return;
}

void lime_graphics_cairo_Cairo_setSourceRGBA(lime__graphics__cairo__Cairo r0,double r1,double r2,double r3,double r4) {
	vdynamic *r6;
	r6 = r0->handle;
	lime_hl_cairo_set_source_rgba(r6,r1,r2,r3,r4);
	return;
}

void lime_graphics_cairo_Cairo_setSourceSurface(lime__graphics__cairo__Cairo r0,vdynamic* r1,double r2,double r3) {
	vdynamic *r5;
	r5 = r0->handle;
	lime_hl_cairo_set_source_surface(r5,r1,r2,r3);
	return;
}

void lime_graphics_cairo_Cairo_showGlyphs(lime__graphics__cairo__Cairo r0,hl__types__ArrayObj r1) {
	hl_type *r6;
	lime__graphics__cairo__CairoGlyph r10;
	vdynamic *r11;
	varray *r5, *r12;
	int r2, r4, r7, r8, r9;
	if( r1 == NULL ) hl_null_access();
	r2 = r1->length;
	r6 = &t$lime_graphics_cairo_CairoGlyph;
	r5 = hl_alloc_array(r6,r2);
	r4 = 0;
	r7 = r1->length;
	label$d92d261_44_6:
	if( r4 >= r7 ) goto label$d92d261_44_20;
	r8 = r4;
	++r4;
	if( r1 == NULL ) hl_null_access();
	r9 = r1->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$d92d261_44_15;
	r10 = NULL;
	goto label$d92d261_44_18;
	label$d92d261_44_15:
	r12 = r1->array;
	r11 = ((vdynamic**)(r12 + 1))[r8];
	r10 = (lime__graphics__cairo__CairoGlyph)r11;
	label$d92d261_44_18:
	((lime__graphics__cairo__CairoGlyph*)(r5 + 1))[r8] = r10;
	goto label$d92d261_44_6;
	label$d92d261_44_20:
	r11 = r0->handle;
	lime_hl_cairo_show_glyphs(r11,r5);
	return;
}

void lime_graphics_cairo_Cairo_showPage(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_show_page(r2);
	return;
}

void lime_graphics_cairo_Cairo_showText(lime__graphics__cairo__Cairo r0,String r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_show_text(r3,r1);
	return;
}

int lime_graphics_cairo_Cairo_status(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	int r1;
	r2 = r0->handle;
	r1 = lime_hl_cairo_status(r2);
	return r1;
}

void lime_graphics_cairo_Cairo_stroke(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_stroke(r2);
	return;
}

void lime_graphics_cairo_Cairo_strokeExtents(lime__graphics__cairo__Cairo r0,double r1,double r2,double r3,double r4) {
	vdynamic *r6;
	r6 = r0->handle;
	lime_hl_cairo_stroke_extents(r6,r1,r2,r3,r4);
	return;
}

void lime_graphics_cairo_Cairo_strokePreserve(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_cairo_stroke_preserve(r2);
	return;
}

void lime_graphics_cairo_Cairo_textPath(lime__graphics__cairo__Cairo r0,String r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_text_path(r3,r1);
	return;
}

void lime_graphics_cairo_Cairo_transform(lime__graphics__cairo__Cairo r0,lime__math__Matrix3 r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_transform(r3,r1);
	return;
}

void lime_graphics_cairo_Cairo_translate(lime__graphics__cairo__Cairo r0,double r1,double r2) {
	vdynamic *r4;
	r4 = r0->handle;
	lime_hl_cairo_translate(r4,r1,r2);
	return;
}

int lime_graphics_cairo_Cairo_get_antialias(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	int r1;
	r2 = r0->handle;
	r1 = lime_hl_cairo_get_antialias(r2);
	return r1;
}

int lime_graphics_cairo_Cairo_set_antialias(lime__graphics__cairo__Cairo r0,int r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_antialias(r3,r1);
	return r1;
}

lime__math__Vector2 lime_graphics_cairo_Cairo_get_currentPoint(lime__graphics__cairo__Cairo r0) {
	lime__math__Vector2 r1;
	double *r3, *r4;
	vdynamic *r2;
	r2 = r0->handle;
	r1 = (lime__math__Vector2)hl_alloc_obj(&t$lime_math_Vector2);
	r3 = NULL;
	r4 = NULL;
	lime_math_Vector2_new(r1,r3,r4);
	r1 = lime_hl_cairo_get_current_point(r2,r1);
	return r1;
}

hl__types__ArrayBytes_Float lime_graphics_cairo_Cairo_get_dash(lime__graphics__cairo__Cairo r0) {
	hl__types__ArrayBytes_Float r4;
	double r10;
	vdynamic *r2;
	int r6, r7, r8, r9;
	vbyte *r5;
	varray *r1;
	r2 = r0->handle;
	r1 = lime_hl_cairo_get_dash(r2);
	if( r1 ) goto label$d92d261_57_9;
	r6 = 0;
	r5 = hl_alloc_bytes(r6);
	r6 = 0;
	r6 = 0;
	r4 = hl_types_ArrayBase_allocF64(r5,r6);
	return r4;
	label$d92d261_57_9:
	r6 = 0;
	r5 = hl_alloc_bytes(r6);
	r6 = 0;
	r6 = 0;
	r4 = hl_types_ArrayBase_allocF64(r5,r6);
	r6 = 0;
	r7 = r1->size;
	label$d92d261_57_16:
	if( r6 >= r7 ) goto label$d92d261_57_30;
	r8 = r6;
	++r6;
	if( r4 == NULL ) hl_null_access();
	r10 = ((double*)(r1 + 1))[r8];
	r9 = r4->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$d92d261_57_25;
	hl_types_ArrayBytes_Float___expand(r4,r8);
	label$d92d261_57_25:
	r5 = r4->bytes;
	r9 = 3;
	r9 = r8 << r9;
	*(double*)(r5 + r9) = r10;
	goto label$d92d261_57_16;
	label$d92d261_57_30:
	return r4;
}

hl__types__ArrayBytes_Float lime_graphics_cairo_Cairo_set_dash(lime__graphics__cairo__Cairo r0,hl__types__ArrayBytes_Float r1) {
	hl_type *r6;
	double r10;
	vdynamic *r12;
	vbyte *r11;
	varray *r5;
	int r2, r4, r7, r8, r9;
	if( r1 == NULL ) hl_null_access();
	r2 = r1->length;
	r6 = &t$_f64;
	r5 = hl_alloc_array(r6,r2);
	r4 = 0;
	r7 = r1->length;
	label$d92d261_58_6:
	if( r4 >= r7 ) goto label$d92d261_58_21;
	r8 = r4;
	++r4;
	if( r1 == NULL ) hl_null_access();
	r9 = r1->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$d92d261_58_15;
	r10 = 0.;
	goto label$d92d261_58_19;
	label$d92d261_58_15:
	r11 = r1->bytes;
	r9 = 3;
	r9 = r8 << r9;
	r10 = *(double*)(r11 + r9);
	label$d92d261_58_19:
	((double*)(r5 + 1))[r8] = r10;
	goto label$d92d261_58_6;
	label$d92d261_58_21:
	r12 = r0->handle;
	lime_hl_cairo_set_dash(r12,r5);
	return r1;
}

int lime_graphics_cairo_Cairo_get_dashCount(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	int r1;
	r2 = r0->handle;
	r1 = lime_hl_cairo_get_dash_count(r2);
	return r1;
}

int lime_graphics_cairo_Cairo_get_fillRule(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	int r1;
	r2 = r0->handle;
	r1 = lime_hl_cairo_get_fill_rule(r2);
	return r1;
}

int lime_graphics_cairo_Cairo_set_fillRule(lime__graphics__cairo__Cairo r0,int r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_fill_rule(r3,r1);
	return r1;
}

vdynamic* lime_graphics_cairo_Cairo_get_fontFace(lime__graphics__cairo__Cairo r0) {
	vdynamic *r1;
	r1 = r0->handle;
	r1 = lime_hl_cairo_get_font_face(r1);
	return r1;
}

vdynamic* lime_graphics_cairo_Cairo_set_fontFace(lime__graphics__cairo__Cairo r0,vdynamic* r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_font_face(r3,r1);
	return r1;
}

vdynamic* lime_graphics_cairo_Cairo_get_fontOptions(lime__graphics__cairo__Cairo r0) {
	vdynamic *r1;
	r1 = r0->handle;
	r1 = lime_hl_cairo_get_font_options(r1);
	return r1;
}

vdynamic* lime_graphics_cairo_Cairo_set_fontOptions(lime__graphics__cairo__Cairo r0,vdynamic* r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_font_options(r3,r1);
	return r1;
}

vdynamic* lime_graphics_cairo_Cairo_get_groupTarget(lime__graphics__cairo__Cairo r0) {
	vdynamic *r1;
	r1 = r0->handle;
	r1 = lime_hl_cairo_get_group_target(r1);
	return r1;
}

bool lime_graphics_cairo_Cairo_get_hasCurrentPoint(lime__graphics__cairo__Cairo r0) {
	bool r1;
	vdynamic *r2;
	r2 = r0->handle;
	r1 = lime_hl_cairo_has_current_point(r2);
	return r1;
}

int lime_graphics_cairo_Cairo_get_lineCap(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	int r1;
	r2 = r0->handle;
	r1 = lime_hl_cairo_get_line_cap(r2);
	return r1;
}

int lime_graphics_cairo_Cairo_set_lineCap(lime__graphics__cairo__Cairo r0,int r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_line_cap(r3,r1);
	return r1;
}

int lime_graphics_cairo_Cairo_get_lineJoin(lime__graphics__cairo__Cairo r0) {
	vdynamic *r2;
	int r1;
	r2 = r0->handle;
	r1 = lime_hl_cairo_get_line_join(r2);
	return r1;
}

int lime_graphics_cairo_Cairo_set_lineJoin(lime__graphics__cairo__Cairo r0,int r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_line_join(r3,r1);
	return r1;
}

double lime_graphics_cairo_Cairo_get_lineWidth(lime__graphics__cairo__Cairo r0) {
	double r1;
	vdynamic *r2;
	r2 = r0->handle;
	r1 = lime_hl_cairo_get_line_width(r2);
	return r1;
}

double lime_graphics_cairo_Cairo_set_lineWidth(lime__graphics__cairo__Cairo r0,double r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_line_width(r3,r1);
	return r1;
}

lime__math__Matrix3 lime_graphics_cairo_Cairo_get_matrix(lime__graphics__cairo__Cairo r0) {
	lime__math__Matrix3 r1;
	double *r3, *r4, *r5, *r6, *r7, *r8;
	vdynamic *r2;
	r2 = r0->handle;
	r1 = (lime__math__Matrix3)hl_alloc_obj(&t$lime_math_Matrix3);
	r3 = NULL;
	r4 = NULL;
	r5 = NULL;
	r6 = NULL;
	r7 = NULL;
	r8 = NULL;
	lime_math_Matrix3_new(r1,r3,r4,r5,r6,r7,r8);
	r1 = lime_hl_cairo_get_matrix(r2,r1);
	return r1;
}

lime__math__Matrix3 lime_graphics_cairo_Cairo_set_matrix(lime__graphics__cairo__Cairo r0,lime__math__Matrix3 r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_matrix(r3,r1);
	return r1;
}

double lime_graphics_cairo_Cairo_get_miterLimit(lime__graphics__cairo__Cairo r0) {
	double r1;
	vdynamic *r2;
	r2 = r0->handle;
	r1 = lime_hl_cairo_get_miter_limit(r2);
	return r1;
}

double lime_graphics_cairo_Cairo_set_miterLimit(lime__graphics__cairo__Cairo r0,double r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_miter_limit(r3,r1);
	return r1;
}

vdynamic* lime_graphics_cairo_Cairo_get_source(lime__graphics__cairo__Cairo r0) {
	vdynamic *r1;
	r1 = r0->handle;
	r1 = lime_hl_cairo_get_source(r1);
	return r1;
}

vdynamic* lime_graphics_cairo_Cairo_set_source(lime__graphics__cairo__Cairo r0,vdynamic* r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_source(r3,r1);
	return r1;
}

vdynamic* lime_graphics_cairo_Cairo_get_target(lime__graphics__cairo__Cairo r0) {
	vdynamic *r1;
	r1 = r0->handle;
	r1 = lime_hl_cairo_get_target(r1);
	return r1;
}

double lime_graphics_cairo_Cairo_get_tolerance(lime__graphics__cairo__Cairo r0) {
	double r1;
	vdynamic *r2;
	r2 = r0->handle;
	r1 = lime_hl_cairo_get_tolerance(r2);
	return r1;
}

double lime_graphics_cairo_Cairo_set_tolerance(lime__graphics__cairo__Cairo r0,double r1) {
	vdynamic *r3;
	r3 = r0->handle;
	lime_hl_cairo_set_tolerance(r3,r1);
	return r1;
}

int lime_graphics_cairo_Cairo_get_version() {
	int r0;
	r0 = lime_hl_cairo_version();
	return r0;
}

String lime_graphics_cairo_Cairo_get_versionString() {
	String r0;
	vbyte *r1;
	r1 = lime_hl_cairo_version_string();
	r0 = String_fromUTF8(r1);
	return r0;
}

