// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__graphics__cairo__Cairo
#define INC_lime__graphics__cairo__Cairo
typedef struct _lime__graphics__cairo__$Cairo *lime__graphics__cairo__$Cairo;
typedef struct _lime__graphics__cairo__Cairo *lime__graphics__cairo__Cairo;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__graphics__cairo__$Cairo {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	int version;
	String versionString;
	vclosure* get_version;
	vclosure* get_versionString;
};
struct _lime__graphics__cairo__Cairo {
	hl_type *$type;
	vdynamic* target;
	vdynamic* userData;
	vdynamic* handle;
};
#endif

