// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/events/EventDispatcher.h>
#include <hl/types/ArrayObj.h>
#include <openfl/events/_EventDispatcher/Listener.h>
#include <openfl/events/_EventDispatcher/DispatchIterator.h>
extern hl_type t$haxe_ds_StringMap;
void haxe_ds_StringMap_new(haxe__ds__StringMap);
bool haxe_ds_StringMap_exists(haxe__ds__StringMap,String);
extern hl_type t$hl_types_ArrayObj;
void hl_types_ArrayObj_new(hl__types__ArrayObj);
extern hl_type t$openfl_events__EventDispatcher_Listener;
void openfl_events__EventDispatcher_Listener_new(openfl__events___EventDispatcher__Listener,vclosure*,bool,int);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
extern hl_type t$openfl_events__EventDispatcher_DispatchIterator;
void openfl_events__EventDispatcher_DispatchIterator_new(openfl__events___EventDispatcher__DispatchIterator,hl__types__ArrayObj);
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
extern hl_type t$_dyn;
bool openfl_events__EventDispatcher_Listener_match(openfl__events___EventDispatcher__Listener,vclosure*,bool);
void openfl_events__EventDispatcher_DispatchIterator_copy(openfl__events___EventDispatcher__DispatchIterator);
void openfl_events_EventDispatcher___addListenerByPriority(openfl__events__EventDispatcher,hl__types__ArrayObj,openfl__events___EventDispatcher__Listener);
#include <hl/types/ArrayBase.h>
void openfl_events__EventDispatcher_DispatchIterator_remove(openfl__events___EventDispatcher__DispatchIterator,openfl__events___EventDispatcher__Listener,int);
hl__types__ArrayBase hl_types_ArrayObj_splice(hl__types__ArrayObj,int,int);
extern hl_type t$hl_types_ArrayBase;
bool haxe_ds_StringMap_remove(haxe__ds__StringMap,String);
vvirtual* haxe_ds_StringMap_iterator(haxe__ds__StringMap);
extern hl_type t$vrt_60f27ce;
extern hl_type t$fun_bf7849e;
String openfl_events_EventDispatcher_toString(openfl__events__EventDispatcher);
hl__Class Type_getClass(vdynamic*);
String Type_getClassName(hl__Class);
extern String s$5058f1a;
hl__types__ArrayObj String_split(String,String);
vdynamic* hl_types_ArrayObj_pop(hl__types__ArrayObj);
extern String s$_object_;
String String___add__(String,String);
extern String s$0fbd177;
void openfl_events__EventDispatcher_DispatchIterator_start(openfl__events___EventDispatcher__DispatchIterator);
bool openfl_events__EventDispatcher_DispatchIterator_hasNext(openfl__events___EventDispatcher__DispatchIterator);
openfl__events___EventDispatcher__Listener openfl_events__EventDispatcher_DispatchIterator_next(openfl__events___EventDispatcher__DispatchIterator);
void openfl_events__EventDispatcher_DispatchIterator_stop(openfl__events___EventDispatcher__DispatchIterator);
bool hl_types_ArrayObj_remove(hl__types__ArrayObj,vdynamic*);
void openfl_events__EventDispatcher_DispatchIterator_reset(openfl__events___EventDispatcher__DispatchIterator,hl__types__ArrayObj);
bool openfl_events_Event_isDefaultPrevented(openfl__events__Event);
void hl_types_ArrayObj_insert(hl__types__ArrayObj,int,vdynamic*);

void openfl_events_EventDispatcher_new(openfl__events__EventDispatcher r0,vvirtual* r1) {
	if( !r1 ) goto label$c094a92_1_2;
	r0->__targetDispatcher = r1;
	label$c094a92_1_2:
	return;
}

void openfl_events_EventDispatcher_addEventListener(openfl__events__EventDispatcher r0,String r1,vclosure* r2,bool* r3,int* r4,bool* r5) {
	openfl__events___EventDispatcher__DispatchIterator r17;
	hl__types__ArrayObj r13, r15;
	haxe__ds__StringMap r11;
	hl_type *r19;
	bool r6, r8, r12;
	openfl__events___EventDispatcher__Listener r16;
	vdynamic *r10;
	varray *r18;
	int r7, r14, r20, r21, r22;
	if( r3 ) goto label$c094a92_2_3;
	r6 = false;
	goto label$c094a92_2_4;
	label$c094a92_2_3:
	r6 = *r3;
	label$c094a92_2_4:
	if( r4 ) goto label$c094a92_2_7;
	r7 = 0;
	goto label$c094a92_2_8;
	label$c094a92_2_7:
	r7 = *r4;
	label$c094a92_2_8:
	if( r5 ) goto label$c094a92_2_11;
	r8 = false;
	goto label$c094a92_2_12;
	label$c094a92_2_11:
	r8 = *r5;
	label$c094a92_2_12:
	if( r2 ) goto label$c094a92_2_14;
	return;
	label$c094a92_2_14:
	r11 = r0->__eventMap;
	if( r11 ) goto label$c094a92_2_22;
	r11 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r11);
	r0->__eventMap = r11;
	r11 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r11);
	r0->__iterators = r11;
	label$c094a92_2_22:
	r11 = r0->__eventMap;
	if( r11 == NULL ) hl_null_access();
	r12 = haxe_ds_StringMap_exists(r11,r1);
	if( r12 ) goto label$c094a92_2_46;
	r13 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r13);
	r16 = (openfl__events___EventDispatcher__Listener)hl_alloc_obj(&t$openfl_events__EventDispatcher_Listener);
	openfl_events__EventDispatcher_Listener_new(r16,r2,r6,r7);
	r14 = hl_types_ArrayObj_push(r13,((vdynamic*)r16));
	r17 = (openfl__events___EventDispatcher__DispatchIterator)hl_alloc_obj(&t$openfl_events__EventDispatcher_DispatchIterator);
	openfl_events__EventDispatcher_DispatchIterator_new(r17,r13);
	r11 = r0->__eventMap;
	if( r11 == NULL ) hl_null_access();
	haxe_ds_StringMap_set(r11,r1,((vdynamic*)r13));
	r11 = r0->__iterators;
	if( r11 == NULL ) hl_null_access();
	r19 = &t$openfl_events__EventDispatcher_DispatchIterator;
	r14 = 1;
	r18 = hl_alloc_array(r19,r14);
	r14 = 0;
	((openfl__events___EventDispatcher__DispatchIterator*)(r18 + 1))[r14] = r17;
	r15 = hl_types_ArrayObj_alloc(r18);
	haxe_ds_StringMap_set(r11,r1,((vdynamic*)r15));
	goto label$c094a92_2_95;
	label$c094a92_2_46:
	r11 = r0->__eventMap;
	if( r11 == NULL ) hl_null_access();
	r10 = haxe_ds_StringMap_get(r11,r1);
	r13 = (hl__types__ArrayObj)hl_dyn_castp(&r10,&t$_dyn,&t$hl_types_ArrayObj);
	r14 = 0;
	if( r13 == NULL ) hl_null_access();
	r20 = r13->length;
	label$c094a92_2_53:
	if( r14 >= r20 ) goto label$c094a92_2_70;
	r21 = r14;
	++r14;
	if( r13 == NULL ) hl_null_access();
	r22 = r13->length;
	if( ((unsigned)r21) < ((unsigned)r22) ) goto label$c094a92_2_62;
	r16 = NULL;
	goto label$c094a92_2_65;
	label$c094a92_2_62:
	r18 = r13->array;
	r10 = ((vdynamic**)(r18 + 1))[r21];
	r16 = (openfl__events___EventDispatcher__Listener)r10;
	label$c094a92_2_65:
	if( r16 == NULL ) hl_null_access();
	r12 = openfl_events__EventDispatcher_Listener_match(r16,r2,r6);
	if( !r12 ) goto label$c094a92_2_69;
	return;
	label$c094a92_2_69:
	goto label$c094a92_2_53;
	label$c094a92_2_70:
	r11 = r0->__iterators;
	if( r11 == NULL ) hl_null_access();
	r10 = haxe_ds_StringMap_get(r11,r1);
	r15 = (hl__types__ArrayObj)hl_dyn_castp(&r10,&t$_dyn,&t$hl_types_ArrayObj);
	r14 = 0;
	label$c094a92_2_75:
	if( r15 == NULL ) hl_null_access();
	r21 = r15->length;
	if( r14 >= r21 ) goto label$c094a92_2_92;
	r21 = r15->length;
	if( ((unsigned)r14) < ((unsigned)r21) ) goto label$c094a92_2_83;
	r17 = NULL;
	goto label$c094a92_2_86;
	label$c094a92_2_83:
	r18 = r15->array;
	r10 = ((vdynamic**)(r18 + 1))[r14];
	r17 = (openfl__events___EventDispatcher__DispatchIterator)r10;
	label$c094a92_2_86:
	++r14;
	if( r17 == NULL ) hl_null_access();
	r12 = r17->active;
	if( !r12 ) goto label$c094a92_2_91;
	openfl_events__EventDispatcher_DispatchIterator_copy(r17);
	label$c094a92_2_91:
	goto label$c094a92_2_75;
	label$c094a92_2_92:
	r16 = (openfl__events___EventDispatcher__Listener)hl_alloc_obj(&t$openfl_events__EventDispatcher_Listener);
	openfl_events__EventDispatcher_Listener_new(r16,r2,r6,r7);
	openfl_events_EventDispatcher___addListenerByPriority(r0,r13,r16);
	label$c094a92_2_95:
	return;
}

bool openfl_events_EventDispatcher_dispatchEvent(openfl__events__EventDispatcher r0,openfl__events__Event r1) {
	vvirtual *r2;
	bool r3;
	r2 = r0->__targetDispatcher;
	if( !r2 ) goto label$c094a92_3_6;
	if( r1 == NULL ) hl_null_access();
	r2 = r0->__targetDispatcher;
	r1->target = ((vdynamic*)r2);
	goto label$c094a92_3_8;
	label$c094a92_3_6:
	if( r1 == NULL ) hl_null_access();
	r1->target = ((vdynamic*)r0);
	label$c094a92_3_8:
	r3 = ((bool (*)(openfl__events__EventDispatcher,openfl__events__Event))r0->$type->vobj_proto[3])(r0,r1);
	return r3;
}

bool openfl_events_EventDispatcher_hasEventListener(openfl__events__EventDispatcher r0,String r1) {
	haxe__ds__StringMap r2;
	bool r3;
	r2 = r0->__eventMap;
	if( r2 ) goto label$c094a92_4_4;
	r3 = false;
	return r3;
	label$c094a92_4_4:
	r2 = r0->__eventMap;
	if( r2 == NULL ) hl_null_access();
	r3 = haxe_ds_StringMap_exists(r2,r1);
	return r3;
}

void openfl_events_EventDispatcher_removeEventListener(openfl__events__EventDispatcher r0,String r1,vclosure* r2,bool* r3) {
	openfl__events___EventDispatcher__DispatchIterator r20;
	vvirtual *r22, *r23;
	hl__types__ArrayObj r8, r9, r12;
	haxe__ds__StringMap r6;
	bool r4, r15;
	hl__types__ArrayBase r21;
	openfl__events___EventDispatcher__Listener r17;
	vdynamic *r7;
	varray *r18;
	int r10, r11, r13, r14, r16, r19;
	if( r3 ) goto label$c094a92_5_3;
	r4 = false;
	goto label$c094a92_5_4;
	label$c094a92_5_3:
	r4 = *r3;
	label$c094a92_5_4:
	r6 = r0->__eventMap;
	if( !r6 ) goto label$c094a92_5_7;
	if( r2 ) goto label$c094a92_5_8;
	label$c094a92_5_7:
	return;
	label$c094a92_5_8:
	r6 = r0->__eventMap;
	if( r6 == NULL ) hl_null_access();
	r7 = haxe_ds_StringMap_get(r6,r1);
	r8 = (hl__types__ArrayObj)hl_dyn_castp(&r7,&t$_dyn,&t$hl_types_ArrayObj);
	if( r8 ) goto label$c094a92_5_14;
	return;
	label$c094a92_5_14:
	r6 = r0->__iterators;
	if( r6 == NULL ) hl_null_access();
	r7 = haxe_ds_StringMap_get(r6,r1);
	r9 = (hl__types__ArrayObj)hl_dyn_castp(&r7,&t$_dyn,&t$hl_types_ArrayObj);
	r10 = 0;
	if( r8 == NULL ) hl_null_access();
	r11 = r8->length;
	label$c094a92_5_21:
	if( r10 >= r11 ) goto label$c094a92_5_66;
	r13 = r10;
	++r10;
	if( r8 == NULL ) hl_null_access();
	r16 = r8->length;
	if( ((unsigned)r13) < ((unsigned)r16) ) goto label$c094a92_5_30;
	r17 = NULL;
	goto label$c094a92_5_33;
	label$c094a92_5_30:
	r18 = r8->array;
	r7 = ((vdynamic**)(r18 + 1))[r13];
	r17 = (openfl__events___EventDispatcher__Listener)r7;
	label$c094a92_5_33:
	if( r17 == NULL ) hl_null_access();
	r15 = openfl_events__EventDispatcher_Listener_match(r17,r2,r4);
	if( !r15 ) goto label$c094a92_5_65;
	r14 = 0;
	label$c094a92_5_37:
	if( r9 == NULL ) hl_null_access();
	r19 = r9->length;
	if( r14 >= r19 ) goto label$c094a92_5_60;
	r19 = r9->length;
	if( ((unsigned)r14) < ((unsigned)r19) ) goto label$c094a92_5_45;
	r20 = NULL;
	goto label$c094a92_5_48;
	label$c094a92_5_45:
	r18 = r9->array;
	r7 = ((vdynamic**)(r18 + 1))[r14];
	r20 = (openfl__events___EventDispatcher__DispatchIterator)r7;
	label$c094a92_5_48:
	++r14;
	if( r20 == NULL ) hl_null_access();
	if( r8 == NULL ) hl_null_access();
	r19 = r8->length;
	if( ((unsigned)r13) < ((unsigned)r19) ) goto label$c094a92_5_55;
	r17 = NULL;
	goto label$c094a92_5_58;
	label$c094a92_5_55:
	r18 = r8->array;
	r7 = ((vdynamic**)(r18 + 1))[r13];
	r17 = (openfl__events___EventDispatcher__Listener)r7;
	label$c094a92_5_58:
	openfl_events__EventDispatcher_DispatchIterator_remove(r20,r17,r13);
	goto label$c094a92_5_37;
	label$c094a92_5_60:
	if( r8 == NULL ) hl_null_access();
	r16 = 1;
	r21 = hl_types_ArrayObj_splice(r8,r13,r16);
	r12 = (hl__types__ArrayObj)hl_dyn_castp(&r21,&t$hl_types_ArrayBase,&t$hl_types_ArrayObj);
	goto label$c094a92_5_66;
	label$c094a92_5_65:
	goto label$c094a92_5_21;
	label$c094a92_5_66:
	if( r8 == NULL ) hl_null_access();
	r10 = r8->length;
	r11 = 0;
	if( r10 != r11 ) goto label$c094a92_5_76;
	r6 = r0->__eventMap;
	if( r6 == NULL ) hl_null_access();
	r15 = haxe_ds_StringMap_remove(r6,r1);
	r6 = r0->__iterators;
	if( r6 == NULL ) hl_null_access();
	r15 = haxe_ds_StringMap_remove(r6,r1);
	label$c094a92_5_76:
	r6 = r0->__eventMap;
	if( r6 == NULL ) hl_null_access();
	r22 = haxe_ds_StringMap_iterator(r6);
	r23 = hl_to_virtual(&t$vrt_60f27ce,(vdynamic*)r22);
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[0] ) r15 = ((bool (*)(vdynamic*))hl_vfields(r23)[0])(r23->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r23->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r15 = (bool)ret.v.i;
	}
	if( r15 ) goto label$c094a92_5_87;
	r6 = NULL;
	r0->__eventMap = r6;
	r6 = NULL;
	r0->__iterators = r6;
	label$c094a92_5_87:
	return;
}

vbyte* openfl_events_EventDispatcher___string(openfl__events__EventDispatcher r0) {
	String r2;
	vbyte *r1;
	r2 = openfl_events_EventDispatcher_toString(r0);
	if( r2 == NULL ) hl_null_access();
	r1 = r2->bytes;
	return r1;
}

String openfl_events_EventDispatcher_toString(openfl__events__EventDispatcher r0) {
	String r1, r5, r6, r7;
	hl__Class r2;
	hl__types__ArrayObj r4;
	vdynamic *r3;
	r2 = Type_getClass(((vdynamic*)r0));
	r1 = Type_getClassName(r2);
	if( r1 == NULL ) hl_null_access();
	r6 = (String)s$5058f1a;
	r4 = String_split(r1,r6);
	if( r4 == NULL ) hl_null_access();
	r3 = hl_types_ArrayObj_pop(r4);
	r5 = (String)r3;
	r6 = (String)s$_object_;
	r6 = String___add__(r6,r5);
	r7 = (String)s$0fbd177;
	r6 = String___add__(r6,r7);
	return r6;
}

bool openfl_events_EventDispatcher_willTrigger(openfl__events__EventDispatcher r0,String r1) {
	bool r2;
	r2 = openfl_events_EventDispatcher_hasEventListener(r0,r1);
	return r2;
}

bool openfl_events_EventDispatcher___dispatchEvent(openfl__events__EventDispatcher r0,openfl__events__Event r1) {
	String r6;
	openfl__events___EventDispatcher__DispatchIterator r12, r15, r16;
	vvirtual *r9;
	hl__types__ArrayObj r7, r8;
	haxe__ds__StringMap r3;
	bool r4, r14;
	vclosure *r18;
	openfl__events___EventDispatcher__Listener r17;
	vdynamic *r5;
	varray *r13;
	int r10, r11;
	r3 = r0->__eventMap;
	if( !r3 ) goto label$c094a92_9_3;
	if( r1 ) goto label$c094a92_9_5;
	label$c094a92_9_3:
	r4 = true;
	return r4;
	label$c094a92_9_5:
	if( r1 == NULL ) hl_null_access();
	r6 = r1->type;
	r3 = r0->__eventMap;
	if( r3 == NULL ) hl_null_access();
	r5 = haxe_ds_StringMap_get(r3,r6);
	r7 = (hl__types__ArrayObj)hl_dyn_castp(&r5,&t$_dyn,&t$hl_types_ArrayObj);
	if( r7 ) goto label$c094a92_9_14;
	r4 = true;
	return r4;
	label$c094a92_9_14:
	r5 = r1->target;
	if( r5 ) goto label$c094a92_9_22;
	r9 = r0->__targetDispatcher;
	if( !r9 ) goto label$c094a92_9_21;
	r9 = r0->__targetDispatcher;
	r1->target = ((vdynamic*)r9);
	goto label$c094a92_9_22;
	label$c094a92_9_21:
	r1->target = ((vdynamic*)r0);
	label$c094a92_9_22:
	r1->currentTarget = ((vdynamic*)r0);
	r10 = r1->eventPhase;
	r11 = 1;
	if( r10 == r11 ) goto label$c094a92_9_28;
	r4 = false;
	goto label$c094a92_9_29;
	label$c094a92_9_28:
	r4 = true;
	label$c094a92_9_29:
	r3 = r0->__iterators;
	if( r3 == NULL ) hl_null_access();
	r5 = haxe_ds_StringMap_get(r3,r6);
	r8 = (hl__types__ArrayObj)hl_dyn_castp(&r5,&t$_dyn,&t$hl_types_ArrayObj);
	if( r8 == NULL ) hl_null_access();
	r10 = 0;
	r11 = r8->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$c094a92_9_39;
	r12 = NULL;
	goto label$c094a92_9_42;
	label$c094a92_9_39:
	r13 = r8->array;
	r5 = ((vdynamic**)(r13 + 1))[r10];
	r12 = (openfl__events___EventDispatcher__DispatchIterator)r5;
	label$c094a92_9_42:
	if( r12 == NULL ) hl_null_access();
	r14 = r12->active;
	if( !r14 ) goto label$c094a92_9_49;
	r15 = (openfl__events___EventDispatcher__DispatchIterator)hl_alloc_obj(&t$openfl_events__EventDispatcher_DispatchIterator);
	openfl_events__EventDispatcher_DispatchIterator_new(r15,r7);
	r12 = r15;
	r10 = hl_types_ArrayObj_push(r8,((vdynamic*)r15));
	label$c094a92_9_49:
	openfl_events__EventDispatcher_DispatchIterator_start(r12);
	r15 = r12;
	label$c094a92_9_51:
	if( r15 == NULL ) hl_null_access();
	r14 = openfl_events__EventDispatcher_DispatchIterator_hasNext(r15);
	if( !r14 ) goto label$c094a92_9_69;
	r17 = openfl_events__EventDispatcher_DispatchIterator_next(r15);
	if( r17 ) goto label$c094a92_9_58;
	goto label$c094a92_9_51;
	label$c094a92_9_58:
	if( r17 == NULL ) hl_null_access();
	r14 = r17->useCapture;
	if( r14 != r4 ) goto label$c094a92_9_68;
	r18 = r17->callback;
	if( r18 == NULL ) hl_null_access();
	r18->hasValue ? ((void (*)(vdynamic*,vdynamic*))r18->fun)((vdynamic*)r18->value,((vdynamic*)r1)) : ((void (*)(vdynamic*))r18->fun)(((vdynamic*)r1));
	if( r1 == NULL ) hl_null_access();
	r14 = r1->__isCanceledNow;
	if( !r14 ) goto label$c094a92_9_68;
	goto label$c094a92_9_69;
	label$c094a92_9_68:
	goto label$c094a92_9_51;
	label$c094a92_9_69:
	if( r12 == NULL ) hl_null_access();
	openfl_events__EventDispatcher_DispatchIterator_stop(r12);
	if( r8 == NULL ) hl_null_access();
	r10 = 0;
	r11 = r8->length;
	if( ((unsigned)r10) < ((unsigned)r11) ) goto label$c094a92_9_77;
	r16 = NULL;
	goto label$c094a92_9_80;
	label$c094a92_9_77:
	r13 = r8->array;
	r5 = ((vdynamic**)(r13 + 1))[r10];
	r16 = (openfl__events___EventDispatcher__DispatchIterator)r5;
	label$c094a92_9_80:
	if( r12 == r16 ) goto label$c094a92_9_83;
	r14 = hl_types_ArrayObj_remove(r8,((vdynamic*)r12));
	goto label$c094a92_9_84;
	label$c094a92_9_83:
	openfl_events__EventDispatcher_DispatchIterator_reset(r12,r7);
	label$c094a92_9_84:
	if( r1 == NULL ) hl_null_access();
	r14 = openfl_events_Event_isDefaultPrevented(r1);
	r14 = !r14;
	return r14;
}

void openfl_events_EventDispatcher___removeAllListeners(openfl__events__EventDispatcher r0) {
	haxe__ds__StringMap r1;
	r1 = NULL;
	r0->__eventMap = r1;
	r1 = NULL;
	r0->__iterators = r1;
	return;
}

void openfl_events_EventDispatcher___addListenerByPriority(openfl__events__EventDispatcher r0,hl__types__ArrayObj r1,openfl__events___EventDispatcher__Listener r2) {
	openfl__events___EventDispatcher__Listener r11;
	vdynamic *r12;
	varray *r13;
	int r3, r5, r6, r7, r8, r9, r10;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->length;
	r5 = r3;
	r6 = 0;
	r7 = r3;
	label$c094a92_11_5:
	if( r6 >= r7 ) goto label$c094a92_11_25;
	r8 = r6;
	++r6;
	if( r1 == NULL ) hl_null_access();
	r10 = r1->length;
	if( ((unsigned)r8) < ((unsigned)r10) ) goto label$c094a92_11_14;
	r11 = NULL;
	goto label$c094a92_11_17;
	label$c094a92_11_14:
	r13 = r1->array;
	r12 = ((vdynamic**)(r13 + 1))[r8];
	r11 = (openfl__events___EventDispatcher__Listener)r12;
	label$c094a92_11_17:
	if( r11 == NULL ) hl_null_access();
	r9 = r11->priority;
	if( r2 == NULL ) hl_null_access();
	r10 = r2->priority;
	if( r9 >= r10 ) goto label$c094a92_11_24;
	r5 = r8;
	goto label$c094a92_11_25;
	label$c094a92_11_24:
	goto label$c094a92_11_5;
	label$c094a92_11_25:
	if( r1 == NULL ) hl_null_access();
	hl_types_ArrayObj_insert(r1,r5,((vdynamic*)r2));
	return;
}

