// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/events/FocusEvent.h>
void openfl_events_Event_new(openfl__events__Event,String,bool*,bool*);
extern hl_type t$openfl_events_FocusEvent;
#include <hl/types/ArrayObj.h>
extern String s$FocusEvent;
extern hl_type t$String;
#include <hl/natives.h>
extern String s$type;
extern String s$bubbles;
extern String s$cancelable;
extern String s$relatedObject;
extern String s$shiftKey;
extern String s$keyCode;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
String openfl_events_Event___formatToString(openfl__events__Event,String,hl__types__ArrayObj);
void openfl_events_Event___init(openfl__events__Event);

void openfl_events_FocusEvent_new(openfl__events__FocusEvent r0,String r1,bool* r2,bool* r3,openfl__display__InteractiveObject r4,bool* r5,int* r6) {
	bool r7, r8, r9, r12, r13;
	int r10;
	if( r2 ) goto label$715d579_1_3;
	r7 = false;
	goto label$715d579_1_4;
	label$715d579_1_3:
	r7 = *r2;
	label$715d579_1_4:
	if( r3 ) goto label$715d579_1_7;
	r8 = false;
	goto label$715d579_1_8;
	label$715d579_1_7:
	r8 = *r3;
	label$715d579_1_8:
	if( r5 ) goto label$715d579_1_11;
	r9 = false;
	goto label$715d579_1_12;
	label$715d579_1_11:
	r9 = *r5;
	label$715d579_1_12:
	if( r6 ) goto label$715d579_1_15;
	r10 = 0;
	goto label$715d579_1_16;
	label$715d579_1_15:
	r10 = *r6;
	label$715d579_1_16:
	r12 = r7;
	r2 = &r12;
	r13 = r8;
	r3 = &r13;
	openfl_events_Event_new(((openfl__events__Event)r0),r1,r2,r3);
	r0->keyCode = r10;
	r0->shiftKey = r9;
	r0->relatedObject = r4;
	return;
}

openfl__events__Event openfl_events_FocusEvent_clone(openfl__events__FocusEvent r0) {
	bool *r4, *r6, *r9;
	String r2;
	openfl__events__FocusEvent r1;
	openfl__display__InteractiveObject r7;
	bool r3, r5, r8;
	vdynamic *r13;
	int *r11;
	int r10, r14;
	r1 = (openfl__events__FocusEvent)hl_alloc_obj(&t$openfl_events_FocusEvent);
	r2 = r0->type;
	r3 = r0->bubbles;
	r4 = &r3;
	r5 = r0->cancelable;
	r6 = &r5;
	r7 = r0->relatedObject;
	r8 = r0->shiftKey;
	r9 = &r8;
	r10 = r0->keyCode;
	r11 = &r10;
	openfl_events_FocusEvent_new(r1,r2,r4,r6,r7,r9,r11);
	r13 = r0->target;
	r1->target = r13;
	r13 = r0->currentTarget;
	r1->currentTarget = r13;
	r14 = r0->eventPhase;
	r1->eventPhase = r14;
	return ((openfl__events__Event)r1);
}

String openfl_events_FocusEvent_toString(openfl__events__FocusEvent r0) {
	String r1, r6;
	hl__types__ArrayObj r2;
	hl_type *r4;
	int r5;
	varray *r3;
	r1 = (String)s$FocusEvent;
	r4 = &t$String;
	r5 = 6;
	r3 = hl_alloc_array(r4,r5);
	r6 = (String)s$type;
	r5 = 0;
	((String*)(r3 + 1))[r5] = r6;
	r6 = (String)s$bubbles;
	r5 = 1;
	((String*)(r3 + 1))[r5] = r6;
	r6 = (String)s$cancelable;
	r5 = 2;
	((String*)(r3 + 1))[r5] = r6;
	r6 = (String)s$relatedObject;
	r5 = 3;
	((String*)(r3 + 1))[r5] = r6;
	r6 = (String)s$shiftKey;
	r5 = 4;
	((String*)(r3 + 1))[r5] = r6;
	r6 = (String)s$keyCode;
	r5 = 5;
	((String*)(r3 + 1))[r5] = r6;
	r2 = hl_types_ArrayObj_alloc(r3);
	r1 = openfl_events_Event___formatToString(((openfl__events__Event)r0),r1,r2);
	return r1;
}

void openfl_events_FocusEvent___init(openfl__events__FocusEvent r0) {
	openfl__display__InteractiveObject r4;
	bool r3;
	int r2;
	openfl_events_Event___init(((openfl__events__Event)r0));
	r2 = 0;
	r0->keyCode = r2;
	r3 = false;
	r0->shiftKey = r3;
	r4 = NULL;
	r0->relatedObject = r4;
	return;
}

