// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/events/HTTPStatusEvent.h>
void openfl_events_Event_new(openfl__events__Event,String,bool*,bool*);
extern hl_type t$openfl_events_HTTPStatusEvent;
extern String s$HTTPStatusEvent;
extern hl_type t$String;
#include <hl/natives.h>
extern String s$type;
extern String s$bubbles;
extern String s$cancelable;
extern String s$status;
extern String s$redirected;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
String openfl_events_Event___formatToString(openfl__events__Event,String,hl__types__ArrayObj);
void openfl_events_Event___init(openfl__events__Event);

void openfl_events_HTTPStatusEvent_new(openfl__events__HTTPStatusEvent r0,String r1,bool* r2,bool* r3,int* r4,bool* r5) {
	bool r6, r7, r9, r10, r12;
	int r8;
	if( r2 ) goto label$916fb8f_1_3;
	r6 = false;
	goto label$916fb8f_1_4;
	label$916fb8f_1_3:
	r6 = *r2;
	label$916fb8f_1_4:
	if( r3 ) goto label$916fb8f_1_7;
	r7 = false;
	goto label$916fb8f_1_8;
	label$916fb8f_1_7:
	r7 = *r3;
	label$916fb8f_1_8:
	if( r4 ) goto label$916fb8f_1_11;
	r8 = 0;
	goto label$916fb8f_1_12;
	label$916fb8f_1_11:
	r8 = *r4;
	label$916fb8f_1_12:
	if( r5 ) goto label$916fb8f_1_15;
	r9 = false;
	goto label$916fb8f_1_16;
	label$916fb8f_1_15:
	r9 = *r5;
	label$916fb8f_1_16:
	r0->status = r8;
	r0->redirected = r9;
	r10 = r6;
	r2 = &r10;
	r12 = r7;
	r3 = &r12;
	openfl_events_Event_new(((openfl__events__Event)r0),r1,r2,r3);
	return;
}

openfl__events__Event openfl_events_HTTPStatusEvent_clone(openfl__events__HTTPStatusEvent r0) {
	bool *r4, *r6, *r10;
	String r2;
	openfl__events__HTTPStatusEvent r1;
	bool r3, r5, r9;
	vdynamic *r12;
	int *r8;
	int r7, r13;
	r1 = (openfl__events__HTTPStatusEvent)hl_alloc_obj(&t$openfl_events_HTTPStatusEvent);
	r2 = r0->type;
	r3 = r0->bubbles;
	r4 = &r3;
	r5 = r0->cancelable;
	r6 = &r5;
	r7 = r0->status;
	r8 = &r7;
	r9 = r0->redirected;
	r10 = &r9;
	openfl_events_HTTPStatusEvent_new(r1,r2,r4,r6,r8,r10);
	r12 = r0->target;
	r1->target = r12;
	r12 = r0->currentTarget;
	r1->currentTarget = r12;
	r13 = r0->eventPhase;
	r1->eventPhase = r13;
	return ((openfl__events__Event)r1);
}

String openfl_events_HTTPStatusEvent_toString(openfl__events__HTTPStatusEvent r0) {
	String r1, r6;
	hl__types__ArrayObj r2;
	hl_type *r4;
	int r5;
	varray *r3;
	r1 = (String)s$HTTPStatusEvent;
	r4 = &t$String;
	r5 = 5;
	r3 = hl_alloc_array(r4,r5);
	r6 = (String)s$type;
	r5 = 0;
	((String*)(r3 + 1))[r5] = r6;
	r6 = (String)s$bubbles;
	r5 = 1;
	((String*)(r3 + 1))[r5] = r6;
	r6 = (String)s$cancelable;
	r5 = 2;
	((String*)(r3 + 1))[r5] = r6;
	r6 = (String)s$status;
	r5 = 3;
	((String*)(r3 + 1))[r5] = r6;
	r6 = (String)s$redirected;
	r5 = 4;
	((String*)(r3 + 1))[r5] = r6;
	r2 = hl_types_ArrayObj_alloc(r3);
	r1 = openfl_events_Event___formatToString(((openfl__events__Event)r0),r1,r2);
	return r1;
}

void openfl_events_HTTPStatusEvent___init(openfl__events__HTTPStatusEvent r0) {
	bool r3;
	int r2;
	openfl_events_Event___init(((openfl__events__Event)r0));
	r2 = 0;
	r0->status = r2;
	r3 = false;
	r0->redirected = r3;
	return;
}

