// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_haxe__zip___InflateImpl__State
#define INC_haxe__zip___InflateImpl__State
typedef struct _haxe__zip___InflateImpl__$State *haxe__zip___InflateImpl__$State;
#include <hl/Enum.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>


struct _haxe__zip___InflateImpl__$State {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __ename__;
	hl_bytes_map* __emap__;
	hl__types__ArrayObj __constructs__;
	varray* __evalues__;
};
#endif

