// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/media/Video.h>
void openfl_display_DisplayObject_new(openfl__display__DisplayObject);
#include <lime/utils/ObjectPool.h>
#include <openfl/geom/Rectangle.h>
extern openfl__geom__$Rectangle g$_openfl_geom_Rectangle;
vdynamic* lime_utils_ObjectPool_get(lime__utils__ObjectPool);
void openfl_geom_Rectangle_setTo(openfl__geom__Rectangle,double,double,double,double);
void openfl_geom_Rectangle___transform(openfl__geom__Rectangle,openfl__geom__Rectangle,openfl__geom__Matrix);
void openfl_geom_Rectangle___expand(openfl__geom__Rectangle,double,double,double,double);
void lime_utils_ObjectPool_release(lime__utils__ObjectPool,vdynamic*);
#include <openfl/display3D/Context3D.h>
#include <lime/_internal/backend/native/NativeOpenGLRenderContext.h>
#include <haxe/io/Bytes.h>
#include <hl/types/ArrayDyn.h>
#include <openfl/_Vector/IntVector.h>
extern hl_type t$lime_utils_ArrayBufferView;
extern hl_type t$_i32;
void lime_utils_ArrayBufferView_new(lime__utils__ArrayBufferView,vdynamic*,int);
void lime_utils_ArrayBufferIO_setInt16(haxe__io__Bytes,int,int);
openfl__display3D__IndexBuffer3D openfl_display3D_Context3D_createIndexBuffer(openfl__display3D__Context3D,int,vdynamic*);
void openfl_display3D_IndexBuffer3D_uploadFromTypedArray(openfl__display3D__IndexBuffer3D,lime__utils__ArrayBufferView,int*);
#include <openfl/_Vector/FloatVector.h>
double openfl_media_Video_get_width(openfl__media__Video);
extern hl_type t$fun_06455fc;
double openfl_media_Video_get_height(openfl__media__Video);
openfl__display3D__VertexBuffer3D openfl_display3D_Context3D_createVertexBuffer(openfl__display3D__Context3D,int,int,vdynamic*);
void openfl_display3D_VertexBuffer3D_uploadFromTypedArray(openfl__display3D__VertexBuffer3D,lime__utils__ArrayBufferView,int*);
bool openfl_display_DisplayObject_get_visible(openfl__display__DisplayObject);
openfl__display__DisplayObject openfl_display_DisplayObject_get_mask(openfl__display__DisplayObject);
openfl__geom__Matrix openfl_display_DisplayObject___getRenderTransform(openfl__display__DisplayObject);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
#include <openfl/geom/Point.h>
extern openfl__geom__$Point g$_openfl_geom_Point;
void openfl_geom_Point_setTo(openfl__geom__Point,double,double);
openfl__geom__Point openfl_display_DisplayObject___globalToLocal(openfl__display__DisplayObject,openfl__geom__Point,openfl__geom__Point);
double openfl_display_DisplayObject_get_scaleY(openfl__display__DisplayObject);
void openfl_display_DisplayObject___setTransformDirty(openfl__display__DisplayObject);
double openfl_display_DisplayObject_set_scaleY(openfl__display__DisplayObject,double);
double openfl_display_DisplayObject_set_scaleX(openfl__display__DisplayObject,double);

void openfl_media_Video_new(openfl__media__Video r0,int* r1,int* r2) {
	bool r8;
	double r7;
	int r3, r4, r6;
	if( r1 ) goto label$b439efa_1_3;
	r3 = 320;
	goto label$b439efa_1_4;
	label$b439efa_1_3:
	r3 = *r1;
	label$b439efa_1_4:
	if( r2 ) goto label$b439efa_1_7;
	r4 = 240;
	goto label$b439efa_1_8;
	label$b439efa_1_7:
	r4 = *r2;
	label$b439efa_1_8:
	openfl_display_DisplayObject_new(((openfl__display__DisplayObject)r0));
	r6 = 8;
	r0->__drawableType = r6;
	r7 = (double)r3;
	r0->__width = r7;
	r7 = (double)r4;
	r0->__height = r7;
	r7 = -1.;
	r0->__textureTime = r7;
	r8 = false;
	r0->smoothing = r8;
	r6 = 0;
	r0->deblocking = r6;
	return;
}

void openfl_media_Video_attachNetStream(openfl__media__Video r0,openfl__net__NetStream r1) {
	r0->__stream = r1;
	return;
}

void openfl_media_Video_clear(openfl__media__Video r0) {
	return;
}

void openfl_media_Video___enterFrame(openfl__media__Video r0,int r1) {
	return;
}

void openfl_media_Video___getBounds(openfl__media__Video r0,openfl__geom__Rectangle r1,openfl__geom__Matrix r2) {
	openfl__geom__Rectangle r6;
	openfl__geom__$Rectangle r5;
	double r8, r9, r10, r11;
	lime__utils__ObjectPool r4;
	vdynamic *r3;
	r5 = (openfl__geom__$Rectangle)g$_openfl_geom_Rectangle;
	r4 = r5->__pool;
	if( r4 == NULL ) hl_null_access();
	r3 = lime_utils_ObjectPool_get(r4);
	r6 = (openfl__geom__Rectangle)r3;
	if( r6 == NULL ) hl_null_access();
	r8 = 0.;
	r9 = 0.;
	r10 = r0->__width;
	r11 = r0->__height;
	openfl_geom_Rectangle_setTo(r6,r8,r9,r10,r11);
	openfl_geom_Rectangle___transform(r6,r6,r2);
	if( r1 == NULL ) hl_null_access();
	r8 = r6->x;
	r9 = r6->y;
	r10 = r6->width;
	r11 = r6->height;
	openfl_geom_Rectangle___expand(r1,r8,r9,r10,r11);
	r5 = (openfl__geom__$Rectangle)g$_openfl_geom_Rectangle;
	r4 = r5->__pool;
	if( r4 == NULL ) hl_null_access();
	lime_utils_ObjectPool_release(r4,((vdynamic*)r6));
	return;
}

openfl__display3D__IndexBuffer3D openfl_media_Video___getIndexBuffer(openfl__media__Video r0,openfl__display3D__Context3D r1) {
	openfl___Vector__IntVector r9;
	haxe__io__Bytes r7, r15;
	lime___internal__backend__native__NativeOpenGLRenderContext r2;
	lime__graphics__RenderContext r5, r6;
	lime__utils__ArrayBufferView r10, r12;
	hl__types__ArrayDyn r8;
	openfl__display3D__IndexBuffer3D r4;
	int *r17;
	vdynamic *r11, *r14;
	int r13, r16;
	if( r1 == NULL ) hl_null_access();
	r2 = r1->gl;
	r4 = r0->__indexBuffer;
	if( !r4 ) goto label$b439efa_6_7;
	r5 = r0->__indexBufferContext;
	r6 = r1->__context;
	if( r5 == r6 ) goto label$b439efa_6_75;
	label$b439efa_6_7:
	r7 = NULL;
	r8 = NULL;
	r9 = NULL;
	r10 = NULL;
	r11 = NULL;
	r12 = (lime__utils__ArrayBufferView)hl_alloc_obj(&t$lime_utils_ArrayBufferView);
	r13 = 6;
	r14 = hl_alloc_dynamic(&t$_i32);
	r14->v.i = r13;
	r13 = 6;
	lime_utils_ArrayBufferView_new(r12,r14,r13);
	r0->__indexBufferData = r12;
	r12 = r0->__indexBufferData;
	if( r12 == NULL ) hl_null_access();
	r15 = r12->buffer;
	r13 = r12->byteOffset;
	r16 = 0;
	lime_utils_ArrayBufferIO_setInt16(r15,r13,r16);
	r12 = r0->__indexBufferData;
	if( r12 == NULL ) hl_null_access();
	r15 = r12->buffer;
	r13 = r12->byteOffset;
	r16 = 2;
	r13 = r13 + r16;
	r16 = 1;
	lime_utils_ArrayBufferIO_setInt16(r15,r13,r16);
	r12 = r0->__indexBufferData;
	if( r12 == NULL ) hl_null_access();
	r15 = r12->buffer;
	r13 = r12->byteOffset;
	r16 = 4;
	r13 = r13 + r16;
	r16 = 2;
	lime_utils_ArrayBufferIO_setInt16(r15,r13,r16);
	r12 = r0->__indexBufferData;
	if( r12 == NULL ) hl_null_access();
	r15 = r12->buffer;
	r13 = r12->byteOffset;
	r16 = 6;
	r13 = r13 + r16;
	r16 = 2;
	lime_utils_ArrayBufferIO_setInt16(r15,r13,r16);
	r12 = r0->__indexBufferData;
	if( r12 == NULL ) hl_null_access();
	r15 = r12->buffer;
	r13 = r12->byteOffset;
	r16 = 8;
	r13 = r13 + r16;
	r16 = 1;
	lime_utils_ArrayBufferIO_setInt16(r15,r13,r16);
	r12 = r0->__indexBufferData;
	if( r12 == NULL ) hl_null_access();
	r15 = r12->buffer;
	r13 = r12->byteOffset;
	r16 = 10;
	r13 = r13 + r16;
	r16 = 3;
	lime_utils_ArrayBufferIO_setInt16(r15,r13,r16);
	r5 = r1->__context;
	r0->__indexBufferContext = r5;
	r13 = 6;
	r14 = NULL;
	r4 = openfl_display3D_Context3D_createIndexBuffer(r1,r13,r14);
	r0->__indexBuffer = r4;
	r4 = r0->__indexBuffer;
	if( r4 == NULL ) hl_null_access();
	r12 = r0->__indexBufferData;
	r17 = NULL;
	openfl_display3D_IndexBuffer3D_uploadFromTypedArray(r4,r12,r17);
	label$b439efa_6_75:
	r4 = r0->__indexBuffer;
	return r4;
}

openfl__display3D__textures__RectangleTexture openfl_media_Video___getTexture(openfl__media__Video r0,openfl__display3D__Context3D r1) {
	openfl__display3D__textures__RectangleTexture r2;
	r2 = NULL;
	return r2;
}

openfl__display3D__VertexBuffer3D openfl_media_Video___getVertexBuffer(openfl__media__Video r0,openfl__display3D__Context3D r1) {
	haxe__io__Bytes r9, r19;
	openfl__display3D__VertexBuffer3D r4;
	lime___internal__backend__native__NativeOpenGLRenderContext r2;
	openfl___Vector__FloatVector r11;
	lime__graphics__RenderContext r5, r6;
	vclosure *r18;
	double r17;
	lime__utils__ArrayBufferView r12, r14;
	hl__types__ArrayDyn r10;
	int *r21;
	vdynamic *r13, *r16;
	int r7, r8, r15, r20;
	if( r1 == NULL ) hl_null_access();
	r2 = r1->gl;
	r4 = r0->__vertexBuffer;
	if( !r4 ) goto label$b439efa_8_7;
	r5 = r0->__vertexBufferContext;
	r6 = r1->__context;
	if( r5 == r6 ) goto label$b439efa_8_118;
	label$b439efa_8_7:
	r7 = 1;
	r8 = 1;
	r9 = NULL;
	r10 = NULL;
	r11 = NULL;
	r12 = NULL;
	r13 = NULL;
	r14 = (lime__utils__ArrayBufferView)hl_alloc_obj(&t$lime_utils_ArrayBufferView);
	r15 = 20;
	r16 = hl_alloc_dynamic(&t$_i32);
	r16->v.i = r15;
	r15 = 8;
	lime_utils_ArrayBufferView_new(r14,r16,r15);
	r0->__vertexBufferData = r14;
	r14 = r0->__vertexBufferData;
	r17 = openfl_media_Video_get_width(r0);
	if( r14 == NULL ) hl_null_access();
	r19 = r14->buffer;
	if( r19 == NULL ) hl_null_access();
	r18 = (vclosure*)hl_dyn_getp((vdynamic*)r19,281751194/*setFloat*/,&t$fun_06455fc);
	if( r18 == NULL ) hl_null_access();
	r15 = r14->byteOffset;
	r18->hasValue ? ((void (*)(vdynamic*,int,double))r18->fun)((vdynamic*)r18->value,r15,r17) : ((void (*)(int,double))r18->fun)(r15,r17);
	r14 = r0->__vertexBufferData;
	r17 = openfl_media_Video_get_height(r0);
	if( r14 == NULL ) hl_null_access();
	r19 = r14->buffer;
	if( r19 == NULL ) hl_null_access();
	r18 = (vclosure*)hl_dyn_getp((vdynamic*)r19,281751194/*setFloat*/,&t$fun_06455fc);
	if( r18 == NULL ) hl_null_access();
	r15 = r14->byteOffset;
	r20 = 4;
	r15 = r15 + r20;
	r18->hasValue ? ((void (*)(vdynamic*,int,double))r18->fun)((vdynamic*)r18->value,r15,r17) : ((void (*)(int,double))r18->fun)(r15,r17);
	r14 = r0->__vertexBufferData;
	if( r14 == NULL ) hl_null_access();
	r19 = r14->buffer;
	if( r19 == NULL ) hl_null_access();
	r18 = (vclosure*)hl_dyn_getp((vdynamic*)r19,281751194/*setFloat*/,&t$fun_06455fc);
	if( r18 == NULL ) hl_null_access();
	r15 = r14->byteOffset;
	r20 = 12;
	r15 = r15 + r20;
	r17 = (double)r7;
	r18->hasValue ? ((void (*)(vdynamic*,int,double))r18->fun)((vdynamic*)r18->value,r15,r17) : ((void (*)(int,double))r18->fun)(r15,r17);
	r14 = r0->__vertexBufferData;
	if( r14 == NULL ) hl_null_access();
	r19 = r14->buffer;
	if( r19 == NULL ) hl_null_access();
	r18 = (vclosure*)hl_dyn_getp((vdynamic*)r19,281751194/*setFloat*/,&t$fun_06455fc);
	if( r18 == NULL ) hl_null_access();
	r15 = r14->byteOffset;
	r20 = 16;
	r15 = r15 + r20;
	r17 = (double)r8;
	r18->hasValue ? ((void (*)(vdynamic*,int,double))r18->fun)((vdynamic*)r18->value,r15,r17) : ((void (*)(int,double))r18->fun)(r15,r17);
	r14 = r0->__vertexBufferData;
	r17 = openfl_media_Video_get_height(r0);
	if( r14 == NULL ) hl_null_access();
	r19 = r14->buffer;
	if( r19 == NULL ) hl_null_access();
	r18 = (vclosure*)hl_dyn_getp((vdynamic*)r19,281751194/*setFloat*/,&t$fun_06455fc);
	if( r18 == NULL ) hl_null_access();
	r15 = r14->byteOffset;
	r20 = 24;
	r15 = r15 + r20;
	r18->hasValue ? ((void (*)(vdynamic*,int,double))r18->fun)((vdynamic*)r18->value,r15,r17) : ((void (*)(int,double))r18->fun)(r15,r17);
	r14 = r0->__vertexBufferData;
	if( r14 == NULL ) hl_null_access();
	r19 = r14->buffer;
	if( r19 == NULL ) hl_null_access();
	r18 = (vclosure*)hl_dyn_getp((vdynamic*)r19,281751194/*setFloat*/,&t$fun_06455fc);
	if( r18 == NULL ) hl_null_access();
	r15 = r14->byteOffset;
	r20 = 36;
	r15 = r15 + r20;
	r17 = (double)r8;
	r18->hasValue ? ((void (*)(vdynamic*,int,double))r18->fun)((vdynamic*)r18->value,r15,r17) : ((void (*)(int,double))r18->fun)(r15,r17);
	r14 = r0->__vertexBufferData;
	r17 = openfl_media_Video_get_width(r0);
	if( r14 == NULL ) hl_null_access();
	r19 = r14->buffer;
	if( r19 == NULL ) hl_null_access();
	r18 = (vclosure*)hl_dyn_getp((vdynamic*)r19,281751194/*setFloat*/,&t$fun_06455fc);
	if( r18 == NULL ) hl_null_access();
	r15 = r14->byteOffset;
	r20 = 40;
	r15 = r15 + r20;
	r18->hasValue ? ((void (*)(vdynamic*,int,double))r18->fun)((vdynamic*)r18->value,r15,r17) : ((void (*)(int,double))r18->fun)(r15,r17);
	r14 = r0->__vertexBufferData;
	if( r14 == NULL ) hl_null_access();
	r19 = r14->buffer;
	if( r19 == NULL ) hl_null_access();
	r18 = (vclosure*)hl_dyn_getp((vdynamic*)r19,281751194/*setFloat*/,&t$fun_06455fc);
	if( r18 == NULL ) hl_null_access();
	r15 = r14->byteOffset;
	r20 = 52;
	r15 = r15 + r20;
	r17 = (double)r7;
	r18->hasValue ? ((void (*)(vdynamic*,int,double))r18->fun)((vdynamic*)r18->value,r15,r17) : ((void (*)(int,double))r18->fun)(r15,r17);
	r5 = r1->__context;
	r0->__vertexBufferContext = r5;
	r15 = 3;
	r20 = 5;
	r16 = NULL;
	r4 = openfl_display3D_Context3D_createVertexBuffer(r1,r15,r20,r16);
	r0->__vertexBuffer = r4;
	r4 = r0->__vertexBuffer;
	if( r4 == NULL ) hl_null_access();
	r14 = r0->__vertexBufferData;
	r21 = NULL;
	openfl_display3D_VertexBuffer3D_uploadFromTypedArray(r4,r14,r21);
	label$b439efa_8_118:
	r4 = r0->__vertexBuffer;
	return r4;
}

bool openfl_media_Video___hitTest(openfl__media__Video r0,double r1,double r2,bool r3,hl__types__ArrayObj r4,bool r5,openfl__display__DisplayObject r6) {
	openfl__display__DisplayObject r8;
	bool r7;
	openfl__geom__Matrix r11, r12;
	double r9, r10, r13, r14, r15, r16, r17;
	int r18;
	if( r6 == NULL ) hl_null_access();
	r7 = openfl_display_DisplayObject_get_visible(r6);
	if( !r7 ) goto label$b439efa_9_5;
	r7 = r0->__isMask;
	if( !r7 ) goto label$b439efa_9_7;
	label$b439efa_9_5:
	r7 = false;
	return r7;
	label$b439efa_9_7:
	r8 = openfl_display_DisplayObject_get_mask(((openfl__display__DisplayObject)r0));
	if( !r8 ) goto label$b439efa_9_15;
	r8 = openfl_display_DisplayObject_get_mask(((openfl__display__DisplayObject)r0));
	if( r8 == NULL ) hl_null_access();
	r7 = ((bool (*)(openfl__display__DisplayObject,double,double))r8->$type->vobj_proto[17])(r8,r1,r2);
	if( r7 ) goto label$b439efa_9_15;
	r7 = false;
	return r7;
	label$b439efa_9_15:
	r11 = openfl_display_DisplayObject___getRenderTransform(((openfl__display__DisplayObject)r0));
	r11 = r0->__renderTransform;
	if( r11 == NULL ) hl_null_access();
	r9 = r11->a;
	r10 = r11->d;
	r9 = r9 * r10;
	r10 = r11->b;
	r13 = r11->c;
	r10 = r10 * r13;
	r9 = r9 - r10;
	r13 = 0.;
	if( r9 != r13 ) goto label$b439efa_9_30;
	r10 = r11->tx;
	r10 = -r10;
	goto label$b439efa_9_42;
	label$b439efa_9_30:
	r10 = 1.;
	r10 = r10 / r9;
	r13 = r11->c;
	r14 = r11->ty;
	r14 = r14 - r2;
	r13 = r13 * r14;
	r14 = r11->d;
	r16 = r11->tx;
	r15 = r1 - r16;
	r14 = r14 * r15;
	r13 = r13 + r14;
	r10 = r10 * r13;
	label$b439efa_9_42:
	r12 = r0->__renderTransform;
	if( r12 == NULL ) hl_null_access();
	r13 = r12->a;
	r14 = r12->d;
	r13 = r13 * r14;
	r14 = r12->b;
	r15 = r12->c;
	r14 = r14 * r15;
	r13 = r13 - r14;
	r15 = 0.;
	if( r13 != r15 ) goto label$b439efa_9_56;
	r14 = r12->ty;
	r14 = -r14;
	goto label$b439efa_9_68;
	label$b439efa_9_56:
	r14 = 1.;
	r14 = r14 / r13;
	r15 = r12->a;
	r17 = r12->ty;
	r16 = r2 - r17;
	r15 = r15 * r16;
	r16 = r12->b;
	r17 = r12->tx;
	r17 = r17 - r1;
	r16 = r16 * r17;
	r15 = r15 + r16;
	r14 = r14 * r15;
	label$b439efa_9_68:
	r16 = 0.;
	if( !(r16 < r10) ) goto label$b439efa_9_82;
	r16 = 0.;
	if( !(r16 < r14) ) goto label$b439efa_9_82;
	r16 = r0->__width;
	if( !(r16 >= r10) ) goto label$b439efa_9_82;
	r16 = r0->__height;
	if( !(r16 >= r14) ) goto label$b439efa_9_82;
	if( !r4 ) goto label$b439efa_9_80;
	if( r5 ) goto label$b439efa_9_80;
	if( r4 == NULL ) hl_null_access();
	r18 = hl_types_ArrayObj_push(r4,((vdynamic*)r6));
	label$b439efa_9_80:
	r7 = true;
	return r7;
	label$b439efa_9_82:
	r7 = false;
	return r7;
}

bool openfl_media_Video___hitTestMask(openfl__media__Video r0,double r1,double r2) {
	bool r11;
	double r9, r10;
	lime__utils__ObjectPool r4;
	vdynamic *r3;
	openfl__geom__Point r6, r8;
	openfl__geom__$Point r5;
	r5 = (openfl__geom__$Point)g$_openfl_geom_Point;
	r4 = r5->__pool;
	if( r4 == NULL ) hl_null_access();
	r3 = lime_utils_ObjectPool_get(r4);
	r6 = (openfl__geom__Point)r3;
	if( r6 == NULL ) hl_null_access();
	openfl_geom_Point_setTo(r6,r1,r2);
	r8 = openfl_display_DisplayObject___globalToLocal(((openfl__display__DisplayObject)r0),r6,r6);
	r9 = r6->x;
	r10 = 0.;
	if( !(r10 < r9) ) goto label$b439efa_10_22;
	r9 = r6->y;
	r10 = 0.;
	if( !(r10 < r9) ) goto label$b439efa_10_22;
	r9 = r6->x;
	r10 = r0->__width;
	if( !(r10 >= r9) ) goto label$b439efa_10_22;
	r9 = r6->y;
	r10 = r0->__height;
	if( !(r10 >= r9) ) goto label$b439efa_10_22;
	r11 = true;
	goto label$b439efa_10_23;
	label$b439efa_10_22:
	r11 = false;
	label$b439efa_10_23:
	r5 = (openfl__geom__$Point)g$_openfl_geom_Point;
	r4 = r5->__pool;
	if( r4 == NULL ) hl_null_access();
	lime_utils_ObjectPool_release(r4,((vdynamic*)r6));
	return r11;
}

double openfl_media_Video_get_height(openfl__media__Video r0) {
	double r1, r2;
	r1 = r0->__height;
	r2 = openfl_display_DisplayObject_get_scaleY(((openfl__display__DisplayObject)r0));
	r1 = r1 * r2;
	return r1;
}

double openfl_media_Video_set_height(openfl__media__Video r0,double r1) {
	bool r5;
	double r3, r4;
	r3 = openfl_display_DisplayObject_get_scaleY(((openfl__display__DisplayObject)r0));
	r4 = 1.;
	if( r3 != r4 ) goto label$b439efa_12_5;
	r4 = r0->__height;
	if( r1 == r4 ) goto label$b439efa_12_8;
	label$b439efa_12_5:
	openfl_display_DisplayObject___setTransformDirty(((openfl__display__DisplayObject)r0));
	r5 = true;
	r0->__dirty = r5;
	label$b439efa_12_8:
	r3 = 1.;
	r3 = openfl_display_DisplayObject_set_scaleY(((openfl__display__DisplayObject)r0),r3);
	r0->__height = r1;
	return r1;
}

int openfl_media_Video_get_videoHeight(openfl__media__Video r0) {
	int r1;
	r1 = 0;
	return r1;
}

int openfl_media_Video_get_videoWidth(openfl__media__Video r0) {
	int r1;
	r1 = 0;
	return r1;
}

double openfl_media_Video_get_width(openfl__media__Video r0) {
	double r1, r2;
	r1 = r0->__width;
	r2 = r0->__scaleX;
	r1 = r1 * r2;
	return r1;
}

double openfl_media_Video_set_width(openfl__media__Video r0,double r1) {
	bool r5;
	double r3, r4;
	r3 = r0->__scaleX;
	r4 = 1.;
	if( r3 != r4 ) goto label$b439efa_16_5;
	r3 = r0->__width;
	if( r3 == r1 ) goto label$b439efa_16_8;
	label$b439efa_16_5:
	openfl_display_DisplayObject___setTransformDirty(((openfl__display__DisplayObject)r0));
	r5 = true;
	r0->__dirty = r5;
	label$b439efa_16_8:
	r3 = 1.;
	r3 = openfl_display_DisplayObject_set_scaleX(((openfl__display__DisplayObject)r0),r3);
	r0->__width = r1;
	return r1;
}

