// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/errors/EOFError.h>
extern String s$End_of_file_was_encountered;
void openfl_errors_IOError_new(openfl__errors__IOError,String);
extern String s$EOFError;

void openfl_errors_EOFError_new(openfl__errors__EOFError r0,String r1,int* r2) {
	String r5;
	int r3, r6;
	if( r2 ) goto label$047abba_1_3;
	r3 = 0;
	goto label$047abba_1_4;
	label$047abba_1_3:
	r3 = *r2;
	label$047abba_1_4:
	r5 = (String)s$End_of_file_was_encountered;
	openfl_errors_IOError_new(((openfl__errors__IOError)r0),r5);
	r5 = (String)s$EOFError;
	r0->name = r5;
	r6 = 2030;
	r0->errorID = r6;
	return;
}

