// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/errors/Error.h>
extern String s$;
void haxe_Exception_new(haxe__Exception,String,haxe__Exception,vdynamic*);
extern String s$Error;
#include <hl/types/ArrayObj.h>
hl__types__ArrayObj haxe__CallStack_CallStack_Impl__exceptionStack(bool*);
String haxe__CallStack_CallStack_Impl__toString(hl__types__ArrayObj);
String haxe_Exception_get_message(haxe__Exception);

void openfl_errors_Error_new(openfl__errors__Error r0,String r1,int* r2) {
	String r3;
	vdynamic *r7;
	haxe__Exception r6;
	int r4;
	if( r1 ) goto label$7c1d465_1_3;
	r3 = (String)s$;
	r1 = r3;
	label$7c1d465_1_3:
	if( r2 ) goto label$7c1d465_1_6;
	r4 = 0;
	goto label$7c1d465_1_7;
	label$7c1d465_1_6:
	r4 = *r2;
	label$7c1d465_1_7:
	r6 = NULL;
	r7 = NULL;
	haxe_Exception_new(((haxe__Exception)r0),r1,r6,r7);
	r0->errorID = r4;
	r3 = (String)s$Error;
	r0->name = r3;
	return;
}

String openfl_errors_Error_getStackTrace(openfl__errors__Error r0) {
	bool *r3;
	String r1;
	hl__types__ArrayObj r2;
	r3 = NULL;
	r2 = haxe__CallStack_CallStack_Impl__exceptionStack(r3);
	r1 = haxe__CallStack_CallStack_Impl__toString(r2);
	return r1;
}

String openfl_errors_Error_toString(openfl__errors__Error r0) {
	String r1;
	r1 = haxe_Exception_get_message(((haxe__Exception)r0));
	if( !r1 ) goto label$7c1d465_3_4;
	r1 = haxe_Exception_get_message(((haxe__Exception)r0));
	return r1;
	label$7c1d465_3_4:
	r1 = (String)s$Error;
	return r1;
}

