// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__errors__Error
#define INC_openfl__errors__Error
typedef struct _openfl__errors__$Error *openfl__errors__$Error;
typedef struct _openfl__errors__Error *openfl__errors__Error;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/Exception.h>


struct _openfl__errors__$Error {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	String DEFAULT_TO_STRING;
};
struct _openfl__errors__Error {
	hl_type *$type;
	String __exceptionMessage;
	varray* __nativeStack;
	vdynamic* __nativeException;
	haxe__Exception __previousException;
	int errorID;
	String name;
};
#endif

