// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/errors/IOError.h>
extern String s$;
void openfl_errors_Error_new(openfl__errors__Error,String,int*);
extern String s$IOError;

void openfl_errors_IOError_new(openfl__errors__IOError r0,String r1) {
	String r2;
	int *r4;
	if( r1 ) goto label$5d0194c_1_3;
	r2 = (String)s$;
	r1 = r2;
	label$5d0194c_1_3:
	r4 = NULL;
	openfl_errors_Error_new(((openfl__errors__Error)r0),r1,r4);
	r2 = (String)s$IOError;
	r0->name = r2;
	return;
}

