// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/errors/TypeError.h>
extern String s$;
void openfl_errors_Error_new(openfl__errors__Error,String,int*);
extern String s$TypeError;

void openfl_errors_TypeError_new(openfl__errors__TypeError r0,String r1) {
	String r2;
	int *r5;
	int r4;
	if( r1 ) goto label$79fb0d3_1_3;
	r2 = (String)s$;
	r1 = r2;
	label$79fb0d3_1_3:
	r4 = 0;
	r5 = &r4;
	openfl_errors_Error_new(((openfl__errors__Error)r0),r1,r5);
	r2 = (String)s$TypeError;
	r0->name = r2;
	return;
}

