// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/media/openal/_ALFilter/ALFilter_Impl_.h>

vdynamic* lime_media_openal__ALFilter_ALFilter_Impl___new(vdynamic* r0) {
	return r0;
}

