// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/ds/_List/ListIterator.h>

void haxe_ds__List_ListIterator_new(haxe__ds___List__ListIterator r0,haxe__ds___List__ListNode r1) {
	r0->head = r1;
	return;
}

bool haxe_ds__List_ListIterator_hasNext(haxe__ds___List__ListIterator r0) {
	bool r1;
	haxe__ds___List__ListNode r2, r3;
	r2 = r0->head;
	r3 = NULL;
	if( r2 != r3 ) goto label$7b8f0f0_2_5;
	r1 = false;
	goto label$7b8f0f0_2_6;
	label$7b8f0f0_2_5:
	r1 = true;
	label$7b8f0f0_2_6:
	return r1;
}

vdynamic* haxe_ds__List_ListIterator_next(haxe__ds___List__ListIterator r0) {
	haxe__ds___List__ListNode r2;
	vdynamic *r1;
	r2 = r0->head;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->item;
	r2 = r0->head;
	if( r2 == NULL ) hl_null_access();
	r2 = r2->next;
	r0->head = r2;
	return r1;
}

