// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/util/_FlxDirectionFlags/FlxDirectionFlags_Impl_.h>
#include <_std/Math.h>
extern $Math g$_Math;
extern String s$NONE;
extern String s$;
extern String s$_L;
String String___add__(String,String);
extern String s$_R;
extern String s$_U;
extern String s$_D;
String String_substr(String,int,vdynamic*);

double flixel_util__FlxDirectionFlags_FlxDirectionFlags_Impl__get_degrees(int r0) {
	double r4;
	int r1, r2, r3, r5, r6, r7;
	r1 = 1;
	if( r1 == r0 ) goto label$d4bb2bb_1_34;
	r1 = 16;
	if( r1 == r0 ) goto label$d4bb2bb_1_36;
	r1 = 256;
	if( r1 == r0 ) goto label$d4bb2bb_1_38;
	r1 = 4096;
	if( r1 == r0 ) goto label$d4bb2bb_1_40;
	r2 = 4096;
	r3 = 16;
	r2 = r2 | r3;
	if( r0 != r2 ) goto label$d4bb2bb_1_14;
	r4 = 45.;
	return r4;
	label$d4bb2bb_1_14:
	r3 = 4096;
	r5 = 1;
	r3 = r3 | r5;
	if( r0 != r3 ) goto label$d4bb2bb_1_20;
	r4 = 135.;
	return r4;
	label$d4bb2bb_1_20:
	r5 = 256;
	r6 = 16;
	r5 = r5 | r6;
	if( r0 != r5 ) goto label$d4bb2bb_1_26;
	r4 = -45.;
	return r4;
	label$d4bb2bb_1_26:
	r6 = 256;
	r7 = 1;
	r6 = r6 | r7;
	if( r0 != r6 ) goto label$d4bb2bb_1_32;
	r4 = -135.;
	return r4;
	label$d4bb2bb_1_32:
	r4 = 0.;
	return r4;
	label$d4bb2bb_1_34:
	r4 = 180.;
	return r4;
	label$d4bb2bb_1_36:
	r4 = 0.;
	return r4;
	label$d4bb2bb_1_38:
	r4 = -90.;
	return r4;
	label$d4bb2bb_1_40:
	r4 = 90.;
	return r4;
}

double flixel_util__FlxDirectionFlags_FlxDirectionFlags_Impl__get_radians(int r0) {
	$Math r3;
	double r1, r2, r4;
	r1 = flixel_util__FlxDirectionFlags_FlxDirectionFlags_Impl__get_degrees(r0);
	r3 = ($Math)g$_Math;
	r2 = r3->PI;
	r4 = 180.;
	r2 = r2 / r4;
	r1 = r1 * r2;
	return r1;
}

bool flixel_util__FlxDirectionFlags_FlxDirectionFlags_Impl__has(int r0,int r1) {
	bool r2;
	int r3;
	r3 = r0 & r1;
	if( r3 == r1 ) goto label$d4bb2bb_3_4;
	r2 = false;
	goto label$d4bb2bb_3_5;
	label$d4bb2bb_3_4:
	r2 = true;
	label$d4bb2bb_3_5:
	return r2;
}

bool flixel_util__FlxDirectionFlags_FlxDirectionFlags_Impl__hasAny(int r0,int r1) {
	bool r2;
	int r3, r4;
	r3 = r0 & r1;
	r4 = 0;
	if( r3 > r4 ) goto label$d4bb2bb_4_5;
	r2 = false;
	goto label$d4bb2bb_4_6;
	label$d4bb2bb_4_5:
	r2 = true;
	label$d4bb2bb_4_6:
	return r2;
}

int flixel_util__FlxDirectionFlags_FlxDirectionFlags_Impl__with(int r0,int r1) {
	int r2;
	r2 = r0 | r1;
	return r2;
}

int flixel_util__FlxDirectionFlags_FlxDirectionFlags_Impl__without(int r0,int r1) {
	int r2, r3, r4;
	r4 = -1;
	r3 = r1 ^ r4;
	r2 = r0 & r3;
	return r2;
}

String flixel_util__FlxDirectionFlags_FlxDirectionFlags_Impl__toString(int r0) {
	String r3, r5, r6;
	vdynamic *r9;
	int r1, r2, r4, r7, r8;
	r2 = 0;
	if( r0 != r2 ) goto label$d4bb2bb_7_4;
	r3 = (String)s$NONE;
	return r3;
	label$d4bb2bb_7_4:
	r3 = (String)s$;
	r1 = 1;
	r2 = r0 & r1;
	if( r2 != r1 ) goto label$d4bb2bb_7_11;
	r6 = (String)s$_L;
	r5 = String___add__(r3,r6);
	r3 = r5;
	label$d4bb2bb_7_11:
	r2 = 16;
	r4 = r0 & r2;
	if( r4 != r2 ) goto label$d4bb2bb_7_17;
	r6 = (String)s$_R;
	r5 = String___add__(r3,r6);
	r3 = r5;
	label$d4bb2bb_7_17:
	r4 = 256;
	r7 = r0 & r4;
	if( r7 != r4 ) goto label$d4bb2bb_7_23;
	r6 = (String)s$_U;
	r5 = String___add__(r3,r6);
	r3 = r5;
	label$d4bb2bb_7_23:
	r7 = 4096;
	r8 = r0 & r7;
	if( r8 != r7 ) goto label$d4bb2bb_7_29;
	r6 = (String)s$_D;
	r5 = String___add__(r3,r6);
	r3 = r5;
	label$d4bb2bb_7_29:
	if( r3 == NULL ) hl_null_access();
	r8 = 3;
	r9 = NULL;
	r5 = String_substr(r3,r8,r9);
	return r5;
}

int flixel_util__FlxDirectionFlags_FlxDirectionFlags_Impl__fromBools(bool r0,bool r1,bool r2,bool r3) {
	int r4, r5;
	if( !r0 ) goto label$d4bb2bb_8_3;
	r4 = 1;
	goto label$d4bb2bb_8_4;
	label$d4bb2bb_8_3:
	r4 = 0;
	label$d4bb2bb_8_4:
	if( !r1 ) goto label$d4bb2bb_8_7;
	r5 = 16;
	goto label$d4bb2bb_8_8;
	label$d4bb2bb_8_7:
	r5 = 0;
	label$d4bb2bb_8_8:
	r4 = r4 | r5;
	if( !r2 ) goto label$d4bb2bb_8_12;
	r5 = 256;
	goto label$d4bb2bb_8_13;
	label$d4bb2bb_8_12:
	r5 = 0;
	label$d4bb2bb_8_13:
	r4 = r4 | r5;
	if( !r3 ) goto label$d4bb2bb_8_17;
	r5 = 4096;
	goto label$d4bb2bb_8_18;
	label$d4bb2bb_8_17:
	r5 = 0;
	label$d4bb2bb_8_18:
	r4 = r4 | r5;
	return r4;
}

