// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/net/NetConnection.h>
void openfl_events_EventDispatcher_new(openfl__events__EventDispatcher,vvirtual*);
#include <openfl/events/NetStatusEvent.h>
extern String s$259b6f2;
extern hl_type t$openfl_events_NetStatusEvent;
extern String s$netStatus;
extern hl_type t$vrt_743a639;
extern String s$NetConnection_Connect_Success;
extern hl_type t$String;
void openfl_events_NetStatusEvent_new(openfl__events__NetStatusEvent,String,bool*,bool*,vdynamic*);
bool openfl_events_EventDispatcher_dispatchEvent(openfl__events__EventDispatcher,openfl__events__Event);

void openfl_net_NetConnection_new(openfl__net__NetConnection r0) {
	vvirtual *r2;
	r2 = NULL;
	openfl_events_EventDispatcher_new(((openfl__events__EventDispatcher)r0),r2);
	return;
}

void openfl_net_NetConnection_connect(openfl__net__NetConnection r0,String r1,vdynamic* r2,vdynamic* r3,vdynamic* r4,vdynamic* r5,vdynamic* r6) {
	bool *r11, *r13;
	String r8, r15;
	vvirtual *r14;
	bool r9, r12;
	openfl__events__NetStatusEvent r10;
	if( !r1 ) goto label$1f9c3cc_2_3;
	r8 = (String)s$259b6f2;
	hl_throw((vdynamic*)r8);
	label$1f9c3cc_2_3:
	r10 = (openfl__events__NetStatusEvent)hl_alloc_obj(&t$openfl_events_NetStatusEvent);
	r8 = (String)s$netStatus;
	r9 = false;
	r11 = &r9;
	r12 = true;
	r13 = &r12;
	r14 = hl_alloc_virtual(&t$vrt_743a639);
	r15 = (String)s$NetConnection_Connect_Success;
	if( hl_vfields(r14)[0] ) *(String*)(hl_vfields(r14)[0]) = (String)r15; else hl_dyn_setp(r14->value,29667895/*code*/,&t$String,r15);
	openfl_events_NetStatusEvent_new(r10,r8,r11,r13,((vdynamic*)r14));
	r9 = openfl_events_EventDispatcher_dispatchEvent(((openfl__events__EventDispatcher)r0),((openfl__events__Event)r10));
	return;
}

