// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__net__SharedObject
#define INC_openfl__net__SharedObject
typedef struct _openfl__net__$SharedObject *openfl__net__$SharedObject;
typedef struct _openfl__net__SharedObject *openfl__net__SharedObject;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/ds/StringMap.h>
#include <openfl/events/EventDispatcher.h>
#include <openfl/events/Event.h>


struct _openfl__net__$SharedObject {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	int defaultObjectEncoding;
	haxe__ds__StringMap __sharedObjects;
	vclosure* getLocal;
	vclosure* getRemote;
	vclosure* __getPath;
	vclosure* __mkdir;
	vclosure* __resolveClass;
	vclosure* application_onExit;
};
struct _openfl__net__SharedObject {
	hl_type *$type;
	haxe__ds__StringMap __eventMap;
	haxe__ds__StringMap __iterators;
	vvirtual* __targetDispatcher;
	vvirtual* f$3;
	vdynamic* client;
	vdynamic* data;
	double fps;
	int objectEncoding;
	String __localPath;
	String __name;
};
#endif

