// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__net__URLRequestDefaults
#define INC_openfl__net__URLRequestDefaults
typedef struct _openfl__net__$URLRequestDefaults *openfl__net__$URLRequestDefaults;
typedef struct _openfl__net__URLRequestDefaults *openfl__net__URLRequestDefaults;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _openfl__net__$URLRequestDefaults {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	bool followRedirects;
	double idleTimeout;
	bool manageCookies;
	String userAgent;
};
struct _openfl__net__URLRequestDefaults {
	hl_type *$type;
};
#endif

