// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <haxe/ds/StringMap.h>
#include <hl/natives.h>
#include <haxe/ds/_StringMap/StringMapKeysIterator.h>
extern hl_type t$haxe_ds__StringMap_StringMapKeysIterator;
void haxe_ds__StringMap_StringMapKeysIterator_new(haxe__ds___StringMap__StringMapKeysIterator,hl_bytes_map*);
extern hl_type t$vrt_0a81a53;
#include <hl/NativeArrayIterator_Dynamic.h>
extern hl_type t$hl_NativeArrayIterator_Dynamic;
void hl_NativeArrayIterator_Dynamic_new(hl__NativeArrayIterator_Dynamic,varray*);
extern hl_type t$vrt_ef76930;
#include <haxe/iterators/MapKeyValueIterator.h>
extern hl_type t$haxe_iterators_MapKeyValueIterator;
extern hl_type t$vrt_b0685cf;
void haxe_iterators_MapKeyValueIterator_new(haxe__iterators__MapKeyValueIterator,vvirtual*);
extern hl_type t$vrt_9282dd1;
String haxe_ds_StringMap_toString(haxe__ds__StringMap);
#include <_std/StringBuf.h>
extern hl_type t$StringBuf;
void StringBuf_new(StringBuf);
void StringBuf_addChar(StringBuf,int);
extern String s$fc763cb;
void StringBuf_add(StringBuf,vdynamic*);
extern String s$c8d2017;
String StringBuf_toString(StringBuf);

void haxe_ds_StringMap_new(haxe__ds__StringMap r0) {
	hl_bytes_map *r1;
	r1 = hl_hballoc();
	r0->h = r1;
	return;
}

void haxe_ds_StringMap_set(haxe__ds__StringMap r0,String r1,vdynamic* r2) {
	hl_bytes_map *r4;
	vbyte *r5;
	r4 = r0->h;
	if( r1 == NULL ) hl_null_access();
	r5 = r1->bytes;
	hl_hbset(r4,r5,r2);
	return;
}

vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap r0,String r1) {
	hl_bytes_map *r3;
	vdynamic *r2;
	vbyte *r4;
	if( r1 ) goto label$1ac35ac_3_3;
	r2 = NULL;
	return r2;
	label$1ac35ac_3_3:
	r3 = r0->h;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->bytes;
	r2 = hl_hbget(r3,r4);
	return r2;
}

bool haxe_ds_StringMap_exists(haxe__ds__StringMap r0,String r1) {
	bool r2;
	hl_bytes_map *r3;
	vbyte *r4;
	if( r1 ) goto label$1ac35ac_4_3;
	r2 = false;
	return r2;
	label$1ac35ac_4_3:
	r3 = r0->h;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->bytes;
	r2 = hl_hbexists(r3,r4);
	return r2;
}

bool haxe_ds_StringMap_remove(haxe__ds__StringMap r0,String r1) {
	bool r2;
	hl_bytes_map *r3;
	vbyte *r4;
	if( r1 ) goto label$1ac35ac_5_3;
	r2 = false;
	return r2;
	label$1ac35ac_5_3:
	r3 = r0->h;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->bytes;
	r2 = hl_hbremove(r3,r4);
	return r2;
}

vvirtual* haxe_ds_StringMap_keys(haxe__ds__StringMap r0) {
	vvirtual *r4;
	hl_bytes_map *r2;
	haxe__ds___StringMap__StringMapKeysIterator r1;
	r1 = (haxe__ds___StringMap__StringMapKeysIterator)hl_alloc_obj(&t$haxe_ds__StringMap_StringMapKeysIterator);
	r2 = r0->h;
	haxe_ds__StringMap_StringMapKeysIterator_new(r1,r2);
	r4 = hl_to_virtual(&t$vrt_0a81a53,(vdynamic*)r1);
	return r4;
}

vvirtual* haxe_ds_StringMap_iterator(haxe__ds__StringMap r0) {
	vvirtual *r5;
	hl_bytes_map *r3;
	hl__NativeArrayIterator_Dynamic r1;
	varray *r2;
	r1 = (hl__NativeArrayIterator_Dynamic)hl_alloc_obj(&t$hl_NativeArrayIterator_Dynamic);
	r3 = r0->h;
	r2 = hl_hbvalues(r3);
	hl_NativeArrayIterator_Dynamic_new(r1,r2);
	r5 = hl_to_virtual(&t$vrt_ef76930,(vdynamic*)r1);
	return r5;
}

vvirtual* haxe_ds_StringMap_keyValueIterator(haxe__ds__StringMap r0) {
	haxe__iterators__MapKeyValueIterator r1;
	vvirtual *r2, *r4;
	r1 = (haxe__iterators__MapKeyValueIterator)hl_alloc_obj(&t$haxe_iterators_MapKeyValueIterator);
	r2 = r0->f$1;
	if( r2 ) goto label$1ac35ac_8_5;
	r2 = hl_to_virtual(&t$vrt_b0685cf,(vdynamic*)r0);
	r0->f$1 = r2;
	label$1ac35ac_8_5:
	haxe_iterators_MapKeyValueIterator_new(r1,r2);
	r4 = hl_to_virtual(&t$vrt_9282dd1,(vdynamic*)r1);
	return r4;
}

vbyte* haxe_ds_StringMap___string(haxe__ds__StringMap r0) {
	String r2;
	vbyte *r1;
	r2 = haxe_ds_StringMap_toString(r0);
	if( r2 == NULL ) hl_null_access();
	r1 = r2->bytes;
	return r1;
}

String haxe_ds_StringMap_toString(haxe__ds__StringMap r0) {
	String r11;
	hl_bytes_map *r4;
	StringBuf r1;
	vdynamic *r19;
	vbyte *r12, *r13, *r17;
	int r6, r7, r8, r9, r10, r14, r15, r16, r18;
	varray *r3, *r5;
	r1 = (StringBuf)hl_alloc_obj(&t$StringBuf);
	StringBuf_new(r1);
	r4 = r0->h;
	r3 = hl_hbkeys(r4);
	r4 = r0->h;
	r5 = hl_hbvalues(r4);
	r6 = 91;
	StringBuf_addChar(r1,r6);
	r6 = 0;
	r7 = r3->size;
	label$1ac35ac_10_10:
	if( r6 >= r7 ) goto label$1ac35ac_10_58;
	r8 = r6;
	++r6;
	r10 = 0;
	if( r10 >= r8 ) goto label$1ac35ac_10_19;
	if( r1 == NULL ) hl_null_access();
	r11 = (String)s$fc763cb;
	StringBuf_add(r1,((vdynamic*)r11));
	label$1ac35ac_10_19:
	r12 = ((vbyte**)(r3 + 1))[r8];
	r9 = 0;
	r9 = hl_ucs2length(r12,r9);
	r10 = 1;
	r9 = r9 << r10;
	if( r1 == NULL ) hl_null_access();
	r10 = r1->pos;
	r10 = r10 + r9;
	r14 = r1->size;
	if( r14 >= r10 ) goto label$1ac35ac_10_46;
	r10 = r1->pos;
	r10 = r10 + r9;
	r14 = r1->size;
	r15 = 3;
	r14 = r14 * r15;
	r15 = 1;
	r14 = r14 >> r15;
	if( r14 >= r10 ) goto label$1ac35ac_10_38;
	r14 = r10;
	label$1ac35ac_10_38:
	r13 = hl_alloc_bytes(r14);
	r15 = 0;
	r17 = r1->b;
	r16 = 0;
	r18 = r1->pos;
	hl_bytes_blit(r13,r15,r17,r16,r18);
	r1->b = r13;
	r1->size = r14;
	label$1ac35ac_10_46:
	r13 = r1->b;
	r10 = r1->pos;
	r14 = 0;
	hl_bytes_blit(r13,r10,r12,r14,r9);
	r10 = r1->pos;
	r10 = r10 + r9;
	r1->pos = r10;
	r11 = (String)s$c8d2017;
	StringBuf_add(r1,((vdynamic*)r11));
	r19 = ((vdynamic**)(r5 + 1))[r8];
	StringBuf_add(r1,r19);
	goto label$1ac35ac_10_10;
	label$1ac35ac_10_58:
	if( r1 == NULL ) hl_null_access();
	r6 = 93;
	StringBuf_addChar(r1,r6);
	r11 = StringBuf_toString(r1);
	return r11;
}

void haxe_ds_StringMap_clear(haxe__ds__StringMap r0) {
	hl_bytes_map *r2;
	r2 = r0->h;
	hl_hbclear(r2);
	return;
}

