// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__media__openal__ALC
#define INC_lime__media__openal__ALC
typedef struct _lime__media__openal__$ALC *lime__media__openal__$ALC;
typedef struct _lime__media__openal__ALC *lime__media__openal__ALC;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayBytes_Int.h>


struct _lime__media__openal__$ALC {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	int FALSE;
	int TRUE;
	int FREQUENCY;
	int REFRESH;
	int SYNC;
	int MONO_SOURCES;
	int STEREO_SOURCES;
	int NO_ERROR;
	int INVALID_DEVICE;
	int INVALID_CONTEXT;
	int INVALID_ENUM;
	int INVALID_VALUE;
	int OUT_OF_MEMORY;
	int ATTRIBUTES_SIZE;
	int ALL_ATTRIBUTES;
	int DEFAULT_DEVICE_SPECIFIER;
	int DEVICE_SPECIFIER;
	int EXTENSIONS;
	int ENUMERATE_ALL_EXT;
	int DEFAULT_ALL_DEVICES_SPECIFIER;
	int ALL_DEVICES_SPECIFIER;
	vclosure* closeDevice;
	vclosure* createContext;
	vclosure* destroyContext;
	vclosure* getContextsDevice;
	vclosure* getCurrentContext;
	vclosure* getError;
	vclosure* getErrorString;
	vclosure* getIntegerv;
	vclosure* getString;
	vclosure* makeContextCurrent;
	vclosure* openDevice;
	vclosure* pauseDevice;
	vclosure* processContext;
	vclosure* resumeDevice;
	vclosure* suspendContext;
};
struct _lime__media__openal__ALC {
	hl_type *$type;
};
#endif

