// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/graphics/opengl/GLObject.h>
#include <hl/natives.h>
extern hl_type t$lime_graphics_opengl_GLObject;

void lime_graphics_opengl_GLObject_new(lime__graphics__opengl__GLObject r0,int r1) {
	r0->id = r1;
	return;
}

lime__graphics__opengl__GLObject lime_graphics_opengl_GLObject_fromInt(int r0,int r1) {
	lime__graphics__opengl__GLObject r4, r6;
	vdynamic *r5;
	int r3;
	r3 = 0;
	if( r1 != r3 ) goto label$a58cf4a_2_4;
	r4 = NULL;
	return r4;
	label$a58cf4a_2_4:
	r4 = lime_hl_gl_object_from_id(r1,r0);
	if( !r4 ) goto label$a58cf4a_2_7;
	return r4;
	label$a58cf4a_2_7:
	r6 = (lime__graphics__opengl__GLObject)hl_alloc_obj(&t$lime_graphics_opengl_GLObject);
	lime_graphics_opengl_GLObject_new(r6,r1);
	r5 = lime_hl_gl_object_register(r1,r0,r6);
	r6->ptr = r5;
	return r6;
}

