// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/display3D/Program3D.h>
extern hl_type t$_i32;
extern hl_type t$haxe_ds_List;
void haxe_ds_List_new(haxe__ds__List);
extern hl_type t$hl_types_ArrayObj;
void hl_types_ArrayObj_new(hl__types__ArrayObj);
extern hl_type t$hl_types_ArrayBytes_Int;
void hl_types_ArrayBytes_Int_new(hl__types__ArrayBytes_Int);
void openfl_display3D_Program3D___deleteShaders(openfl__display3D__Program3D);
extern String s$va;
bool StringTools_startsWith(String,String);
String String_substring(String,int,vdynamic*);
vdynamic* Std_parseInt(String);
int String___compare(String,vdynamic*);
extern String s$vc;
extern String s$fc;
#include <openfl/utils/ByteArrayData.h>
#include <lime/utils/Log.h>
#include <hl/types/ArrayDyn.h>
#include <openfl/display/_internal/SamplerState.h>
String openfl_display3D__internal_AGALConverter_convertToGLSL(openfl__utils__ByteArrayData,hl__types__ArrayObj);
extern lime__utils__$Log g$_lime_utils_Log;
extern hl_type t$vrt_329ffa8;
extern String s$openfl_display3D_Program3D_hx;
extern hl_type t$String;
extern String s$openfl_display3D_Program3D;
extern String s$upload;
extern hl_type t$vrt_eaa6a3b;
void lime_utils_Log_info(vdynamic*,vvirtual*);
void openfl_display3D_Program3D___uploadFromGLSL(openfl__display3D__Program3D,String,String);
void openfl_display3D_Program3D___buildAGALUniformList(openfl__display3D__Program3D);
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);
#include <lime/_internal/backend/native/NativeOpenGLRenderContext.h>
extern String s$3927b53;
String String___add__(String,String);
extern String s$attribute;
void openfl_display3D_Program3D___processGLSLData(openfl__display3D__Program3D,String,String);
extern String s$uniform;
extern hl_type t$fun_a361529;
void hl_types_ArrayBytes_Int___expand(hl__types__ArrayBytes_Int,int);
#include <lime/utils/ArrayBufferView.h>
void haxe_ds_List_clear(haxe__ds__List);
extern hl_type t$openfl_display3D_Uniform;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern hl_type t$fun_90c71d8;
extern hl_type t$_dyn;
extern hl_type t$fun_f6fc5b4;
void openfl_display3D_Uniform_new(openfl__display3D__Uniform,openfl__display3D__Context3D);
extern String s$8154172;
int String_indexOf(String,String,vdynamic*);
void haxe_ds_List_add(haxe__ds__List,vdynamic*);
extern String s$vcPositionScale;
extern String s$sampler;
extern String s$alpha;
extern String s$_alpha;
bool StringTools_endsWith(String,String);
extern String s$b14a7b8;
extern String s$_alphaEnabled;
extern String s$;
String String___alloc__(vbyte*,int);
extern String s$233e6b4;
extern String s$_type_;
extern String s$_size_;
extern String s$_location_;
extern String s$__buildAGALUniformList;
void lime_utils_Log_verbose(vdynamic*,vvirtual*);
extern hl_type t$openfl_display3D_UniformMap;
extern hl_type t$vrt_c8138d1;
hl__types__ArrayDyn Lambda_array(vvirtual*);
extern hl_type t$hl_types_ArrayDyn;
void openfl_display3D_UniformMap_new(openfl__display3D__UniformMap,hl__types__ArrayObj);
extern hl_type t$fun_9a74d20;
#include <haxe/ds/_List/ListNode.h>
#include <openfl/errors/IllegalOperationError.h>
void openfl_display3D_UniformMap_markAllDirty(openfl__display3D__UniformMap);
extern hl_type t$fun_efca04c;
extern hl_type t$openfl_errors_IllegalOperationError;
extern String s$147a76a;
void openfl_errors_IllegalOperationError_new(openfl__errors__IllegalOperationError,String);
void openfl_display3D_UniformMap_flush(openfl__display3D__UniformMap);
void openfl_display3D_UniformMap_markDirty(openfl__display3D__UniformMap,int,int);
#include <_std/EReg.h>
extern hl_type t$EReg;
extern String s$248fba9;
void EReg_new(EReg,String,String);
extern String s$6030fbd;
bool EReg_matchSub(EReg,String,int,int*);
String EReg_matched(EReg,int);
extern String s$gl_;
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
vvirtual* EReg_matchedPos(EReg);
extern hl_type t$fun_589d191;
double lime_utils__DataPointer_DataPointer_Impl__fromArrayBufferView(lime__utils__ArrayBufferView);
extern hl_type t$fun_e4463cb;
extern hl_type t$fun_938098a;
extern String s$Error_compiling_vertex_shader;
extern String s$68b329d;
extern hl_type t$fun_716c0c7;
extern String s$__uploadFromGLSL;
void lime_utils_Log_error(vdynamic*,vvirtual*);
extern String s$Error_compiling_fragment_shader;
extern hl_type t$fun_1532d29;
extern String s$7215ee9;
extern hl_type t$fun_1cb686b;
extern String s$Position;
extern String s$38fd598;
extern hl_type t$fun_842af41;
extern String s$b175e45;

void openfl_display3D_Program3D_new(openfl__display3D__Program3D r0,openfl__display3D__Context3D r1,vdynamic* r2) {
	hl__types__ArrayObj r8;
	hl__types__ArrayBytes_Int r9;
	haxe__ds__List r7;
	vdynamic *r3, *r6;
	int r5;
	r0->__context = r1;
	r0->__format = r2;
	r3 = r0->__format;
	r5 = 0;
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r5;
	if( r3 != r6 && (!r3 || !r6 || (r3->v.i != r6->v.i)) ) goto label$49d1ec1_1_21;
	r5 = 0;
	r0->__agalSamplerUsageMask = r5;
	r7 = (haxe__ds__List)hl_alloc_obj(&t$haxe_ds_List);
	haxe_ds_List_new(r7);
	r0->__agalUniforms = r7;
	r7 = (haxe__ds__List)hl_alloc_obj(&t$haxe_ds_List);
	haxe_ds_List_new(r7);
	r0->__agalSamplerUniforms = r7;
	r7 = (haxe__ds__List)hl_alloc_obj(&t$haxe_ds_List);
	haxe_ds_List_new(r7);
	r0->__agalAlphaSamplerUniforms = r7;
	r8 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r8);
	r0->__agalAlphaSamplerEnabled = r8;
	goto label$49d1ec1_1_39;
	label$49d1ec1_1_21:
	r8 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r8);
	r0->__glslAttribNames = r8;
	r8 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r8);
	r0->__glslAttribTypes = r8;
	r8 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r8);
	r0->__glslSamplerNames = r8;
	r9 = (hl__types__ArrayBytes_Int)hl_alloc_obj(&t$hl_types_ArrayBytes_Int);
	hl_types_ArrayBytes_Int_new(r9);
	r0->__glslUniformLocations = r9;
	r8 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r8);
	r0->__glslUniformNames = r8;
	r8 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r8);
	r0->__glslUniformTypes = r8;
	label$49d1ec1_1_39:
	r8 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r8);
	r0->__samplerStates = r8;
	return;
}

void openfl_display3D_Program3D_dispose(openfl__display3D__Program3D r0) {
	openfl_display3D_Program3D___deleteShaders(r0);
	return;
}

int openfl_display3D_Program3D_getAttributeIndex(openfl__display3D__Program3D r0,String r1) {
	String r6, r7;
	hl__types__ArrayObj r10;
	bool r5;
	vdynamic *r2, *r4, *r8;
	varray *r13;
	int r3, r9, r11, r12;
	r2 = r0->__format;
	r3 = 0;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r3;
	if( r2 != r4 && (!r2 || !r4 || (r2->v.i != r4->v.i)) ) goto label$49d1ec1_3_16;
	r7 = (String)s$va;
	r5 = StringTools_startsWith(r1,r7);
	if( !r5 ) goto label$49d1ec1_3_14;
	if( r1 == NULL ) hl_null_access();
	r3 = 2;
	r2 = NULL;
	r6 = String_substring(r1,r3,r2);
	r2 = Std_parseInt(r6);
	r3 = r2 ? r2->v.i : 0;
	return r3;
	label$49d1ec1_3_14:
	r3 = -1;
	return r3;
	label$49d1ec1_3_16:
	r3 = 0;
	r10 = r0->__glslAttribNames;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->length;
	label$49d1ec1_3_20:
	if( r3 >= r9 ) goto label$49d1ec1_3_36;
	r11 = r3;
	++r3;
	r10 = r0->__glslAttribNames;
	if( r10 == NULL ) hl_null_access();
	r12 = r10->length;
	if( ((unsigned)r11) < ((unsigned)r12) ) goto label$49d1ec1_3_30;
	r6 = NULL;
	goto label$49d1ec1_3_33;
	label$49d1ec1_3_30:
	r13 = r10->array;
	r8 = ((vdynamic**)(r13 + 1))[r11];
	r6 = (String)r8;
	label$49d1ec1_3_33:
	if( r6 != r1 && (!r6 || !r1 || String___compare(r6,(vdynamic*)r1) != 0) ) goto label$49d1ec1_3_35;
	return r11;
	label$49d1ec1_3_35:
	goto label$49d1ec1_3_20;
	label$49d1ec1_3_36:
	r3 = -1;
	return r3;
}

int openfl_display3D_Program3D_getConstantIndex(openfl__display3D__Program3D r0,String r1) {
	String r6, r7;
	hl__types__ArrayObj r10;
	bool r5;
	hl__types__ArrayBytes_Int r15;
	vdynamic *r2, *r4, *r8;
	vbyte *r16;
	varray *r14;
	int r3, r9, r11, r12, r13;
	r2 = r0->__format;
	r3 = 0;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r3;
	if( r2 != r4 && (!r2 || !r4 || (r2->v.i != r4->v.i)) ) goto label$49d1ec1_4_26;
	r7 = (String)s$vc;
	r5 = StringTools_startsWith(r1,r7);
	if( !r5 ) goto label$49d1ec1_4_14;
	if( r1 == NULL ) hl_null_access();
	r3 = 2;
	r2 = NULL;
	r6 = String_substring(r1,r3,r2);
	r2 = Std_parseInt(r6);
	r3 = r2 ? r2->v.i : 0;
	return r3;
	label$49d1ec1_4_14:
	r7 = (String)s$fc;
	r5 = StringTools_startsWith(r1,r7);
	if( !r5 ) goto label$49d1ec1_4_24;
	if( r1 == NULL ) hl_null_access();
	r3 = 2;
	r2 = NULL;
	r6 = String_substring(r1,r3,r2);
	r2 = Std_parseInt(r6);
	r3 = r2 ? r2->v.i : 0;
	return r3;
	label$49d1ec1_4_24:
	r3 = -1;
	return r3;
	label$49d1ec1_4_26:
	r3 = 0;
	r10 = r0->__glslUniformNames;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->length;
	label$49d1ec1_4_30:
	if( r3 >= r9 ) goto label$49d1ec1_4_56;
	r11 = r3;
	++r3;
	r10 = r0->__glslUniformNames;
	if( r10 == NULL ) hl_null_access();
	r13 = r10->length;
	if( ((unsigned)r11) < ((unsigned)r13) ) goto label$49d1ec1_4_40;
	r6 = NULL;
	goto label$49d1ec1_4_43;
	label$49d1ec1_4_40:
	r14 = r10->array;
	r8 = ((vdynamic**)(r14 + 1))[r11];
	r6 = (String)r8;
	label$49d1ec1_4_43:
	if( r6 != r1 && (!r6 || !r1 || String___compare(r6,(vdynamic*)r1) != 0) ) goto label$49d1ec1_4_55;
	r15 = r0->__glslUniformLocations;
	if( r15 == NULL ) hl_null_access();
	r13 = r15->length;
	if( ((unsigned)r11) < ((unsigned)r13) ) goto label$49d1ec1_4_50;
	r12 = 0;
	goto label$49d1ec1_4_54;
	label$49d1ec1_4_50:
	r16 = r15->bytes;
	r13 = 2;
	r13 = r11 << r13;
	r12 = *(int*)(r16 + r13);
	label$49d1ec1_4_54:
	return r12;
	label$49d1ec1_4_55:
	goto label$49d1ec1_4_30;
	label$49d1ec1_4_56:
	r3 = -1;
	return r3;
}

void openfl_display3D_Program3D_upload(openfl__display3D__Program3D r0,openfl__utils__ByteArrayData r1,openfl__utils__ByteArrayData r2) {
	String r9, r11, r15;
	vvirtual *r14, *r16;
	hl__types__ArrayObj r8, r10;
	openfl__display___internal__SamplerState r20;
	lime__utils__$Log r12;
	vdynamic *r4, *r6, *r7;
	varray *r21;
	int r5, r13, r17, r18, r19;
	r4 = r0->__format;
	r5 = 0;
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r5;
	if( r4 == r6 || (r4 && r6 && (r4->v.i == r6->v.i)) ) goto label$49d1ec1_5_5;
	return;
	label$49d1ec1_5_5:
	r8 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r8);
	r10 = NULL;
	r9 = openfl_display3D__internal_AGALConverter_convertToGLSL(r1,r10);
	r11 = openfl_display3D__internal_AGALConverter_convertToGLSL(r2,r8);
	r12 = (lime__utils__$Log)g$_lime_utils_Log;
	r5 = r12->level;
	r13 = 5;
	if( r5 != r13 ) goto label$49d1ec1_5_36;
	r14 = hl_alloc_virtual(&t$vrt_329ffa8);
	r15 = (String)s$openfl_display3D_Program3D_hx;
	if( hl_vfields(r14)[1] ) *(String*)(hl_vfields(r14)[1]) = (String)r15; else hl_dyn_setp(r14->value,37969014/*fileName*/,&t$String,r15);
	r5 = 399;
	if( hl_vfields(r14)[2] ) *(int*)(hl_vfields(r14)[2]) = (int)r5; else hl_dyn_seti(r14->value,371360620/*lineNumber*/,&t$_i32,r5);
	r15 = (String)s$openfl_display3D_Program3D;
	if( hl_vfields(r14)[0] ) *(String*)(hl_vfields(r14)[0]) = (String)r15; else hl_dyn_setp(r14->value,-63073762/*className*/,&t$String,r15);
	r15 = (String)s$upload;
	if( hl_vfields(r14)[3] ) *(String*)(hl_vfields(r14)[3]) = (String)r15; else hl_dyn_setp(r14->value,302979532/*methodName*/,&t$String,r15);
	r16 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r14);
	lime_utils_Log_info(((vdynamic*)r9),r16);
	r14 = hl_alloc_virtual(&t$vrt_329ffa8);
	r15 = (String)s$openfl_display3D_Program3D_hx;
	if( hl_vfields(r14)[1] ) *(String*)(hl_vfields(r14)[1]) = (String)r15; else hl_dyn_setp(r14->value,37969014/*fileName*/,&t$String,r15);
	r5 = 400;
	if( hl_vfields(r14)[2] ) *(int*)(hl_vfields(r14)[2]) = (int)r5; else hl_dyn_seti(r14->value,371360620/*lineNumber*/,&t$_i32,r5);
	r15 = (String)s$openfl_display3D_Program3D;
	if( hl_vfields(r14)[0] ) *(String*)(hl_vfields(r14)[0]) = (String)r15; else hl_dyn_setp(r14->value,-63073762/*className*/,&t$String,r15);
	r15 = (String)s$upload;
	if( hl_vfields(r14)[3] ) *(String*)(hl_vfields(r14)[3]) = (String)r15; else hl_dyn_setp(r14->value,302979532/*methodName*/,&t$String,r15);
	r16 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r14);
	lime_utils_Log_info(((vdynamic*)r11),r16);
	label$49d1ec1_5_36:
	openfl_display3D_Program3D___deleteShaders(r0);
	openfl_display3D_Program3D___uploadFromGLSL(r0,r9,r11);
	openfl_display3D_Program3D___buildAGALUniformList(r0);
	r5 = 0;
	r13 = r8->length;
	label$49d1ec1_5_41:
	if( r5 >= r13 ) goto label$49d1ec1_5_61;
	r17 = r5;
	++r5;
	r10 = r0->__samplerStates;
	if( r10 == NULL ) hl_null_access();
	if( r8 == NULL ) hl_null_access();
	r19 = r8->length;
	if( ((unsigned)r17) < ((unsigned)r19) ) goto label$49d1ec1_5_52;
	r20 = NULL;
	goto label$49d1ec1_5_55;
	label$49d1ec1_5_52:
	r21 = r8->array;
	r7 = ((vdynamic**)(r21 + 1))[r17];
	r20 = (openfl__display___internal__SamplerState)r7;
	label$49d1ec1_5_55:
	r18 = r10->length;
	if( ((unsigned)r17) < ((unsigned)r18) ) goto label$49d1ec1_5_58;
	hl_types_ArrayObj___expand(r10,r17);
	label$49d1ec1_5_58:
	r21 = r10->array;
	((openfl__display___internal__SamplerState*)(r21 + 1))[r17] = r20;
	goto label$49d1ec1_5_41;
	label$49d1ec1_5_61:
	return;
}

void openfl_display3D_Program3D_uploadSources(openfl__display3D__Program3D r0,String r1,String r2) {
	String r8, r9, r10, r11, r12;
	openfl__display3D__Context3D r20;
	hl__types__ArrayObj r13, r14, r15, r16, r17;
	lime___internal__backend__native__NativeOpenGLRenderContext r19;
	lime__graphics__opengl__GLObject r24;
	hl__types__ArrayBytes_Int r18;
	vclosure *r23;
	vdynamic *r4, *r6, *r7;
	vbyte *r30;
	varray *r22;
	int r5, r21, r25, r26, r27, r28, r29;
	r4 = r0->__format;
	r5 = 1;
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r5;
	if( r4 == r6 || (r4 && r6 && (r4->v.i == r6->v.i)) ) goto label$49d1ec1_6_5;
	return;
	label$49d1ec1_6_5:
	r8 = (String)s$3927b53;
	r9 = String___add__(r8,r1);
	r10 = String___add__(r8,r2);
	r12 = r0->__glVertexSource;
	if( r9 != r12 && (!r9 || !r12 || String___compare(r9,(vdynamic*)r12) != 0) ) goto label$49d1ec1_6_13;
	r12 = r0->__glFragmentSource;
	if( r10 != r12 && (!r10 || !r12 || String___compare(r10,(vdynamic*)r12) != 0) ) goto label$49d1ec1_6_13;
	return;
	label$49d1ec1_6_13:
	r12 = (String)s$attribute;
	openfl_display3D_Program3D___processGLSLData(r0,r1,r12);
	r12 = (String)s$uniform;
	openfl_display3D_Program3D___processGLSLData(r0,r1,r12);
	r12 = (String)s$uniform;
	openfl_display3D_Program3D___processGLSLData(r0,r2,r12);
	openfl_display3D_Program3D___deleteShaders(r0);
	openfl_display3D_Program3D___uploadFromGLSL(r0,r9,r10);
	r13 = r0->__glslSamplerNames;
	r14 = r0->__glslAttribNames;
	r15 = r0->__glslAttribTypes;
	r16 = r0->__glslUniformNames;
	r17 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r17);
	r0->__glslSamplerNames = r17;
	r17 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r17);
	r0->__glslAttribNames = r17;
	r17 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r17);
	r0->__glslAttribTypes = r17;
	r18 = (hl__types__ArrayBytes_Int)hl_alloc_obj(&t$hl_types_ArrayBytes_Int);
	hl_types_ArrayBytes_Int_new(r18);
	r0->__glslUniformLocations = r18;
	r20 = r0->__context;
	if( r20 == NULL ) hl_null_access();
	r19 = r20->gl;
	r5 = 0;
	label$49d1ec1_6_41:
	if( r13 == NULL ) hl_null_access();
	r21 = r13->length;
	if( r5 >= r21 ) goto label$49d1ec1_6_66;
	r21 = r13->length;
	if( ((unsigned)r5) < ((unsigned)r21) ) goto label$49d1ec1_6_49;
	r11 = NULL;
	goto label$49d1ec1_6_52;
	label$49d1ec1_6_49:
	r22 = r13->array;
	r7 = ((vdynamic**)(r22 + 1))[r5];
	r11 = (String)r7;
	label$49d1ec1_6_52:
	++r5;
	if( r19 == NULL ) hl_null_access();
	r23 = (vclosure*)hl_dyn_getp((vdynamic*)r19,265576605/*getUniformLocation*/,&t$fun_a361529);
	if( r23 == NULL ) hl_null_access();
	r24 = r0->__glProgram;
	r21 = r23->hasValue ? ((int (*)(vdynamic*,lime__graphics__opengl__GLObject,String))r23->fun)((vdynamic*)r23->value,r24,r11) : ((int (*)(lime__graphics__opengl__GLObject,String))r23->fun)(r24,r11);
	r17 = r0->__glslSamplerNames;
	if( r17 == NULL ) hl_null_access();
	r25 = r17->length;
	if( ((unsigned)r21) < ((unsigned)r25) ) goto label$49d1ec1_6_63;
	hl_types_ArrayObj___expand(r17,r21);
	label$49d1ec1_6_63:
	r22 = r17->array;
	((String*)(r22 + 1))[r21] = r11;
	goto label$49d1ec1_6_41;
	label$49d1ec1_6_66:
	r5 = 0;
	if( r14 == NULL ) hl_null_access();
	r21 = r14->length;
	label$49d1ec1_6_69:
	if( r5 >= r21 ) goto label$49d1ec1_6_116;
	r25 = r5;
	++r5;
	if( r19 == NULL ) hl_null_access();
	r23 = (vclosure*)hl_dyn_getp((vdynamic*)r19,487594975/*getAttribLocation*/,&t$fun_a361529);
	if( r23 == NULL ) hl_null_access();
	r24 = r0->__glProgram;
	if( r14 == NULL ) hl_null_access();
	r27 = r14->length;
	if( ((unsigned)r25) < ((unsigned)r27) ) goto label$49d1ec1_6_82;
	r11 = NULL;
	goto label$49d1ec1_6_85;
	label$49d1ec1_6_82:
	r22 = r14->array;
	r7 = ((vdynamic**)(r22 + 1))[r25];
	r11 = (String)r7;
	label$49d1ec1_6_85:
	r26 = r23->hasValue ? ((int (*)(vdynamic*,lime__graphics__opengl__GLObject,String))r23->fun)((vdynamic*)r23->value,r24,r11) : ((int (*)(lime__graphics__opengl__GLObject,String))r23->fun)(r24,r11);
	r17 = r0->__glslAttribNames;
	if( r17 == NULL ) hl_null_access();
	r28 = r14->length;
	if( ((unsigned)r25) < ((unsigned)r28) ) goto label$49d1ec1_6_92;
	r11 = NULL;
	goto label$49d1ec1_6_95;
	label$49d1ec1_6_92:
	r22 = r14->array;
	r7 = ((vdynamic**)(r22 + 1))[r25];
	r11 = (String)r7;
	label$49d1ec1_6_95:
	r27 = r17->length;
	if( ((unsigned)r26) < ((unsigned)r27) ) goto label$49d1ec1_6_98;
	hl_types_ArrayObj___expand(r17,r26);
	label$49d1ec1_6_98:
	r22 = r17->array;
	((String*)(r22 + 1))[r26] = r11;
	r17 = r0->__glslAttribTypes;
	if( r17 == NULL ) hl_null_access();
	if( r15 == NULL ) hl_null_access();
	r28 = r15->length;
	if( ((unsigned)r25) < ((unsigned)r28) ) goto label$49d1ec1_6_107;
	r4 = NULL;
	goto label$49d1ec1_6_110;
	label$49d1ec1_6_107:
	r22 = r15->array;
	r7 = ((vdynamic**)(r22 + 1))[r25];
	r4 = (vdynamic*)r7;
	label$49d1ec1_6_110:
	r27 = r17->length;
	if( ((unsigned)r26) < ((unsigned)r27) ) goto label$49d1ec1_6_113;
	hl_types_ArrayObj___expand(r17,r26);
	label$49d1ec1_6_113:
	r22 = r17->array;
	((vdynamic**)(r22 + 1))[r26] = r4;
	goto label$49d1ec1_6_69;
	label$49d1ec1_6_116:
	r5 = 0;
	if( r16 == NULL ) hl_null_access();
	r21 = r16->length;
	label$49d1ec1_6_119:
	if( r5 >= r21 ) goto label$49d1ec1_6_147;
	r25 = r5;
	++r5;
	if( r19 == NULL ) hl_null_access();
	r23 = (vclosure*)hl_dyn_getp((vdynamic*)r19,265576605/*getUniformLocation*/,&t$fun_a361529);
	if( r23 == NULL ) hl_null_access();
	r24 = r0->__glProgram;
	if( r16 == NULL ) hl_null_access();
	r28 = r16->length;
	if( ((unsigned)r25) < ((unsigned)r28) ) goto label$49d1ec1_6_132;
	r11 = NULL;
	goto label$49d1ec1_6_135;
	label$49d1ec1_6_132:
	r22 = r16->array;
	r7 = ((vdynamic**)(r22 + 1))[r25];
	r11 = (String)r7;
	label$49d1ec1_6_135:
	r27 = r23->hasValue ? ((int (*)(vdynamic*,lime__graphics__opengl__GLObject,String))r23->fun)((vdynamic*)r23->value,r24,r11) : ((int (*)(lime__graphics__opengl__GLObject,String))r23->fun)(r24,r11);
	r26 = r27;
	r18 = r0->__glslUniformLocations;
	if( r18 == NULL ) hl_null_access();
	r29 = r18->length;
	if( ((unsigned)r25) < ((unsigned)r29) ) goto label$49d1ec1_6_142;
	hl_types_ArrayBytes_Int___expand(r18,r25);
	label$49d1ec1_6_142:
	r30 = r18->bytes;
	r29 = 2;
	r29 = r25 << r29;
	*(int*)(r30 + r29) = r26;
	goto label$49d1ec1_6_119;
	label$49d1ec1_6_147:
	return;
}

void openfl_display3D_Program3D___buildAGALUniformList(openfl__display3D__Program3D r0) {
	String r21, r24, r27;
	openfl__display3D__Uniform r23;
	vvirtual *r19, *r40, *r41, *r44;
	hl__types__ArrayObj r9;
	openfl__display3D__Context3D r7;
	openfl__display3D__UniformMap r42;
	hl_type *r11;
	bool r31;
	lime___internal__backend__native__NativeOpenGLRenderContext r6;
	lime__graphics__opengl__GLObject r13;
	lime__utils__$Log r37;
	haxe__ds__List r8, r15, r30;
	hl__types__ArrayDyn r43;
	lime__utils__ArrayBufferView r32;
	vclosure *r12, *r20, *r26;
	int *r38;
	vdynamic *r2, *r4, *r5;
	vbyte *r39;
	varray *r10;
	int r3, r14, r16, r17, r18, r22, r25, r28, r29, r33, r34, r35, r36;
	r2 = r0->__format;
	r3 = 1;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r3;
	if( r2 != r4 && (!r2 || !r4 || (r2->v.i != r4->v.i)) ) goto label$49d1ec1_7_5;
	return;
	label$49d1ec1_7_5:
	r7 = r0->__context;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->gl;
	r8 = r0->__agalUniforms;
	if( r8 == NULL ) hl_null_access();
	haxe_ds_List_clear(r8);
	r8 = r0->__agalSamplerUniforms;
	if( r8 == NULL ) hl_null_access();
	haxe_ds_List_clear(r8);
	r8 = r0->__agalAlphaSamplerUniforms;
	if( r8 == NULL ) hl_null_access();
	haxe_ds_List_clear(r8);
	r11 = &t$openfl_display3D_Uniform;
	r3 = 0;
	r10 = hl_alloc_array(r11,r3);
	r9 = hl_types_ArrayObj_alloc(r10);
	r0->__agalAlphaSamplerEnabled = r9;
	r3 = 0;
	r0->__agalSamplerUsageMask = r3;
	r3 = 0;
	if( r6 == NULL ) hl_null_access();
	r12 = (vclosure*)hl_dyn_getp((vdynamic*)r6,-157498964/*getProgramParameter*/,&t$fun_90c71d8);
	if( r12 == NULL ) hl_null_access();
	r13 = r0->__glProgram;
	r14 = r6->ACTIVE_UNIFORMS;
	r5 = r12->hasValue ? ((vdynamic* (*)(vdynamic*,lime__graphics__opengl__GLObject,int))r12->fun)((vdynamic*)r12->value,r13,r14) : ((vdynamic* (*)(lime__graphics__opengl__GLObject,int))r12->fun)(r13,r14);
	r14 = (int)hl_dyn_casti(&r5,&t$_dyn,&t$_i32);
	r3 = r14;
	r8 = (haxe__ds__List)hl_alloc_obj(&t$haxe_ds_List);
	haxe_ds_List_new(r8);
	r15 = (haxe__ds__List)hl_alloc_obj(&t$haxe_ds_List);
	haxe_ds_List_new(r15);
	r14 = 0;
	r16 = r3;
	label$49d1ec1_7_39:
	if( r14 >= r16 ) goto label$49d1ec1_7_286;
	r17 = r14;
	++r14;
	if( r6 == NULL ) hl_null_access();
	r20 = (vclosure*)hl_dyn_getp((vdynamic*)r6,-145869549/*getActiveUniform*/,&t$fun_f6fc5b4);
	if( r20 == NULL ) hl_null_access();
	r13 = r0->__glProgram;
	r19 = r20->hasValue ? ((vvirtual* (*)(vdynamic*,lime__graphics__opengl__GLObject,int))r20->fun)((vdynamic*)r20->value,r13,r17) : ((vvirtual* (*)(lime__graphics__opengl__GLObject,int))r20->fun)(r13,r17);
	if( r19 == NULL ) hl_null_access();
	r21 = hl_vfields(r19)[0] ? (*(String*)(hl_vfields(r19)[0])) : (String)hl_dyn_getp(r19->value,150958933/*name*/,&t$String);
	r18 = hl_vfields(r19)[1] ? (*(int*)(hl_vfields(r19)[1])) : (int)hl_dyn_geti(r19->value,206807499/*size*/,&t$_i32);
	r22 = hl_vfields(r19)[2] ? (*(int*)(hl_vfields(r19)[2])) : (int)hl_dyn_geti(r19->value,218690500/*type*/,&t$_i32);
	r23 = (openfl__display3D__Uniform)hl_alloc_obj(&t$openfl_display3D_Uniform);
	r7 = r0->__context;
	openfl_display3D_Uniform_new(r23,r7);
	r23->name = r21;
	r23->size = r18;
	r23->type = r22;
	r26 = (vclosure*)hl_dyn_getp((vdynamic*)r6,265576605/*getUniformLocation*/,&t$fun_a361529);
	if( r26 == NULL ) hl_null_access();
	r13 = r0->__glProgram;
	r24 = r23->name;
	r25 = r26->hasValue ? ((int (*)(vdynamic*,lime__graphics__opengl__GLObject,String))r26->fun)((vdynamic*)r26->value,r13,r24) : ((int (*)(lime__graphics__opengl__GLObject,String))r26->fun)(r13,r24);
	r23->location = r25;
	r24 = r23->name;
	if( r24 == NULL ) hl_null_access();
	r27 = (String)s$8154172;
	r2 = NULL;
	r25 = String_indexOf(r24,r27,r2);
	r29 = 0;
	if( r25 < r29 ) goto label$49d1ec1_7_77;
	r24 = r23->name;
	if( r24 == NULL ) hl_null_access();
	r28 = 0;
	r2 = hl_alloc_dynamic(&t$_i32);
	r2->v.i = r25;
	r24 = String_substring(r24,r28,r2);
	r23->name = r24;
	label$49d1ec1_7_77:
	r28 = r23->type;
	r29 = 35674;
	if( r29 == r28 ) goto label$49d1ec1_7_87;
	r29 = 35675;
	if( r29 == r28 ) goto label$49d1ec1_7_90;
	r29 = 35676;
	if( r29 == r28 ) goto label$49d1ec1_7_93;
	r28 = 1;
	r23->regCount = r28;
	goto label$49d1ec1_7_95;
	label$49d1ec1_7_87:
	r28 = 2;
	r23->regCount = r28;
	goto label$49d1ec1_7_95;
	label$49d1ec1_7_90:
	r28 = 3;
	r23->regCount = r28;
	goto label$49d1ec1_7_95;
	label$49d1ec1_7_93:
	r28 = 4;
	r23->regCount = r28;
	label$49d1ec1_7_95:
	r28 = r23->regCount;
	r29 = r23->size;
	r28 = r28 * r29;
	r23->regCount = r28;
	r30 = r0->__agalUniforms;
	if( r30 == NULL ) hl_null_access();
	haxe_ds_List_add(r30,((vdynamic*)r23));
	r24 = r23->name;
	r27 = (String)s$vcPositionScale;
	if( r24 != r27 && (!r24 || !r27 || String___compare(r24,(vdynamic*)r27) != 0) ) goto label$49d1ec1_7_107;
	r0->__agalPositionScale = r23;
	goto label$49d1ec1_7_238;
	label$49d1ec1_7_107:
	r24 = r23->name;
	r27 = (String)s$vc;
	r31 = StringTools_startsWith(r24,r27);
	if( !r31 ) goto label$49d1ec1_7_126;
	r24 = r23->name;
	if( r24 == NULL ) hl_null_access();
	r28 = 2;
	r2 = NULL;
	r24 = String_substring(r24,r28,r2);
	r2 = Std_parseInt(r24);
	r28 = r2 ? r2->v.i : 0;
	r23->regIndex = r28;
	r7 = r0->__context;
	if( r7 == NULL ) hl_null_access();
	r32 = r7->__vertexConstants;
	r23->regData = r32;
	if( r8 == NULL ) hl_null_access();
	haxe_ds_List_add(r8,((vdynamic*)r23));
	goto label$49d1ec1_7_238;
	label$49d1ec1_7_126:
	r24 = r23->name;
	r27 = (String)s$fc;
	r31 = StringTools_startsWith(r24,r27);
	if( !r31 ) goto label$49d1ec1_7_145;
	r24 = r23->name;
	if( r24 == NULL ) hl_null_access();
	r28 = 2;
	r2 = NULL;
	r24 = String_substring(r24,r28,r2);
	r2 = Std_parseInt(r24);
	r28 = r2 ? r2->v.i : 0;
	r23->regIndex = r28;
	r7 = r0->__context;
	if( r7 == NULL ) hl_null_access();
	r32 = r7->__fragmentConstants;
	r23->regData = r32;
	if( r15 == NULL ) hl_null_access();
	haxe_ds_List_add(r15,((vdynamic*)r23));
	goto label$49d1ec1_7_238;
	label$49d1ec1_7_145:
	r24 = r23->name;
	r27 = (String)s$sampler;
	r31 = StringTools_startsWith(r24,r27);
	if( !r31 ) goto label$49d1ec1_7_183;
	r24 = r23->name;
	if( r24 == NULL ) hl_null_access();
	r27 = (String)s$alpha;
	r2 = NULL;
	r28 = String_indexOf(r24,r27,r2);
	r29 = -1;
	if( r28 != r29 ) goto label$49d1ec1_7_183;
	r24 = r23->name;
	if( r24 == NULL ) hl_null_access();
	r28 = 7;
	r2 = NULL;
	r24 = String_substring(r24,r28,r2);
	r2 = Std_parseInt(r24);
	r28 = r2 ? r2->v.i : 0;
	r23->regIndex = r28;
	r30 = r0->__agalSamplerUniforms;
	if( r30 == NULL ) hl_null_access();
	haxe_ds_List_add(r30,((vdynamic*)r23));
	r28 = 0;
	r29 = r23->regCount;
	label$49d1ec1_7_169:
	if( r28 >= r29 ) goto label$49d1ec1_7_182;
	r33 = r28;
	++r28;
	r34 = r0->__agalSamplerUsageMask;
	r35 = 1;
	if( r23 == NULL ) hl_null_access();
	r36 = r23->regIndex;
	r36 = r36 + r33;
	r35 = r35 << r36;
	r34 = r34 | r35;
	r0->__agalSamplerUsageMask = r34;
	goto label$49d1ec1_7_169;
	label$49d1ec1_7_182:
	goto label$49d1ec1_7_238;
	label$49d1ec1_7_183:
	r24 = r23->name;
	r27 = (String)s$sampler;
	r31 = StringTools_startsWith(r24,r27);
	if( !r31 ) goto label$49d1ec1_7_214;
	r24 = r23->name;
	r27 = (String)s$_alpha;
	r31 = StringTools_endsWith(r24,r27);
	if( !r31 ) goto label$49d1ec1_7_214;
	r24 = r23->name;
	if( r24 == NULL ) hl_null_access();
	r27 = (String)s$b14a7b8;
	r2 = NULL;
	r28 = String_indexOf(r24,r27,r2);
	r29 = 7;
	r28 = r28 - r29;
	r24 = r23->name;
	if( r24 == NULL ) hl_null_access();
	r29 = 7;
	r33 = 7;
	r33 = r33 + r28;
	r2 = hl_alloc_dynamic(&t$_i32);
	r2->v.i = r33;
	r24 = String_substring(r24,r29,r2);
	r2 = Std_parseInt(r24);
	r29 = r2 ? r2->v.i : 0;
	r33 = 4;
	r29 = r29 + r33;
	r23->regIndex = r29;
	r30 = r0->__agalAlphaSamplerUniforms;
	if( r30 == NULL ) hl_null_access();
	haxe_ds_List_add(r30,((vdynamic*)r23));
	goto label$49d1ec1_7_238;
	label$49d1ec1_7_214:
	r24 = r23->name;
	r27 = (String)s$sampler;
	r31 = StringTools_startsWith(r24,r27);
	if( !r31 ) goto label$49d1ec1_7_238;
	r24 = r23->name;
	r27 = (String)s$_alphaEnabled;
	r31 = StringTools_endsWith(r24,r27);
	if( !r31 ) goto label$49d1ec1_7_238;
	r24 = r23->name;
	if( r24 == NULL ) hl_null_access();
	r28 = 7;
	r2 = NULL;
	r24 = String_substring(r24,r28,r2);
	r2 = Std_parseInt(r24);
	r28 = r2 ? r2->v.i : 0;
	r23->regIndex = r28;
	r9 = r0->__agalAlphaSamplerEnabled;
	if( r9 == NULL ) hl_null_access();
	r28 = r23->regIndex;
	r29 = r9->length;
	if( ((unsigned)r28) < ((unsigned)r29) ) goto label$49d1ec1_7_236;
	hl_types_ArrayObj___expand(r9,r28);
	label$49d1ec1_7_236:
	r10 = r9->array;
	((openfl__display3D__Uniform*)(r10 + 1))[r28] = r23;
	label$49d1ec1_7_238:
	r37 = (lime__utils__$Log)g$_lime_utils_Log;
	r28 = r37->level;
	r29 = 5;
	if( r28 != r29 ) goto label$49d1ec1_7_285;
	r24 = (String)s$;
	r28 = r17;
	r38 = &r28;
	r39 = hl_itos(r28,r38);
	r27 = String___alloc__(r39,r28);
	r24 = String___add__(r24,r27);
	r27 = (String)s$233e6b4;
	r24 = String___add__(r24,r27);
	if( r23 == NULL ) hl_null_access();
	r27 = r23->name;
	r24 = String___add__(r24,r27);
	r27 = (String)s$_type_;
	r24 = String___add__(r24,r27);
	r28 = r23->type;
	r38 = &r28;
	r39 = hl_itos(r28,r38);
	r27 = String___alloc__(r39,r28);
	r24 = String___add__(r24,r27);
	r27 = (String)s$_size_;
	r24 = String___add__(r24,r27);
	r28 = r23->size;
	r38 = &r28;
	r39 = hl_itos(r28,r38);
	r27 = String___alloc__(r39,r28);
	r24 = String___add__(r24,r27);
	r27 = (String)s$_location_;
	r24 = String___add__(r24,r27);
	r28 = r23->location;
	r38 = &r28;
	r39 = hl_itos(r28,r38);
	r27 = String___alloc__(r39,r28);
	r24 = String___add__(r24,r27);
	r40 = hl_alloc_virtual(&t$vrt_329ffa8);
	r27 = (String)s$openfl_display3D_Program3D_hx;
	if( hl_vfields(r40)[1] ) *(String*)(hl_vfields(r40)[1]) = (String)r27; else hl_dyn_setp(r40->value,37969014/*fileName*/,&t$String,r27);
	r28 = 577;
	if( hl_vfields(r40)[2] ) *(int*)(hl_vfields(r40)[2]) = (int)r28; else hl_dyn_seti(r40->value,371360620/*lineNumber*/,&t$_i32,r28);
	r27 = (String)s$openfl_display3D_Program3D;
	if( hl_vfields(r40)[0] ) *(String*)(hl_vfields(r40)[0]) = (String)r27; else hl_dyn_setp(r40->value,-63073762/*className*/,&t$String,r27);
	r27 = (String)s$__buildAGALUniformList;
	if( hl_vfields(r40)[3] ) *(String*)(hl_vfields(r40)[3]) = (String)r27; else hl_dyn_setp(r40->value,302979532/*methodName*/,&t$String,r27);
	r41 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r40);
	lime_utils_Log_verbose(((vdynamic*)r24),r41);
	label$49d1ec1_7_285:
	goto label$49d1ec1_7_39;
	label$49d1ec1_7_286:
	r42 = (openfl__display3D__UniformMap)hl_alloc_obj(&t$openfl_display3D_UniformMap);
	r44 = hl_to_virtual(&t$vrt_c8138d1,(vdynamic*)r8);
	r43 = Lambda_array(r44);
	r9 = (hl__types__ArrayObj)hl_dyn_castp(&r43,&t$hl_types_ArrayDyn,&t$hl_types_ArrayObj);
	openfl_display3D_UniformMap_new(r42,r9);
	r0->__agalVertexUniformMap = r42;
	r42 = (openfl__display3D__UniformMap)hl_alloc_obj(&t$openfl_display3D_UniformMap);
	r44 = hl_to_virtual(&t$vrt_c8138d1,(vdynamic*)r15);
	r43 = Lambda_array(r44);
	r9 = (hl__types__ArrayObj)hl_dyn_castp(&r43,&t$hl_types_ArrayDyn,&t$hl_types_ArrayObj);
	openfl_display3D_UniformMap_new(r42,r9);
	r0->__agalFragmentUniformMap = r42;
	return;
}

void openfl_display3D_Program3D___deleteShaders(openfl__display3D__Program3D r0) {
	openfl__display3D__Context3D r2;
	lime___internal__backend__native__NativeOpenGLRenderContext r1;
	lime__graphics__opengl__GLObject r4;
	vclosure *r5;
	r2 = r0->__context;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->gl;
	r4 = r0->__glProgram;
	if( !r4 ) goto label$49d1ec1_8_7;
	r4 = NULL;
	r0->__glProgram = r4;
	label$49d1ec1_8_7:
	r4 = r0->__glVertexShader;
	if( !r4 ) goto label$49d1ec1_8_16;
	if( r1 == NULL ) hl_null_access();
	r5 = (vclosure*)hl_dyn_getp((vdynamic*)r1,-474422239/*deleteShader*/,&t$fun_9a74d20);
	if( r5 == NULL ) hl_null_access();
	r4 = r0->__glVertexShader;
	r5->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject))r5->fun)((vdynamic*)r5->value,r4) : ((void (*)(lime__graphics__opengl__GLObject))r5->fun)(r4);
	r4 = NULL;
	r0->__glVertexShader = r4;
	label$49d1ec1_8_16:
	r4 = r0->__glFragmentShader;
	if( !r4 ) goto label$49d1ec1_8_25;
	if( r1 == NULL ) hl_null_access();
	r5 = (vclosure*)hl_dyn_getp((vdynamic*)r1,-474422239/*deleteShader*/,&t$fun_9a74d20);
	if( r5 == NULL ) hl_null_access();
	r4 = r0->__glFragmentShader;
	r5->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject))r5->fun)((vdynamic*)r5->value,r4) : ((void (*)(lime__graphics__opengl__GLObject))r5->fun)(r4);
	r4 = NULL;
	r0->__glFragmentShader = r4;
	label$49d1ec1_8_25:
	return;
}

void openfl_display3D_Program3D___disable(openfl__display3D__Program3D r0) {
	bool r1;
	vdynamic *r2, *r4;
	int r3;
	r2 = r0->__format;
	r3 = 1;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r3;
	if( r2 == r4 || (r2 && r4 && (r2->v.i == r4->v.i)) ) goto label$49d1ec1_9_6;
	r1 = false;
	goto label$49d1ec1_9_7;
	label$49d1ec1_9_6:
	r1 = true;
	label$49d1ec1_9_7:
	return;
}

void openfl_display3D_Program3D___enable(openfl__display3D__Program3D r0) {
	String r18;
	openfl__display3D__Uniform r14;
	openfl__display3D__Context3D r2;
	openfl__display3D__UniformMap r9;
	openfl__errors__IllegalOperationError r17;
	lime___internal__backend__native__NativeOpenGLRenderContext r1;
	lime__graphics__opengl__GLObject r5;
	haxe__ds__List r11;
	vclosure *r4, *r16;
	haxe__ds___List__ListNode r10, r12;
	vdynamic *r6, *r8, *r13;
	int r7, r15;
	r2 = r0->__context;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->gl;
	if( r1 == NULL ) hl_null_access();
	r4 = (vclosure*)hl_dyn_getp((vdynamic*)r1,-156472067/*useProgram*/,&t$fun_9a74d20);
	if( r4 == NULL ) hl_null_access();
	r5 = r0->__glProgram;
	r4->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject))r4->fun)((vdynamic*)r4->value,r5) : ((void (*)(lime__graphics__opengl__GLObject))r4->fun)(r5);
	r6 = r0->__format;
	r7 = 0;
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r7;
	if( r6 != r8 && (!r6 || !r8 || (r6->v.i != r8->v.i)) ) goto label$49d1ec1_10_70;
	r9 = r0->__agalVertexUniformMap;
	if( r9 == NULL ) hl_null_access();
	openfl_display3D_UniformMap_markAllDirty(r9);
	r9 = r0->__agalFragmentUniformMap;
	if( r9 == NULL ) hl_null_access();
	openfl_display3D_UniformMap_markAllDirty(r9);
	r11 = r0->__agalSamplerUniforms;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->h;
	label$49d1ec1_10_21:
	if( !r10 ) goto label$49d1ec1_10_44;
	if( r10 == NULL ) hl_null_access();
	r13 = r10->item;
	r14 = (openfl__display3D__Uniform)r13;
	r12 = r10->next;
	r10 = r12;
	if( r14 == NULL ) hl_null_access();
	r7 = r14->regCount;
	r15 = 1;
	if( r7 != r15 ) goto label$49d1ec1_10_39;
	if( r1 == NULL ) hl_null_access();
	r16 = (vclosure*)hl_dyn_getp((vdynamic*)r1,131998028/*uniform1i*/,&t$fun_efca04c);
	if( r16 == NULL ) hl_null_access();
	r7 = r14->location;
	r15 = r14->regIndex;
	r16->hasValue ? ((void (*)(vdynamic*,int,int))r16->fun)((vdynamic*)r16->value,r7,r15) : ((void (*)(int,int))r16->fun)(r7,r15);
	goto label$49d1ec1_10_43;
	label$49d1ec1_10_39:
	r17 = (openfl__errors__IllegalOperationError)hl_alloc_obj(&t$openfl_errors_IllegalOperationError);
	r18 = (String)s$147a76a;
	openfl_errors_IllegalOperationError_new(r17,r18);
	hl_throw((vdynamic*)r17);
	label$49d1ec1_10_43:
	goto label$49d1ec1_10_21;
	label$49d1ec1_10_44:
	r11 = r0->__agalAlphaSamplerUniforms;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->h;
	label$49d1ec1_10_47:
	if( !r10 ) goto label$49d1ec1_10_70;
	if( r10 == NULL ) hl_null_access();
	r13 = r10->item;
	r14 = (openfl__display3D__Uniform)r13;
	r12 = r10->next;
	r10 = r12;
	if( r14 == NULL ) hl_null_access();
	r7 = r14->regCount;
	r15 = 1;
	if( r7 != r15 ) goto label$49d1ec1_10_65;
	if( r1 == NULL ) hl_null_access();
	r16 = (vclosure*)hl_dyn_getp((vdynamic*)r1,131998028/*uniform1i*/,&t$fun_efca04c);
	if( r16 == NULL ) hl_null_access();
	r7 = r14->location;
	r15 = r14->regIndex;
	r16->hasValue ? ((void (*)(vdynamic*,int,int))r16->fun)((vdynamic*)r16->value,r7,r15) : ((void (*)(int,int))r16->fun)(r7,r15);
	goto label$49d1ec1_10_69;
	label$49d1ec1_10_65:
	r17 = (openfl__errors__IllegalOperationError)hl_alloc_obj(&t$openfl_errors_IllegalOperationError);
	r18 = (String)s$147a76a;
	openfl_errors_IllegalOperationError_new(r17,r18);
	hl_throw((vdynamic*)r17);
	label$49d1ec1_10_69:
	goto label$49d1ec1_10_47;
	label$49d1ec1_10_70:
	return;
}

void openfl_display3D_Program3D___flush(openfl__display3D__Program3D r0) {
	openfl__display3D__UniformMap r5;
	vdynamic *r2, *r4;
	int r3;
	r2 = r0->__format;
	r3 = 0;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r3;
	if( r2 != r4 && (!r2 || !r4 || (r2->v.i != r4->v.i)) ) goto label$49d1ec1_11_11;
	r5 = r0->__agalVertexUniformMap;
	if( r5 == NULL ) hl_null_access();
	openfl_display3D_UniformMap_flush(r5);
	r5 = r0->__agalFragmentUniformMap;
	if( r5 == NULL ) hl_null_access();
	openfl_display3D_UniformMap_flush(r5);
	goto label$49d1ec1_11_12;
	label$49d1ec1_11_11:
	return;
	label$49d1ec1_11_12:
	return;
}

openfl__display___internal__SamplerState openfl_display3D_Program3D___getSamplerState(openfl__display3D__Program3D r0,int r1) {
	hl__types__ArrayObj r2;
	openfl__display___internal__SamplerState r4;
	vdynamic *r5;
	varray *r6;
	int r3;
	r2 = r0->__samplerStates;
	if( r2 == NULL ) hl_null_access();
	r3 = r2->length;
	if( ((unsigned)r1) < ((unsigned)r3) ) goto label$49d1ec1_12_6;
	r4 = NULL;
	goto label$49d1ec1_12_9;
	label$49d1ec1_12_6:
	r6 = r2->array;
	r5 = ((vdynamic**)(r6 + 1))[r1];
	r4 = (openfl__display___internal__SamplerState)r5;
	label$49d1ec1_12_9:
	return r4;
}

void openfl_display3D_Program3D___markDirty(openfl__display3D__Program3D r0,bool r1,int r2,int r3) {
	openfl__display3D__UniformMap r8;
	vdynamic *r5, *r7;
	int r6;
	r5 = r0->__format;
	r6 = 1;
	r7 = hl_alloc_dynamic(&t$_i32);
	r7->v.i = r6;
	if( r5 != r7 && (!r5 || !r7 || (r5->v.i != r7->v.i)) ) goto label$49d1ec1_13_5;
	return;
	label$49d1ec1_13_5:
	if( !r1 ) goto label$49d1ec1_13_10;
	r8 = r0->__agalVertexUniformMap;
	if( r8 == NULL ) hl_null_access();
	openfl_display3D_UniformMap_markDirty(r8,r2,r3);
	goto label$49d1ec1_13_13;
	label$49d1ec1_13_10:
	r8 = r0->__agalFragmentUniformMap;
	if( r8 == NULL ) hl_null_access();
	openfl_display3D_UniformMap_markDirty(r8,r2,r3);
	label$49d1ec1_13_13:
	return;
}

void openfl_display3D_Program3D___processGLSLData(openfl__display3D__Program3D r0,String r1,String r2) {
	String r5, r6, r12, r13;
	vvirtual *r19;
	hl__types__ArrayObj r14;
	bool r9;
	EReg r7, r8;
	vdynamic *r18;
	int *r11;
	vbyte *r16, *r17;
	int r3, r10, r15;
	r3 = 0;
	r6 = (String)s$uniform;
	if( r2 != r6 && (!r2 || !r6 || String___compare(r2,(vdynamic*)r6) != 0) ) goto label$49d1ec1_14_9;
	r8 = (EReg)hl_alloc_obj(&t$EReg);
	r5 = (String)s$248fba9;
	r6 = (String)s$;
	EReg_new(r8,r5,r6);
	r7 = r8;
	goto label$49d1ec1_14_14;
	label$49d1ec1_14_9:
	r8 = (EReg)hl_alloc_obj(&t$EReg);
	r5 = (String)s$6030fbd;
	r6 = (String)s$;
	EReg_new(r8,r5,r6);
	r7 = r8;
	label$49d1ec1_14_14:
	if( r7 == NULL ) hl_null_access();
	r11 = NULL;
	r9 = EReg_matchSub(r7,r1,r3,r11);
	if( !r9 ) goto label$49d1ec1_14_410;
	r10 = 1;
	r6 = EReg_matched(r7,r10);
	r5 = r6;
	r10 = 2;
	r12 = EReg_matched(r7,r10);
	r6 = r12;
	r13 = (String)s$gl_;
	r9 = StringTools_startsWith(r12,r13);
	if( !r9 ) goto label$49d1ec1_14_29;
	goto label$49d1ec1_14_14;
	label$49d1ec1_14_29:
	r13 = (String)s$sampler;
	r9 = StringTools_startsWith(r5,r13);
	if( !r9 ) goto label$49d1ec1_14_36;
	r14 = r0->__glslSamplerNames;
	if( r14 == NULL ) hl_null_access();
	r10 = hl_types_ArrayObj_push(r14,((vdynamic*)r6));
	goto label$49d1ec1_14_403;
	label$49d1ec1_14_36:
	if( !r5 ) goto label$49d1ec1_14_45;
	r10 = r5->length;
	r15 = 4;
	if( r10 != r15 ) goto label$49d1ec1_14_45;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("bool");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_326;
	label$49d1ec1_14_45:
	if( !r5 ) goto label$49d1ec1_14_54;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_54;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("bvec2");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_329;
	label$49d1ec1_14_54:
	if( !r5 ) goto label$49d1ec1_14_63;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_63;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("bvec3");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_332;
	label$49d1ec1_14_63:
	if( !r5 ) goto label$49d1ec1_14_72;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_72;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("bvec4");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_335;
	label$49d1ec1_14_72:
	if( !r5 ) goto label$49d1ec1_14_81;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_81;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("dvec2");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_338;
	label$49d1ec1_14_81:
	if( !r5 ) goto label$49d1ec1_14_90;
	r10 = r5->length;
	r15 = 4;
	if( r10 != r15 ) goto label$49d1ec1_14_90;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("vec2");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_338;
	label$49d1ec1_14_90:
	if( !r5 ) goto label$49d1ec1_14_99;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_99;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("dvec3");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_341;
	label$49d1ec1_14_99:
	if( !r5 ) goto label$49d1ec1_14_108;
	r10 = r5->length;
	r15 = 4;
	if( r10 != r15 ) goto label$49d1ec1_14_108;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("vec3");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_341;
	label$49d1ec1_14_108:
	if( !r5 ) goto label$49d1ec1_14_117;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_117;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("dvec4");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_344;
	label$49d1ec1_14_117:
	if( !r5 ) goto label$49d1ec1_14_126;
	r10 = r5->length;
	r15 = 4;
	if( r10 != r15 ) goto label$49d1ec1_14_126;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("vec4");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_344;
	label$49d1ec1_14_126:
	if( !r5 ) goto label$49d1ec1_14_135;
	r10 = r5->length;
	r15 = 6;
	if( r10 != r15 ) goto label$49d1ec1_14_135;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("double");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_347;
	label$49d1ec1_14_135:
	if( !r5 ) goto label$49d1ec1_14_144;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_144;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("float");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_347;
	label$49d1ec1_14_144:
	if( !r5 ) goto label$49d1ec1_14_153;
	r10 = r5->length;
	r15 = 4;
	if( r10 != r15 ) goto label$49d1ec1_14_153;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat2");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_350;
	label$49d1ec1_14_153:
	if( !r5 ) goto label$49d1ec1_14_162;
	r10 = r5->length;
	r15 = 6;
	if( r10 != r15 ) goto label$49d1ec1_14_162;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat2x2");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_350;
	label$49d1ec1_14_162:
	if( !r5 ) goto label$49d1ec1_14_171;
	r10 = r5->length;
	r15 = 6;
	if( r10 != r15 ) goto label$49d1ec1_14_171;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat2x3");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_353;
	label$49d1ec1_14_171:
	if( !r5 ) goto label$49d1ec1_14_180;
	r10 = r5->length;
	r15 = 6;
	if( r10 != r15 ) goto label$49d1ec1_14_180;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat2x4");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_356;
	label$49d1ec1_14_180:
	if( !r5 ) goto label$49d1ec1_14_189;
	r10 = r5->length;
	r15 = 6;
	if( r10 != r15 ) goto label$49d1ec1_14_189;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat3x2");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_359;
	label$49d1ec1_14_189:
	if( !r5 ) goto label$49d1ec1_14_198;
	r10 = r5->length;
	r15 = 4;
	if( r10 != r15 ) goto label$49d1ec1_14_198;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat3");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_362;
	label$49d1ec1_14_198:
	if( !r5 ) goto label$49d1ec1_14_207;
	r10 = r5->length;
	r15 = 6;
	if( r10 != r15 ) goto label$49d1ec1_14_207;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat3x3");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_362;
	label$49d1ec1_14_207:
	if( !r5 ) goto label$49d1ec1_14_216;
	r10 = r5->length;
	r15 = 6;
	if( r10 != r15 ) goto label$49d1ec1_14_216;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat3x4");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_365;
	label$49d1ec1_14_216:
	if( !r5 ) goto label$49d1ec1_14_225;
	r10 = r5->length;
	r15 = 6;
	if( r10 != r15 ) goto label$49d1ec1_14_225;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat4x2");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_368;
	label$49d1ec1_14_225:
	if( !r5 ) goto label$49d1ec1_14_234;
	r10 = r5->length;
	r15 = 6;
	if( r10 != r15 ) goto label$49d1ec1_14_234;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat4x3");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_371;
	label$49d1ec1_14_234:
	if( !r5 ) goto label$49d1ec1_14_243;
	r10 = r5->length;
	r15 = 4;
	if( r10 != r15 ) goto label$49d1ec1_14_243;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat4");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_374;
	label$49d1ec1_14_243:
	if( !r5 ) goto label$49d1ec1_14_252;
	r10 = r5->length;
	r15 = 6;
	if( r10 != r15 ) goto label$49d1ec1_14_252;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("mat4x4");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_374;
	label$49d1ec1_14_252:
	if( !r5 ) goto label$49d1ec1_14_261;
	r10 = r5->length;
	r15 = 3;
	if( r10 != r15 ) goto label$49d1ec1_14_261;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("int");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_377;
	label$49d1ec1_14_261:
	if( !r5 ) goto label$49d1ec1_14_270;
	r10 = r5->length;
	r15 = 4;
	if( r10 != r15 ) goto label$49d1ec1_14_270;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("uint");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_377;
	label$49d1ec1_14_270:
	if( !r5 ) goto label$49d1ec1_14_279;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_279;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("ivec2");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_380;
	label$49d1ec1_14_279:
	if( !r5 ) goto label$49d1ec1_14_288;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_288;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("uvec2");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_380;
	label$49d1ec1_14_288:
	if( !r5 ) goto label$49d1ec1_14_297;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_297;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("ivec3");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_383;
	label$49d1ec1_14_297:
	if( !r5 ) goto label$49d1ec1_14_306;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_306;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("uvec3");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_383;
	label$49d1ec1_14_306:
	if( !r5 ) goto label$49d1ec1_14_315;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_315;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("ivec4");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_386;
	label$49d1ec1_14_315:
	if( !r5 ) goto label$49d1ec1_14_324;
	r10 = r5->length;
	r15 = 5;
	if( r10 != r15 ) goto label$49d1ec1_14_324;
	r16 = r5->bytes;
	r17 = (vbyte*)USTR("uvec4");
	r10 = hl_string_compare(r16,r17,r10);
	r15 = 0;
	if( r10 == r15 ) goto label$49d1ec1_14_386;
	label$49d1ec1_14_324:
	r18 = NULL;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_326:
	r10 = 0;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_329:
	r10 = 1;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_332:
	r10 = 2;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_335:
	r10 = 3;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_338:
	r10 = 5;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_341:
	r10 = 6;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_344:
	r10 = 7;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_347:
	r10 = 4;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_350:
	r10 = 12;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_353:
	r10 = 13;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_356:
	r10 = 14;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_359:
	r10 = 15;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_362:
	r10 = 16;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_365:
	r10 = 17;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_368:
	r10 = 18;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_371:
	r10 = 19;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_374:
	r10 = 20;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_377:
	r10 = 8;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_380:
	r10 = 9;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_383:
	r10 = 10;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	goto label$49d1ec1_14_388;
	label$49d1ec1_14_386:
	r10 = 11;
	r18 = hl_alloc_dynamic(&t$_i32);
	r18->v.i = r10;
	label$49d1ec1_14_388:
	r13 = (String)s$uniform;
	if( r2 != r13 && (!r2 || !r13 || String___compare(r2,(vdynamic*)r13) != 0) ) goto label$49d1ec1_14_397;
	r14 = r0->__glslUniformNames;
	if( r14 == NULL ) hl_null_access();
	r10 = hl_types_ArrayObj_push(r14,((vdynamic*)r6));
	r14 = r0->__glslUniformTypes;
	if( r14 == NULL ) hl_null_access();
	r10 = hl_types_ArrayObj_push(r14,((vdynamic*)r18));
	goto label$49d1ec1_14_403;
	label$49d1ec1_14_397:
	r14 = r0->__glslAttribNames;
	if( r14 == NULL ) hl_null_access();
	r10 = hl_types_ArrayObj_push(r14,((vdynamic*)r6));
	r14 = r0->__glslAttribTypes;
	if( r14 == NULL ) hl_null_access();
	r10 = hl_types_ArrayObj_push(r14,((vdynamic*)r18));
	label$49d1ec1_14_403:
	r19 = EReg_matchedPos(r7);
	if( r19 == NULL ) hl_null_access();
	r10 = hl_vfields(r19)[1] ? (*(int*)(hl_vfields(r19)[1])) : (int)hl_dyn_geti(r19->value,5594516/*pos*/,&t$_i32);
	r15 = hl_vfields(r19)[0] ? (*(int*)(hl_vfields(r19)[0])) : (int)hl_dyn_geti(r19->value,5393365/*len*/,&t$_i32);
	r10 = r10 + r15;
	r3 = r10;
	goto label$49d1ec1_14_14;
	label$49d1ec1_14_410:
	return;
}

void openfl_display3D_Program3D___setPositionScale(openfl__display3D__Program3D r0,lime__utils__ArrayBufferView r1) {
	openfl__display3D__Uniform r6;
	openfl__display3D__Context3D r8;
	lime___internal__backend__native__NativeOpenGLRenderContext r7;
	double r12;
	vclosure *r9;
	vdynamic *r3, *r5;
	int r4, r10, r11;
	r3 = r0->__format;
	r4 = 1;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r4;
	if( r3 != r5 && (!r3 || !r5 || (r3->v.i != r5->v.i)) ) goto label$49d1ec1_15_5;
	return;
	label$49d1ec1_15_5:
	r6 = r0->__agalPositionScale;
	if( !r6 ) goto label$49d1ec1_15_25;
	r8 = r0->__context;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->gl;
	if( r7 == NULL ) hl_null_access();
	r9 = (vclosure*)hl_dyn_getp((vdynamic*)r7,-92191413/*uniform4fv*/,&t$fun_589d191);
	if( r9 == NULL ) hl_null_access();
	r6 = r0->__agalPositionScale;
	if( r6 == NULL ) hl_null_access();
	r4 = r6->location;
	if( !r1 ) goto label$49d1ec1_15_22;
	if( r1 == NULL ) hl_null_access();
	r10 = r1->length;
	r11 = 2;
	r10 = r10 >> r11;
	goto label$49d1ec1_15_23;
	label$49d1ec1_15_22:
	r10 = 0;
	label$49d1ec1_15_23:
	r12 = lime_utils__DataPointer_DataPointer_Impl__fromArrayBufferView(r1);
	r9->hasValue ? ((void (*)(vdynamic*,int,int,double))r9->fun)((vdynamic*)r9->value,r4,r10,r12) : ((void (*)(int,int,double))r9->fun)(r4,r10,r12);
	label$49d1ec1_15_25:
	return;
}

void openfl_display3D_Program3D___setSamplerState(openfl__display3D__Program3D r0,int r1,openfl__display___internal__SamplerState r2) {
	hl__types__ArrayObj r3;
	varray *r6;
	int r4;
	r3 = r0->__samplerStates;
	if( r3 == NULL ) hl_null_access();
	r4 = r3->length;
	if( ((unsigned)r1) < ((unsigned)r4) ) goto label$49d1ec1_16_5;
	hl_types_ArrayObj___expand(r3,r1);
	label$49d1ec1_16_5:
	r6 = r3->array;
	((openfl__display___internal__SamplerState*)(r6 + 1))[r1] = r2;
	return;
}

void openfl_display3D_Program3D___uploadFromGLSL(openfl__display3D__Program3D r0,String r1,String r2) {
	String r6, r16, r17, r18;
	hl__types__ArrayObj r31;
	vvirtual *r20, *r21;
	openfl__display3D__Context3D r4;
	bool r33;
	lime___internal__backend__native__NativeOpenGLRenderContext r3;
	lime__graphics__opengl__GLObject r7, r35;
	double r14, r15;
	vclosure *r8, *r10, *r11, *r13, *r19, *r22, *r30, *r34;
	int *r27;
	vdynamic *r12, *r23, *r24;
	varray *r32;
	vbyte *r28;
	int r9, r25, r26, r29;
	r4 = r0->__context;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->gl;
	r0->__glVertexSource = r1;
	r0->__glFragmentSource = r2;
	if( r3 == NULL ) hl_null_access();
	r8 = (vclosure*)hl_dyn_getp((vdynamic*)r3,527826886/*createShader*/,&t$fun_e4463cb);
	if( r8 == NULL ) hl_null_access();
	r9 = r3->VERTEX_SHADER;
	r7 = r8->hasValue ? ((lime__graphics__opengl__GLObject (*)(vdynamic*,int))r8->fun)((vdynamic*)r8->value,r9) : ((lime__graphics__opengl__GLObject (*)(int))r8->fun)(r9);
	r0->__glVertexShader = r7;
	r10 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-501592874/*shaderSource*/,&t$fun_938098a);
	if( r10 == NULL ) hl_null_access();
	r7 = r0->__glVertexShader;
	r10->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject,String))r10->fun)((vdynamic*)r10->value,r7,r1) : ((void (*)(lime__graphics__opengl__GLObject,String))r10->fun)(r7,r1);
	r11 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-88969101/*compileShader*/,&t$fun_9a74d20);
	if( r11 == NULL ) hl_null_access();
	r7 = r0->__glVertexShader;
	r11->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject))r11->fun)((vdynamic*)r11->value,r7) : ((void (*)(lime__graphics__opengl__GLObject))r11->fun)(r7);
	r13 = (vclosure*)hl_dyn_getp((vdynamic*)r3,375089747/*getShaderParameter*/,&t$fun_90c71d8);
	if( r13 == NULL ) hl_null_access();
	r7 = r0->__glVertexShader;
	r9 = r3->COMPILE_STATUS;
	r12 = r13->hasValue ? ((vdynamic* (*)(vdynamic*,lime__graphics__opengl__GLObject,int))r13->fun)((vdynamic*)r13->value,r7,r9) : ((vdynamic* (*)(lime__graphics__opengl__GLObject,int))r13->fun)(r7,r9);
	r14 = (double)hl_dyn_castd(&r12,&t$_dyn);
	r15 = 0.;
	if( r14 != r15 ) goto label$49d1ec1_17_49;
	r6 = (String)s$Error_compiling_vertex_shader;
	r17 = (String)s$68b329d;
	r19 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-204948069/*getShaderInfoLog*/,&t$fun_716c0c7);
	if( r19 == NULL ) hl_null_access();
	r7 = r0->__glVertexShader;
	r18 = r19->hasValue ? ((String (*)(vdynamic*,lime__graphics__opengl__GLObject))r19->fun)((vdynamic*)r19->value,r7) : ((String (*)(lime__graphics__opengl__GLObject))r19->fun)(r7);
	r17 = String___add__(r17,r18);
	r16 = String___add__(r6,r17);
	r17 = (String)s$68b329d;
	r17 = String___add__(r17,r1);
	r16 = String___add__(r16,r17);
	r20 = hl_alloc_virtual(&t$vrt_329ffa8);
	r17 = (String)s$openfl_display3D_Program3D_hx;
	if( hl_vfields(r20)[1] ) *(String*)(hl_vfields(r20)[1]) = (String)r17; else hl_dyn_setp(r20->value,37969014/*fileName*/,&t$String,r17);
	r9 = 869;
	if( hl_vfields(r20)[2] ) *(int*)(hl_vfields(r20)[2]) = (int)r9; else hl_dyn_seti(r20->value,371360620/*lineNumber*/,&t$_i32,r9);
	r17 = (String)s$openfl_display3D_Program3D;
	if( hl_vfields(r20)[0] ) *(String*)(hl_vfields(r20)[0]) = (String)r17; else hl_dyn_setp(r20->value,-63073762/*className*/,&t$String,r17);
	r17 = (String)s$__uploadFromGLSL;
	if( hl_vfields(r20)[3] ) *(String*)(hl_vfields(r20)[3]) = (String)r17; else hl_dyn_setp(r20->value,302979532/*methodName*/,&t$String,r17);
	r21 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r20);
	lime_utils_Log_error(((vdynamic*)r16),r21);
	label$49d1ec1_17_49:
	r8 = (vclosure*)hl_dyn_getp((vdynamic*)r3,527826886/*createShader*/,&t$fun_e4463cb);
	if( r8 == NULL ) hl_null_access();
	r9 = r3->FRAGMENT_SHADER;
	r7 = r8->hasValue ? ((lime__graphics__opengl__GLObject (*)(vdynamic*,int))r8->fun)((vdynamic*)r8->value,r9) : ((lime__graphics__opengl__GLObject (*)(int))r8->fun)(r9);
	r0->__glFragmentShader = r7;
	r10 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-501592874/*shaderSource*/,&t$fun_938098a);
	if( r10 == NULL ) hl_null_access();
	r7 = r0->__glFragmentShader;
	r10->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject,String))r10->fun)((vdynamic*)r10->value,r7,r2) : ((void (*)(lime__graphics__opengl__GLObject,String))r10->fun)(r7,r2);
	r11 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-88969101/*compileShader*/,&t$fun_9a74d20);
	if( r11 == NULL ) hl_null_access();
	r7 = r0->__glFragmentShader;
	r11->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject))r11->fun)((vdynamic*)r11->value,r7) : ((void (*)(lime__graphics__opengl__GLObject))r11->fun)(r7);
	r13 = (vclosure*)hl_dyn_getp((vdynamic*)r3,375089747/*getShaderParameter*/,&t$fun_90c71d8);
	if( r13 == NULL ) hl_null_access();
	r7 = r0->__glFragmentShader;
	r9 = r3->COMPILE_STATUS;
	r12 = r13->hasValue ? ((vdynamic* (*)(vdynamic*,lime__graphics__opengl__GLObject,int))r13->fun)((vdynamic*)r13->value,r7,r9) : ((vdynamic* (*)(lime__graphics__opengl__GLObject,int))r13->fun)(r7,r9);
	r14 = (double)hl_dyn_castd(&r12,&t$_dyn);
	r15 = 0.;
	if( r14 != r15 ) goto label$49d1ec1_17_92;
	r6 = (String)s$Error_compiling_fragment_shader;
	r17 = (String)s$68b329d;
	r19 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-204948069/*getShaderInfoLog*/,&t$fun_716c0c7);
	if( r19 == NULL ) hl_null_access();
	r7 = r0->__glFragmentShader;
	r18 = r19->hasValue ? ((String (*)(vdynamic*,lime__graphics__opengl__GLObject))r19->fun)((vdynamic*)r19->value,r7) : ((String (*)(lime__graphics__opengl__GLObject))r19->fun)(r7);
	r17 = String___add__(r17,r18);
	r16 = String___add__(r6,r17);
	r17 = (String)s$68b329d;
	r17 = String___add__(r17,r2);
	r16 = String___add__(r16,r17);
	r20 = hl_alloc_virtual(&t$vrt_329ffa8);
	r17 = (String)s$openfl_display3D_Program3D_hx;
	if( hl_vfields(r20)[1] ) *(String*)(hl_vfields(r20)[1]) = (String)r17; else hl_dyn_setp(r20->value,37969014/*fileName*/,&t$String,r17);
	r9 = 881;
	if( hl_vfields(r20)[2] ) *(int*)(hl_vfields(r20)[2]) = (int)r9; else hl_dyn_seti(r20->value,371360620/*lineNumber*/,&t$_i32,r9);
	r17 = (String)s$openfl_display3D_Program3D;
	if( hl_vfields(r20)[0] ) *(String*)(hl_vfields(r20)[0]) = (String)r17; else hl_dyn_setp(r20->value,-63073762/*className*/,&t$String,r17);
	r17 = (String)s$__uploadFromGLSL;
	if( hl_vfields(r20)[3] ) *(String*)(hl_vfields(r20)[3]) = (String)r17; else hl_dyn_setp(r20->value,302979532/*methodName*/,&t$String,r17);
	r21 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r20);
	lime_utils_Log_error(((vdynamic*)r16),r21);
	label$49d1ec1_17_92:
	r22 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-63167901/*createProgram*/,&t$fun_1532d29);
	if( r22 == NULL ) hl_null_access();
	r7 = r22->hasValue ? ((lime__graphics__opengl__GLObject (*)(vdynamic*))r22->fun)((vdynamic*)r22->value) : ((lime__graphics__opengl__GLObject (*)(void))r22->fun)();
	r0->__glProgram = r7;
	r23 = r0->__format;
	r9 = 0;
	r24 = hl_alloc_dynamic(&t$_i32);
	r24->v.i = r9;
	if( r23 != r24 && (!r23 || !r24 || (r23->v.i != r24->v.i)) ) goto label$49d1ec1_17_126;
	r9 = 0;
	label$49d1ec1_17_101:
	r26 = 16;
	if( r9 >= r26 ) goto label$49d1ec1_17_125;
	r25 = r9;
	++r9;
	r6 = (String)s$va;
	r26 = r25;
	r27 = &r26;
	r28 = hl_itos(r26,r27);
	r16 = String___alloc__(r28,r26);
	r6 = String___add__(r6,r16);
	if( r1 == NULL ) hl_null_access();
	r17 = (String)s$7215ee9;
	r17 = String___add__(r17,r6);
	r23 = NULL;
	r26 = String_indexOf(r1,r17,r23);
	r29 = -1;
	if( r26 == r29 ) goto label$49d1ec1_17_124;
	if( r3 == NULL ) hl_null_access();
	r30 = (vclosure*)hl_dyn_getp((vdynamic*)r3,506504764/*bindAttribLocation*/,&t$fun_1cb686b);
	if( r30 == NULL ) hl_null_access();
	r7 = r0->__glProgram;
	r30->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject,int,String))r30->fun)((vdynamic*)r30->value,r7,r25,r6) : ((void (*)(lime__graphics__opengl__GLObject,int,String))r30->fun)(r7,r25,r6);
	label$49d1ec1_17_124:
	goto label$49d1ec1_17_101;
	label$49d1ec1_17_125:
	goto label$49d1ec1_17_157;
	label$49d1ec1_17_126:
	r9 = 0;
	r31 = r0->__glslAttribNames;
	label$49d1ec1_17_128:
	if( r31 == NULL ) hl_null_access();
	r26 = r31->length;
	if( r9 >= r26 ) goto label$49d1ec1_17_157;
	r26 = r31->length;
	if( ((unsigned)r9) < ((unsigned)r26) ) goto label$49d1ec1_17_136;
	r6 = NULL;
	goto label$49d1ec1_17_139;
	label$49d1ec1_17_136:
	r32 = r31->array;
	r12 = ((vdynamic**)(r32 + 1))[r9];
	r6 = (String)r12;
	label$49d1ec1_17_139:
	++r9;
	if( r6 == NULL ) hl_null_access();
	r17 = (String)s$Position;
	r23 = NULL;
	r25 = String_indexOf(r6,r17,r23);
	r26 = -1;
	if( r26 >= r25 ) goto label$49d1ec1_17_156;
	r17 = (String)s$38fd598;
	r33 = StringTools_startsWith(r6,r17);
	if( !r33 ) goto label$49d1ec1_17_156;
	if( r3 == NULL ) hl_null_access();
	r30 = (vclosure*)hl_dyn_getp((vdynamic*)r3,506504764/*bindAttribLocation*/,&t$fun_1cb686b);
	if( r30 == NULL ) hl_null_access();
	r7 = r0->__glProgram;
	r25 = 0;
	r30->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject,int,String))r30->fun)((vdynamic*)r30->value,r7,r25,r6) : ((void (*)(lime__graphics__opengl__GLObject,int,String))r30->fun)(r7,r25,r6);
	goto label$49d1ec1_17_157;
	label$49d1ec1_17_156:
	goto label$49d1ec1_17_128;
	label$49d1ec1_17_157:
	if( r3 == NULL ) hl_null_access();
	r34 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-227029056/*attachShader*/,&t$fun_842af41);
	if( r34 == NULL ) hl_null_access();
	r7 = r0->__glProgram;
	r35 = r0->__glVertexShader;
	r34->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject,lime__graphics__opengl__GLObject))r34->fun)((vdynamic*)r34->value,r7,r35) : ((void (*)(lime__graphics__opengl__GLObject,lime__graphics__opengl__GLObject))r34->fun)(r7,r35);
	r34 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-227029056/*attachShader*/,&t$fun_842af41);
	if( r34 == NULL ) hl_null_access();
	r7 = r0->__glProgram;
	r35 = r0->__glFragmentShader;
	r34->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject,lime__graphics__opengl__GLObject))r34->fun)((vdynamic*)r34->value,r7,r35) : ((void (*)(lime__graphics__opengl__GLObject,lime__graphics__opengl__GLObject))r34->fun)(r7,r35);
	r11 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-377770981/*linkProgram*/,&t$fun_9a74d20);
	if( r11 == NULL ) hl_null_access();
	r7 = r0->__glProgram;
	r11->hasValue ? ((void (*)(vdynamic*,lime__graphics__opengl__GLObject))r11->fun)((vdynamic*)r11->value,r7) : ((void (*)(lime__graphics__opengl__GLObject))r11->fun)(r7);
	r13 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-157498964/*getProgramParameter*/,&t$fun_90c71d8);
	if( r13 == NULL ) hl_null_access();
	r7 = r0->__glProgram;
	r9 = r3->LINK_STATUS;
	r12 = r13->hasValue ? ((vdynamic* (*)(vdynamic*,lime__graphics__opengl__GLObject,int))r13->fun)((vdynamic*)r13->value,r7,r9) : ((vdynamic* (*)(lime__graphics__opengl__GLObject,int))r13->fun)(r7,r9);
	r14 = (double)hl_dyn_castd(&r12,&t$_dyn);
	r15 = 0.;
	if( r14 != r15 ) goto label$49d1ec1_17_199;
	r6 = (String)s$b175e45;
	r17 = (String)s$68b329d;
	r19 = (vclosure*)hl_dyn_getp((vdynamic*)r3,-302845629/*getProgramInfoLog*/,&t$fun_716c0c7);
	if( r19 == NULL ) hl_null_access();
	r7 = r0->__glProgram;
	r18 = r19->hasValue ? ((String (*)(vdynamic*,lime__graphics__opengl__GLObject))r19->fun)((vdynamic*)r19->value,r7) : ((String (*)(lime__graphics__opengl__GLObject))r19->fun)(r7);
	r17 = String___add__(r17,r18);
	r16 = String___add__(r6,r17);
	r20 = hl_alloc_virtual(&t$vrt_329ffa8);
	r17 = (String)s$openfl_display3D_Program3D_hx;
	if( hl_vfields(r20)[1] ) *(String*)(hl_vfields(r20)[1]) = (String)r17; else hl_dyn_setp(r20->value,37969014/*fileName*/,&t$String,r17);
	r9 = 922;
	if( hl_vfields(r20)[2] ) *(int*)(hl_vfields(r20)[2]) = (int)r9; else hl_dyn_seti(r20->value,371360620/*lineNumber*/,&t$_i32,r9);
	r17 = (String)s$openfl_display3D_Program3D;
	if( hl_vfields(r20)[0] ) *(String*)(hl_vfields(r20)[0]) = (String)r17; else hl_dyn_setp(r20->value,-63073762/*className*/,&t$String,r17);
	r17 = (String)s$__uploadFromGLSL;
	if( hl_vfields(r20)[3] ) *(String*)(hl_vfields(r20)[3]) = (String)r17; else hl_dyn_setp(r20->value,302979532/*methodName*/,&t$String,r17);
	r21 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r20);
	lime_utils_Log_error(((vdynamic*)r16),r21);
	label$49d1ec1_17_199:
	return;
}

