// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/text/_internal/GlyphPosition.h>
extern hl_type t$lime_math_Vector2;
void lime_math_Vector2_new(lime__math__Vector2,double*,double*);

void openfl_text__internal_GlyphPosition_new(openfl__text___internal__GlyphPosition r0,int r1,lime__math__Vector2 r2,lime__math__Vector2 r3) {
	lime__math__Vector2 r4;
	double *r6, *r7;
	r0->glyph = r1;
	r0->advance = r2;
	if( !r3 ) goto label$16854b2_1_5;
	r0->offset = r3;
	goto label$16854b2_1_10;
	label$16854b2_1_5:
	r4 = (lime__math__Vector2)hl_alloc_obj(&t$lime_math_Vector2);
	r6 = NULL;
	r7 = NULL;
	lime_math_Vector2_new(r4,r6,r7);
	r0->offset = r4;
	label$16854b2_1_10:
	return;
}

