// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__text___internal__GlyphPosition
#define INC_openfl__text___internal__GlyphPosition
typedef struct _openfl__text___internal__$GlyphPosition *openfl__text___internal__$GlyphPosition;
typedef struct _openfl__text___internal__GlyphPosition *openfl__text___internal__GlyphPosition;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <lime/math/Vector2.h>


struct _openfl__text___internal__$GlyphPosition {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _openfl__text___internal__GlyphPosition {
	hl_type *$type;
	lime__math__Vector2 advance;
	int glyph;
	lime__math__Vector2 offset;
};
#endif

