// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/group/FlxTypedGroupIterator.h>
int hl_types_ArrayDyn_get_length(hl__types__ArrayDyn);
bool flixel_group_FlxTypedGroupIterator_hasNext(flixel__group__FlxTypedGroupIterator);

void flixel_group_FlxTypedGroupIterator_new(flixel__group__FlxTypedGroupIterator r0,hl__types__ArrayDyn r1,vclosure* r2) {
	hl__types__ArrayDyn r3;
	int r4;
	r0->_groupMembers = r1;
	r0->_filter = r2;
	r4 = 0;
	r0->_cursor = r4;
	r3 = r0->_groupMembers;
	if( r3 == NULL ) hl_null_access();
	r4 = hl_types_ArrayDyn_get_length(r3);
	r0->_length = r4;
	return;
}

vdynamic* flixel_group_FlxTypedGroupIterator_next(flixel__group__FlxTypedGroupIterator r0) {
	bool r1;
	hl__types__ArrayDyn r2;
	vdynamic *r5;
	int r3, r4;
	r1 = flixel_group_FlxTypedGroupIterator_hasNext(r0);
	if( !r1 ) goto label$8a33c1d_2_10;
	r2 = r0->_groupMembers;
	if( r2 == NULL ) hl_null_access();
	r3 = r0->_cursor;
	r4 = r3;
	++r3;
	r0->_cursor = r3;
	r5 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r2->$type->vobj_proto[0])(r2,r4);
	return r5;
	label$8a33c1d_2_10:
	r5 = NULL;
	return r5;
}

bool flixel_group_FlxTypedGroupIterator_hasNext(flixel__group__FlxTypedGroupIterator r0) {
	bool r6;
	vclosure *r5;
	hl__types__ArrayDyn r3;
	vdynamic *r4;
	int r1, r2;
	label$8a33c1d_3_0:
	r1 = r0->_cursor;
	r2 = r0->_length;
	if( r1 >= r2 ) goto label$8a33c1d_3_23;
	r3 = r0->_groupMembers;
	if( r3 == NULL ) hl_null_access();
	r1 = r0->_cursor;
	r4 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r3->$type->vobj_proto[0])(r3,r1);
	if( !r4 ) goto label$8a33c1d_3_19;
	r5 = r0->_filter;
	if( !r5 ) goto label$8a33c1d_3_23;
	r5 = r0->_filter;
	if( r5 == NULL ) hl_null_access();
	r3 = r0->_groupMembers;
	if( r3 == NULL ) hl_null_access();
	r1 = r0->_cursor;
	r4 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r3->$type->vobj_proto[0])(r3,r1);
	r6 = r5->hasValue ? ((bool (*)(vdynamic*,vdynamic*))r5->fun)((vdynamic*)r5->value,r4) : ((bool (*)(vdynamic*))r5->fun)(r4);
	if( r6 ) goto label$8a33c1d_3_23;
	label$8a33c1d_3_19:
	r1 = r0->_cursor;
	++r1;
	r0->_cursor = r1;
	goto label$8a33c1d_3_0;
	label$8a33c1d_3_23:
	r1 = r0->_cursor;
	r2 = r0->_length;
	if( r1 < r2 ) goto label$8a33c1d_3_28;
	r6 = false;
	goto label$8a33c1d_3_29;
	label$8a33c1d_3_28:
	r6 = true;
	label$8a33c1d_3_29:
	return r6;
}

