// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/utils/AssetManifest.h>
extern hl_type t$_dyn;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
#include <hl/types/ArrayBase.h>
hl__types__ArrayDyn hl_types_ArrayDyn_alloc(hl__types__ArrayBase,bool*);
extern hl_type t$String;
#include <haxe/io/Encoding.h>
String haxe_io_Bytes_getString(haxe__io__Bytes,int,int,venum*);
lime__utils__AssetManifest lime_utils_AssetManifest_parse(String,String);
String lime_utils_AssetManifest___resolvePath(String);
String lime_utils_AssetManifest___resolveRootPath(String,String);
haxe__io__Bytes lime_utils__Bytes_Bytes_Impl__fromFile(String);
lime__app__Future lime_app_Future_withValue(vdynamic*);
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);
lime__app__Future lime_utils__Bytes_Bytes_Impl__loadFromFile(String);
lime__app__Future lime_utils_AssetManifest_loadFromFile__$1(hl__types__ArrayObj,haxe__io__Bytes);
extern hl_type t$fun_5c407a2;
lime__app__Future wrapt$fun_425acda(vclosure*,vdynamic*);
extern hl_type t$fun_425acda;
lime__app__Future lime_app_Future_then(lime__app__Future,vclosure*);
#include <haxe/format/JsonParser.h>
extern String s$;
int String___compare(String,vdynamic*);
extern hl_type t$haxe_format_JsonParser;
void haxe_format_JsonParser_new(haxe__format__JsonParser,String);
vdynamic* haxe_format_JsonParser_doParse(haxe__format__JsonParser);
extern hl_type t$vrt_5252630;
extern hl_type t$lime_utils_AssetManifest;
extern String s$name;
bool Reflect_hasField(vdynamic*,String);
extern String s$libraryType;
extern String s$libraryArgs;
extern hl_type t$hl_types_ArrayObj;
extern String s$assets;
extern String s$version;
extern hl_type t$_i32;
vdynamic* haxe_Unserializer_run(String);
extern hl_type t$hl_types_ArrayDyn;
extern String s$rootPath;
extern String s$6666cd7;
String String___add__(String,String);
String haxe_Serializer_run(vdynamic*);
String haxe_format_JsonPrinter_print(vdynamic*,vclosure*,String);
extern String s$d1457b7;
int String_indexOf(String,String,vdynamic*);
String String_substr(String,int,vdynamic*);
extern String s$28d397e;
String StringTools_replace(String,String,String);
bool StringTools_endsWith(String,String);
extern String s$_bundle;
extern String s$_library_json;
String haxe_io_Path_directory(String);

void lime_utils_AssetManifest_new(lime__utils__AssetManifest r0) {
	bool *r7;
	hl__types__ArrayObj r5;
	hl_type *r3;
	bool r6;
	hl__types__ArrayDyn r1;
	int r4;
	varray *r2;
	r3 = &t$_dyn;
	r4 = 0;
	r2 = hl_alloc_array(r3,r4);
	r5 = hl_types_ArrayObj_alloc(r2);
	r6 = true;
	r7 = &r6;
	r1 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r5),r7);
	r0->assets = r1;
	r3 = &t$String;
	r4 = 0;
	r2 = hl_alloc_array(r3,r4);
	r5 = hl_types_ArrayObj_alloc(r2);
	r0->libraryArgs = r5;
	r4 = 2;
	r0->version = r4;
	return;
}

lime__utils__AssetManifest lime_utils_AssetManifest_fromBytes(haxe__io__Bytes r0,String r1) {
	String r3;
	venum *r6;
	lime__utils__AssetManifest r2;
	int r4, r5;
	if( !r0 ) goto label$3ed49e2_2_8;
	if( r0 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r0->length;
	r6 = NULL;
	r3 = haxe_io_Bytes_getString(r0,r4,r5,r6);
	r2 = lime_utils_AssetManifest_parse(r3,r1);
	return r2;
	label$3ed49e2_2_8:
	r2 = NULL;
	return r2;
}

lime__utils__AssetManifest lime_utils_AssetManifest_fromFile(String r0,String r1) {
	String r2;
	haxe__io__Bytes r4;
	lime__utils__AssetManifest r3;
	r2 = lime_utils_AssetManifest___resolvePath(r0);
	r0 = r2;
	r2 = lime_utils_AssetManifest___resolveRootPath(r1,r0);
	r1 = r2;
	if( r0 ) goto label$3ed49e2_3_7;
	r3 = NULL;
	return r3;
	label$3ed49e2_3_7:
	r4 = lime_utils__Bytes_Bytes_Impl__fromFile(r0);
	r3 = lime_utils_AssetManifest_fromBytes(r4,r1);
	return r3;
}

lime__app__Future lime_utils_AssetManifest_loadFromBytes(haxe__io__Bytes r0,String r1) {
	lime__app__Future r2;
	lime__utils__AssetManifest r3;
	r3 = lime_utils_AssetManifest_fromBytes(r0,r1);
	r2 = lime_app_Future_withValue(((vdynamic*)r3));
	return r2;
}

lime__app__Future lime_utils_AssetManifest_loadFromFile(String r0,String r1) {
	String r6;
	hl__types__ArrayObj r2;
	hl_type *r4;
	lime__app__Future r11;
	vclosure *r12, *r13;
	vdynamic *r10;
	int r5, r8, r9;
	varray *r3;
	r4 = &t$String;
	r5 = 1;
	r3 = hl_alloc_array(r4,r5);
	r5 = 0;
	((String*)(r3 + 1))[r5] = r1;
	r2 = hl_types_ArrayObj_alloc(r3);
	r6 = lime_utils_AssetManifest___resolvePath(r0);
	r0 = r6;
	if( r2 == NULL ) hl_null_access();
	r5 = 0;
	r8 = 0;
	r9 = r2->length;
	if( ((unsigned)r8) < ((unsigned)r9) ) goto label$3ed49e2_5_15;
	r6 = NULL;
	goto label$3ed49e2_5_18;
	label$3ed49e2_5_15:
	r3 = r2->array;
	r10 = ((vdynamic**)(r3 + 1))[r8];
	r6 = (String)r10;
	label$3ed49e2_5_18:
	r6 = lime_utils_AssetManifest___resolveRootPath(r6,r0);
	r8 = r2->length;
	if( ((unsigned)r5) < ((unsigned)r8) ) goto label$3ed49e2_5_22;
	hl_types_ArrayObj___expand(r2,r5);
	label$3ed49e2_5_22:
	r3 = r2->array;
	((String*)(r3 + 1))[r5] = r6;
	if( r0 ) goto label$3ed49e2_5_27;
	r11 = NULL;
	return r11;
	label$3ed49e2_5_27:
	r11 = lime_utils__Bytes_Bytes_Impl__loadFromFile(r0);
	if( r11 == NULL ) hl_null_access();
	r12 = hl_alloc_closure_ptr(&t$fun_5c407a2,lime_utils_AssetManifest_loadFromFile__$1,r2);
	if( r12 ) goto label$3ed49e2_5_33;
	r13 = NULL;
	goto label$3ed49e2_5_34;
	label$3ed49e2_5_33:
	r13 = hl_alloc_closure_ptr(&t$fun_425acda,wrapt$fun_425acda,r12);
	label$3ed49e2_5_34:
	r11 = lime_app_Future_then(r11,r13);
	return r11;
}

lime__app__Future lime_utils_AssetManifest_loadFromFile__$1(hl__types__ArrayObj r0,haxe__io__Bytes r1) {
	String r6;
	lime__app__Future r2;
	lime__utils__AssetManifest r3;
	vdynamic *r7;
	varray *r8;
	int r4, r5;
	if( r0 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r0->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$3ed49e2_6_6;
	r6 = NULL;
	goto label$3ed49e2_6_9;
	label$3ed49e2_6_6:
	r8 = r0->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r6 = (String)r7;
	label$3ed49e2_6_9:
	r3 = lime_utils_AssetManifest_fromBytes(r1,r6);
	r2 = lime_app_Future_withValue(((vdynamic*)r3));
	return r2;
}

lime__utils__AssetManifest lime_utils_AssetManifest_parse(String r0,String r1) {
	String r3, r4;
	hl__types__ArrayObj r10;
	vvirtual *r8;
	bool r9;
	haxe__format__JsonParser r7;
	lime__utils__AssetManifest r5;
	hl__types__ArrayDyn r14;
	vdynamic *r6, *r13;
	int r11, r12;
	if( !r0 ) goto label$3ed49e2_7_3;
	r4 = (String)s$;
	if( r0 != r4 && (!r0 || !r4 || String___compare(r0,(vdynamic*)r4) != 0) ) goto label$3ed49e2_7_5;
	label$3ed49e2_7_3:
	r5 = NULL;
	return r5;
	label$3ed49e2_7_5:
	r7 = (haxe__format__JsonParser)hl_alloc_obj(&t$haxe_format_JsonParser);
	haxe_format_JsonParser_new(r7,r0);
	r6 = haxe_format_JsonParser_doParse(r7);
	r8 = hl_to_virtual(&t$vrt_5252630,(vdynamic*)r6);
	r5 = (lime__utils__AssetManifest)hl_alloc_obj(&t$lime_utils_AssetManifest);
	lime_utils_AssetManifest_new(r5);
	r3 = (String)s$name;
	r9 = Reflect_hasField(((vdynamic*)r8),r3);
	if( !r9 ) goto label$3ed49e2_7_17;
	if( r8 == NULL ) hl_null_access();
	r3 = hl_vfields(r8)[3] ? (*(String*)(hl_vfields(r8)[3])) : (String)hl_dyn_getp(r8->value,150958933/*name*/,&t$String);
	r5->name = r3;
	label$3ed49e2_7_17:
	r3 = (String)s$libraryType;
	r9 = Reflect_hasField(((vdynamic*)r8),r3);
	if( !r9 ) goto label$3ed49e2_7_23;
	if( r8 == NULL ) hl_null_access();
	r3 = hl_vfields(r8)[2] ? (*(String*)(hl_vfields(r8)[2])) : (String)hl_dyn_getp(r8->value,-286204341/*libraryType*/,&t$String);
	r5->libraryType = r3;
	label$3ed49e2_7_23:
	r3 = (String)s$libraryArgs;
	r9 = Reflect_hasField(((vdynamic*)r8),r3);
	if( !r9 ) goto label$3ed49e2_7_29;
	if( r8 == NULL ) hl_null_access();
	r10 = hl_vfields(r8)[1] ? (*(hl__types__ArrayObj*)(hl_vfields(r8)[1])) : (hl__types__ArrayObj)hl_dyn_getp(r8->value,-497256210/*libraryArgs*/,&t$hl_types_ArrayObj);
	r5->libraryArgs = r10;
	label$3ed49e2_7_29:
	r3 = (String)s$assets;
	r9 = Reflect_hasField(((vdynamic*)r8),r3);
	if( !r9 ) goto label$3ed49e2_7_47;
	if( r8 == NULL ) hl_null_access();
	r6 = hl_vfields(r8)[0] ? (*(vdynamic**)(hl_vfields(r8)[0])) : (vdynamic*)hl_dyn_getp(r8->value,201542029/*assets*/,&t$_dyn);
	r3 = (String)s$version;
	r9 = Reflect_hasField(((vdynamic*)r8),r3);
	if( !r9 ) goto label$3ed49e2_7_45;
	r11 = hl_vfields(r8)[5] ? (*(int*)(hl_vfields(r8)[5])) : (int)hl_dyn_geti(r8->value,485615783/*version*/,&t$_i32);
	r12 = 2;
	if( r12 < r11 ) goto label$3ed49e2_7_45;
	r3 = (String)hl_dyn_castp(&r6,&t$_dyn,&t$String);
	r13 = haxe_Unserializer_run(r3);
	r14 = (hl__types__ArrayDyn)hl_dyn_castp(&r13,&t$_dyn,&t$hl_types_ArrayDyn);
	r5->assets = r14;
	goto label$3ed49e2_7_47;
	label$3ed49e2_7_45:
	r14 = (hl__types__ArrayDyn)hl_dyn_castp(&r6,&t$_dyn,&t$hl_types_ArrayDyn);
	r5->assets = r14;
	label$3ed49e2_7_47:
	r3 = (String)s$rootPath;
	r9 = Reflect_hasField(((vdynamic*)r8),r3);
	if( !r9 ) goto label$3ed49e2_7_53;
	if( r8 == NULL ) hl_null_access();
	r3 = hl_vfields(r8)[4] ? (*(String*)(hl_vfields(r8)[4])) : (String)hl_dyn_getp(r8->value,-511133465/*rootPath*/,&t$String);
	r5->rootPath = r3;
	label$3ed49e2_7_53:
	if( !r1 ) goto label$3ed49e2_7_68;
	r4 = (String)s$;
	if( r1 == r4 || (r1 && r4 && String___compare(r1,(vdynamic*)r4) == 0) ) goto label$3ed49e2_7_68;
	r3 = r5->rootPath;
	if( !r3 ) goto label$3ed49e2_7_61;
	r3 = r5->rootPath;
	r4 = (String)s$;
	if( r3 != r4 && (!r3 || !r4 || String___compare(r3,(vdynamic*)r4) != 0) ) goto label$3ed49e2_7_63;
	label$3ed49e2_7_61:
	r5->rootPath = r1;
	goto label$3ed49e2_7_68;
	label$3ed49e2_7_63:
	r4 = (String)s$6666cd7;
	r3 = String___add__(r1,r4);
	r4 = r5->rootPath;
	r3 = String___add__(r3,r4);
	r5->rootPath = r3;
	label$3ed49e2_7_68:
	return r5;
}

String lime_utils_AssetManifest_serialize(lime__utils__AssetManifest r0) {
	String r3;
	vdynobj *r1;
	hl__types__ArrayObj r4;
	vclosure *r6;
	hl__types__ArrayDyn r5;
	int r2;
	r1 = hl_alloc_dynobj();
	r2 = r0->version;
	hl_dyn_seti((vdynamic*)r1,485615783/*version*/,&t$_i32,r2);
	r3 = r0->libraryType;
	hl_dyn_setp((vdynamic*)r1,-286204341/*libraryType*/,&t$String,r3);
	r4 = r0->libraryArgs;
	hl_dyn_setp((vdynamic*)r1,-497256210/*libraryArgs*/,&t$hl_types_ArrayObj,r4);
	r3 = r0->name;
	hl_dyn_setp((vdynamic*)r1,150958933/*name*/,&t$String,r3);
	r5 = r0->assets;
	r3 = haxe_Serializer_run(((vdynamic*)r5));
	hl_dyn_setp((vdynamic*)r1,201542029/*assets*/,&t$String,r3);
	r3 = r0->rootPath;
	hl_dyn_setp((vdynamic*)r1,-511133465/*rootPath*/,&t$String,r3);
	r6 = NULL;
	r3 = NULL;
	r3 = haxe_format_JsonPrinter_print(((vdynamic*)r1),r6,r3);
	return r3;
}

String lime_utils_AssetManifest___resolvePath(String r0) {
	String r1, r3, r7, r8;
	bool r9;
	vdynamic *r4;
	int r2, r5, r6, r10;
	if( r0 ) goto label$3ed49e2_9_3;
	r1 = NULL;
	return r1;
	label$3ed49e2_9_3:
	if( r0 == NULL ) hl_null_access();
	r3 = (String)s$d1457b7;
	r4 = NULL;
	r2 = String_indexOf(r0,r3,r4);
	r6 = -1;
	if( r6 >= r2 ) goto label$3ed49e2_9_14;
	r5 = 0;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r2;
	r3 = String_substr(r0,r5,r4);
	r1 = r3;
	goto label$3ed49e2_9_15;
	label$3ed49e2_9_14:
	r1 = r0;
	label$3ed49e2_9_15:
	r7 = (String)s$28d397e;
	r8 = (String)s$6666cd7;
	r3 = StringTools_replace(r1,r7,r8);
	r1 = r3;
	label$3ed49e2_9_19:
	r7 = (String)s$6666cd7;
	r9 = StringTools_endsWith(r1,r7);
	if( !r9 ) goto label$3ed49e2_9_32;
	if( r1 == NULL ) hl_null_access();
	r5 = 0;
	r6 = r1->length;
	r10 = 1;
	r6 = r6 - r10;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r6;
	r3 = String_substr(r1,r5,r4);
	r1 = r3;
	goto label$3ed49e2_9_19;
	label$3ed49e2_9_32:
	r7 = (String)s$_bundle;
	r9 = StringTools_endsWith(r1,r7);
	if( !r9 ) goto label$3ed49e2_9_47;
	r6 = -1;
	if( r6 >= r2 ) goto label$3ed49e2_9_44;
	r7 = (String)s$_library_json;
	r3 = String___add__(r1,r7);
	if( r0 == NULL ) hl_null_access();
	r4 = NULL;
	r7 = String_substr(r0,r2,r4);
	r3 = String___add__(r3,r7);
	return r3;
	label$3ed49e2_9_44:
	r7 = (String)s$_library_json;
	r3 = String___add__(r1,r7);
	return r3;
	label$3ed49e2_9_47:
	return r0;
}

String lime_utils_AssetManifest___resolveRootPath(String r0,String r1) {
	String r2, r4, r8;
	bool r9;
	vdynamic *r5;
	int r3, r6, r7, r10;
	if( !r0 ) goto label$3ed49e2_10_2;
	return r0;
	label$3ed49e2_10_2:
	if( r1 == NULL ) hl_null_access();
	r4 = (String)s$d1457b7;
	r5 = NULL;
	r3 = String_indexOf(r1,r4,r5);
	r7 = -1;
	if( r7 >= r3 ) goto label$3ed49e2_10_13;
	r6 = 0;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r3;
	r2 = String_substr(r1,r6,r5);
	r0 = r2;
	goto label$3ed49e2_10_14;
	label$3ed49e2_10_13:
	r0 = r1;
	label$3ed49e2_10_14:
	r4 = (String)s$28d397e;
	r8 = (String)s$6666cd7;
	r2 = StringTools_replace(r0,r4,r8);
	r0 = r2;
	label$3ed49e2_10_18:
	r4 = (String)s$6666cd7;
	r9 = StringTools_endsWith(r0,r4);
	if( !r9 ) goto label$3ed49e2_10_34;
	r4 = (String)s$6666cd7;
	if( r0 != r4 && (!r0 || !r4 || String___compare(r0,(vdynamic*)r4) != 0) ) goto label$3ed49e2_10_25;
	return r0;
	label$3ed49e2_10_25:
	if( r0 == NULL ) hl_null_access();
	r6 = 0;
	r7 = r0->length;
	r10 = 1;
	r7 = r7 - r10;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r7;
	r2 = String_substr(r0,r6,r5);
	r0 = r2;
	goto label$3ed49e2_10_18;
	label$3ed49e2_10_34:
	r4 = (String)s$_bundle;
	r9 = StringTools_endsWith(r0,r4);
	if( !r9 ) goto label$3ed49e2_10_38;
	return r0;
	label$3ed49e2_10_38:
	r2 = haxe_io_Path_directory(r0);
	return r2;
}

