// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__utils__Log
#define INC_lime__utils__Log
typedef struct _lime__utils__$Log *lime__utils__$Log;
typedef struct _lime__utils__Log *lime__utils__Log;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayDyn.h>


struct _lime__utils__$Log {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	int level;
	bool throwErrors;
	vclosure* debug;
	vclosure* error;
	vclosure* info;
	vclosure* print;
	vclosure* println;
	vclosure* verbose;
	vclosure* warn;
};
struct _lime__utils__Log {
	hl_type *$type;
};
#endif

