// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__math__FlxBasePoint
#define INC_flixel__math__FlxBasePoint
typedef struct _flixel__math__$FlxBasePoint *flixel__math__$FlxBasePoint;
typedef struct _flixel__math__FlxBasePoint *flixel__math__FlxBasePoint;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <flixel/util/FlxPool_flixel_math_FlxBasePoint.h>


struct _flixel__math__$FlxBasePoint {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	flixel__util__FlxPool_flixel_math_FlxBasePoint pool;
	vclosure* get;
	vclosure* weak;
};
struct _flixel__math__FlxBasePoint {
	hl_type *$type;
	double x;
	double y;
	bool _weak;
	bool _inPool;
	vvirtual* f$4;
};
#endif

