// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/math/FlxMath.h>
#include <hl/natives.h>
#include <flixel/input/mouse/FlxMouse.h>
#include <flixel/FlxG.h>
extern flixel__$FlxG g$_flixel_FlxG;
double openfl_geom_Rectangle_get_right(openfl__geom__Rectangle);
double openfl_geom_Rectangle_get_bottom(openfl__geom__Rectangle);
#include <hl/types/ArrayObj.h>
extern hl_type t$_f64;
String Std_string(vdynamic*);
extern String s$5058f1a;
hl__types__ArrayObj String_split(String,String);

double flixel_math_FlxMath_roundDecimal(double r0,int r1) {
	double r2, r5, r6;
	int r3, r4;
	r2 = 1.;
	r3 = 0;
	r4 = r1;
	label$83854ae_1_3:
	if( r3 >= r4 ) goto label$83854ae_1_10;
	++r3;
	r6 = 10.;
	r5 = r2 * r6;
	r2 = r5;
	goto label$83854ae_1_3;
	label$83854ae_1_10:
	r5 = r0 * r2;
	r5 = hl_math_fround(r5);
	r5 = r5 / r2;
	return r5;
}

double flixel_math_FlxMath_bound(double r0,vdynamic* r1,vdynamic* r2) {
	double r3, r4, r5;
	if( !r1 ) goto label$83854ae_2_5;
	r4 = r1 ? r1->v.d : 0;
	if( !(r0 < r4) ) goto label$83854ae_2_5;
	r3 = r1 ? r1->v.d : 0;
	goto label$83854ae_2_6;
	label$83854ae_2_5:
	r3 = r0;
	label$83854ae_2_6:
	if( !r2 ) goto label$83854ae_2_11;
	r5 = r2 ? r2->v.d : 0;
	if( !(r5 < r3) ) goto label$83854ae_2_11;
	r4 = r2 ? r2->v.d : 0;
	return r4;
	label$83854ae_2_11:
	return r3;
}

double flixel_math_FlxMath_lerp(double r0,double r1,double r2) {
	double r3, r4, r5;
	r5 = r1 - r0;
	r4 = r2 * r5;
	r3 = r0 + r4;
	return r3;
}

bool flixel_math_FlxMath_inBounds(double r0,vdynamic* r1,vdynamic* r2) {
	bool r4;
	double r3;
	if( !r1 ) goto label$83854ae_4_3;
	r3 = r1 ? r1->v.d : 0;
	if( !(r0 >= r3) ) goto label$83854ae_4_12;
	label$83854ae_4_3:
	if( !r2 ) goto label$83854ae_4_10;
	r3 = r2 ? r2->v.d : 0;
	if( r0 <= r3 ) goto label$83854ae_4_8;
	r4 = false;
	goto label$83854ae_4_9;
	label$83854ae_4_8:
	r4 = true;
	label$83854ae_4_9:
	return r4;
	label$83854ae_4_10:
	r4 = true;
	return r4;
	label$83854ae_4_12:
	r4 = false;
	return r4;
}

bool flixel_math_FlxMath_isOdd(double r0) {
	bool r1;
	int r2, r3;
	r2 = (int)r0;
	r3 = 1;
	r2 = r2 & r3;
	r3 = 0;
	if( r2 != r3 ) goto label$83854ae_5_7;
	r1 = false;
	goto label$83854ae_5_8;
	label$83854ae_5_7:
	r1 = true;
	label$83854ae_5_8:
	return r1;
}

bool flixel_math_FlxMath_isEven(double r0) {
	bool r1;
	int r2, r3;
	r2 = (int)r0;
	r3 = 1;
	r2 = r2 & r3;
	r3 = 0;
	if( r2 == r3 ) goto label$83854ae_6_7;
	r1 = false;
	goto label$83854ae_6_8;
	label$83854ae_6_7:
	r1 = true;
	label$83854ae_6_8:
	return r1;
}

int flixel_math_FlxMath_numericComparison(double r0,double r1) {
	int r2;
	if( !(r0 < r1) ) goto label$83854ae_7_3;
	r2 = -1;
	return r2;
	label$83854ae_7_3:
	if( !(r1 < r0) ) goto label$83854ae_7_6;
	r2 = 1;
	return r2;
	label$83854ae_7_6:
	r2 = 0;
	return r2;
}

bool flixel_math_FlxMath_pointInCoordinates(double r0,double r1,double r2,double r3,double r4,double r5) {
	bool r7;
	double r6;
	if( !(r0 >= r2) ) goto label$83854ae_8_8;
	r6 = r2 + r4;
	if( !(r6 >= r0) ) goto label$83854ae_8_8;
	if( !(r1 >= r3) ) goto label$83854ae_8_8;
	r6 = r3 + r5;
	if( !(r6 >= r1) ) goto label$83854ae_8_8;
	r7 = true;
	return r7;
	label$83854ae_8_8:
	r7 = false;
	return r7;
}

bool flixel_math_FlxMath_pointInFlxRect(double r0,double r1,flixel__math__FlxRect r2) {
	bool r5;
	double r3, r4;
	if( r2 == NULL ) hl_null_access();
	r3 = r2->x;
	if( !(r0 >= r3) ) goto label$83854ae_9_17;
	r3 = r2->x;
	r4 = r2->width;
	r3 = r3 + r4;
	if( !(r3 >= r0) ) goto label$83854ae_9_17;
	r3 = r2->y;
	if( !(r1 >= r3) ) goto label$83854ae_9_17;
	r3 = r2->y;
	r4 = r2->height;
	r3 = r3 + r4;
	if( r1 <= r3 ) goto label$83854ae_9_15;
	r5 = false;
	goto label$83854ae_9_16;
	label$83854ae_9_15:
	r5 = true;
	label$83854ae_9_16:
	return r5;
	label$83854ae_9_17:
	r5 = false;
	return r5;
}

bool flixel_math_FlxMath_mouseInFlxRect(bool r0,flixel__math__FlxRect r1) {
	flixel__input__mouse__FlxMouse r4;
	bool r2;
	flixel__$FlxG r5;
	double r6, r7;
	int r3;
	if( r1 ) goto label$83854ae_10_3;
	r2 = true;
	return r2;
	label$83854ae_10_3:
	if( !r0 ) goto label$83854ae_10_20;
	r5 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r5->mouse;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->x;
	r6 = (double)r3;
	r3 = hl_math_floor(r6);
	r6 = (double)r3;
	r5 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r5->mouse;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->y;
	r7 = (double)r3;
	r3 = hl_math_floor(r7);
	r7 = (double)r3;
	r2 = flixel_math_FlxMath_pointInFlxRect(r6,r7,r1);
	return r2;
	label$83854ae_10_20:
	r5 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r5->mouse;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->screenX;
	r6 = (double)r3;
	r5 = (flixel__$FlxG)g$_flixel_FlxG;
	r4 = r5->mouse;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->screenY;
	r7 = (double)r3;
	r2 = flixel_math_FlxMath_pointInFlxRect(r6,r7,r1);
	return r2;
}

bool flixel_math_FlxMath_pointInRectangle(double r0,double r1,openfl__geom__Rectangle r2) {
	bool r4;
	double r3;
	if( r2 == NULL ) hl_null_access();
	r3 = r2->x;
	if( !(r0 >= r3) ) goto label$83854ae_11_13;
	r3 = openfl_geom_Rectangle_get_right(r2);
	if( !(r3 >= r0) ) goto label$83854ae_11_13;
	r3 = r2->y;
	if( !(r1 >= r3) ) goto label$83854ae_11_13;
	r3 = openfl_geom_Rectangle_get_bottom(r2);
	if( r1 <= r3 ) goto label$83854ae_11_11;
	r4 = false;
	goto label$83854ae_11_12;
	label$83854ae_11_11:
	r4 = true;
	label$83854ae_11_12:
	return r4;
	label$83854ae_11_13:
	r4 = false;
	return r4;
}

int flixel_math_FlxMath_maxAdd(int r0,int r1,int r2,int* r3) {
	int r4, r5;
	if( r3 ) goto label$83854ae_12_3;
	r4 = 0;
	goto label$83854ae_12_4;
	label$83854ae_12_3:
	r4 = *r3;
	label$83854ae_12_4:
	r5 = r0 + r1;
	r0 = r5;
	if( r2 >= r5 ) goto label$83854ae_12_9;
	r0 = r2;
	goto label$83854ae_12_11;
	label$83854ae_12_9:
	if( r4 < r5 ) goto label$83854ae_12_11;
	r0 = r4;
	label$83854ae_12_11:
	return r0;
}

int flixel_math_FlxMath_wrap(int r0,int r1,int r2) {
	double r7, r8;
	int r3, r4, r5, r6;
	r3 = r2 - r1;
	r4 = 1;
	r3 = r3 + r4;
	if( r0 >= r1 ) goto label$83854ae_13_14;
	r6 = r1 - r0;
	r7 = (double)r6;
	r8 = (double)r3;
	r7 = r7 / r8;
	r8 = 1.;
	r7 = r7 + r8;
	r6 = (int)r7;
	r5 = r3 * r6;
	r4 = r0 + r5;
	r0 = r4;
	label$83854ae_13_14:
	r5 = r0 - r1;
	r5 = r3 == 0 ? 0 : r5 % r3;
	r4 = r1 + r5;
	return r4;
}

double flixel_math_FlxMath_remapToRange(double r0,double r1,double r2,double r3,double r4) {
	double r5, r6, r7, r8;
	r6 = r0 - r1;
	r7 = r4 - r3;
	r8 = r2 - r1;
	r7 = r7 / r8;
	r6 = r6 * r7;
	r5 = r3 + r6;
	return r5;
}

double flixel_math_FlxMath_dotProduct(double r0,double r1,double r2,double r3) {
	double r4, r5;
	r4 = r0 * r2;
	r5 = r1 * r3;
	r4 = r4 + r5;
	return r4;
}

double flixel_math_FlxMath_vectorLength(double r0,double r1) {
	double r2, r3;
	r2 = r0 * r0;
	r3 = r1 * r1;
	r2 = r2 + r3;
	r2 = hl_math_sqrt(r2);
	return r2;
}

int flixel_math_FlxMath_distanceBetween(flixel__FlxSprite r0,flixel__FlxSprite r1) {
	flixel__math__FlxBasePoint r4;
	double r2, r3, r5, r6;
	int r7;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->x;
	r4 = r0->origin;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->x;
	r2 = r2 + r3;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->x;
	r4 = r1->origin;
	if( r4 == NULL ) hl_null_access();
	r5 = r4->x;
	r3 = r3 + r5;
	r2 = r2 - r3;
	r3 = r0->y;
	r4 = r0->origin;
	if( r4 == NULL ) hl_null_access();
	r5 = r4->y;
	r3 = r3 + r5;
	r5 = r1->y;
	r4 = r1->origin;
	if( r4 == NULL ) hl_null_access();
	r6 = r4->y;
	r5 = r5 + r6;
	r3 = r3 - r5;
	r5 = r2 * r2;
	r6 = r3 * r3;
	r5 = r5 + r6;
	r5 = hl_math_sqrt(r5);
	r7 = (int)r5;
	return r7;
}

bool flixel_math_FlxMath_isDistanceWithin(flixel__FlxSprite r0,flixel__FlxSprite r1,double r2,bool* r3) {
	flixel__math__FlxBasePoint r7;
	bool r4, r10;
	double r5, r6, r8, r9;
	if( r3 ) goto label$83854ae_18_3;
	r4 = false;
	goto label$83854ae_18_4;
	label$83854ae_18_3:
	r4 = *r3;
	label$83854ae_18_4:
	if( r0 == NULL ) hl_null_access();
	r5 = r0->x;
	r7 = r0->origin;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->x;
	r5 = r5 + r6;
	if( r1 == NULL ) hl_null_access();
	r6 = r1->x;
	r7 = r1->origin;
	if( r7 == NULL ) hl_null_access();
	r8 = r7->x;
	r6 = r6 + r8;
	r5 = r5 - r6;
	r6 = r0->y;
	r7 = r0->origin;
	if( r7 == NULL ) hl_null_access();
	r8 = r7->y;
	r6 = r6 + r8;
	r8 = r1->y;
	r7 = r1->origin;
	if( r7 == NULL ) hl_null_access();
	r9 = r7->y;
	r8 = r8 + r9;
	r6 = r6 - r8;
	if( !r4 ) goto label$83854ae_18_38;
	r8 = r5 * r5;
	r9 = r6 * r6;
	r8 = r8 + r9;
	r9 = r2 * r2;
	if( r8 <= r9 ) goto label$83854ae_18_36;
	r10 = false;
	goto label$83854ae_18_37;
	label$83854ae_18_36:
	r10 = true;
	label$83854ae_18_37:
	return r10;
	label$83854ae_18_38:
	r8 = r5 * r5;
	r9 = r6 * r6;
	r8 = r8 + r9;
	r9 = r2 * r2;
	if( r8 < r9 ) goto label$83854ae_18_45;
	r10 = false;
	goto label$83854ae_18_46;
	label$83854ae_18_45:
	r10 = true;
	label$83854ae_18_46:
	return r10;
}

int flixel_math_FlxMath_distanceToPoint(flixel__FlxSprite r0,flixel__math__FlxBasePoint r1) {
	flixel__math__FlxBasePoint r4;
	bool r7;
	double r2, r3, r6, r8;
	int r9;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->x;
	r4 = r0->origin;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->x;
	r2 = r2 + r3;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->x;
	r2 = r2 - r3;
	r3 = r0->y;
	r4 = r0->origin;
	if( r4 == NULL ) hl_null_access();
	r6 = r4->y;
	r3 = r3 + r6;
	r6 = r1->y;
	r3 = r3 - r6;
	r7 = r1->_weak;
	if( !r7 ) goto label$83854ae_19_19;
	((void (*)(flixel__math__FlxBasePoint))r1->$type->vobj_proto[1])(r1);
	label$83854ae_19_19:
	r6 = r2 * r2;
	r8 = r3 * r3;
	r6 = r6 + r8;
	r6 = hl_math_sqrt(r6);
	r9 = (int)r6;
	return r9;
}

bool flixel_math_FlxMath_isDistanceToPointWithin(flixel__FlxSprite r0,flixel__math__FlxBasePoint r1,double r2,bool* r3) {
	flixel__math__FlxBasePoint r7;
	bool r4, r10;
	double r5, r6, r9, r11;
	if( r3 ) goto label$83854ae_20_3;
	r4 = false;
	goto label$83854ae_20_4;
	label$83854ae_20_3:
	r4 = *r3;
	label$83854ae_20_4:
	if( r0 == NULL ) hl_null_access();
	r5 = r0->x;
	r7 = r0->origin;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->x;
	r5 = r5 + r6;
	if( r1 == NULL ) hl_null_access();
	r6 = r1->x;
	r5 = r5 - r6;
	r6 = r0->y;
	r7 = r0->origin;
	if( r7 == NULL ) hl_null_access();
	r9 = r7->y;
	r6 = r6 + r9;
	r9 = r1->y;
	r6 = r6 - r9;
	r10 = r1->_weak;
	if( !r10 ) goto label$83854ae_20_23;
	((void (*)(flixel__math__FlxBasePoint))r1->$type->vobj_proto[1])(r1);
	label$83854ae_20_23:
	if( !r4 ) goto label$83854ae_20_33;
	r9 = r5 * r5;
	r11 = r6 * r6;
	r9 = r9 + r11;
	r11 = r2 * r2;
	if( r9 <= r11 ) goto label$83854ae_20_31;
	r10 = false;
	goto label$83854ae_20_32;
	label$83854ae_20_31:
	r10 = true;
	label$83854ae_20_32:
	return r10;
	label$83854ae_20_33:
	r9 = r5 * r5;
	r11 = r6 * r6;
	r9 = r9 + r11;
	r11 = r2 * r2;
	if( r9 < r11 ) goto label$83854ae_20_40;
	r10 = false;
	goto label$83854ae_20_41;
	label$83854ae_20_40:
	r10 = true;
	label$83854ae_20_41:
	return r10;
}

int flixel_math_FlxMath_distanceToMouse(flixel__FlxSprite r0) {
	flixel__input__mouse__FlxMouse r5;
	flixel__math__FlxBasePoint r3;
	flixel__$FlxG r6;
	double r1, r2, r7, r8;
	int r4;
	if( r0 == NULL ) hl_null_access();
	r1 = r0->x;
	r3 = r0->origin;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->x;
	r1 = r1 + r2;
	r6 = (flixel__$FlxG)g$_flixel_FlxG;
	r5 = r6->mouse;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->screenX;
	r2 = (double)r4;
	r1 = r1 - r2;
	r2 = r0->y;
	r3 = r0->origin;
	if( r3 == NULL ) hl_null_access();
	r7 = r3->y;
	r2 = r2 + r7;
	r6 = (flixel__$FlxG)g$_flixel_FlxG;
	r5 = r6->mouse;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->screenY;
	r7 = (double)r4;
	r2 = r2 - r7;
	r7 = r1 * r1;
	r8 = r2 * r2;
	r7 = r7 + r8;
	r7 = hl_math_sqrt(r7);
	r4 = (int)r7;
	return r4;
}

bool flixel_math_FlxMath_isDistanceToMouseWithin(flixel__FlxSprite r0,double r1,bool* r2) {
	flixel__input__mouse__FlxMouse r8;
	flixel__math__FlxBasePoint r6;
	bool r3, r11;
	flixel__$FlxG r9;
	double r4, r5, r10, r12;
	int r7;
	if( r2 ) goto label$83854ae_22_3;
	r3 = false;
	goto label$83854ae_22_4;
	label$83854ae_22_3:
	r3 = *r2;
	label$83854ae_22_4:
	if( r0 == NULL ) hl_null_access();
	r4 = r0->x;
	r6 = r0->origin;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->x;
	r4 = r4 + r5;
	r9 = (flixel__$FlxG)g$_flixel_FlxG;
	r8 = r9->mouse;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->screenX;
	r5 = (double)r7;
	r4 = r4 - r5;
	r5 = r0->y;
	r6 = r0->origin;
	if( r6 == NULL ) hl_null_access();
	r10 = r6->y;
	r5 = r5 + r10;
	r9 = (flixel__$FlxG)g$_flixel_FlxG;
	r8 = r9->mouse;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->screenY;
	r10 = (double)r7;
	r5 = r5 - r10;
	if( !r3 ) goto label$83854ae_22_37;
	r10 = r4 * r4;
	r12 = r5 * r5;
	r10 = r10 + r12;
	r12 = r1 * r1;
	if( r10 <= r12 ) goto label$83854ae_22_35;
	r11 = false;
	goto label$83854ae_22_36;
	label$83854ae_22_35:
	r11 = true;
	label$83854ae_22_36:
	return r11;
	label$83854ae_22_37:
	r10 = r4 * r4;
	r12 = r5 * r5;
	r10 = r10 + r12;
	r12 = r1 * r1;
	if( r10 < r12 ) goto label$83854ae_22_44;
	r11 = false;
	goto label$83854ae_22_45;
	label$83854ae_22_44:
	r11 = true;
	label$83854ae_22_45:
	return r11;
}

int flixel_math_FlxMath_getDecimals(double r0) {
	String r2, r4;
	hl__types__ArrayObj r1;
	vdynamic *r3;
	varray *r8;
	int r5, r6, r7;
	r3 = hl_alloc_dynamic(&t$_f64);
	r3->v.d = r0;
	r2 = Std_string(r3);
	if( r2 == NULL ) hl_null_access();
	r4 = (String)s$5058f1a;
	r1 = String_split(r2,r4);
	r5 = 0;
	if( r1 == NULL ) hl_null_access();
	r6 = r1->length;
	r7 = 1;
	if( r7 >= r6 ) goto label$83854ae_23_21;
	r6 = 1;
	r7 = r1->length;
	if( ((unsigned)r6) < ((unsigned)r7) ) goto label$83854ae_23_15;
	r2 = NULL;
	goto label$83854ae_23_18;
	label$83854ae_23_15:
	r8 = r1->array;
	r3 = ((vdynamic**)(r8 + 1))[r6];
	r2 = (String)r3;
	label$83854ae_23_18:
	if( r2 == NULL ) hl_null_access();
	r6 = r2->length;
	r5 = r6;
	label$83854ae_23_21:
	return r5;
}

bool flixel_math_FlxMath_equal(double r0,double r1,double* r2) {
	bool r4;
	double r3, r5;
	if( r2 ) goto label$83854ae_24_3;
	r3 = 9.9999999999999995e-008;
	goto label$83854ae_24_4;
	label$83854ae_24_3:
	r3 = *r2;
	label$83854ae_24_4:
	r5 = r0 - r1;
	r5 = hl_math_abs(r5);
	if( r5 <= r3 ) goto label$83854ae_24_9;
	r4 = false;
	goto label$83854ae_24_10;
	label$83854ae_24_9:
	r4 = true;
	label$83854ae_24_10:
	return r4;
}

int flixel_math_FlxMath_signOf(double r0) {
	double r1;
	int r2;
	r1 = 0.;
	if( !(r0 < r1) ) goto label$83854ae_25_4;
	r2 = -1;
	return r2;
	label$83854ae_25_4:
	r2 = 1;
	return r2;
}

bool flixel_math_FlxMath_sameSign(double r0,double r1) {
	bool r2;
	double r4;
	int r3, r5;
	r4 = 0.;
	if( !(r0 < r4) ) goto label$83854ae_26_4;
	r3 = -1;
	goto label$83854ae_26_5;
	label$83854ae_26_4:
	r3 = 1;
	label$83854ae_26_5:
	r4 = 0.;
	if( !(r1 < r4) ) goto label$83854ae_26_9;
	r5 = -1;
	goto label$83854ae_26_10;
	label$83854ae_26_9:
	r5 = 1;
	label$83854ae_26_10:
	if( r3 == r5 ) goto label$83854ae_26_13;
	r2 = false;
	goto label$83854ae_26_14;
	label$83854ae_26_13:
	r2 = true;
	label$83854ae_26_14:
	return r2;
}

double flixel_math_FlxMath_fastSin(double r0) {
	double r1, r2, r5, r6, r7, r8, r9, r10;
	int r3, r4;
	r2 = 0.3183098862;
	r1 = r0 * r2;
	r2 = 1.;
	if( !(r2 < r1) ) goto label$83854ae_27_12;
	r3 = hl_math_ceil(r1);
	r4 = 1;
	r3 = r3 >> r4;
	r4 = 1;
	r3 = r3 << r4;
	r2 = (double)r3;
	r1 = r1 - r2;
	goto label$83854ae_27_22;
	label$83854ae_27_12:
	r2 = -1.;
	if( !(r1 < r2) ) goto label$83854ae_27_22;
	r2 = -r1;
	r3 = hl_math_ceil(r2);
	r4 = 1;
	r3 = r3 >> r4;
	r4 = 1;
	r3 = r3 << r4;
	r2 = (double)r3;
	r1 = r1 + r2;
	label$83854ae_27_22:
	r2 = 0.;
	if( !(r2 < r1) ) goto label$83854ae_27_36;
	r2 = 3.1000000000000001;
	r6 = 0.5;
	r8 = -7.2000000000000002;
	r10 = 3.6000000000000001;
	r9 = r1 * r10;
	r8 = r8 + r9;
	r7 = r1 * r8;
	r6 = r6 + r7;
	r5 = r1 * r6;
	r2 = r2 + r5;
	r1 = r1 * r2;
	return r1;
	label$83854ae_27_36:
	r2 = 3.1000000000000001;
	r6 = 0.5;
	r8 = 7.2000000000000002;
	r10 = 3.6000000000000001;
	r9 = r1 * r10;
	r8 = r8 + r9;
	r7 = r1 * r8;
	r6 = r6 + r7;
	r5 = r1 * r6;
	r2 = r2 - r5;
	r1 = r1 * r2;
	return r1;
}

double flixel_math_FlxMath_fastCos(double r0) {
	double r1, r2, r3, r6, r7, r8, r9, r10, r11;
	int r4, r5;
	r2 = 1.570796327;
	r1 = r0 + r2;
	r3 = 0.3183098862;
	r2 = r1 * r3;
	r3 = 1.;
	if( !(r3 < r2) ) goto label$83854ae_28_14;
	r4 = hl_math_ceil(r2);
	r5 = 1;
	r4 = r4 >> r5;
	r5 = 1;
	r4 = r4 << r5;
	r3 = (double)r4;
	r2 = r2 - r3;
	goto label$83854ae_28_24;
	label$83854ae_28_14:
	r3 = -1.;
	if( !(r2 < r3) ) goto label$83854ae_28_24;
	r3 = -r2;
	r4 = hl_math_ceil(r3);
	r5 = 1;
	r4 = r4 >> r5;
	r5 = 1;
	r4 = r4 << r5;
	r3 = (double)r4;
	r2 = r2 + r3;
	label$83854ae_28_24:
	r3 = 0.;
	if( !(r3 < r2) ) goto label$83854ae_28_38;
	r3 = 3.1000000000000001;
	r7 = 0.5;
	r9 = -7.2000000000000002;
	r11 = 3.6000000000000001;
	r10 = r2 * r11;
	r9 = r9 + r10;
	r8 = r2 * r9;
	r7 = r7 + r8;
	r6 = r2 * r7;
	r3 = r3 + r6;
	r2 = r2 * r3;
	return r2;
	label$83854ae_28_38:
	r3 = 3.1000000000000001;
	r7 = 0.5;
	r9 = 7.2000000000000002;
	r11 = 3.6000000000000001;
	r10 = r2 * r11;
	r9 = r9 + r10;
	r8 = r2 * r9;
	r7 = r7 + r8;
	r6 = r2 * r7;
	r3 = r3 - r6;
	r2 = r2 * r3;
	return r2;
}

double flixel_math_FlxMath_sinh(double r0) {
	double r1, r2;
	r1 = hl_math_exp(r0);
	r2 = -r0;
	r2 = hl_math_exp(r2);
	r1 = r1 - r2;
	r2 = 2.;
	r1 = r1 / r2;
	return r1;
}

int flixel_math_FlxMath_maxInt(int r0,int r1) {
	if( r1 >= r0 ) goto label$83854ae_30_2;
	return r0;
	label$83854ae_30_2:
	return r1;
}

int flixel_math_FlxMath_minInt(int r0,int r1) {
	if( r1 >= r0 ) goto label$83854ae_31_2;
	return r1;
	label$83854ae_31_2:
	return r0;
}

int flixel_math_FlxMath_absInt(int r0) {
	int r1, r2;
	r2 = 0;
	if( r2 >= r0 ) goto label$83854ae_32_3;
	return r0;
	label$83854ae_32_3:
	r1 = -r0;
	return r1;
}

