// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__math__FlxMatrix
#define INC_flixel__math__FlxMatrix
typedef struct _flixel__math__$FlxMatrix *flixel__math__$FlxMatrix;
typedef struct _flixel__math__FlxMatrix *flixel__math__FlxMatrix;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <openfl/geom/Matrix.h>
#include <lime/utils/ArrayBufferView.h>


struct _flixel__math__$FlxMatrix {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _flixel__math__FlxMatrix {
	hl_type *$type;
	double a;
	double b;
	double c;
	double d;
	double tx;
	double ty;
	lime__utils__ArrayBufferView __array;
};
#endif

