// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__math__FlxVelocity
#define INC_flixel__math__FlxVelocity
typedef struct _flixel__math__$FlxVelocity *flixel__math__$FlxVelocity;
typedef struct _flixel__math__FlxVelocity *flixel__math__FlxVelocity;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <flixel/FlxSprite.h>
#include <flixel/math/FlxBasePoint.h>


struct _flixel__math__$FlxVelocity {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* moveTowardsObject;
	vclosure* accelerateTowardsObject;
	vclosure* moveTowardsMouse;
	vclosure* accelerateTowardsMouse;
	vclosure* moveTowardsPoint;
	vclosure* accelerateTowardsPoint;
	vclosure* velocityFromAngle;
	vclosure* velocityFromFacing;
	vclosure* computeVelocity;
	vclosure* accelerateFromAngle;
};
struct _flixel__math__FlxVelocity {
	hl_type *$type;
};
#endif

