// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__animation__FlxAnimationController
#define INC_flixel__animation__FlxAnimationController
typedef struct _flixel__animation__$FlxAnimationController *flixel__animation__$FlxAnimationController;
typedef struct _flixel__animation__FlxAnimationController *flixel__animation__FlxAnimationController;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <flixel/FlxSprite.h>
#include <flixel/animation/FlxAnimation.h>
#include <haxe/ds/StringMap.h>
#include <flixel/animation/FlxPrerotatedAnimation.h>


struct _flixel__animation__$FlxAnimationController {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _flixel__animation__FlxAnimationController {
	hl_type *$type;
	int frameIndex;
	vclosure* callback;
	vclosure* finishCallback;
	flixel__FlxSprite _sprite;
	flixel__animation__FlxAnimation _curAnim;
	haxe__ds__StringMap _animations;
	flixel__animation__FlxPrerotatedAnimation _prerotated;
	vvirtual* f$7;
};
#endif

