// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__utils___Endian__Endian_Impl_
#define INC_openfl__utils___Endian__Endian_Impl_
typedef struct _openfl__utils___Endian__$Endian_Impl_ *openfl__utils___Endian__$Endian_Impl_;
typedef struct _openfl__utils___Endian__Endian_Impl_ *openfl__utils___Endian__Endian_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <lime/system/Endian.h>


struct _openfl__utils___Endian__$Endian_Impl_ {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vdynamic* BIG_ENDIAN;
	vdynamic* LITTLE_ENDIAN;
	vclosure* fromLimeEndian;
	vclosure* fromString;
	vclosure* toLimeEndian;
	vclosure* toString;
};
struct _openfl__utils___Endian__Endian_Impl_ {
	hl_type *$type;
};
#endif

