// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__graphics__tile__FlxDrawItemType
#define INC_flixel__graphics__tile__FlxDrawItemType
typedef struct _flixel__graphics__tile__$FlxDrawItemType *flixel__graphics__tile__$FlxDrawItemType;
#include <hl/Enum.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>


struct _flixel__graphics__tile__$FlxDrawItemType {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __ename__;
	hl_bytes_map* __emap__;
	hl__types__ArrayObj __constructs__;
	varray* __evalues__;
};
#endif

