// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__text__harfbuzz__HBGlyphPosition
#define INC_lime__text__harfbuzz__HBGlyphPosition
typedef struct _lime__text__harfbuzz__$HBGlyphPosition *lime__text__harfbuzz__$HBGlyphPosition;
typedef struct _lime__text__harfbuzz__HBGlyphPosition *lime__text__harfbuzz__HBGlyphPosition;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__text__harfbuzz__$HBGlyphPosition {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__text__harfbuzz__HBGlyphPosition {
	hl_type *$type;
	int xAdvance;
	int xOffset;
	int yAdvance;
	int yOffset;
};
#endif

