// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__text__harfbuzz__HBSegmentProperties
#define INC_lime__text__harfbuzz__HBSegmentProperties
typedef struct _lime__text__harfbuzz__$HBSegmentProperties *lime__text__harfbuzz__$HBSegmentProperties;
typedef struct _lime__text__harfbuzz__HBSegmentProperties *lime__text__harfbuzz__HBSegmentProperties;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__text__harfbuzz__$HBSegmentProperties {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__text__harfbuzz__HBSegmentProperties {
	hl_type *$type;
};
#endif

