// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/display/_internal/_DrawCommandReader/BeginFillView_Impl_.h>
#include <hl/types/ArrayBytes_Int.h>
#include <openfl/display/_internal/DrawCommandBuffer.h>
#include <hl/types/ArrayBytes_Float.h>

openfl__display___internal__DrawCommandReader openfl_display__internal__DrawCommandReader_BeginFillView_Impl___new(openfl__display___internal__DrawCommandReader r0) {
	return r0;
}

int openfl_display__internal__DrawCommandReader_BeginFillView_Impl__get_color(openfl__display___internal__DrawCommandReader r0) {
	openfl__display___internal__DrawCommandBuffer r2;
	hl__types__ArrayBytes_Int r1;
	vbyte *r5;
	int r3, r4;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->buffer;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->i;
	if( r1 == NULL ) hl_null_access();
	r3 = r0->iPos;
	r4 = r1->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$64d0e16_2_10;
	r3 = 0;
	goto label$64d0e16_2_14;
	label$64d0e16_2_10:
	r5 = r1->bytes;
	r4 = 2;
	r4 = r3 << r4;
	r3 = *(int*)(r5 + r4);
	label$64d0e16_2_14:
	return r3;
}

double openfl_display__internal__DrawCommandReader_BeginFillView_Impl__get_alpha(openfl__display___internal__DrawCommandReader r0) {
	openfl__display___internal__DrawCommandBuffer r2;
	hl__types__ArrayBytes_Float r1;
	double r5;
	vbyte *r6;
	int r3, r4;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->buffer;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->f;
	if( r1 == NULL ) hl_null_access();
	r3 = r0->fPos;
	r4 = r1->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$64d0e16_3_10;
	r5 = 0.;
	goto label$64d0e16_3_14;
	label$64d0e16_3_10:
	r6 = r1->bytes;
	r4 = 3;
	r4 = r3 << r4;
	r5 = *(double*)(r6 + r4);
	label$64d0e16_3_14:
	return r5;
}

