// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__display___internal___DrawCommandReader__CurveToView_Impl_
#define INC_openfl__display___internal___DrawCommandReader__CurveToView_Impl_
typedef struct _openfl__display___internal___DrawCommandReader__$CurveToView_Impl_ *openfl__display___internal___DrawCommandReader__$CurveToView_Impl_;
typedef struct _openfl__display___internal___DrawCommandReader__CurveToView_Impl_ *openfl__display___internal___DrawCommandReader__CurveToView_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <openfl/display/_internal/DrawCommandReader.h>


struct _openfl__display___internal___DrawCommandReader__$CurveToView_Impl_ {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* _new;
	vclosure* get_controlX;
	vclosure* get_controlY;
	vclosure* get_anchorX;
	vclosure* get_anchorY;
};
struct _openfl__display___internal___DrawCommandReader__CurveToView_Impl_ {
	hl_type *$type;
};
#endif

