// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__display___internal___DrawCommandReader__LineGradientStyleView_Impl_
#define INC_openfl__display___internal___DrawCommandReader__LineGradientStyleView_Impl_
typedef struct _openfl__display___internal___DrawCommandReader__$LineGradientStyleView_Impl_ *openfl__display___internal___DrawCommandReader__$LineGradientStyleView_Impl_;
typedef struct _openfl__display___internal___DrawCommandReader__LineGradientStyleView_Impl_ *openfl__display___internal___DrawCommandReader__LineGradientStyleView_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <openfl/display/_internal/DrawCommandReader.h>
#include <hl/types/ArrayBytes_Int.h>
#include <hl/types/ArrayBytes_Float.h>
#include <openfl/geom/Matrix.h>


struct _openfl__display___internal___DrawCommandReader__$LineGradientStyleView_Impl_ {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* _new;
	vclosure* get_type;
	vclosure* get_colors;
	vclosure* get_alphas;
	vclosure* get_ratios;
	vclosure* get_matrix;
	vclosure* get_spreadMethod;
	vclosure* get_interpolationMethod;
	vclosure* get_focalPointRatio;
};
struct _openfl__display___internal___DrawCommandReader__LineGradientStyleView_Impl_ {
	hl_type *$type;
};
#endif

