// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/_internal/graphics/_ImageDataUtil/ImageDataView.h>
#include <lime/graphics/ImageBuffer.h>
lime__math__Rectangle lime_graphics_Image_get_rect(lime__graphics__Image);
int lime_graphics_ImageBuffer_get_stride(lime__graphics__ImageBuffer);
void lime__internal_graphics__ImageDataUtil_ImageDataView___update(lime___internal__graphics___ImageDataUtil__ImageDataView);
extern hl_type t$lime_math_Rectangle;
void lime_math_Rectangle_new(lime__math__Rectangle,double*,double*,double*,double*);
void lime_math_Rectangle_setTo(lime__math__Rectangle,double,double,double,double);
lime__math__Rectangle lime_math_Rectangle_intersection(lime__math__Rectangle,lime__math__Rectangle,lime__math__Rectangle);
#include <hl/natives.h>

void lime__internal_graphics__ImageDataUtil_ImageDataView_new(lime___internal__graphics___ImageDataUtil__ImageDataView r0,lime__graphics__Image r1,lime__math__Rectangle r2) {
	lime__graphics__ImageBuffer r8;
	double r5, r6;
	lime__math__Rectangle r4;
	int r7;
	r0->image = r1;
	if( r2 ) goto label$1fc2a00_1_6;
	if( r1 == NULL ) hl_null_access();
	r4 = lime_graphics_Image_get_rect(r1);
	r0->rect = r4;
	goto label$1fc2a00_1_51;
	label$1fc2a00_1_6:
	if( r2 == NULL ) hl_null_access();
	r5 = r2->x;
	r6 = 0.;
	if( !(r5 < r6) ) goto label$1fc2a00_1_12;
	r5 = 0.;
	r2->x = r5;
	label$1fc2a00_1_12:
	r5 = r2->y;
	r6 = 0.;
	if( !(r5 < r6) ) goto label$1fc2a00_1_17;
	r5 = 0.;
	r2->y = r5;
	label$1fc2a00_1_17:
	r5 = r2->x;
	r6 = r2->width;
	r5 = r5 + r6;
	if( r1 == NULL ) hl_null_access();
	r7 = r1->width;
	r6 = (double)r7;
	if( !(r6 < r5) ) goto label$1fc2a00_1_29;
	r7 = r1->width;
	r5 = (double)r7;
	r6 = r2->x;
	r5 = r5 - r6;
	r2->width = r5;
	label$1fc2a00_1_29:
	r5 = r2->y;
	r6 = r2->height;
	r5 = r5 + r6;
	r7 = r1->height;
	r6 = (double)r7;
	if( !(r6 < r5) ) goto label$1fc2a00_1_40;
	r7 = r1->height;
	r5 = (double)r7;
	r6 = r2->y;
	r5 = r5 - r6;
	r2->height = r5;
	label$1fc2a00_1_40:
	r5 = r2->width;
	r6 = 0.;
	if( !(r5 < r6) ) goto label$1fc2a00_1_45;
	r5 = 0.;
	r2->width = r5;
	label$1fc2a00_1_45:
	r5 = r2->height;
	r6 = 0.;
	if( !(r5 < r6) ) goto label$1fc2a00_1_50;
	r5 = 0.;
	r2->height = r5;
	label$1fc2a00_1_50:
	r0->rect = r2;
	label$1fc2a00_1_51:
	r8 = r1->buffer;
	if( r8 == NULL ) hl_null_access();
	r7 = lime_graphics_ImageBuffer_get_stride(r8);
	r0->stride = r7;
	lime__internal_graphics__ImageDataUtil_ImageDataView___update(r0);
	return;
}

void lime__internal_graphics__ImageDataUtil_ImageDataView_clip(lime___internal__graphics___ImageDataUtil__ImageDataView r0,int r1,int r2,int r3,int r4) {
	double r11, r12, r13, r14;
	lime__math__Rectangle r6, r15, r16;
	double *r7, *r8, *r9, *r10;
	r6 = r0->tempRect;
	if( r6 ) goto label$1fc2a00_2_9;
	r6 = (lime__math__Rectangle)hl_alloc_obj(&t$lime_math_Rectangle);
	r7 = NULL;
	r8 = NULL;
	r9 = NULL;
	r10 = NULL;
	lime_math_Rectangle_new(r6,r7,r8,r9,r10);
	r0->tempRect = r6;
	label$1fc2a00_2_9:
	r6 = r0->tempRect;
	if( r6 == NULL ) hl_null_access();
	r11 = (double)r1;
	r12 = (double)r2;
	r13 = (double)r3;
	r14 = (double)r4;
	lime_math_Rectangle_setTo(r6,r11,r12,r13,r14);
	r6 = r0->rect;
	if( r6 == NULL ) hl_null_access();
	r15 = r0->tempRect;
	r16 = r0->rect;
	r6 = lime_math_Rectangle_intersection(r6,r15,r16);
	lime__internal_graphics__ImageDataUtil_ImageDataView___update(r0);
	return;
}

bool lime__internal_graphics__ImageDataUtil_ImageDataView_hasRow(lime___internal__graphics___ImageDataUtil__ImageDataView r0,int r1) {
	bool r3;
	int r2;
	r2 = 0;
	if( r1 < r2 ) goto label$1fc2a00_3_8;
	r2 = r0->height;
	if( r1 < r2 ) goto label$1fc2a00_3_6;
	r3 = false;
	goto label$1fc2a00_3_7;
	label$1fc2a00_3_6:
	r3 = true;
	label$1fc2a00_3_7:
	return r3;
	label$1fc2a00_3_8:
	r3 = false;
	return r3;
}

void lime__internal_graphics__ImageDataUtil_ImageDataView_offset(lime___internal__graphics___ImageDataUtil__ImageDataView r0,int r1,int r2) {
	double r6, r7;
	lime__math__Rectangle r5;
	int r4;
	r4 = 0;
	if( r1 >= r4 ) goto label$1fc2a00_4_18;
	r5 = r0->rect;
	if( r5 == NULL ) hl_null_access();
	r6 = r5->x;
	r7 = (double)r1;
	r6 = r6 + r7;
	r5->x = r6;
	r5 = r0->rect;
	if( r5 == NULL ) hl_null_access();
	r6 = r5->x;
	r7 = 0.;
	if( !(r6 < r7) ) goto label$1fc2a00_4_17;
	r5 = r0->rect;
	if( r5 == NULL ) hl_null_access();
	r6 = 0.;
	r5->x = r6;
	label$1fc2a00_4_17:
	goto label$1fc2a00_4_30;
	label$1fc2a00_4_18:
	r5 = r0->rect;
	if( r5 == NULL ) hl_null_access();
	r6 = r5->x;
	r7 = (double)r1;
	r6 = r6 + r7;
	r5->x = r6;
	r5 = r0->rect;
	if( r5 == NULL ) hl_null_access();
	r6 = r5->width;
	r7 = (double)r1;
	r6 = r6 - r7;
	r5->width = r6;
	label$1fc2a00_4_30:
	r4 = 0;
	if( r2 >= r4 ) goto label$1fc2a00_4_48;
	r5 = r0->rect;
	if( r5 == NULL ) hl_null_access();
	r6 = r5->y;
	r7 = (double)r2;
	r6 = r6 + r7;
	r5->y = r6;
	r5 = r0->rect;
	if( r5 == NULL ) hl_null_access();
	r6 = r5->y;
	r7 = 0.;
	if( !(r6 < r7) ) goto label$1fc2a00_4_47;
	r5 = r0->rect;
	if( r5 == NULL ) hl_null_access();
	r6 = 0.;
	r5->y = r6;
	label$1fc2a00_4_47:
	goto label$1fc2a00_4_60;
	label$1fc2a00_4_48:
	r5 = r0->rect;
	if( r5 == NULL ) hl_null_access();
	r6 = r5->y;
	r7 = (double)r2;
	r6 = r6 + r7;
	r5->y = r6;
	r5 = r0->rect;
	if( r5 == NULL ) hl_null_access();
	r6 = r5->height;
	r7 = (double)r2;
	r6 = r6 - r7;
	r5->height = r6;
	label$1fc2a00_4_60:
	lime__internal_graphics__ImageDataUtil_ImageDataView___update(r0);
	return;
}

int lime__internal_graphics__ImageDataUtil_ImageDataView_row(lime___internal__graphics___ImageDataUtil__ImageDataView r0,int r1) {
	int r2, r3;
	r2 = r0->byteOffset;
	r3 = r0->stride;
	r3 = r3 * r1;
	r2 = r2 + r3;
	return r2;
}

void lime__internal_graphics__ImageDataUtil_ImageDataView___update(lime___internal__graphics___ImageDataUtil__ImageDataView r0) {
	lime__graphics__Image r6;
	lime__math__Rectangle r3;
	double r2;
	int r1, r4, r5;
	r3 = r0->rect;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->x;
	r1 = hl_math_ceil(r2);
	r0->x = r1;
	r3 = r0->rect;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->y;
	r1 = hl_math_ceil(r2);
	r0->y = r1;
	r3 = r0->rect;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->width;
	r1 = hl_math_floor(r2);
	r0->width = r1;
	r3 = r0->rect;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->height;
	r1 = hl_math_floor(r2);
	r0->height = r1;
	r1 = r0->stride;
	r4 = r0->y;
	r6 = r0->image;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->offsetY;
	r4 = r4 + r5;
	r1 = r1 * r4;
	r4 = r0->x;
	r6 = r0->image;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->offsetX;
	r4 = r4 + r5;
	r5 = 4;
	r4 = r4 * r5;
	r1 = r1 + r4;
	r0->byteOffset = r1;
	return;
}

