// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/media/vorbis/VorbisFile.h>
#include <hl/natives.h>
#include <hl/types/ArrayObj.h>
#include <lime/media/vorbis/VorbisComment.h>
extern hl_type t$vrt_fd13afc;
extern hl_type t$lime_media_vorbis_VorbisComment;
void lime_media_vorbis_VorbisComment_new(lime__media__vorbis__VorbisComment);
extern hl_type t$hl_types_ArrayObj;
extern hl_type t$String;
extern hl_type t$lime_media_vorbis_VorbisFile;
#include <lime/media/vorbis/VorbisInfo.h>
extern hl_type t$vrt_abad545;
extern hl_type t$lime_media_vorbis_VorbisInfo;
void lime_media_vorbis_VorbisInfo_new(lime__media__vorbis__VorbisInfo);
extern hl_type t$_i32;
#include <haxe/_Int64/Int64_Impl_.h>
extern hl_type t$vrt_6813d24;
extern haxe___Int64__$Int64_Impl_ g$_haxe__Int64_Int64_Impl_;
extern hl_type t$vrt_fa01dab;

void lime_media_vorbis_VorbisFile_new(lime__media__vorbis__VorbisFile r0,vdynamic* r1) {
	r0->handle = r1;
	return;
}

int lime_media_vorbis_VorbisFile_bitrate(lime__media__vorbis__VorbisFile r0,int* r1) {
	vdynamic *r4;
	int r2, r3;
	if( r1 ) goto label$a176188_2_3;
	r2 = -1;
	goto label$a176188_2_4;
	label$a176188_2_3:
	r2 = *r1;
	label$a176188_2_4:
	r4 = r0->handle;
	r3 = lime_hl_vorbis_file_bitrate(r4,r2);
	return r3;
}

int lime_media_vorbis_VorbisFile_bitrateInstant(lime__media__vorbis__VorbisFile r0) {
	vdynamic *r2;
	int r1;
	r2 = r0->handle;
	r1 = lime_hl_vorbis_file_bitrate_instant(r2);
	return r1;
}

void lime_media_vorbis_VorbisFile_clear(lime__media__vorbis__VorbisFile r0) {
	vdynamic *r2;
	r2 = r0->handle;
	lime_hl_vorbis_file_clear(r2);
	return;
}

lime__media__vorbis__VorbisComment lime_media_vorbis_VorbisFile_comment(lime__media__vorbis__VorbisFile r0,int* r1) {
	String r8;
	hl__types__ArrayObj r7;
	vvirtual *r4;
	lime__media__vorbis__VorbisComment r6;
	vdynamic *r3;
	int r2;
	if( r1 ) goto label$a176188_5_3;
	r2 = -1;
	goto label$a176188_5_4;
	label$a176188_5_3:
	r2 = *r1;
	label$a176188_5_4:
	r3 = r0->handle;
	r3 = lime_hl_vorbis_file_comment(r3,r2);
	r4 = hl_to_virtual(&t$vrt_fd13afc,(vdynamic*)r3);
	if( !r4 ) goto label$a176188_5_16;
	r6 = (lime__media__vorbis__VorbisComment)hl_alloc_obj(&t$lime_media_vorbis_VorbisComment);
	lime_media_vorbis_VorbisComment_new(r6);
	if( r4 == NULL ) hl_null_access();
	r7 = hl_vfields(r4)[0] ? (*(hl__types__ArrayObj*)(hl_vfields(r4)[0])) : (hl__types__ArrayObj)hl_dyn_getp(r4->value,401976233/*userComments*/,&t$hl_types_ArrayObj);
	r6->userComments = r7;
	r8 = hl_vfields(r4)[1] ? (*(String*)(hl_vfields(r4)[1])) : (String)hl_dyn_getp(r4->value,-23665671/*vendor*/,&t$String);
	r6->vendor = r8;
	return r6;
	label$a176188_5_16:
	r6 = NULL;
	return r6;
}

int lime_media_vorbis_VorbisFile_crosslap(lime__media__vorbis__VorbisFile r0,lime__media__vorbis__VorbisFile r1) {
	vdynamic *r3, *r4;
	int r2;
	r3 = r0->handle;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->handle;
	r2 = lime_hl_vorbis_file_crosslap(r3,r4);
	return r2;
}

lime__media__vorbis__VorbisFile lime_media_vorbis_VorbisFile_fromBytes(haxe__io__Bytes r0) {
	lime__media__vorbis__VorbisFile r3;
	vdynamic *r1;
	r1 = lime_hl_vorbis_file_from_bytes(r0);
	if( !r1 ) goto label$a176188_7_5;
	r3 = (lime__media__vorbis__VorbisFile)hl_alloc_obj(&t$lime_media_vorbis_VorbisFile);
	lime_media_vorbis_VorbisFile_new(r3,r1);
	return r3;
	label$a176188_7_5:
	r3 = NULL;
	return r3;
}

lime__media__vorbis__VorbisFile lime_media_vorbis_VorbisFile_fromFile(String r0) {
	lime__media__vorbis__VorbisFile r3;
	vdynamic *r1;
	r1 = lime_hl_vorbis_file_from_file(r0);
	if( !r1 ) goto label$a176188_8_5;
	r3 = (lime__media__vorbis__VorbisFile)hl_alloc_obj(&t$lime_media_vorbis_VorbisFile);
	lime_media_vorbis_VorbisFile_new(r3,r1);
	return r3;
	label$a176188_8_5:
	r3 = NULL;
	return r3;
}

lime__media__vorbis__VorbisInfo lime_media_vorbis_VorbisFile_info(lime__media__vorbis__VorbisFile r0,int* r1) {
	vvirtual *r5;
	lime__media__vorbis__VorbisInfo r7;
	vdynamic *r3;
	int r2, r4;
	if( r1 ) goto label$a176188_9_3;
	r2 = -1;
	goto label$a176188_9_4;
	label$a176188_9_3:
	r2 = *r1;
	label$a176188_9_4:
	r3 = r0->handle;
	r3 = lime_hl_vorbis_file_info(r3,r2);
	r5 = hl_to_virtual(&t$vrt_abad545,(vdynamic*)r3);
	if( !r5 ) goto label$a176188_9_24;
	r7 = (lime__media__vorbis__VorbisInfo)hl_alloc_obj(&t$lime_media_vorbis_VorbisInfo);
	lime_media_vorbis_VorbisInfo_new(r7);
	if( r5 == NULL ) hl_null_access();
	r4 = hl_vfields(r5)[0] ? (*(int*)(hl_vfields(r5)[0])) : (int)hl_dyn_geti(r5->value,164688020/*bitrateLower*/,&t$_i32);
	r7->bitrateLower = r4;
	r4 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,136873470/*bitrateNominal*/,&t$_i32);
	r7->bitrateNominal = r4;
	r4 = hl_vfields(r5)[2] ? (*(int*)(hl_vfields(r5)[2])) : (int)hl_dyn_geti(r5->value,420483194/*bitrateUpper*/,&t$_i32);
	r7->bitrateUpper = r4;
	r4 = hl_vfields(r5)[3] ? (*(int*)(hl_vfields(r5)[3])) : (int)hl_dyn_geti(r5->value,183413727/*channels*/,&t$_i32);
	r7->channels = r4;
	r4 = hl_vfields(r5)[4] ? (*(int*)(hl_vfields(r5)[4])) : (int)hl_dyn_geti(r5->value,195318762/*rate*/,&t$_i32);
	r7->rate = r4;
	r4 = hl_vfields(r5)[5] ? (*(int*)(hl_vfields(r5)[5])) : (int)hl_dyn_geti(r5->value,485615783/*version*/,&t$_i32);
	r7->version = r4;
	return r7;
	label$a176188_9_24:
	r7 = NULL;
	return r7;
}

int lime_media_vorbis_VorbisFile_pcmSeek(lime__media__vorbis__VorbisFile r0,int64 r1) {
	int64 r4, r6;
	vdynamic *r3;
	int r2, r5;
	r3 = r0->handle;
	r2 = (int)r1;
	r5 = 32;
	r6 = (int)r5;
	r4 = r1 >> r6;
	r5 = (int)r4;
	r2 = lime_hl_vorbis_file_pcm_seek(r3,r2,r5);
	return r2;
}

int lime_media_vorbis_VorbisFile_pcmSeekLap(lime__media__vorbis__VorbisFile r0,int64 r1) {
	int64 r4, r6;
	vdynamic *r3;
	int r2, r5;
	r3 = r0->handle;
	r2 = (int)r1;
	r5 = 32;
	r6 = (int)r5;
	r4 = r1 >> r6;
	r5 = (int)r4;
	r2 = lime_hl_vorbis_file_pcm_seek_lap(r3,r2,r5);
	return r2;
}

int lime_media_vorbis_VorbisFile_pcmSeekPage(lime__media__vorbis__VorbisFile r0,int64 r1) {
	int64 r4, r6;
	vdynamic *r3;
	int r2, r5;
	r3 = r0->handle;
	r2 = (int)r1;
	r5 = 32;
	r6 = (int)r5;
	r4 = r1 >> r6;
	r5 = (int)r4;
	r2 = lime_hl_vorbis_file_pcm_seek_page(r3,r2,r5);
	return r2;
}

int lime_media_vorbis_VorbisFile_pcmSeekPageLap(lime__media__vorbis__VorbisFile r0,int64 r1) {
	int64 r4, r6;
	vdynamic *r3;
	int r2, r5;
	r3 = r0->handle;
	r2 = (int)r1;
	r5 = 32;
	r6 = (int)r5;
	r4 = r1 >> r6;
	r5 = (int)r4;
	r2 = lime_hl_vorbis_file_pcm_seek_page_lap(r3,r2,r5);
	return r2;
}

int64 lime_media_vorbis_VorbisFile_pcmTell(lime__media__vorbis__VorbisFile r0) {
	vvirtual *r2;
	int64 r4, r5, r6, r7, r8;
	haxe___Int64__$Int64_Impl_ r9;
	vdynamic *r1;
	int r3;
	r1 = r0->handle;
	r1 = lime_hl_vorbis_file_pcm_tell(r1);
	r2 = hl_to_virtual(&t$vrt_6813d24,(vdynamic*)r1);
	if( !r2 ) goto label$a176188_14_17;
	if( r2 == NULL ) hl_null_access();
	r3 = hl_vfields(r2)[0] ? (*(int*)(hl_vfields(r2)[0])) : (int)hl_dyn_geti(r2->value,84818028/*high*/,&t$_i32);
	r4 = (int)r3;
	r3 = hl_vfields(r2)[1] ? (*(int*)(hl_vfields(r2)[1])) : (int)hl_dyn_geti(r2->value,5395604/*low*/,&t$_i32);
	r5 = (int)r3;
	r3 = 32;
	r7 = (int)r3;
	r6 = r4 << r7;
	r9 = (haxe___Int64__$Int64_Impl_)g$_haxe__Int64_Int64_Impl_;
	r8 = r9->MASK;
	r7 = r5 & r8;
	r6 = r6 | r7;
	return r6;
	label$a176188_14_17:
	r3 = 0;
	r4 = (int)r3;
	return r4;
}

int64 lime_media_vorbis_VorbisFile_pcmTotal(lime__media__vorbis__VorbisFile r0,int* r1) {
	vvirtual *r5;
	int64 r6, r7, r8, r9, r10;
	haxe___Int64__$Int64_Impl_ r11;
	vdynamic *r3;
	int r2, r4;
	if( r1 ) goto label$a176188_15_3;
	r2 = -1;
	goto label$a176188_15_4;
	label$a176188_15_3:
	r2 = *r1;
	label$a176188_15_4:
	r3 = r0->handle;
	r3 = lime_hl_vorbis_file_pcm_total(r3,r2);
	r5 = hl_to_virtual(&t$vrt_6813d24,(vdynamic*)r3);
	if( !r5 ) goto label$a176188_15_21;
	if( r5 == NULL ) hl_null_access();
	r4 = hl_vfields(r5)[0] ? (*(int*)(hl_vfields(r5)[0])) : (int)hl_dyn_geti(r5->value,84818028/*high*/,&t$_i32);
	r6 = (int)r4;
	r4 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,5395604/*low*/,&t$_i32);
	r7 = (int)r4;
	r4 = 32;
	r9 = (int)r4;
	r8 = r6 << r9;
	r11 = (haxe___Int64__$Int64_Impl_)g$_haxe__Int64_Int64_Impl_;
	r10 = r11->MASK;
	r9 = r7 & r10;
	r8 = r8 | r9;
	return r8;
	label$a176188_15_21:
	r4 = 0;
	r6 = (int)r4;
	return r6;
}

int lime_media_vorbis_VorbisFile_rawSeek(lime__media__vorbis__VorbisFile r0,int64 r1) {
	int64 r4, r6;
	vdynamic *r3;
	int r2, r5;
	r3 = r0->handle;
	r2 = (int)r1;
	r5 = 32;
	r6 = (int)r5;
	r4 = r1 >> r6;
	r5 = (int)r4;
	r2 = lime_hl_vorbis_file_raw_seek(r3,r2,r5);
	return r2;
}

int lime_media_vorbis_VorbisFile_rawSeekLap(lime__media__vorbis__VorbisFile r0,int64 r1) {
	int64 r4, r6;
	vdynamic *r3;
	int r2, r5;
	r3 = r0->handle;
	r2 = (int)r1;
	r5 = 32;
	r6 = (int)r5;
	r4 = r1 >> r6;
	r5 = (int)r4;
	r2 = lime_hl_vorbis_file_raw_seek_lap(r3,r2,r5);
	return r2;
}

int64 lime_media_vorbis_VorbisFile_rawTell(lime__media__vorbis__VorbisFile r0) {
	vvirtual *r2;
	int64 r4, r5, r6, r7, r8;
	haxe___Int64__$Int64_Impl_ r9;
	vdynamic *r1;
	int r3;
	r1 = r0->handle;
	r1 = lime_hl_vorbis_file_raw_tell(r1);
	r2 = hl_to_virtual(&t$vrt_6813d24,(vdynamic*)r1);
	if( !r2 ) goto label$a176188_18_17;
	if( r2 == NULL ) hl_null_access();
	r3 = hl_vfields(r2)[0] ? (*(int*)(hl_vfields(r2)[0])) : (int)hl_dyn_geti(r2->value,84818028/*high*/,&t$_i32);
	r4 = (int)r3;
	r3 = hl_vfields(r2)[1] ? (*(int*)(hl_vfields(r2)[1])) : (int)hl_dyn_geti(r2->value,5395604/*low*/,&t$_i32);
	r5 = (int)r3;
	r3 = 32;
	r7 = (int)r3;
	r6 = r4 << r7;
	r9 = (haxe___Int64__$Int64_Impl_)g$_haxe__Int64_Int64_Impl_;
	r8 = r9->MASK;
	r7 = r5 & r8;
	r6 = r6 | r7;
	return r6;
	label$a176188_18_17:
	r3 = 0;
	r4 = (int)r3;
	return r4;
}

int64 lime_media_vorbis_VorbisFile_rawTotal(lime__media__vorbis__VorbisFile r0,int* r1) {
	vvirtual *r5;
	int64 r6, r7, r8, r9, r10;
	haxe___Int64__$Int64_Impl_ r11;
	vdynamic *r3;
	int r2, r4;
	if( r1 ) goto label$a176188_19_3;
	r2 = -1;
	goto label$a176188_19_4;
	label$a176188_19_3:
	r2 = *r1;
	label$a176188_19_4:
	r3 = r0->handle;
	r3 = lime_hl_vorbis_file_raw_total(r3,r2);
	r5 = hl_to_virtual(&t$vrt_6813d24,(vdynamic*)r3);
	if( !r5 ) goto label$a176188_19_21;
	if( r5 == NULL ) hl_null_access();
	r4 = hl_vfields(r5)[0] ? (*(int*)(hl_vfields(r5)[0])) : (int)hl_dyn_geti(r5->value,84818028/*high*/,&t$_i32);
	r6 = (int)r4;
	r4 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,5395604/*low*/,&t$_i32);
	r7 = (int)r4;
	r4 = 32;
	r9 = (int)r4;
	r8 = r6 << r9;
	r11 = (haxe___Int64__$Int64_Impl_)g$_haxe__Int64_Int64_Impl_;
	r10 = r11->MASK;
	r9 = r7 & r10;
	r8 = r8 | r9;
	return r8;
	label$a176188_19_21:
	r4 = 0;
	r6 = (int)r4;
	return r6;
}

int lime_media_vorbis_VorbisFile_read(lime__media__vorbis__VorbisFile r0,haxe__io__Bytes r1,int r2,int* r3,bool* r4,int* r5,bool* r6) {
	vvirtual *r13;
	bool r8, r10;
	vdynamic *r11;
	int r7, r9, r12;
	if( r3 ) goto label$a176188_20_3;
	r7 = 4096;
	goto label$a176188_20_4;
	label$a176188_20_3:
	r7 = *r3;
	label$a176188_20_4:
	if( r4 ) goto label$a176188_20_7;
	r8 = false;
	goto label$a176188_20_8;
	label$a176188_20_7:
	r8 = *r4;
	label$a176188_20_8:
	if( r5 ) goto label$a176188_20_11;
	r9 = 2;
	goto label$a176188_20_12;
	label$a176188_20_11:
	r9 = *r5;
	label$a176188_20_12:
	if( r6 ) goto label$a176188_20_15;
	r10 = true;
	goto label$a176188_20_16;
	label$a176188_20_15:
	r10 = *r6;
	label$a176188_20_16:
	r11 = r0->handle;
	r11 = lime_hl_vorbis_file_read(r11,r1,r2,r7,r8,r9,r10);
	r13 = hl_to_virtual(&t$vrt_fa01dab,(vdynamic*)r11);
	if( r13 ) goto label$a176188_20_22;
	r12 = 0;
	return r12;
	label$a176188_20_22:
	if( r13 == NULL ) hl_null_access();
	r12 = hl_vfields(r13)[0] ? (*(int*)(hl_vfields(r13)[0])) : (int)hl_dyn_geti(r13->value,520217869/*bitstream*/,&t$_i32);
	r0->bitstream = r12;
	r12 = hl_vfields(r13)[1] ? (*(int*)(hl_vfields(r13)[1])) : (int)hl_dyn_geti(r13->value,513101094/*returnValue*/,&t$_i32);
	return r12;
}

int lime_media_vorbis_VorbisFile_readFloat(lime__media__vorbis__VorbisFile r0,haxe__io__Bytes r1,int r2) {
	vvirtual *r5;
	vdynamic *r3;
	int r4;
	r3 = r0->handle;
	r3 = lime_hl_vorbis_file_read_float(r3,r1,r2);
	r5 = hl_to_virtual(&t$vrt_fa01dab,(vdynamic*)r3);
	if( r5 ) goto label$a176188_21_6;
	r4 = 0;
	return r4;
	label$a176188_21_6:
	if( r5 == NULL ) hl_null_access();
	r4 = hl_vfields(r5)[0] ? (*(int*)(hl_vfields(r5)[0])) : (int)hl_dyn_geti(r5->value,520217869/*bitstream*/,&t$_i32);
	r0->bitstream = r4;
	r4 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,513101094/*returnValue*/,&t$_i32);
	return r4;
}

bool lime_media_vorbis_VorbisFile_seekable(lime__media__vorbis__VorbisFile r0) {
	bool r1;
	vdynamic *r2;
	r2 = r0->handle;
	r1 = lime_hl_vorbis_file_seekable(r2);
	return r1;
}

int lime_media_vorbis_VorbisFile_serialNumber(lime__media__vorbis__VorbisFile r0,int* r1) {
	vdynamic *r4;
	int r2, r3;
	if( r1 ) goto label$a176188_23_3;
	r2 = -1;
	goto label$a176188_23_4;
	label$a176188_23_3:
	r2 = *r1;
	label$a176188_23_4:
	r4 = r0->handle;
	r3 = lime_hl_vorbis_file_serial_number(r4,r2);
	return r3;
}

int lime_media_vorbis_VorbisFile_streams(lime__media__vorbis__VorbisFile r0) {
	vdynamic *r2;
	int r1;
	r2 = r0->handle;
	r1 = lime_hl_vorbis_file_streams(r2);
	return r1;
}

int lime_media_vorbis_VorbisFile_timeSeek(lime__media__vorbis__VorbisFile r0,double r1) {
	vdynamic *r3;
	int r2;
	r3 = r0->handle;
	r2 = lime_hl_vorbis_file_time_seek(r3,r1);
	return r2;
}

int lime_media_vorbis_VorbisFile_timeSeekLap(lime__media__vorbis__VorbisFile r0,double r1) {
	vdynamic *r3;
	int r2;
	r3 = r0->handle;
	r2 = lime_hl_vorbis_file_time_seek_lap(r3,r1);
	return r2;
}

int lime_media_vorbis_VorbisFile_timeSeekPage(lime__media__vorbis__VorbisFile r0,double r1) {
	vdynamic *r3;
	int r2;
	r3 = r0->handle;
	r2 = lime_hl_vorbis_file_time_seek_page(r3,r1);
	return r2;
}

int lime_media_vorbis_VorbisFile_timeSeekPageLap(lime__media__vorbis__VorbisFile r0,double r1) {
	vdynamic *r3;
	int r2;
	r3 = r0->handle;
	r2 = lime_hl_vorbis_file_time_seek_page_lap(r3,r1);
	return r2;
}

double lime_media_vorbis_VorbisFile_timeTell(lime__media__vorbis__VorbisFile r0) {
	double r1;
	vdynamic *r2;
	r2 = r0->handle;
	r1 = lime_hl_vorbis_file_time_tell(r2);
	return r1;
}

double lime_media_vorbis_VorbisFile_timeTotal(lime__media__vorbis__VorbisFile r0,int* r1) {
	double r3;
	vdynamic *r4;
	int r2;
	if( r1 ) goto label$a176188_30_3;
	r2 = -1;
	goto label$a176188_30_4;
	label$a176188_30_3:
	r2 = *r1;
	label$a176188_30_4:
	r4 = r0->handle;
	r3 = lime_hl_vorbis_file_time_total(r4,r2);
	return r3;
}

