// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime___internal__graphics__ImageDataUtil
#define INC_lime___internal__graphics__ImageDataUtil
typedef struct _lime___internal__graphics__$ImageDataUtil *lime___internal__graphics__$ImageDataUtil;
typedef struct _lime___internal__graphics__ImageDataUtil *lime___internal__graphics__ImageDataUtil;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <lime/graphics/Image.h>
#include <lime/math/Vector2.h>
#include <lime/math/Vector4.h>
#include <lime/math/Rectangle.h>
#include <lime/utils/ArrayBufferView.h>
#include <lime/graphics/ImageChannel.h>
#include <haxe/io/Bytes.h>
#include <lime/utils/BytePointerData.h>
#include <lime/system/Endian.h>
#include <hl/types/ArrayBytes_Float.h>


struct _lime___internal__graphics__$ImageDataUtil {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* displaceMap;
	vclosure* bilinear;
	vclosure* lerpRGBA;
	vclosure* lerp4f;
	vclosure* lerp;
	vclosure* colorTransform;
	vclosure* copyChannel;
	vclosure* copyPixels;
	vclosure* fillRect;
	vclosure* floodFill;
	vclosure* gaussianBlur;
	vclosure* getColorBoundsRect;
	vclosure* getPixel;
	vclosure* getPixel32;
	vclosure* getPixels;
	vclosure* merge;
	vclosure* multiplyAlpha;
	vclosure* resize;
	vclosure* resizeBuffer;
	vclosure* setFormat;
	vclosure* setPixel;
	vclosure* setPixel32;
	vclosure* setPixels;
	vclosure* threshold;
	vclosure* unmultiplyAlpha;
	vclosure* __boxBlur;
	vclosure* __boxBlurH;
	vclosure* __boxBlurT;
	vclosure* __calculateSourceOffset;
	vclosure* __getBoxesForGaussianBlur;
	vclosure* __pixelCompare;
	vclosure* __translatePixel;
};
struct _lime___internal__graphics__ImageDataUtil {
	hl_type *$type;
};
#endif

