// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime___internal__graphics__StackBlur
#define INC_lime___internal__graphics__StackBlur
typedef struct _lime___internal__graphics__$StackBlur *lime___internal__graphics__$StackBlur;
typedef struct _lime___internal__graphics__StackBlur *lime___internal__graphics__StackBlur;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayBytes_Int.h>
#include <lime/graphics/Image.h>
#include <lime/math/Rectangle.h>
#include <lime/math/Vector2.h>


struct _lime___internal__graphics__$StackBlur {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	hl__types__ArrayBytes_Int MUL_TABLE;
	hl__types__ArrayBytes_Int SHG_TABLE;
	vclosure* blur;
	vclosure* __stackBlurCanvasRGBA;
};
struct _lime___internal__graphics__StackBlur {
	hl_type *$type;
};
#endif

