// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__system__FlxAssets
#define INC_flixel__system__FlxAssets
typedef struct _flixel__system__$FlxAssets *flixel__system__$FlxAssets;
typedef struct _flixel__system__FlxAssets *flixel__system__FlxAssets;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <openfl/display/Graphics.h>
#include <openfl/display/BitmapData.h>
#include <openfl/media/Sound.h>
#include <flixel/graphics/frames/FlxAtlasFrames.h>


struct _flixel__system__$FlxAssets {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	String defaultSoundExtension;
	String FONT_DEFAULT;
	String FONT_DEBUGGER;
	vclosure* drawLogo;
	vclosure* getBitmapData;
	vclosure* getBitmapFromClass;
	vclosure* resolveBitmapData;
	vclosure* resolveKey;
	vclosure* getSound;
	vclosure* getVirtualInputFrames;
};
struct _flixel__system__FlxAssets {
	hl_type *$type;
};
#endif

