// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/system/VirtualInputData.h>
extern hl_type t$_i32;
void openfl_utils_ByteArrayData_new(openfl__utils__ByteArrayData,int*);
extern flixel__system__$VirtualInputData g$_flixel_system_VirtualInputData;
haxe__io__Bytes haxe_Resource_getBytes(String);
void openfl_utils_ByteArrayData___fromBytes(openfl__utils__ByteArrayData,haxe__io__Bytes);

void flixel_system_VirtualInputData_new(flixel__system__VirtualInputData r0,vdynamic* r1) {
	String r6;
	haxe__io__Bytes r5;
	flixel__system__$VirtualInputData r7;
	int *r4;
	int r2;
	if( r1 ) goto label$ebf4128_1_3;
	r2 = 0;
	r1 = hl_alloc_dynamic(&t$_i32);
	r1->v.i = r2;
	label$ebf4128_1_3:
	r4 = NULL;
	openfl_utils_ByteArrayData_new(((openfl__utils__ByteArrayData)r0),r4);
	r7 = (flixel__system__$VirtualInputData)g$_flixel_system_VirtualInputData;
	r6 = r7->resourceName;
	r5 = haxe_Resource_getBytes(r6);
	openfl_utils_ByteArrayData___fromBytes(((openfl__utils__ByteArrayData)r0),r5);
	return;
}

