// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__system__JNIMethod
#define INC_lime__system__JNIMethod
typedef struct _lime__system__$JNIMethod *lime__system__$JNIMethod;
typedef struct _lime__system__JNIMethod *lime__system__JNIMethod;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__system__$JNIMethod {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__system__JNIMethod {
	hl_type *$type;
	vdynamic* method;
};
#endif

