// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <lime/system/JNIMethod.h>
#include <hl/types/ArrayDyn.h>
extern hl_type t$fun_9cb06e9;
vdynamic* Reflect__makeVarArgs(vclosure*);

void lime_system_JNIMethod_new(lime__system__JNIMethod r0,vdynamic* r1) {
	r0->method = r1;
	return;
}

vdynamic* lime_system_JNIMethod_callMember(lime__system__JNIMethod r0,hl__types__ArrayDyn r1) {
	vdynamic *r2;
	r2 = NULL;
	return r2;
}

vdynamic* lime_system_JNIMethod_callStatic(lime__system__JNIMethod r0,hl__types__ArrayDyn r1) {
	vdynamic *r2;
	r2 = NULL;
	return r2;
}

vdynamic* lime_system_JNIMethod_getMemberMethod(lime__system__JNIMethod r0,bool r1) {
	vclosure *r2;
	vdynamic *r3;
	if( !r1 ) goto label$4eb5db8_4_3;
	r2 = hl_alloc_closure_ptr(&t$fun_9cb06e9,lime_system_JNIMethod_callMember,r0);
	return ((vdynamic*)r2);
	label$4eb5db8_4_3:
	r2 = hl_alloc_closure_ptr(&t$fun_9cb06e9,lime_system_JNIMethod_callMember,r0);
	r3 = Reflect__makeVarArgs(r2);
	return r3;
}

vdynamic* lime_system_JNIMethod_getStaticMethod(lime__system__JNIMethod r0,bool r1) {
	vclosure *r2;
	vdynamic *r3;
	if( !r1 ) goto label$4eb5db8_5_3;
	r2 = hl_alloc_closure_ptr(&t$fun_9cb06e9,lime_system_JNIMethod_callStatic,r0);
	return ((vdynamic*)r2);
	label$4eb5db8_5_3:
	r2 = hl_alloc_closure_ptr(&t$fun_9cb06e9,lime_system_JNIMethod_callStatic,r0);
	r3 = Reflect__makeVarArgs(r2);
	return r3;
}

