// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__system__JNIStaticField
#define INC_lime__system__JNIStaticField
typedef struct _lime__system__$JNIStaticField *lime__system__$JNIStaticField;
typedef struct _lime__system__JNIStaticField *lime__system__JNIStaticField;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _lime__system__$JNIStaticField {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _lime__system__JNIStaticField {
	hl_type *$type;
	vdynamic* field;
};
#endif

