// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__system__System
#define INC_lime__system__System
typedef struct _lime__system__$System *lime__system__$System;
typedef struct _lime__system__System *lime__system__System;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/ds/StringMap.h>
#include <haxe/ds/IntMap.h>
#include <lime/system/Endian.h>
#include <lime/system/Display.h>
#include <hl/types/ArrayObj.h>


struct _lime__system__$System {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	bool disableCFFI;
	String __applicationDirectory;
	haxe__ds__StringMap __applicationEntryPoint;
	String __applicationStorageDirectory;
	String __desktopDirectory;
	String __deviceModel;
	String __deviceVendor;
	haxe__ds__IntMap __directories;
	String __documentsDirectory;
	venum* __endianness;
	String __fontsDirectory;
	String __platformLabel;
	String __platformName;
	String __platformVersion;
	String __userDirectory;
	vclosure* exit;
	vclosure* getDisplay;
	vclosure* getTimer;
	vclosure* load;
	vclosure* openFile;
	vclosure* openURL;
	vclosure* __copyMissingFields;
	vclosure* __getDirectory;
	vclosure* __parseArguments;
	vclosure* __parseBool;
	vclosure* __registerEntryPoint;
	vclosure* __runProcess;
	vclosure* get_allowScreenTimeout;
	vclosure* set_allowScreenTimeout;
	vclosure* get_applicationDirectory;
	vclosure* get_applicationStorageDirectory;
	vclosure* get_deviceModel;
	vclosure* get_deviceVendor;
	vclosure* get_desktopDirectory;
	vclosure* get_documentsDirectory;
	vclosure* get_endianness;
	vclosure* get_fontsDirectory;
	vclosure* get_numDisplays;
	vclosure* get_platformLabel;
	vclosure* get_platformName;
	vclosure* get_platformVersion;
	vclosure* get_userDirectory;
};
struct _lime__system__System {
	hl_type *$type;
};
#endif

