// Generated by HLC 4.3.1 (HL v5)
#ifndef INC__std____ASSET__OPENFL__flixel_fonts_monsterrat_ttf
#define INC__std____ASSET__OPENFL__flixel_fonts_monsterrat_ttf
typedef struct _$__ASSET__OPENFL__flixel_fonts_monsterrat_ttf *$__ASSET__OPENFL__flixel_fonts_monsterrat_ttf;
typedef struct ___ASSET__OPENFL__flixel_fonts_monsterrat_ttf *__ASSET__OPENFL__flixel_fonts_monsterrat_ttf;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <openfl/text/Font.h>
#include <lime/text/Font.h>


struct _$__ASSET__OPENFL__flixel_fonts_monsterrat_ttf {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct ___ASSET__OPENFL__flixel_fonts_monsterrat_ttf {
	hl_type *$type;
	int ascender;
	int descender;
	int height;
	String name;
	int numGlyphs;
	vdynamic* src;
	int underlinePosition;
	int underlineThickness;
	int unitsPerEM;
	String __fontID;
	String __fontPath;
	String __fontPathWithoutDirectory;
	bool __init;
	vdynamic* fontStyle;
	vdynamic* fontType;
	bool __initialized;
};
#endif

