// Generated by HLC 4.3.1 (HL v5)
#ifndef INC__std____ASSET__flixel_sounds_flixel_ogg
#define INC__std____ASSET__flixel_sounds_flixel_ogg
typedef struct _$__ASSET__flixel_sounds_flixel_ogg *$__ASSET__flixel_sounds_flixel_ogg;
typedef struct ___ASSET__flixel_sounds_flixel_ogg *__ASSET__flixel_sounds_flixel_ogg;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/io/Bytes.h>


struct _$__ASSET__flixel_sounds_flixel_ogg {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	String resourceName;
};
struct ___ASSET__flixel_sounds_flixel_ogg {
	hl_type *$type;
	int length;
	vbyte* b;
};
#endif

