// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <_std/__ASSET__flixel_fonts_monsterrat_ttf.h>
#include <haxe/io/Bytes.h>
void lime_text_Font_new(lime__text__Font,String);
extern $__ASSET__flixel_fonts_monsterrat_ttf g$99a366f;
haxe__io__Bytes haxe_Resource_getBytes(String);
void lime_text_Font___fromBytes(lime__text__Font,haxe__io__Bytes);

void __ASSET__flixel_fonts_monsterrat_ttf_new(__ASSET__flixel_fonts_monsterrat_ttf r0) {
	String r2;
	haxe__io__Bytes r3;
	$__ASSET__flixel_fonts_monsterrat_ttf r4;
	r2 = NULL;
	lime_text_Font_new(((lime__text__Font)r0),r2);
	r4 = ($__ASSET__flixel_fonts_monsterrat_ttf)g$99a366f;
	r2 = r4->resourceName;
	r3 = haxe_Resource_getBytes(r2);
	lime_text_Font___fromBytes(((lime__text__Font)r0),r3);
	return;
}

