// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/util/FlxColorTransformUtil.h>

openfl__geom__ColorTransform flixel_util_FlxColorTransformUtil_setMultipliers(openfl__geom__ColorTransform r0,double r1,double r2,double r3,double r4) {
	if( r0 == NULL ) hl_null_access();
	r0->redMultiplier = r1;
	r0->greenMultiplier = r2;
	r0->blueMultiplier = r3;
	r0->alphaMultiplier = r4;
	return r0;
}

openfl__geom__ColorTransform flixel_util_FlxColorTransformUtil_setOffsets(openfl__geom__ColorTransform r0,int r1,int r2,int r3,int r4) {
	double r5;
	if( r0 == NULL ) hl_null_access();
	r5 = (double)r1;
	r0->redOffset = r5;
	r5 = (double)r2;
	r0->greenOffset = r5;
	r5 = (double)r3;
	r0->blueOffset = r5;
	r5 = (double)r4;
	r0->alphaOffset = r5;
	return r0;
}

bool flixel_util_FlxColorTransformUtil_hasRGBMultipliers(openfl__geom__ColorTransform r0) {
	bool r3;
	double r1, r2;
	if( r0 == NULL ) hl_null_access();
	r1 = r0->redMultiplier;
	r2 = 1.;
	if( r1 != r2 ) goto label$894f36c_3_14;
	r1 = r0->greenMultiplier;
	r2 = 1.;
	if( r1 != r2 ) goto label$894f36c_3_14;
	r1 = r0->blueMultiplier;
	r2 = 1.;
	if( r1 != r2 ) goto label$894f36c_3_12;
	r3 = false;
	goto label$894f36c_3_13;
	label$894f36c_3_12:
	r3 = true;
	label$894f36c_3_13:
	return r3;
	label$894f36c_3_14:
	r3 = true;
	return r3;
}

bool flixel_util_FlxColorTransformUtil_hasRGBAMultipliers(openfl__geom__ColorTransform r0) {
	bool r1;
	double r2, r3;
	r1 = flixel_util_FlxColorTransformUtil_hasRGBMultipliers(r0);
	if( r1 ) goto label$894f36c_4_10;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->alphaMultiplier;
	r3 = 1.;
	if( r2 != r3 ) goto label$894f36c_4_8;
	r1 = false;
	goto label$894f36c_4_9;
	label$894f36c_4_8:
	r1 = true;
	label$894f36c_4_9:
	return r1;
	label$894f36c_4_10:
	r1 = true;
	return r1;
}

bool flixel_util_FlxColorTransformUtil_hasRGBOffsets(openfl__geom__ColorTransform r0) {
	bool r3;
	double r1, r2;
	if( r0 == NULL ) hl_null_access();
	r1 = r0->redOffset;
	r2 = 0.;
	if( r1 != r2 ) goto label$894f36c_5_14;
	r1 = r0->greenOffset;
	r2 = 0.;
	if( r1 != r2 ) goto label$894f36c_5_14;
	r1 = r0->blueOffset;
	r2 = 0.;
	if( r1 != r2 ) goto label$894f36c_5_12;
	r3 = false;
	goto label$894f36c_5_13;
	label$894f36c_5_12:
	r3 = true;
	label$894f36c_5_13:
	return r3;
	label$894f36c_5_14:
	r3 = true;
	return r3;
}

bool flixel_util_FlxColorTransformUtil_hasRGBAOffsets(openfl__geom__ColorTransform r0) {
	bool r1;
	double r2, r3;
	r1 = flixel_util_FlxColorTransformUtil_hasRGBOffsets(r0);
	if( r1 ) goto label$894f36c_6_10;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->alphaOffset;
	r3 = 0.;
	if( r2 != r3 ) goto label$894f36c_6_8;
	r1 = false;
	goto label$894f36c_6_9;
	label$894f36c_6_8:
	r1 = true;
	label$894f36c_6_9:
	return r1;
	label$894f36c_6_10:
	r1 = true;
	return r1;
}

