// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/util/FlxPool.h>
#include <hl/types/ArrayObj.h>
extern hl_type t$_dyn;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
#include <hl/types/ArrayBase.h>
hl__types__ArrayDyn hl_types_ArrayDyn_alloc(hl__types__ArrayBase,bool*);
vdynamic* Type_createInstance(hl__Class,hl__types__ArrayDyn);
int hl_types_ArrayDyn_indexOf(hl__types__ArrayDyn,vdynamic*,vdynamic*);
extern hl_type t$fun_7b48b4f;

vdynamic* flixel_util_FlxPool_get(flixel__util__FlxPool r0) {
	bool *r10;
	hl__Class r4;
	hl__types__ArrayObj r8;
	hl_type *r7;
	bool r9;
	hl__types__ArrayDyn r5;
	vdynamic *r3;
	varray *r6;
	int r1, r2;
	r1 = r0->_count;
	r2 = 0;
	if( r1 != r2 ) goto label$3992dcf_1_13;
	r4 = r0->_class;
	r7 = &t$_dyn;
	r1 = 0;
	r6 = hl_alloc_array(r7,r1);
	r8 = hl_types_ArrayObj_alloc(r6);
	r9 = true;
	r10 = &r9;
	r5 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r8),r10);
	r3 = Type_createInstance(r4,r5);
	return r3;
	label$3992dcf_1_13:
	r5 = r0->_pool;
	if( r5 == NULL ) hl_null_access();
	r1 = r0->_count;
	--r1;
	r0->_count = r1;
	r3 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r5->$type->vobj_proto[0])(r5,r1);
	return r3;
}

void flixel_util_FlxPool_put(flixel__util__FlxPool r0,vdynamic* r1) {
	vclosure *r8;
	hl__types__ArrayDyn r4;
	vdynamic *r5;
	int r3, r6, r7;
	if( !r1 ) goto label$3992dcf_2_20;
	r4 = r0->_pool;
	if( r4 == NULL ) hl_null_access();
	r5 = NULL;
	r3 = hl_types_ArrayDyn_indexOf(r4,r1,r5);
	r7 = -1;
	if( r3 == r7 ) goto label$3992dcf_2_9;
	r7 = r0->_count;
	if( r3 < r7 ) goto label$3992dcf_2_20;
	label$3992dcf_2_9:
	if( r1 == NULL ) hl_null_access();
	r8 = (vclosure*)hl_dyn_getp((vdynamic*)r1,75902335/*destroy*/,&t$fun_7b48b4f);
	if( r8 == NULL ) hl_null_access();
	r8->hasValue ? ((void (*)(vdynamic*))r8->fun)((vdynamic*)r8->value) : ((void (*)(void))r8->fun)();
	r4 = r0->_pool;
	if( r4 == NULL ) hl_null_access();
	r6 = r0->_count;
	r7 = r6;
	++r6;
	r0->_count = r6;
	((void (*)(hl__types__ArrayDyn,int,vdynamic*))r4->$type->vobj_proto[1])(r4,r7,r1);
	label$3992dcf_2_20:
	return;
}

void flixel_util_FlxPool_putUnsafe(flixel__util__FlxPool r0,vdynamic* r1) {
	hl__types__ArrayDyn r4;
	vclosure *r3;
	int r5, r6;
	if( !r1 ) goto label$3992dcf_3_12;
	if( r1 == NULL ) hl_null_access();
	r3 = (vclosure*)hl_dyn_getp((vdynamic*)r1,75902335/*destroy*/,&t$fun_7b48b4f);
	if( r3 == NULL ) hl_null_access();
	r3->hasValue ? ((void (*)(vdynamic*))r3->fun)((vdynamic*)r3->value) : ((void (*)(void))r3->fun)();
	r4 = r0->_pool;
	if( r4 == NULL ) hl_null_access();
	r5 = r0->_count;
	r6 = r5;
	++r5;
	r0->_count = r5;
	((void (*)(hl__types__ArrayDyn,int,vdynamic*))r4->$type->vobj_proto[1])(r4,r6,r1);
	label$3992dcf_3_12:
	return;
}

void flixel_util_FlxPool_preAllocate(flixel__util__FlxPool r0,int r1) {
	bool *r12;
	hl__Class r6;
	hl__types__ArrayObj r10;
	hl_type *r9;
	bool r11;
	hl__types__ArrayDyn r4, r7;
	vdynamic *r5;
	varray *r8;
	int r2, r3;
	label$3992dcf_4_0:
	r2 = r1;
	--r1;
	r3 = 0;
	if( r3 >= r2 ) goto label$3992dcf_4_22;
	r4 = r0->_pool;
	if( r4 == NULL ) hl_null_access();
	r2 = r0->_count;
	r3 = r2;
	++r2;
	r0->_count = r2;
	r6 = r0->_class;
	r9 = &t$_dyn;
	r2 = 0;
	r8 = hl_alloc_array(r9,r2);
	r10 = hl_types_ArrayObj_alloc(r8);
	r11 = true;
	r12 = &r11;
	r7 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r10),r12);
	r5 = Type_createInstance(r6,r7);
	((void (*)(hl__types__ArrayDyn,int,vdynamic*))r4->$type->vobj_proto[1])(r4,r3,r5);
	goto label$3992dcf_4_0;
	label$3992dcf_4_22:
	return;
}

hl__types__ArrayDyn flixel_util_FlxPool_clear(flixel__util__FlxPool r0) {
	bool *r8;
	hl__types__ArrayObj r6;
	hl_type *r5;
	bool r7;
	hl__types__ArrayDyn r2, r3;
	varray *r4;
	int r1;
	r1 = 0;
	r0->_count = r1;
	r2 = r0->_pool;
	r5 = &t$_dyn;
	r1 = 0;
	r4 = hl_alloc_array(r5,r1);
	r6 = hl_types_ArrayObj_alloc(r4);
	r7 = true;
	r8 = &r7;
	r3 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r6),r8);
	r0->_pool = r3;
	return r2;
}

int flixel_util_FlxPool_get_length(flixel__util__FlxPool r0) {
	int r1;
	r1 = r0->_count;
	return r1;
}

void flixel_util_FlxPool_new(flixel__util__FlxPool r0,hl__Class r1) {
	bool *r8;
	hl__types__ArrayObj r6;
	hl_type *r5;
	bool r7;
	hl__types__ArrayDyn r3;
	varray *r4;
	int r2;
	r2 = 0;
	r0->_count = r2;
	r5 = &t$_dyn;
	r2 = 0;
	r4 = hl_alloc_array(r5,r2);
	r6 = hl_types_ArrayObj_alloc(r4);
	r7 = true;
	r8 = &r7;
	r3 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r6),r8);
	r0->_pool = r3;
	r0->_class = r1;
	return;
}

