// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/util/FlxPool_flixel_effects_FlxFlicker.h>
#include <flixel/effects/FlxFlicker.h>
extern hl_type t$_dyn;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
#include <hl/types/ArrayBase.h>
hl__types__ArrayDyn hl_types_ArrayDyn_alloc(hl__types__ArrayBase,bool*);
vdynamic* Type_createInstance(hl__Class,hl__types__ArrayDyn);
extern hl_type t$flixel_effects_FlxFlicker;
int hl_types_ArrayObj_indexOf(hl__types__ArrayObj,vdynamic*,vdynamic*);
void flixel_effects_FlxFlicker_destroy(flixel__effects__FlxFlicker);
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);

flixel__effects__FlxFlicker flixel_util_FlxPool_flixel_effects_FlxFlicker_get(flixel__util__FlxPool_flixel_effects_FlxFlicker r0) {
	bool *r10;
	hl__Class r4;
	hl__types__ArrayObj r8;
	hl_type *r7;
	bool r9;
	hl__types__ArrayDyn r5;
	vdynamic *r3;
	flixel__effects__FlxFlicker r11;
	varray *r6;
	int r1, r2;
	r1 = r0->_count;
	r2 = 0;
	if( r1 != r2 ) goto label$b3be65e_1_14;
	r4 = r0->_class;
	r7 = &t$_dyn;
	r1 = 0;
	r6 = hl_alloc_array(r7,r1);
	r8 = hl_types_ArrayObj_alloc(r6);
	r9 = true;
	r10 = &r9;
	r5 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r8),r10);
	r3 = Type_createInstance(r4,r5);
	r11 = (flixel__effects__FlxFlicker)hl_dyn_castp(&r3,&t$_dyn,&t$flixel_effects_FlxFlicker);
	return r11;
	label$b3be65e_1_14:
	r8 = r0->_pool;
	if( r8 == NULL ) hl_null_access();
	r1 = r0->_count;
	--r1;
	r0->_count = r1;
	r2 = r8->length;
	if( ((unsigned)r1) < ((unsigned)r2) ) goto label$b3be65e_1_23;
	r11 = NULL;
	goto label$b3be65e_1_26;
	label$b3be65e_1_23:
	r6 = r8->array;
	r3 = ((vdynamic**)(r6 + 1))[r1];
	r11 = (flixel__effects__FlxFlicker)r3;
	label$b3be65e_1_26:
	return r11;
}

void flixel_util_FlxPool_flixel_effects_FlxFlicker_put(flixel__util__FlxPool_flixel_effects_FlxFlicker r0,flixel__effects__FlxFlicker r1) {
	hl__types__ArrayObj r4;
	vdynamic *r5;
	varray *r8;
	int r3, r6, r7;
	if( !r1 ) goto label$b3be65e_2_22;
	r4 = r0->_pool;
	if( r4 == NULL ) hl_null_access();
	r5 = NULL;
	r3 = hl_types_ArrayObj_indexOf(r4,((vdynamic*)r1),r5);
	r7 = -1;
	if( r3 == r7 ) goto label$b3be65e_2_9;
	r7 = r0->_count;
	if( r3 < r7 ) goto label$b3be65e_2_22;
	label$b3be65e_2_9:
	if( r1 == NULL ) hl_null_access();
	flixel_effects_FlxFlicker_destroy(r1);
	r4 = r0->_pool;
	if( r4 == NULL ) hl_null_access();
	r6 = r0->_count;
	r7 = r6;
	++r6;
	r0->_count = r6;
	r6 = r4->length;
	if( ((unsigned)r7) < ((unsigned)r6) ) goto label$b3be65e_2_20;
	hl_types_ArrayObj___expand(r4,r7);
	label$b3be65e_2_20:
	r8 = r4->array;
	((flixel__effects__FlxFlicker*)(r8 + 1))[r7] = r1;
	label$b3be65e_2_22:
	return;
}

void flixel_util_FlxPool_flixel_effects_FlxFlicker_putUnsafe(flixel__util__FlxPool_flixel_effects_FlxFlicker r0,flixel__effects__FlxFlicker r1) {
	hl__types__ArrayObj r3;
	varray *r6;
	int r4, r5;
	if( !r1 ) goto label$b3be65e_3_14;
	if( r1 == NULL ) hl_null_access();
	flixel_effects_FlxFlicker_destroy(r1);
	r3 = r0->_pool;
	if( r3 == NULL ) hl_null_access();
	r4 = r0->_count;
	r5 = r4;
	++r4;
	r0->_count = r4;
	r4 = r3->length;
	if( ((unsigned)r5) < ((unsigned)r4) ) goto label$b3be65e_3_12;
	hl_types_ArrayObj___expand(r3,r5);
	label$b3be65e_3_12:
	r6 = r3->array;
	((flixel__effects__FlxFlicker*)(r6 + 1))[r5] = r1;
	label$b3be65e_3_14:
	return;
}

void flixel_util_FlxPool_flixel_effects_FlxFlicker_preAllocate(flixel__util__FlxPool_flixel_effects_FlxFlicker r0,int r1) {
	bool *r12;
	hl__Class r6;
	hl__types__ArrayObj r4, r10;
	hl_type *r9;
	bool r11;
	hl__types__ArrayDyn r7;
	vdynamic *r5;
	flixel__effects__FlxFlicker r13;
	varray *r8;
	int r2, r3;
	label$b3be65e_4_0:
	r2 = r1;
	--r1;
	r3 = 0;
	if( r3 >= r2 ) goto label$b3be65e_4_27;
	r4 = r0->_pool;
	if( r4 == NULL ) hl_null_access();
	r2 = r0->_count;
	r3 = r2;
	++r2;
	r0->_count = r2;
	r6 = r0->_class;
	r9 = &t$_dyn;
	r2 = 0;
	r8 = hl_alloc_array(r9,r2);
	r10 = hl_types_ArrayObj_alloc(r8);
	r11 = true;
	r12 = &r11;
	r7 = hl_types_ArrayDyn_alloc(((hl__types__ArrayBase)r10),r12);
	r5 = Type_createInstance(r6,r7);
	r13 = (flixel__effects__FlxFlicker)hl_dyn_castp(&r5,&t$_dyn,&t$flixel_effects_FlxFlicker);
	r2 = r4->length;
	if( ((unsigned)r3) < ((unsigned)r2) ) goto label$b3be65e_4_24;
	hl_types_ArrayObj___expand(r4,r3);
	label$b3be65e_4_24:
	r8 = r4->array;
	((flixel__effects__FlxFlicker*)(r8 + 1))[r3] = r13;
	goto label$b3be65e_4_0;
	label$b3be65e_4_27:
	return;
}

hl__types__ArrayObj flixel_util_FlxPool_flixel_effects_FlxFlicker_clear(flixel__util__FlxPool_flixel_effects_FlxFlicker r0) {
	hl__types__ArrayObj r2, r3;
	hl_type *r5;
	varray *r4;
	int r1;
	r1 = 0;
	r0->_count = r1;
	r2 = r0->_pool;
	r5 = &t$flixel_effects_FlxFlicker;
	r1 = 0;
	r4 = hl_alloc_array(r5,r1);
	r3 = hl_types_ArrayObj_alloc(r4);
	r0->_pool = r3;
	return r2;
}

int flixel_util_FlxPool_flixel_effects_FlxFlicker_get_length(flixel__util__FlxPool_flixel_effects_FlxFlicker r0) {
	int r1;
	r1 = r0->_count;
	return r1;
}

void flixel_util_FlxPool_flixel_effects_FlxFlicker_new(flixel__util__FlxPool_flixel_effects_FlxFlicker r0,hl__Class r1) {
	hl__types__ArrayObj r3;
	hl_type *r5;
	varray *r4;
	int r2;
	r2 = 0;
	r0->_count = r2;
	r5 = &t$flixel_effects_FlxFlicker;
	r2 = 0;
	r4 = hl_alloc_array(r5,r2);
	r3 = hl_types_ArrayObj_alloc(r4);
	r0->_pool = r3;
	r0->_class = r1;
	return;
}

