// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__util__FlxSpriteUtil
#define INC_flixel__util__FlxSpriteUtil
typedef struct _flixel__util__$FlxSpriteUtil *flixel__util__$FlxSpriteUtil;
typedef struct _flixel__util__FlxSpriteUtil *flixel__util__FlxSpriteUtil;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <openfl/display/Sprite.h>
#include <openfl/display/Graphics.h>
#include <flixel/FlxSprite.h>
#include <flixel/FlxCamera.h>
#include <hl/types/ArrayObj.h>
#include <flixel/FlxObject.h>
#include <openfl/geom/Rectangle.h>
#include <openfl/geom/ColorTransform.h>
#include <openfl/geom/Matrix.h>
#include <flixel/effects/FlxFlicker.h>
#include <flixel/tweens/FlxTween.h>


struct _flixel__util__$FlxSpriteUtil {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	openfl__display__Sprite flashGfxSprite;
	openfl__display__Graphics flashGfx;
	vclosure* alphaMask;
	vclosure* alphaMaskFlxSprite;
	vclosure* screenWrap;
	vclosure* bound;
	vclosure* cameraWrap;
	vclosure* cameraBound;
	vclosure* space;
	vclosure* drawLine;
	vclosure* drawCurve;
	vclosure* drawRect;
	vclosure* drawRoundRect;
	vclosure* drawRoundRectComplex;
	vclosure* drawCircle;
	vclosure* drawEllipse;
	vclosure* drawTriangle;
	vclosure* drawPolygon;
	vclosure* beginDraw;
	vclosure* endDraw;
	vclosure* updateSpriteGraphic;
	vclosure* setLineStyle;
	vclosure* getDefaultLineStyle;
	vclosure* fill;
	vclosure* flicker;
	vclosure* isFlickering;
	vclosure* stopFlickering;
	vclosure* fadeIn;
	vclosure* fadeOut;
	vclosure* alphaTween;
};
struct _flixel__util__FlxSpriteUtil {
	hl_type *$type;
};
#endif

