// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/util/FlxTimerManager.h>
#include <hl/types/ArrayDyn.h>
#include <flixel/util/_FlxSignal/FlxSignal0.h>
#include <flixel/system/frontEnds/SignalFrontEnd.h>
#include <flixel/FlxG.h>
extern hl_type t$hl_types_ArrayDyn;
extern hl_type t$hl_types_ArrayObj;
hl__types__ArrayDyn flixel_util_FlxArrayUtil_clearArray(hl__types__ArrayDyn,bool*);
extern flixel__$FlxG g$_flixel_FlxG;
void flixel_util_FlxTimerManager_clear(flixel__util__FlxTimerManager);
extern hl_type t$fun_85f8432;
#include <flixel/util/_FlxSignal/FlxBaseSignal.h>
void flixel_util__FlxSignal_FlxBaseSignal_remove(flixel__util___FlxSignal__FlxBaseSignal,vdynamic*);
void flixel_FlxBasic_destroy(flixel__FlxBasic);
#include <flixel/util/FlxTimer.h>
void flixel_util_FlxTimer_update(flixel__util__FlxTimer,double);
extern hl_type t$flixel_util_FlxTimer;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
vdynamic* hl_types_ArrayObj_shift(hl__types__ArrayObj);
void flixel_util_FlxTimer_onLoopFinished(flixel__util__FlxTimer);
int hl_types_ArrayObj_indexOf(hl__types__ArrayObj,vdynamic*,vdynamic*);
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);
vdynamic* hl_types_ArrayObj_pop(hl__types__ArrayObj);
void flixel_FlxBasic_new(flixel__FlxBasic);
bool flixel_FlxBasic_set_visible(flixel__FlxBasic,bool);
void flixel_util__FlxSignal_FlxBaseSignal_add(flixel__util___FlxSignal__FlxBaseSignal,vdynamic*);

void flixel_util_FlxTimerManager_destroy(flixel__util__FlxTimerManager r0) {
	bool *r3;
	hl__types__ArrayObj r2;
	flixel__$FlxG r7;
	flixel__system__frontEnds__SignalFrontEnd r6;
	flixel__util___FlxSignal__FlxSignal0 r5;
	vclosure *r8;
	hl__types__ArrayDyn r1;
	r2 = r0->_timers;
	r1 = (hl__types__ArrayDyn)hl_dyn_castp(&r2,&t$hl_types_ArrayObj,&t$hl_types_ArrayDyn);
	r3 = NULL;
	r1 = flixel_util_FlxArrayUtil_clearArray(r1,r3);
	r2 = (hl__types__ArrayObj)hl_dyn_castp(&r1,&t$hl_types_ArrayDyn,&t$hl_types_ArrayObj);
	r2 = NULL;
	r0->_timers = r2;
	r7 = (flixel__$FlxG)g$_flixel_FlxG;
	r6 = r7->signals;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->preStateSwitch;
	if( r5 == NULL ) hl_null_access();
	r8 = hl_alloc_closure_ptr(&t$fun_85f8432,flixel_util_FlxTimerManager_clear,r0);
	flixel_util__FlxSignal_FlxBaseSignal_remove(((flixel__util___FlxSignal__FlxBaseSignal)r5),((vdynamic*)r8));
	flixel_FlxBasic_destroy(((flixel__FlxBasic)r0));
	return;
}

void flixel_util_FlxTimerManager_update(flixel__util__FlxTimerManager r0,double r1) {
	hl__types__ArrayObj r2, r5, r8;
	hl_type *r16;
	bool r12;
	flixel__util__FlxTimer r9;
	double r13, r14;
	vdynamic *r10;
	varray *r11;
	int r4, r6, r7, r15;
	r2 = NULL;
	r4 = 0;
	r5 = r0->_timers;
	label$0b61a7c_2_3:
	if( r5 == NULL ) hl_null_access();
	r7 = r5->length;
	if( r4 >= r7 ) goto label$0b61a7c_2_36;
	r7 = r5->length;
	if( ((unsigned)r4) < ((unsigned)r7) ) goto label$0b61a7c_2_11;
	r9 = NULL;
	goto label$0b61a7c_2_14;
	label$0b61a7c_2_11:
	r11 = r5->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (flixel__util__FlxTimer)r10;
	label$0b61a7c_2_14:
	++r4;
	if( r9 == NULL ) hl_null_access();
	r12 = r9->active;
	if( !r12 ) goto label$0b61a7c_2_35;
	r12 = r9->finished;
	if( r12 ) goto label$0b61a7c_2_35;
	r13 = r9->time;
	r14 = 0.;
	if( !(r13 >= r14) ) goto label$0b61a7c_2_35;
	r6 = r9->_loopsCounter;
	flixel_util_FlxTimer_update(r9,r1);
	r15 = r9->_loopsCounter;
	if( r6 == r15 ) goto label$0b61a7c_2_35;
	if( r2 ) goto label$0b61a7c_2_33;
	r16 = &t$flixel_util_FlxTimer;
	r7 = 0;
	r11 = hl_alloc_array(r16,r7);
	r8 = hl_types_ArrayObj_alloc(r11);
	r2 = r8;
	label$0b61a7c_2_33:
	if( r2 == NULL ) hl_null_access();
	r7 = hl_types_ArrayObj_push(r2,((vdynamic*)r9));
	label$0b61a7c_2_35:
	goto label$0b61a7c_2_3;
	label$0b61a7c_2_36:
	if( !r2 ) goto label$0b61a7c_2_47;
	label$0b61a7c_2_37:
	if( r2 == NULL ) hl_null_access();
	r4 = r2->length;
	r6 = 0;
	if( r6 >= r4 ) goto label$0b61a7c_2_47;
	r10 = hl_types_ArrayObj_shift(r2);
	r9 = (flixel__util__FlxTimer)r10;
	if( r9 == NULL ) hl_null_access();
	flixel_util_FlxTimer_onLoopFinished(r9);
	goto label$0b61a7c_2_37;
	label$0b61a7c_2_47:
	return;
}

void flixel_util_FlxTimerManager_add(flixel__util__FlxTimerManager r0,flixel__util__FlxTimer r1) {
	hl__types__ArrayObj r3;
	int r2;
	r3 = r0->_timers;
	if( r3 == NULL ) hl_null_access();
	r2 = hl_types_ArrayObj_push(r3,((vdynamic*)r1));
	return;
}

void flixel_util_FlxTimerManager_remove(flixel__util__FlxTimerManager r0,flixel__util__FlxTimer r1) {
	hl__types__ArrayObj r2;
	flixel__util__FlxTimer r5;
	vdynamic *r6, *r9;
	varray *r10;
	int r4, r7, r8;
	r2 = r0->_timers;
	if( r2 == NULL ) hl_null_access();
	r6 = NULL;
	r4 = hl_types_ArrayObj_indexOf(r2,((vdynamic*)r1),r6);
	r7 = -1;
	if( r4 == r7 ) goto label$0b61a7c_4_23;
	r7 = r2->length;
	r8 = 1;
	r7 = r7 - r8;
	r8 = r2->length;
	if( ((unsigned)r7) < ((unsigned)r8) ) goto label$0b61a7c_4_13;
	r5 = NULL;
	goto label$0b61a7c_4_16;
	label$0b61a7c_4_13:
	r10 = r2->array;
	r9 = ((vdynamic**)(r10 + 1))[r7];
	r5 = (flixel__util__FlxTimer)r9;
	label$0b61a7c_4_16:
	r7 = r2->length;
	if( ((unsigned)r4) < ((unsigned)r7) ) goto label$0b61a7c_4_19;
	hl_types_ArrayObj___expand(r2,r4);
	label$0b61a7c_4_19:
	r10 = r2->array;
	((flixel__util__FlxTimer*)(r10 + 1))[r4] = r5;
	r9 = hl_types_ArrayObj_pop(r2);
	r5 = (flixel__util__FlxTimer)r9;
	label$0b61a7c_4_23:
	return;
}

void flixel_util_FlxTimerManager_completeAll(flixel__util__FlxTimerManager r0) {
	hl__types__ArrayObj r1, r6;
	hl_type *r3;
	bool r11;
	flixel__util__FlxTimer r9;
	double r12, r13;
	vdynamic *r10;
	int r4, r7, r8;
	varray *r2;
	r3 = &t$flixel_util_FlxTimer;
	r4 = 0;
	r2 = hl_alloc_array(r3,r4);
	r1 = hl_types_ArrayObj_alloc(r2);
	r4 = 0;
	r6 = r0->_timers;
	label$0b61a7c_5_6:
	if( r6 == NULL ) hl_null_access();
	r8 = r6->length;
	if( r4 >= r8 ) goto label$0b61a7c_5_27;
	r8 = r6->length;
	if( ((unsigned)r4) < ((unsigned)r8) ) goto label$0b61a7c_5_14;
	r9 = NULL;
	goto label$0b61a7c_5_17;
	label$0b61a7c_5_14:
	r2 = r6->array;
	r10 = ((vdynamic**)(r2 + 1))[r4];
	r9 = (flixel__util__FlxTimer)r10;
	label$0b61a7c_5_17:
	++r4;
	if( r9 == NULL ) hl_null_access();
	r7 = r9->loops;
	r8 = 0;
	if( r8 >= r7 ) goto label$0b61a7c_5_26;
	r11 = r9->active;
	if( !r11 ) goto label$0b61a7c_5_26;
	if( r1 == NULL ) hl_null_access();
	r7 = hl_types_ArrayObj_push(r1,((vdynamic*)r9));
	label$0b61a7c_5_26:
	goto label$0b61a7c_5_6;
	label$0b61a7c_5_27:
	r4 = 0;
	label$0b61a7c_5_28:
	if( r1 == NULL ) hl_null_access();
	r8 = r1->length;
	if( r4 >= r8 ) goto label$0b61a7c_5_51;
	r8 = r1->length;
	if( ((unsigned)r4) < ((unsigned)r8) ) goto label$0b61a7c_5_36;
	r9 = NULL;
	goto label$0b61a7c_5_39;
	label$0b61a7c_5_36:
	r2 = r1->array;
	r10 = ((vdynamic**)(r2 + 1))[r4];
	r9 = (flixel__util__FlxTimer)r10;
	label$0b61a7c_5_39:
	++r4;
	label$0b61a7c_5_40:
	if( r9 == NULL ) hl_null_access();
	r11 = r9->finished;
	if( r11 ) goto label$0b61a7c_5_50;
	r12 = r9->time;
	r13 = r9->_timeCounter;
	r12 = r12 - r13;
	flixel_util_FlxTimer_update(r9,r12);
	flixel_util_FlxTimer_onLoopFinished(r9);
	goto label$0b61a7c_5_40;
	label$0b61a7c_5_50:
	goto label$0b61a7c_5_28;
	label$0b61a7c_5_51:
	return;
}

void flixel_util_FlxTimerManager_clear(flixel__util__FlxTimerManager r0) {
	bool *r3;
	hl__types__ArrayObj r2;
	hl__types__ArrayDyn r1;
	r2 = r0->_timers;
	r1 = (hl__types__ArrayDyn)hl_dyn_castp(&r2,&t$hl_types_ArrayObj,&t$hl_types_ArrayDyn);
	r3 = NULL;
	r1 = flixel_util_FlxArrayUtil_clearArray(r1,r3);
	r2 = (hl__types__ArrayObj)hl_dyn_castp(&r1,&t$hl_types_ArrayDyn,&t$hl_types_ArrayObj);
	return;
}

void flixel_util_FlxTimerManager_forEach(flixel__util__FlxTimerManager r0,vclosure* r1) {
	hl__types__ArrayObj r4;
	flixel__util__FlxTimer r6;
	vdynamic *r7;
	varray *r8;
	int r2, r5;
	r2 = 0;
	r4 = r0->_timers;
	label$0b61a7c_7_2:
	if( r4 == NULL ) hl_null_access();
	r5 = r4->length;
	if( r2 >= r5 ) goto label$0b61a7c_7_17;
	r5 = r4->length;
	if( ((unsigned)r2) < ((unsigned)r5) ) goto label$0b61a7c_7_10;
	r6 = NULL;
	goto label$0b61a7c_7_13;
	label$0b61a7c_7_10:
	r8 = r4->array;
	r7 = ((vdynamic**)(r8 + 1))[r2];
	r6 = (flixel__util__FlxTimer)r7;
	label$0b61a7c_7_13:
	++r2;
	if( r1 == NULL ) hl_null_access();
	r1->hasValue ? ((void (*)(vdynamic*,flixel__util__FlxTimer))r1->fun)((vdynamic*)r1->value,r6) : ((void (*)(flixel__util__FlxTimer))r1->fun)(r6);
	goto label$0b61a7c_7_2;
	label$0b61a7c_7_17:
	return;
}

void flixel_util_FlxTimerManager_new(flixel__util__FlxTimerManager r0) {
	hl__types__ArrayObj r1;
	hl_type *r3;
	bool r6;
	flixel__$FlxG r9;
	flixel__system__frontEnds__SignalFrontEnd r8;
	flixel__util___FlxSignal__FlxSignal0 r7;
	vclosure *r10;
	int r4;
	varray *r2;
	r3 = &t$flixel_util_FlxTimer;
	r4 = 0;
	r2 = hl_alloc_array(r3,r4);
	r1 = hl_types_ArrayObj_alloc(r2);
	r0->_timers = r1;
	flixel_FlxBasic_new(((flixel__FlxBasic)r0));
	r6 = false;
	r6 = flixel_FlxBasic_set_visible(((flixel__FlxBasic)r0),r6);
	r9 = (flixel__$FlxG)g$_flixel_FlxG;
	r8 = r9->signals;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->preStateSwitch;
	if( r7 == NULL ) hl_null_access();
	r10 = hl_alloc_closure_ptr(&t$fun_85f8432,flixel_util_FlxTimerManager_clear,r0);
	flixel_util__FlxSignal_FlxBaseSignal_add(((flixel__util___FlxSignal__FlxBaseSignal)r7),((vdynamic*)r10));
	return;
}

