// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__util__IFlxSignal
#define INC_flixel__util__IFlxSignal
typedef struct _flixel__util__$IFlxSignal *flixel__util__$IFlxSignal;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _flixel__util__$IFlxSignal {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
#endif

