// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/util/LabelValuePair.h>
extern flixel__util__$LabelValuePair g$_flixel_util_LabelValuePair;
flixel__util__LabelValuePair flixel_util_FlxPool_flixel_util_LabelValuePair_get(flixel__util__FlxPool_flixel_util_LabelValuePair);
void flixel_util_FlxPool_flixel_util_LabelValuePair_put(flixel__util__FlxPool_flixel_util_LabelValuePair,flixel__util__LabelValuePair);

flixel__util__LabelValuePair flixel_util_LabelValuePair_weak(String r0,vdynamic* r1) {
	flixel__util__$LabelValuePair r4;
	flixel__util__FlxPool_flixel_util_LabelValuePair r3;
	flixel__util__LabelValuePair r2;
	r4 = (flixel__util__$LabelValuePair)g$_flixel_util_LabelValuePair;
	r3 = r4->_pool;
	if( r3 == NULL ) hl_null_access();
	r2 = flixel_util_FlxPool_flixel_util_LabelValuePair_get(r3);
	if( r2 == NULL ) hl_null_access();
	r2->label = r0;
	r2->value = r1;
	return r2;
}

flixel__util__LabelValuePair flixel_util_LabelValuePair_create(flixel__util__LabelValuePair r0,String r1,vdynamic* r2) {
	r0->label = r1;
	r0->value = r2;
	return r0;
}

void flixel_util_LabelValuePair_put(flixel__util__LabelValuePair r0) {
	flixel__util__$LabelValuePair r3;
	flixel__util__FlxPool_flixel_util_LabelValuePair r2;
	r3 = (flixel__util__$LabelValuePair)g$_flixel_util_LabelValuePair;
	r2 = r3->_pool;
	if( r2 == NULL ) hl_null_access();
	flixel_util_FlxPool_flixel_util_LabelValuePair_put(r2,r0);
	return;
}

void flixel_util_LabelValuePair_destroy(flixel__util__LabelValuePair r0) {
	String r1;
	vdynamic *r2;
	r1 = NULL;
	r0->label = r1;
	r2 = NULL;
	r0->value = r2;
	return;
}

void flixel_util_LabelValuePair_new(flixel__util__LabelValuePair r0) {
	return;
}

