// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_lime__utils___ArrayBuffer__ArrayBuffer_Impl_
#define INC_lime__utils___ArrayBuffer__ArrayBuffer_Impl_
typedef struct _lime__utils___ArrayBuffer__$ArrayBuffer_Impl_ *lime__utils___ArrayBuffer__$ArrayBuffer_Impl_;
typedef struct _lime__utils___ArrayBuffer__ArrayBuffer_Impl_ *lime__utils___ArrayBuffer__ArrayBuffer_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/io/Bytes.h>


struct _lime__utils___ArrayBuffer__$ArrayBuffer_Impl_ {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* get_byteLength;
	vclosure* _new;
	vclosure* isView;
	vclosure* slice;
};
struct _lime__utils___ArrayBuffer__ArrayBuffer_Impl_ {
	hl_type *$type;
};
#endif

