// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_flixel__tweens__FlxTweenManager
#define INC_flixel__tweens__FlxTweenManager
typedef struct _flixel__tweens__$FlxTweenManager *flixel__tweens__$FlxTweenManager;
typedef struct _flixel__tweens__FlxTweenManager *flixel__tweens__FlxTweenManager;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <flixel/FlxBasic.h>
#include <hl/types/ArrayObj.h>


struct _flixel__tweens__$FlxTweenManager {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _flixel__tweens__FlxTweenManager {
	hl_type *$type;
	int ID;
	bool active;
	bool visible;
	bool alive;
	bool exists;
	int flixelType;
	hl__types__ArrayObj _cameras;
	vvirtual* f$7;
	hl__types__ArrayObj _tweens;
};
#endif

