// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <flixel/system/debug/interaction/tools/Eraser.h>
flixel__system__debug__interaction__tools__Tool flixel_system_debug_interaction_tools_Tool_init(flixel__system__debug__interaction__tools__Tool,flixel__system__debug__interaction__Interaction);
extern String s$Eraser;
bool flixel_system_debug_interaction_Interaction_keyJustPressed(flixel__system__debug__interaction__Interaction,int);
bool flixel_system_debug_interaction_Interaction_keyPressed(flixel__system__debug__interaction__Interaction,int);
void flixel_system_debug_interaction_tools_Eraser_doDeletion(flixel__system__debug__interaction__tools__Eraser,bool);
void flixel_system_debug_interaction_Interaction_setActiveTool(flixel__system__debug__interaction__Interaction,flixel__system__debug__interaction__tools__Tool);
#include <flixel/group/FlxTypedGroup.h>
void flixel_system_debug_interaction_tools_Eraser_findAndDelete(flixel__system__debug__interaction__tools__Eraser,flixel__group__FlxTypedGroup,bool*);
void flixel_group_FlxTypedGroup_clear(flixel__group__FlxTypedGroup);
#include <flixel/group/FlxTypedGroupIterator.h>
#include <hl/types/ArrayDyn.h>
#include <flixel/FlxObject.h>
#include <flixel/FlxState.h>
#include <flixel/FlxGame.h>
#include <flixel/FlxG.h>
extern hl_type t$flixel_group_FlxTypedGroupIterator;
extern hl_type t$hl_types_ArrayDyn;
extern hl_type t$hl_types_ArrayObj;
bool wrapt$fun_88f06d9(vclosure*,vdynamic*);
extern hl_type t$fun_88f06d9;
void flixel_group_FlxTypedGroupIterator_new(flixel__group__FlxTypedGroupIterator,hl__types__ArrayDyn,vclosure*);
bool flixel_group_FlxTypedGroupIterator_hasNext(flixel__group__FlxTypedGroupIterator);
vdynamic* flixel_group_FlxTypedGroupIterator_next(flixel__group__FlxTypedGroupIterator);
extern flixel__group__$FlxTypedGroup g$_flixel_group_FlxTypedGroup;
bool Std_isOfType(vdynamic*,vdynamic*);
extern flixel__$FlxG g$_flixel_FlxG;
#include <flixel/FlxBasic.h>
void flixel_system_debug_interaction_tools_Eraser_removeFromMemory(flixel__system__debug__interaction__tools__Eraser,flixel__FlxBasic,flixel__group__FlxTypedGroup);
extern hl_type t$flixel_group_FlxTypedGroup;
extern hl_type t$flixel_FlxBasic;
flixel__FlxBasic flixel_group_FlxTypedGroup_remove(flixel__group__FlxTypedGroup,flixel__FlxBasic,bool*);
void flixel_system_debug_interaction_tools_Tool_new(flixel__system__debug__interaction__tools__Tool);

flixel__system__debug__interaction__tools__Tool flixel_system_debug_interaction_tools_Eraser_init(flixel__system__debug__interaction__tools__Eraser r0,flixel__system__debug__interaction__Interaction r1) {
	String r3;
	flixel__system__debug__interaction__tools__Tool r2;
	r2 = flixel_system_debug_interaction_tools_Tool_init(((flixel__system__debug__interaction__tools__Tool)r0),r1);
	r3 = (String)s$Eraser;
	r0->_name = r3;
	return ((flixel__system__debug__interaction__tools__Tool)r0);
}

void flixel_system_debug_interaction_tools_Eraser_update(flixel__system__debug__interaction__tools__Eraser r0) {
	bool r2;
	flixel__system__debug__interaction__Interaction r3;
	int r4;
	r3 = r0->_brain;
	if( r3 == NULL ) hl_null_access();
	r4 = 46;
	r2 = flixel_system_debug_interaction_Interaction_keyJustPressed(r3,r4);
	if( !r2 ) goto label$8f6f369_2_10;
	r3 = r0->_brain;
	if( r3 == NULL ) hl_null_access();
	r4 = 16;
	r2 = flixel_system_debug_interaction_Interaction_keyPressed(r3,r4);
	flixel_system_debug_interaction_tools_Eraser_doDeletion(r0,r2);
	label$8f6f369_2_10:
	return;
}

void flixel_system_debug_interaction_tools_Eraser_activate(flixel__system__debug__interaction__tools__Eraser r0) {
	flixel__system__debug__interaction__tools__Tool r5;
	bool r2;
	flixel__system__debug__interaction__Interaction r3;
	int r4;
	r3 = r0->_brain;
	if( r3 == NULL ) hl_null_access();
	r4 = 16;
	r2 = flixel_system_debug_interaction_Interaction_keyPressed(r3,r4);
	flixel_system_debug_interaction_tools_Eraser_doDeletion(r0,r2);
	r3 = r0->_brain;
	if( r3 == NULL ) hl_null_access();
	r5 = NULL;
	flixel_system_debug_interaction_Interaction_setActiveTool(r3,r5);
	return;
}

void flixel_system_debug_interaction_tools_Eraser_doDeletion(flixel__system__debug__interaction__tools__Eraser r0,bool r1) {
	bool *r6;
	bool r5;
	flixel__group__FlxTypedGroup r2;
	flixel__system__debug__interaction__Interaction r3;
	r3 = r0->_brain;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->selectedItems;
	if( !r2 ) goto label$8f6f369_4_9;
	r5 = r1;
	r6 = &r5;
	flixel_system_debug_interaction_tools_Eraser_findAndDelete(r0,r2,r6);
	if( r2 == NULL ) hl_null_access();
	flixel_group_FlxTypedGroup_clear(r2);
	label$8f6f369_4_9:
	return;
}

void flixel_system_debug_interaction_tools_Eraser_findAndDelete(flixel__system__debug__interaction__tools__Eraser r0,flixel__group__FlxTypedGroup r1,bool* r2) {
	flixel__FlxState r14;
	flixel__group__$FlxTypedGroup r13;
	flixel__group__FlxTypedGroupIterator r4;
	hl__types__ArrayObj r5;
	bool r3, r10;
	flixel__$FlxG r16;
	flixel__FlxObject r12;
	vclosure *r7, *r8;
	hl__types__ArrayDyn r6;
	flixel__FlxGame r15;
	vdynamic *r11;
	if( r2 ) goto label$8f6f369_5_3;
	r3 = false;
	goto label$8f6f369_5_4;
	label$8f6f369_5_3:
	r3 = *r2;
	label$8f6f369_5_4:
	r4 = (flixel__group__FlxTypedGroupIterator)hl_alloc_obj(&t$flixel_group_FlxTypedGroupIterator);
	if( r1 == NULL ) hl_null_access();
	r5 = r1->members;
	r6 = (hl__types__ArrayDyn)hl_dyn_castp(&r5,&t$hl_types_ArrayObj,&t$hl_types_ArrayDyn);
	r7 = NULL;
	if( r7 ) goto label$8f6f369_5_12;
	r8 = NULL;
	goto label$8f6f369_5_13;
	label$8f6f369_5_12:
	r8 = hl_alloc_closure_ptr(&t$fun_88f06d9,wrapt$fun_88f06d9,r7);
	label$8f6f369_5_13:
	flixel_group_FlxTypedGroupIterator_new(r4,r6,r8);
	label$8f6f369_5_14:
	if( r4 == NULL ) hl_null_access();
	r10 = flixel_group_FlxTypedGroupIterator_hasNext(r4);
	if( !r10 ) goto label$8f6f369_5_34;
	r11 = flixel_group_FlxTypedGroupIterator_next(r4);
	r12 = (flixel__FlxObject)r11;
	if( r12 ) goto label$8f6f369_5_22;
	goto label$8f6f369_5_14;
	label$8f6f369_5_22:
	r13 = (flixel__group__$FlxTypedGroup)g$_flixel_group_FlxTypedGroup;
	r10 = Std_isOfType(((vdynamic*)r12),((vdynamic*)r13));
	if( r10 ) goto label$8f6f369_5_33;
	if( r12 == NULL ) hl_null_access();
	((void (*)(flixel__FlxObject))r12->$type->vobj_proto[1])(r12);
	if( !r3 ) goto label$8f6f369_5_33;
	r16 = (flixel__$FlxG)g$_flixel_FlxG;
	r15 = r16->game;
	if( r15 == NULL ) hl_null_access();
	r14 = r15->_state;
	flixel_system_debug_interaction_tools_Eraser_removeFromMemory(r0,((flixel__FlxBasic)r12),((flixel__group__FlxTypedGroup)r14));
	label$8f6f369_5_33:
	goto label$8f6f369_5_14;
	label$8f6f369_5_34:
	return;
}

void flixel_system_debug_interaction_tools_Eraser_removeFromMemory(flixel__system__debug__interaction__tools__Eraser r0,flixel__FlxBasic r1,flixel__group__FlxTypedGroup r2) {
	bool *r14;
	flixel__group__$FlxTypedGroup r13;
	hl__types__ArrayObj r5;
	bool r12;
	flixel__group__FlxTypedGroup r6;
	vdynamic *r9;
	flixel__FlxBasic r8, r11;
	varray *r10;
	int r3, r7;
	r3 = 0;
	if( r2 == NULL ) hl_null_access();
	r5 = r2->members;
	label$8f6f369_6_3:
	if( r5 == NULL ) hl_null_access();
	r7 = r5->length;
	if( r3 >= r7 ) goto label$8f6f369_6_28;
	r7 = r5->length;
	if( ((unsigned)r3) < ((unsigned)r7) ) goto label$8f6f369_6_11;
	r8 = NULL;
	goto label$8f6f369_6_14;
	label$8f6f369_6_11:
	r10 = r5->array;
	r9 = ((vdynamic**)(r10 + 1))[r3];
	r8 = (flixel__FlxBasic)r9;
	label$8f6f369_6_14:
	++r3;
	if( r8 ) goto label$8f6f369_6_17;
	goto label$8f6f369_6_3;
	label$8f6f369_6_17:
	r13 = (flixel__group__$FlxTypedGroup)g$_flixel_group_FlxTypedGroup;
	r12 = Std_isOfType(((vdynamic*)r8),((vdynamic*)r13));
	if( !r12 ) goto label$8f6f369_6_23;
	r6 = (flixel__group__FlxTypedGroup)hl_dyn_castp(&r8,&t$flixel_FlxBasic,&t$flixel_group_FlxTypedGroup);
	flixel_system_debug_interaction_tools_Eraser_removeFromMemory(r0,r1,r6);
	goto label$8f6f369_6_27;
	label$8f6f369_6_23:
	if( r8 != r1 ) goto label$8f6f369_6_27;
	if( r2 == NULL ) hl_null_access();
	r14 = NULL;
	r11 = flixel_group_FlxTypedGroup_remove(r2,r8,r14);
	label$8f6f369_6_27:
	goto label$8f6f369_6_3;
	label$8f6f369_6_28:
	return;
}

void flixel_system_debug_interaction_tools_Eraser_new(flixel__system__debug__interaction__tools__Eraser r0) {
	flixel_system_debug_interaction_tools_Tool_new(((flixel__system__debug__interaction__tools__Tool)r0));
	return;
}

