// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__events___EventDispatcher__DispatchIterator
#define INC_openfl__events___EventDispatcher__DispatchIterator
typedef struct _openfl__events___EventDispatcher__$DispatchIterator *openfl__events___EventDispatcher__$DispatchIterator;
typedef struct _openfl__events___EventDispatcher__DispatchIterator *openfl__events___EventDispatcher__DispatchIterator;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>


struct _openfl__events___EventDispatcher__$DispatchIterator {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _openfl__events___EventDispatcher__DispatchIterator {
	hl_type *$type;
	bool active;
	int index;
	bool isCopy;
	hl__types__ArrayObj list;
};
#endif

