// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/filters/BitmapFilter.h>
extern hl_type t$_i32;
extern hl_type t$openfl_filters_BitmapFilter;
#include <openfl/display/BitmapData.h>
#include <openfl/geom/Rectangle.h>
#include <openfl/geom/Point.h>
#include <openfl/display/DisplayObjectRenderer.h>
#include <openfl/display/Shader.h>

void openfl_filters_BitmapFilter_new(openfl__filters__BitmapFilter r0) {
	bool r2;
	vdynamic *r3;
	int r1;
	r1 = 0;
	r0->__bottomExtension = r1;
	r1 = 0;
	r0->__leftExtension = r1;
	r2 = true;
	r0->__needSecondBitmapData = r2;
	r1 = 0;
	r0->__numShaderPasses = r1;
	r2 = false;
	r0->__preserveObject = r2;
	r1 = 0;
	r0->__rightExtension = r1;
	r1 = 10;
	r3 = hl_alloc_dynamic(&t$_i32);
	r3->v.i = r1;
	r0->__shaderBlendMode = r3;
	r1 = 0;
	r0->__topExtension = r1;
	r2 = true;
	r0->__smooth = r2;
	return;
}

openfl__filters__BitmapFilter openfl_filters_BitmapFilter_clone(openfl__filters__BitmapFilter r0) {
	openfl__filters__BitmapFilter r1;
	r1 = (openfl__filters__BitmapFilter)hl_alloc_obj(&t$openfl_filters_BitmapFilter);
	openfl_filters_BitmapFilter_new(r1);
	return r1;
}

openfl__display__BitmapData openfl_filters_BitmapFilter___applyFilter(openfl__filters__BitmapFilter r0,openfl__display__BitmapData r1,openfl__display__BitmapData r2,openfl__geom__Rectangle r3,openfl__geom__Point r4) {
	return r2;
}

openfl__display__Shader openfl_filters_BitmapFilter___initShader(openfl__filters__BitmapFilter r0,openfl__display__DisplayObjectRenderer r1,int r2,openfl__display__BitmapData r3) {
	openfl__display__Shader r4;
	r4 = NULL;
	return r4;
}

