// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/display/GraphicsStroke.h>
#include <_std/Math.h>
extern hl_type t$_i32;
extern $Math g$_Math;
extern hl_type t$_f64;

void openfl_display_GraphicsStroke_new(openfl__display__GraphicsStroke r0,vdynamic* r1,bool* r2,vdynamic* r3,vdynamic* r4,vdynamic* r5,double* r6,vvirtual* r7) {
	bool r8;
	$Math r14;
	double r10, r13;
	vdynamic *r12;
	int r9;
	if( r2 ) goto label$9b61ffd_1_3;
	r8 = false;
	goto label$9b61ffd_1_4;
	label$9b61ffd_1_3:
	r8 = *r2;
	label$9b61ffd_1_4:
	if( r3 ) goto label$9b61ffd_1_7;
	r9 = 2;
	r3 = hl_alloc_dynamic(&t$_i32);
	r3->v.i = r9;
	label$9b61ffd_1_7:
	if( r4 ) goto label$9b61ffd_1_10;
	r9 = 0;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r9;
	label$9b61ffd_1_10:
	if( r5 ) goto label$9b61ffd_1_13;
	r9 = 2;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r9;
	label$9b61ffd_1_13:
	if( r6 ) goto label$9b61ffd_1_16;
	r10 = 3.;
	goto label$9b61ffd_1_17;
	label$9b61ffd_1_16:
	r10 = *r6;
	label$9b61ffd_1_17:
	if( r1 ) goto label$9b61ffd_1_22;
	r14 = ($Math)g$_Math;
	r13 = r14->NaN;
	r12 = hl_alloc_dynamic(&t$_f64);
	r12->v.d = r13;
	r1 = r12;
	label$9b61ffd_1_22:
	r0->caps = r4;
	r0->fill = r7;
	r0->joints = r5;
	r0->miterLimit = r10;
	r0->pixelHinting = r8;
	r0->scaleMode = r3;
	r13 = r1 ? r1->v.d : 0;
	r0->thickness = r13;
	r9 = 0;
	r0->__graphicsDataType = r9;
	return;
}

