// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/display/GraphicsQuadPath.h>

void openfl_display_GraphicsQuadPath_new(openfl__display__GraphicsQuadPath r0,openfl___Vector__FloatVector r1,openfl___Vector__IntVector r2,openfl___Vector__FloatVector r3) {
	int r4;
	r0->rects = r1;
	r0->indices = r2;
	r0->transforms = r3;
	r4 = 6;
	r0->__graphicsDataType = r4;
	return;
}

