// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__display__OpenGLRenderer
#define INC_openfl__display__OpenGLRenderer
typedef struct _openfl__display__$OpenGLRenderer *openfl__display__$OpenGLRenderer;
typedef struct _openfl__display__OpenGLRenderer *openfl__display__OpenGLRenderer;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayBytes_Float.h>
#include <hl/types/ArrayObj.h>
#include <openfl/geom/Rectangle.h>
#include <openfl/display/DisplayObjectRenderer.h>
#include <openfl/events/EventDispatcher.h>
#include <haxe/ds/StringMap.h>
#include <openfl/events/Event.h>
#include <lime/graphics/RenderContext.h>
#include <openfl/display/Stage.h>
#include <openfl/geom/ColorTransform.h>
#include <openfl/geom/Matrix.h>
#include <lime/_internal/backend/native/NativeOpenGLRenderContext.h>
#include <openfl/display3D/Context3D.h>
#include <openfl/display/Shader.h>
#include <openfl/display/BitmapData.h>
#include <openfl/display/_internal/ShaderBuffer.h>
#include <openfl/display/DisplayObjectShader.h>
#include <openfl/display/GraphicsShader.h>
#include <openfl/display/_internal/Context3DMaskShader.h>
#include <lime/utils/ArrayBufferView.h>
#include <lime/utils/ObjectPool.h>


struct _openfl__display__$OpenGLRenderer {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	hl__types__ArrayBytes_Float __alphaValue;
	hl__types__ArrayBytes_Float __colorMultipliersValue;
	hl__types__ArrayBytes_Float __colorOffsetsValue;
	hl__types__ArrayBytes_Float __defaultColorMultipliersValue;
	hl__types__ArrayBytes_Float __emptyColorValue;
	hl__types__ArrayBytes_Float __emptyAlphaValue;
	hl__types__ArrayObj __hasColorTransformValue;
	openfl__geom__Rectangle __scissorRectangle;
	hl__types__ArrayBytes_Float __textureSizeValue;
};
struct _openfl__display__OpenGLRenderer {
	hl_type *$type;
	haxe__ds__StringMap __eventMap;
	haxe__ds__StringMap __iterators;
	vvirtual* __targetDispatcher;
	vvirtual* f$3;
	bool __allowSmoothing;
	vdynamic* __blendMode;
	bool __cleared;
	lime__graphics__RenderContext __context;
	vdynamic* __overrideBlendMode;
	double __pixelRatio;
	bool __roundPixels;
	openfl__display__Stage __stage;
	openfl__geom__ColorTransform __tempColorTransform;
	bool __transparent;
	String __type;
	double __worldAlpha;
	openfl__geom__ColorTransform __worldColorTransform;
	openfl__geom__Matrix __worldTransform;
	lime___internal__backend__native__NativeOpenGLRenderContext gl;
	openfl__display3D__Context3D __context3D;
	hl__types__ArrayObj __clipRects;
	openfl__display__Shader __currentDisplayShader;
	openfl__display__Shader __currentGraphicsShader;
	openfl__display__BitmapData __currentRenderTarget;
	openfl__display__Shader __currentShader;
	openfl__display___internal__ShaderBuffer __currentShaderBuffer;
	openfl__display__DisplayObjectShader __defaultDisplayShader;
	openfl__display__GraphicsShader __defaultGraphicsShader;
	openfl__display__BitmapData __defaultRenderTarget;
	openfl__display__Shader __defaultShader;
	int __displayHeight;
	int __displayWidth;
	bool __flipped;
	lime___internal__backend__native__NativeOpenGLRenderContext __gl;
	int __height;
	openfl__display___internal__Context3DMaskShader __maskShader;
	lime__utils__ArrayBufferView __matrix;
	hl__types__ArrayObj __maskObjects;
	int __numClipRects;
	int __offsetX;
	int __offsetY;
	lime__utils__ArrayBufferView __projection;
	lime__utils__ArrayBufferView __projectionFlipped;
	lime__utils__ObjectPool __scrollRectMasks;
	openfl__display__DisplayObjectRenderer __softwareRenderer;
	int __stencilReference;
	openfl__geom__Rectangle __tempRect;
	bool __updatedStencil;
	bool __upscaled;
	hl__types__ArrayBytes_Float __values;
	int __width;
};
#endif

