// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__display__ShaderParameter_Float
#define INC_openfl__display__ShaderParameter_Float
typedef struct _openfl__display__$ShaderParameter_Float *openfl__display__$ShaderParameter_Float;
typedef struct _openfl__display__ShaderParameter_Float *openfl__display__ShaderParameter_Float;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayBytes_Float.h>
#include <lime/utils/ArrayBufferView.h>


struct _openfl__display__$ShaderParameter_Float {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _openfl__display__ShaderParameter_Float {
	hl_type *$type;
	vdynamic* index;
	String name;
	vdynamic* type;
	hl__types__ArrayBytes_Float value;
	int __arrayLength;
	bool __internal;
	bool __isBool;
	bool __isFloat;
	bool __isInt;
	bool __isUniform;
	int __length;
	lime__utils__ArrayBufferView __uniformMatrix;
	bool __useArray;
};
#endif

