// Generated by HLC 4.3.1 (HL v5)
#ifndef INC_openfl__display__Stage3D
#define INC_openfl__display__Stage3D
typedef struct _openfl__display__$Stage3D *openfl__display__$Stage3D;
typedef struct _openfl__display__Stage3D *openfl__display__Stage3D;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <openfl/events/EventDispatcher.h>
#include <haxe/ds/StringMap.h>
#include <openfl/events/Event.h>
#include <openfl/display3D/Context3D.h>
#include <openfl/display3D/IndexBuffer3D.h>
#include <openfl/geom/Matrix3D.h>
#include <openfl/display/Stage.h>
#include <openfl/display3D/VertexBuffer3D.h>


struct _openfl__display__$Stage3D {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	bool __active;
};
struct _openfl__display__Stage3D {
	hl_type *$type;
	haxe__ds__StringMap __eventMap;
	haxe__ds__StringMap __iterators;
	vvirtual* __targetDispatcher;
	vvirtual* f$3;
	openfl__display3D__Context3D context3D;
	bool visible;
	bool __contextLost;
	bool __contextRequested;
	int __height;
	openfl__display3D__IndexBuffer3D __indexBuffer;
	openfl__geom__Matrix3D __projectionTransform;
	openfl__geom__Matrix3D __renderTransform;
	openfl__display__Stage __stage;
	openfl__display3D__VertexBuffer3D __vertexBuffer;
	int __width;
	double __x;
	double __y;
};
#endif

