// Generated by HLC 4.3.1 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <openfl/display/Tilemap.h>
void openfl_display_DisplayObject_new(openfl__display__DisplayObject);
extern hl_type t$openfl_display_TileContainer;
void openfl_display_TileContainer_new(openfl__display__TileContainer,double*,double*,double*,double*,double*,double*,double*);
openfl__display__Tileset openfl_display_Tile_set_tileset(openfl__display__Tile,openfl__display__Tileset);
openfl__display__Tile openfl_display_TileContainer_addTile(openfl__display__TileContainer,openfl__display__Tile);
openfl__display__Tile openfl_display_TileContainer_addTileAt(openfl__display__TileContainer,openfl__display__Tile,int);
hl__types__ArrayObj openfl_display_TileContainer_addTiles(openfl__display__TileContainer,hl__types__ArrayObj);
bool openfl_display_TileContainer_contains(openfl__display__TileContainer,openfl__display__Tile);
openfl__display__Tile openfl_display_TileContainer_getTileAt(openfl__display__TileContainer,int);
int openfl_display_TileContainer_getTileIndex(openfl__display__TileContainer,openfl__display__Tile);
openfl__display__Tile openfl_display_TileContainer_clone(openfl__display__TileContainer);
extern hl_type t$openfl_display_Tile;
openfl__display__Tile openfl_display_TileContainer_removeTile(openfl__display__TileContainer,openfl__display__Tile);
openfl__display__Tile openfl_display_TileContainer_removeTileAt(openfl__display__TileContainer,int);
void openfl_display_TileContainer_removeTiles(openfl__display__TileContainer,int*,int*);
void openfl_display_TileContainer_setTileIndex(openfl__display__TileContainer,openfl__display__Tile,int);
void openfl_display_TileContainer_sortTiles(openfl__display__TileContainer,vclosure*);
void openfl_display_TileContainer_swapTiles(openfl__display__TileContainer,openfl__display__Tile,openfl__display__Tile);
void openfl_display_TileContainer_swapTilesAt(openfl__display__TileContainer,int,int);
void openfl_display_DisplayObject___setParentRenderDirty(openfl__display__DisplayObject);
#include <lime/utils/ObjectPool.h>
#include <openfl/geom/Rectangle.h>
extern openfl__geom__$Rectangle g$_openfl_geom_Rectangle;
vdynamic* lime_utils_ObjectPool_get(lime__utils__ObjectPool);
void openfl_geom_Rectangle_setTo(openfl__geom__Rectangle,double,double,double,double);
void openfl_geom_Rectangle___transform(openfl__geom__Rectangle,openfl__geom__Rectangle,openfl__geom__Matrix);
void openfl_geom_Rectangle___expand(openfl__geom__Rectangle,double,double,double,double);
void lime_utils_ObjectPool_release(lime__utils__ObjectPool,vdynamic*);
bool openfl_display_DisplayObject_get_visible(openfl__display__DisplayObject);
openfl__display__DisplayObject openfl_display_DisplayObject_get_mask(openfl__display__DisplayObject);
openfl__geom__Matrix openfl_display_DisplayObject___getRenderTransform(openfl__display__DisplayObject);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
double openfl_display_DisplayObject_get_scaleY(openfl__display__DisplayObject);
#include <hl/natives.h>

void openfl_display_Tilemap_new(openfl__display__Tilemap r0,int r1,int r2,openfl__display__Tileset r3,bool* r4) {
	bool r5, r9;
	openfl__display__TileContainer r10;
	openfl__display__Tileset r8;
	double *r11, *r12, *r13, *r14, *r15, *r16, *r17;
	int r7;
	if( r4 ) goto label$1b11b56_1_3;
	r5 = true;
	goto label$1b11b56_1_4;
	label$1b11b56_1_3:
	r5 = *r4;
	label$1b11b56_1_4:
	openfl_display_DisplayObject_new(((openfl__display__DisplayObject)r0));
	r7 = 9;
	r0->__drawableType = r7;
	r0->__tileset = r3;
	r0->smoothing = r5;
	r9 = true;
	r0->tileAlphaEnabled = r9;
	r9 = true;
	r0->tileBlendModeEnabled = r9;
	r9 = true;
	r0->tileColorTransformEnabled = r9;
	r10 = (openfl__display__TileContainer)hl_alloc_obj(&t$openfl_display_TileContainer);
	r11 = NULL;
	r12 = NULL;
	r13 = NULL;
	r14 = NULL;
	r15 = NULL;
	r16 = NULL;
	r17 = NULL;
	openfl_display_TileContainer_new(r10,r11,r12,r13,r14,r15,r16,r17);
	r0->__group = r10;
	r10 = r0->__group;
	if( r10 == NULL ) hl_null_access();
	r8 = openfl_display_Tile_set_tileset(((openfl__display__Tile)r10),r3);
	r0->__width = r1;
	r0->__height = r2;
	return;
}

openfl__display__Tile openfl_display_Tilemap_addTile(openfl__display__Tilemap r0,openfl__display__Tile r1) {
	openfl__display__TileContainer r3;
	openfl__display__Tile r2;
	r3 = r0->__group;
	if( r3 == NULL ) hl_null_access();
	r2 = openfl_display_TileContainer_addTile(r3,r1);
	return r2;
}

openfl__display__Tile openfl_display_Tilemap_addTileAt(openfl__display__Tilemap r0,openfl__display__Tile r1,int r2) {
	openfl__display__TileContainer r4;
	openfl__display__Tile r3;
	r4 = r0->__group;
	if( r4 == NULL ) hl_null_access();
	r3 = openfl_display_TileContainer_addTileAt(r4,r1,r2);
	return r3;
}

hl__types__ArrayObj openfl_display_Tilemap_addTiles(openfl__display__Tilemap r0,hl__types__ArrayObj r1) {
	hl__types__ArrayObj r2;
	openfl__display__TileContainer r3;
	r3 = r0->__group;
	if( r3 == NULL ) hl_null_access();
	r2 = openfl_display_TileContainer_addTiles(r3,r1);
	return r2;
}

bool openfl_display_Tilemap_contains(openfl__display__Tilemap r0,openfl__display__Tile r1) {
	bool r2;
	openfl__display__TileContainer r3;
	r3 = r0->__group;
	if( r3 == NULL ) hl_null_access();
	r2 = openfl_display_TileContainer_contains(r3,r1);
	return r2;
}

openfl__display__Tile openfl_display_Tilemap_getTileAt(openfl__display__Tilemap r0,int r1) {
	openfl__display__TileContainer r3;
	openfl__display__Tile r2;
	r3 = r0->__group;
	if( r3 == NULL ) hl_null_access();
	r2 = openfl_display_TileContainer_getTileAt(r3,r1);
	return r2;
}

int openfl_display_Tilemap_getTileIndex(openfl__display__Tilemap r0,openfl__display__Tile r1) {
	openfl__display__TileContainer r3;
	int r2;
	r3 = r0->__group;
	if( r3 == NULL ) hl_null_access();
	r2 = openfl_display_TileContainer_getTileIndex(r3,r1);
	return r2;
}

openfl__display__TileContainer openfl_display_Tilemap_getTiles(openfl__display__Tilemap r0) {
	openfl__display__TileContainer r2;
	openfl__display__Tile r1;
	r2 = r0->__group;
	if( r2 == NULL ) hl_null_access();
	r1 = openfl_display_TileContainer_clone(r2);
	r2 = (openfl__display__TileContainer)hl_dyn_castp(&r1,&t$openfl_display_Tile,&t$openfl_display_TileContainer);
	return r2;
}

openfl__display__Tile openfl_display_Tilemap_removeTile(openfl__display__Tilemap r0,openfl__display__Tile r1) {
	openfl__display__TileContainer r3;
	openfl__display__Tile r2;
	r3 = r0->__group;
	if( r3 == NULL ) hl_null_access();
	r2 = openfl_display_TileContainer_removeTile(r3,r1);
	return r2;
}

openfl__display__Tile openfl_display_Tilemap_removeTileAt(openfl__display__Tilemap r0,int r1) {
	openfl__display__TileContainer r3;
	openfl__display__Tile r2;
	r3 = r0->__group;
	if( r3 == NULL ) hl_null_access();
	r2 = openfl_display_TileContainer_removeTileAt(r3,r1);
	return r2;
}

void openfl_display_Tilemap_removeTiles(openfl__display__Tilemap r0,int* r1,int* r2) {
	openfl__display__TileContainer r6;
	int r3, r4, r7, r8;
	if( r1 ) goto label$1b11b56_11_3;
	r3 = 0;
	goto label$1b11b56_11_4;
	label$1b11b56_11_3:
	r3 = *r1;
	label$1b11b56_11_4:
	if( r2 ) goto label$1b11b56_11_7;
	r4 = 2147483647;
	goto label$1b11b56_11_8;
	label$1b11b56_11_7:
	r4 = *r2;
	label$1b11b56_11_8:
	r6 = r0->__group;
	if( r6 == NULL ) hl_null_access();
	r7 = r3;
	r1 = &r7;
	r8 = r4;
	r2 = &r8;
	openfl_display_TileContainer_removeTiles(r6,r1,r2);
	return;
}

void openfl_display_Tilemap_setTileIndex(openfl__display__Tilemap r0,openfl__display__Tile r1,int r2) {
	openfl__display__TileContainer r4;
	r4 = r0->__group;
	if( r4 == NULL ) hl_null_access();
	openfl_display_TileContainer_setTileIndex(r4,r1,r2);
	return;
}

void openfl_display_Tilemap_setTiles(openfl__display__Tilemap r0,openfl__display__TileContainer r1) {
	hl__types__ArrayObj r4;
	openfl__display__TileContainer r5;
	openfl__display__Tile r7, r10;
	vdynamic *r8;
	varray *r9;
	int r2, r6;
	r2 = 0;
	r5 = r0->__group;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->__tiles;
	label$1b11b56_13_4:
	if( r4 == NULL ) hl_null_access();
	r6 = r4->length;
	if( r2 >= r6 ) goto label$1b11b56_13_18;
	r6 = r4->length;
	if( ((unsigned)r2) < ((unsigned)r6) ) goto label$1b11b56_13_12;
	r7 = NULL;
	goto label$1b11b56_13_15;
	label$1b11b56_13_12:
	r9 = r4->array;
	r8 = ((vdynamic**)(r9 + 1))[r2];
	r7 = (openfl__display__Tile)r8;
	label$1b11b56_13_15:
	++r2;
	r10 = openfl_display_Tilemap_removeTile(r0,r7);
	goto label$1b11b56_13_4;
	label$1b11b56_13_18:
	r2 = 0;
	if( r1 == NULL ) hl_null_access();
	r4 = r1->__tiles;
	label$1b11b56_13_21:
	if( r4 == NULL ) hl_null_access();
	r6 = r4->length;
	if( r2 >= r6 ) goto label$1b11b56_13_35;
	r6 = r4->length;
	if( ((unsigned)r2) < ((unsigned)r6) ) goto label$1b11b56_13_29;
	r7 = NULL;
	goto label$1b11b56_13_32;
	label$1b11b56_13_29:
	r9 = r4->array;
	r8 = ((vdynamic**)(r9 + 1))[r2];
	r7 = (openfl__display__Tile)r8;
	label$1b11b56_13_32:
	++r2;
	r10 = openfl_display_Tilemap_addTile(r0,r7);
	goto label$1b11b56_13_21;
	label$1b11b56_13_35:
	return;
}

void openfl_display_Tilemap_sortTiles(openfl__display__Tilemap r0,vclosure* r1) {
	openfl__display__TileContainer r3;
	r3 = r0->__group;
	if( r3 == NULL ) hl_null_access();
	openfl_display_TileContainer_sortTiles(r3,r1);
	return;
}

void openfl_display_Tilemap_swapTiles(openfl__display__Tilemap r0,openfl__display__Tile r1,openfl__display__Tile r2) {
	openfl__display__TileContainer r4;
	r4 = r0->__group;
	if( r4 == NULL ) hl_null_access();
	openfl_display_TileContainer_swapTiles(r4,r1,r2);
	return;
}

void openfl_display_Tilemap_swapTilesAt(openfl__display__Tilemap r0,int r1,int r2) {
	openfl__display__TileContainer r4;
	r4 = r0->__group;
	if( r4 == NULL ) hl_null_access();
	openfl_display_TileContainer_swapTilesAt(r4,r1,r2);
	return;
}

void openfl_display_Tilemap___enterFrame(openfl__display__Tilemap r0,int r1) {
	bool r3;
	openfl__display__TileContainer r4;
	r4 = r0->__group;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->__dirty;
	if( !r3 ) goto label$1b11b56_17_9;
	r3 = r0->__renderDirty;
	if( r3 ) goto label$1b11b56_17_9;
	r3 = true;
	r0->__renderDirty = r3;
	openfl_display_DisplayObject___setParentRenderDirty(((openfl__display__DisplayObject)r0));
	label$1b11b56_17_9:
	return;
}

void openfl_display_Tilemap___getBounds(openfl__display__Tilemap r0,openfl__geom__Rectangle r1,openfl__geom__Matrix r2) {
	openfl__geom__Rectangle r6;
	openfl__geom__$Rectangle r5;
	double r8, r9, r11, r12;
	lime__utils__ObjectPool r4;
	vdynamic *r3;
	int r10;
	r5 = (openfl__geom__$Rectangle)g$_openfl_geom_Rectangle;
	r4 = r5->__pool;
	if( r4 == NULL ) hl_null_access();
	r3 = lime_utils_ObjectPool_get(r4);
	r6 = (openfl__geom__Rectangle)r3;
	if( r6 == NULL ) hl_null_access();
	r8 = 0.;
	r9 = 0.;
	r10 = r0->__width;
	r11 = (double)r10;
	r10 = r0->__height;
	r12 = (double)r10;
	openfl_geom_Rectangle_setTo(r6,r8,r9,r11,r12);
	openfl_geom_Rectangle___transform(r6,r6,r2);
	if( r1 == NULL ) hl_null_access();
	r8 = r6->x;
	r9 = r6->y;
	r11 = r6->width;
	r12 = r6->height;
	openfl_geom_Rectangle___expand(r1,r8,r9,r11,r12);
	r5 = (openfl__geom__$Rectangle)g$_openfl_geom_Rectangle;
	r4 = r5->__pool;
	if( r4 == NULL ) hl_null_access();
	lime_utils_ObjectPool_release(r4,((vdynamic*)r6));
	return;
}

bool openfl_display_Tilemap___hitTest(openfl__display__Tilemap r0,double r1,double r2,bool r3,hl__types__ArrayObj r4,bool r5,openfl__display__DisplayObject r6) {
	openfl__display__DisplayObject r8;
	bool r7;
	openfl__geom__Matrix r11, r12;
	double r9, r10, r13, r14, r15, r16, r17;
	int r18;
	if( r6 == NULL ) hl_null_access();
	r7 = openfl_display_DisplayObject_get_visible(r6);
	if( !r7 ) goto label$1b11b56_19_5;
	r7 = r0->__isMask;
	if( !r7 ) goto label$1b11b56_19_7;
	label$1b11b56_19_5:
	r7 = false;
	return r7;
	label$1b11b56_19_7:
	r8 = openfl_display_DisplayObject_get_mask(((openfl__display__DisplayObject)r0));
	if( !r8 ) goto label$1b11b56_19_15;
	r8 = openfl_display_DisplayObject_get_mask(((openfl__display__DisplayObject)r0));
	if( r8 == NULL ) hl_null_access();
	r7 = ((bool (*)(openfl__display__DisplayObject,double,double))r8->$type->vobj_proto[17])(r8,r1,r2);
	if( r7 ) goto label$1b11b56_19_15;
	r7 = false;
	return r7;
	label$1b11b56_19_15:
	r11 = openfl_display_DisplayObject___getRenderTransform(((openfl__display__DisplayObject)r0));
	r11 = r0->__renderTransform;
	if( r11 == NULL ) hl_null_access();
	r9 = r11->a;
	r10 = r11->d;
	r9 = r9 * r10;
	r10 = r11->b;
	r13 = r11->c;
	r10 = r10 * r13;
	r9 = r9 - r10;
	r13 = 0.;
	if( r9 != r13 ) goto label$1b11b56_19_30;
	r10 = r11->tx;
	r10 = -r10;
	goto label$1b11b56_19_42;
	label$1b11b56_19_30:
	r10 = 1.;
	r10 = r10 / r9;
	r13 = r11->c;
	r14 = r11->ty;
	r14 = r14 - r2;
	r13 = r13 * r14;
	r14 = r11->d;
	r16 = r11->tx;
	r15 = r1 - r16;
	r14 = r14 * r15;
	r13 = r13 + r14;
	r10 = r10 * r13;
	label$1b11b56_19_42:
	r12 = r0->__renderTransform;
	if( r12 == NULL ) hl_null_access();
	r13 = r12->a;
	r14 = r12->d;
	r13 = r13 * r14;
	r14 = r12->b;
	r15 = r12->c;
	r14 = r14 * r15;
	r13 = r13 - r14;
	r15 = 0.;
	if( r13 != r15 ) goto label$1b11b56_19_56;
	r14 = r12->ty;
	r14 = -r14;
	goto label$1b11b56_19_68;
	label$1b11b56_19_56:
	r14 = 1.;
	r14 = r14 / r13;
	r15 = r12->a;
	r17 = r12->ty;
	r16 = r2 - r17;
	r15 = r15 * r16;
	r16 = r12->b;
	r17 = r12->tx;
	r17 = r17 - r1;
	r16 = r16 * r17;
	r15 = r15 + r16;
	r14 = r14 * r15;
	label$1b11b56_19_68:
	r16 = 0.;
	if( !(r16 < r10) ) goto label$1b11b56_19_84;
	r16 = 0.;
	if( !(r16 < r14) ) goto label$1b11b56_19_84;
	r18 = r0->__width;
	r16 = (double)r18;
	if( !(r16 >= r10) ) goto label$1b11b56_19_84;
	r18 = r0->__height;
	r16 = (double)r18;
	if( !(r16 >= r14) ) goto label$1b11b56_19_84;
	if( !r4 ) goto label$1b11b56_19_82;
	if( r5 ) goto label$1b11b56_19_82;
	if( r4 == NULL ) hl_null_access();
	r18 = hl_types_ArrayObj_push(r4,((vdynamic*)r6));
	label$1b11b56_19_82:
	r7 = true;
	return r7;
	label$1b11b56_19_84:
	r7 = false;
	return r7;
}

void openfl_display_Tilemap___renderFlash(openfl__display__Tilemap r0) {
	return;
}

double openfl_display_Tilemap_get_height(openfl__display__Tilemap r0) {
	double r1, r3;
	int r2;
	r2 = r0->__height;
	r1 = (double)r2;
	r3 = openfl_display_DisplayObject_get_scaleY(((openfl__display__DisplayObject)r0));
	r3 = hl_math_abs(r3);
	r1 = r1 * r3;
	return r1;
}

double openfl_display_Tilemap_set_height(openfl__display__Tilemap r0,double r1) {
	double r3, r4;
	int r2;
	r2 = (int)r1;
	r0->__height = r2;
	r2 = r0->__height;
	r3 = (double)r2;
	r4 = openfl_display_DisplayObject_get_scaleY(((openfl__display__DisplayObject)r0));
	r4 = hl_math_abs(r4);
	r3 = r3 * r4;
	return r3;
}

int openfl_display_Tilemap_get_numTiles(openfl__display__Tilemap r0) {
	openfl__display__TileContainer r2;
	int r1;
	r2 = r0->__group;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->__length;
	return r1;
}

openfl__display__Tileset openfl_display_Tilemap_get_tileset(openfl__display__Tilemap r0) {
	openfl__display__Tileset r1;
	r1 = r0->__tileset;
	return r1;
}

openfl__display__Tileset openfl_display_Tilemap_set_tileset(openfl__display__Tilemap r0,openfl__display__Tileset r1) {
	bool r6;
	openfl__display__TileContainer r5;
	openfl__display__Tileset r3, r4;
	r4 = r0->__tileset;
	if( r1 == r4 ) goto label$1b11b56_25_15;
	r0->__tileset = r1;
	r5 = r0->__group;
	if( r5 == NULL ) hl_null_access();
	r3 = openfl_display_Tile_set_tileset(((openfl__display__Tile)r5),r1);
	r5 = r0->__group;
	if( r5 == NULL ) hl_null_access();
	r6 = true;
	r5->__dirty = r6;
	r6 = r0->__renderDirty;
	if( r6 ) goto label$1b11b56_25_15;
	r6 = true;
	r0->__renderDirty = r6;
	openfl_display_DisplayObject___setParentRenderDirty(((openfl__display__DisplayObject)r0));
	label$1b11b56_25_15:
	return r1;
}

double openfl_display_Tilemap_get_width(openfl__display__Tilemap r0) {
	double r1, r3;
	int r2;
	r2 = r0->__width;
	r1 = (double)r2;
	r3 = r0->__scaleX;
	r3 = hl_math_abs(r3);
	r1 = r1 * r3;
	return r1;
}

double openfl_display_Tilemap_set_width(openfl__display__Tilemap r0,double r1) {
	double r3, r4;
	int r2;
	r2 = (int)r1;
	r0->__width = r2;
	r2 = r0->__width;
	r3 = (double)r2;
	r4 = r0->__scaleX;
	r4 = hl_math_abs(r4);
	r3 = r3 * r4;
	return r3;
}

